#!/usr/bin/env python3
"""da_assembler.py 的 pytest 風格測試 — CRD → YAML 組合器。"""

import json
import tempfile
from pathlib import Path
from unittest import mock

import pytest
import yaml

from _lib_exitcodes import EXIT_CALLER_ERROR  # noqa: E402
from _lib_io import OutputWriteError  # noqa: E402  (#1789)
from da_assembler import (  # noqa: E402
    _content_sha256,
    _is_dns1123_label,
    _is_dns1123_subdomain,
    _output_filename,
    _signal_handler,
    reconcile_one,
    remove_rendered,
    render_cr_file,
    render_cr_to_yaml,
    run_once,
    update_cr_status,
    write_rendered,
)


def _make_cr(name="db-a", namespace="db-a", tenants=None):
    """輔助函數：建立最小的 ThresholdConfig CR 字典。"""
    if tenants is None:
        tenants = {name: {"mysql_connections": "70"}}
    return {
        "apiVersion": "dynamicalerting.io/v1alpha1",
        "kind": "ThresholdConfig",
        "metadata": {"name": name, "namespace": namespace},
        "spec": {"tenants": tenants},
    }


class TestRenderCrToYaml:
    """render_cr_to_yaml() 測試。"""

    def test_basic_render(self):
        """測試基本渲染。"""
        cr = _make_cr()
        result = render_cr_to_yaml(cr)
        assert "# Auto-generated by da-assembler" in result
        assert "mysql_connections" in result
        # Should be valid YAML (skip header lines starting with #)
        body = "\n".join(
            ln for ln in result.splitlines() if not ln.startswith("#"))
        parsed = yaml.safe_load(body)
        assert "tenants" in parsed
        assert "db-a" in parsed["tenants"]

    def test_render_with_defaults(self):
        """測試含 defaults 的渲染。"""
        cr = _make_cr()
        cr["spec"]["defaults"] = {"mysql_connections": 80}
        result = render_cr_to_yaml(cr)
        parsed = yaml.safe_load(
            "\n".join(ln for ln in result.splitlines()
                      if not ln.startswith("#")))
        assert "defaults" in parsed

    def test_render_with_state_filters(self):
        """測試含 state filters 的渲染。"""
        cr = _make_cr()
        cr["spec"]["stateFilters"] = {
            "crashloop": {"reasons": ["CrashLoopBackOff"]}
        }
        result = render_cr_to_yaml(cr)
        parsed = yaml.safe_load(
            "\n".join(ln for ln in result.splitlines()
                      if not ln.startswith("#")))
        assert "state_filters" in parsed

    def test_empty_tenants(self):
        """測試空 tenants 的渲染。"""
        cr = _make_cr(tenants={})
        result = render_cr_to_yaml(cr)
        # Should still produce valid output (empty doc or {})
        assert "Auto-generated" in result


class TestOutputFilename:
    """_output_filename() 測試。"""

    def test_from_name(self):
        """測試從名稱產生輸出檔名。"""
        cr = _make_cr(name="payment-db")
        assert _output_filename(cr) == "payment-db.yaml"

    def test_missing_name(self):
        """測試缺失名稱時的預設檔名。"""
        cr = {"metadata": {}}
        assert _output_filename(cr) == "unknown.yaml"


class TestWriteRendered:
    """write_rendered() 測試。"""

    def test_writes_file(self):
        """測試寫入檔案。"""
        with tempfile.TemporaryDirectory() as d:
            changed = write_rendered(
                Path(d), "test.yaml", "tenants:\n  a: 1\n")
            assert changed
            assert (Path(d) / "test.yaml").exists()

    def test_no_change_skips_write(self):
        """測試無變更時跳過寫入。"""
        with tempfile.TemporaryDirectory() as d:
            content = "tenants:\n  a: 1\n"
            (Path(d) / "test.yaml").write_text(content, encoding="utf-8")
            changed = write_rendered(Path(d), "test.yaml", content)
            assert not changed

    def test_dry_run(self):
        """測試乾執行模式。"""
        with tempfile.TemporaryDirectory() as d:
            changed = write_rendered(
                Path(d), "test.yaml", "content", dry_run=True)
            assert changed
            assert not (Path(d) / "test.yaml").exists()


class TestRemoveRendered:
    """remove_rendered() 測試。"""

    def test_removes_existing(self):
        """測試刪除現存檔案。"""
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "test.yaml"
            p.write_text("data", encoding="utf-8")
            removed = remove_rendered(Path(d), "test.yaml")
            assert removed
            assert not p.exists()

    def test_nonexistent_noop(self):
        """測試不存在的檔案不執行操作。"""
        with tempfile.TemporaryDirectory() as d:
            removed = remove_rendered(Path(d), "nonexistent.yaml")
            assert not removed

    def test_dry_run(self):
        """測試乾執行模式不刪除檔案。"""
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "test.yaml"
            p.write_text("data", encoding="utf-8")
            removed = remove_rendered(Path(d), "test.yaml", dry_run=True)
            assert removed
            assert p.exists()  # not actually deleted


class TestContentSha256:
    """_content_sha256() 測試。"""

    def test_deterministic(self):
        """測試確定性雜湊。"""
        assert (
            _content_sha256("hello") ==
            _content_sha256("hello"))

    def test_different_content(self):
        """測試不同內容的不同雜湊。"""
        assert (
            _content_sha256("hello") !=
            _content_sha256("world"))


class TestRenderCrFile:
    """render_cr_file() 測試。"""

    def test_offline_render(self):
        """測試離線渲染。"""
        cr = _make_cr(name="offline-test")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            rc = render_cr_file(cr_path, out_dir)
            assert rc == 0
            assert (out_dir / "offline-test.yaml").exists()

    def test_invalid_kind(self):
        """測試無效的 kind。"""
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "bad.yaml"
            cr_path.write_text("kind: NotAThresholdConfig\nspec: {}",
                               encoding="utf-8")
            rc = render_cr_file(cr_path, Path(d))
            assert rc == EXIT_CALLER_ERROR

    def test_dry_run(self):
        """測試乾執行模式。"""
        cr = _make_cr(name="dry-test")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            rc = render_cr_file(cr_path, out_dir, dry_run=True)
            assert rc == 0
            assert not (out_dir / "dry-test.yaml").exists()

    def test_invalid_yaml(self):
        """測試無法解析的 YAML 檔案。"""
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "bad.yaml"
            cr_path.write_text(": : invalid yaml {{{", encoding="utf-8")
            rc = render_cr_file(cr_path, Path(d))
            assert rc == EXIT_CALLER_ERROR

    def test_nonexistent_file(self):
        """測試不存在的檔案。"""
        with tempfile.TemporaryDirectory() as d:
            rc = render_cr_file(Path(d) / "nonexistent.yaml", Path(d))
            assert rc == EXIT_CALLER_ERROR

    def test_empty_file(self):
        """測試空檔案。"""
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "empty.yaml"
            cr_path.write_text("", encoding="utf-8")
            rc = render_cr_file(cr_path, Path(d))
            assert rc == EXIT_CALLER_ERROR

    _K = "kind: ThresholdConfig\n"
    _T = "spec:\n  tenants:\n    t1: {}\n"
    _NOT_TC = "is not a ThresholdConfig resource"
    _BAD_NAME = "metadata.name must be a non-empty string"
    _BAD_SPEC = "spec must be a mapping"

    @pytest.mark.parametrize("text, message", [
        pytest.param("- kind: ThresholdConfig\n", _NOT_TC,
                     id="non-empty-list"),
        pytest.param("just-a-string\n", _NOT_TC, id="scalar"),
        pytest.param("42\n", _NOT_TC, id="int"),
        pytest.param("null\n", _NOT_TC, id="null-document"),
        pytest.param("[]\n", _NOT_TC, id="empty-list"),
        pytest.param("kind: Foo\n", _NOT_TC, id="wrong-kind-control"),
        pytest.param(_K + _T, _BAD_NAME, id="metadata-missing"),
        pytest.param(_K + "metadata: [x]\n" + _T, _BAD_NAME,
                     id="metadata-list"),
        pytest.param(_K + "metadata: null\n" + _T, _BAD_NAME,
                     id="metadata-null"),
        pytest.param(_K + "metadata: {namespace: n}\n" + _T, _BAD_NAME,
                     id="name-missing"),
        pytest.param(_K + 'metadata: {name: ""}\n' + _T, _BAD_NAME,
                     id="name-empty"),
        pytest.param(_K + "metadata: {name: [a]}\n" + _T, _BAD_NAME,
                     id="name-list"),
        pytest.param(_K + "metadata: {name: null}\n" + _T, _BAD_NAME,
                     id="name-null"),
        pytest.param(_K + "metadata: {name: ~}\n" + _T, _BAD_NAME,
                     id="name-tilde"),
        pytest.param(_K + "metadata: {name: ok}\nspec: [x]\n", _BAD_SPEC,
                     id="spec-list"),
        pytest.param(_K + "metadata: {name: ok}\nspec: hello\n", _BAD_SPEC,
                     id="spec-scalar"),
        pytest.param(_K + "metadata: {name: ok}\nspec: null\n", _BAD_SPEC,
                     id="spec-null"),
    ])
    def test_malformed_cr_is_caller_error(
            self, text, message, tmp_path, caplog):
        """#2371 (b)：形狀不對的 CR 一律 rc 2、一行訊息、不寫任何檔案。

        先前頂層 list／純量在 `cr.get("kind")` 丟 AttributeError；缺
        metadata／name 在 reconcile_one 的 try 外丟 KeyError／TypeError，
        兩者都是 traceback rc 1。name 為空或不是字串時會寫出 `.yaml`、
        `42.yaml` 這類檔名。spec 不是 mapping 則被 reconcile_one 的
        except 吞掉，rc 0 卻什麼都沒寫。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(text, encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        rc = render_cr_file(cr_path, out_dir)
        assert rc == EXIT_CALLER_ERROR
        assert message in caplog.text
        assert list(out_dir.iterdir()) == []

    # Unquoted names YAML 1.1 (PyYAML resolver, measured) types as int /
    # float / bool are a caller error. This is CLOSE TO, not the same as,
    # what Kubernetes sees after YAML→JSON (sigs.k8s.io/yaml, go-yaml v2).
    # Known differences, deliberately NOT asserted (the #2371 contract is
    # "YAML 1.1 as PyYAML reads it", not "as Kubernetes reads it"):
    #   `0o17`  PyYAML str (1.1 has no 0o)       go-yaml int
    #   `1e3`   PyYAML str (1.1 float needs `.`) go-yaml float
    #   `08`    PyYAML str (not valid octal)     go-yaml differs
    #   `y`/`n` PyYAML str                       go-yaml v2 bool
    #   `1:30`  PyYAML int (sexagesimal)         go-yaml string
    # Shapes let through here that are not a DNS-1123 name are refused by
    # the name-format check instead (#2396, TestRenderCrNameFormat).
    @pytest.mark.parametrize("name, kind", [
        pytest.param("42", "int", id="name-int"),
        pytest.param("8", "int", id="name-int-8"),
        pytest.param("010", "int", id="name-int-octal"),
        pytest.param("0x1F", "int", id="name-int-hex"),
        pytest.param("1:30", "int", id="name-int-sexagesimal"),
        pytest.param("-5", "int", id="name-int-negative"),
        pytest.param("1.5", "float", id="name-float"),
        pytest.param(".inf", "float", id="name-float-inf"),
        pytest.param("true", "bool", id="name-bool-true"),
        pytest.param("yes", "bool", id="name-bool-yes"),
        pytest.param("off", "bool", id="name-bool-off"),
    ])
    def test_non_string_name_is_caller_error(
            self, name, kind, tmp_path, caplog):
        """#2371：未加引號、YAML 會解成數字／布林的 name 一律 rc 2。

        以 YAML 1.1（PyYAML）的隱式型別判定，與 Kubernetes 經 YAML→JSON
        後的型別大致相同但不完全一致（見上方註解）。訊息要指名型別，並說明
        加引號只讓它變成字串，仍須是合法的 Kubernetes 名稱（DNS-1123）。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(
            self._K + f"metadata: {{name: {name}}}\n" + self._T,
            encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "metadata.name must be a string" in caplog.text
        assert f"read as {kind}" in caplog.text
        assert "Quoting makes it a string" in caplog.text
        assert "DNS-1123" in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("spec", [
        pytest.param("", id="spec-missing"),
        pytest.param("spec: {}\n", id="spec-empty"),
    ])
    def test_absent_or_empty_spec_still_renders(self, spec, tmp_path):
        """#2371：缺 spec 維持既有行為，等同 `spec: {}`，只寫 header。

        只有「spec 存在但不是 mapping」算 caller error。缺 spec 與空 spec
        先前都是 rc 0 並寫出檔案，本次刻意不改。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + "metadata: {name: ok}\n" + spec,
                           encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == 0
        assert (out_dir / "ok.yaml").exists()

    @pytest.mark.parametrize("name, want", [
        pytest.param("2024-01-01", "2024-01-01", id="date"),
        # PyYAML's date resolver needs two-digit month/day: this one stays str.
        pytest.param("2024-1-1", "2024-1-1", id="date-short-is-str"),
        pytest.param('"2024-01-01"', "2024-01-01", id="quoted-date"),
        pytest.param('"010"', "010", id="quoted-int"),
        pytest.param("'0x1f'", "0x1f", id="quoted-hex"),
        pytest.param('"1.5"', "1.5", id="quoted-float"),
        pytest.param('"yes"', "yes", id="quoted-bool"),
        pytest.param('"null"', "null", id="quoted-null"),
        pytest.param("!!str 010", "010", id="tagged-str-int"),
        # Only a PLAIN scalar is RawPlain: an explicit tag still builds a
        # `date` object. Rendered `2024-01-01.yaml` before #2371 (rc 0).
        pytest.param('!!timestamp "2024-01-01"', "2024-01-01",
                     id="tagged-timestamp-date"),
    ])
    def test_string_name_renders_as_written(self, name, want, tmp_path):
        """#2371：字串 name 照原文收，檔名與檔頭用原文。

        未加引號的日期照原文收；加了引號（或 `!!str`）的值同理。明示
        `!!timestamp` 的日期是 `date` 物件，轉 isoformat 後照收。日期時間
        （含 `:`、大寫 `T`／`Z`、空白）不是 DNS-1123 名稱，#2396 起 rc 2，
        見 TestRenderCrNameFormat。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(
            self._K + f"metadata: {{name: {name}}}\n" + self._T,
            encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == 0
        assert [p.name for p in out_dir.iterdir()] == [f"{want}.yaml"]
        header = (out_dir / f"{want}.yaml").read_text(
            encoding="utf-8").split("\n")[0]
        assert header.endswith(f"/{want}"), header


class TestRenderCrNameFormat:
    """#2396：`--render-cr` 以 Kubernetes 的規則驗 name／namespace。

    name 直接當輸出檔名、name 與 namespace 都寫進檔頭註解。先前不驗：
    `../escaped` rc 0 並寫到 `--config-dir` 之外；含換行的 name／namespace
    把檔頭註解斷行，輸出多出頂層鍵。現在 name 須是 RFC 1123 subdomain、
    namespace（有給時）須是 RFC 1123 label，否則 rc 2 且不寫任何檔案。

    會讓本組反例轉紅的改動：拿掉 render_cr_file 裡的
    `_is_dns1123_subdomain` / `_is_dns1123_label` 檢查。
    """

    @staticmethod
    def _run(tmp_path, metadata_yaml):
        """寫 CR、渲染，回傳 (rc, 渲染前後 tmp_path 下新增的檔案)。

        輸出目錄放兩層深，逃出 `--config-dir` 的檔案也還在 tmp_path 內，
        才量得到「目錄內外都沒有新檔」。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(
            "kind: ThresholdConfig\nmetadata:\n" + metadata_yaml
            + "spec:\n  tenants:\n    t1: {}\n", encoding="utf-8")
        out_dir = tmp_path / "work" / "out"
        out_dir.mkdir(parents=True)
        before = {p for p in tmp_path.rglob("*") if p.is_file()}
        rc = render_cr_file(cr_path, out_dir)
        after = {p for p in tmp_path.rglob("*") if p.is_file()}
        return rc, sorted(str(p.relative_to(tmp_path))
                          for p in after - before)

    @staticmethod
    def _q(text):
        """YAML 雙引號字串（JSON 字串是合法的 YAML flow scalar）。"""
        return json.dumps(text)

    @pytest.mark.parametrize("name", [
        pytest.param("../escaped", id="dotdot-escape"),
        pytest.param("sub/x", id="slash"),
        pytest.param("x\nevil: 1", id="newline-injects-key"),
        pytest.param("ok\n", id="trailing-newline"),
        pytest.param("Foo", id="uppercase"),
        pytest.param("a_b", id="underscore"),
        pytest.param("-a", id="leading-dash"),
        pytest.param("a-", id="trailing-dash"),
        pytest.param("a..b", id="empty-label"),
        pytest.param(".a", id="leading-dot"),
        pytest.param("a" * 254, id="len-254"),
    ])
    def test_invalid_name_is_caller_error(self, name, tmp_path, caplog):
        rc, new_files = self._run(tmp_path, f"  name: {self._q(name)}\n")
        assert rc == EXIT_CALLER_ERROR
        assert new_files == []
        assert "is not a valid Kubernetes object name" in caplog.text

    @pytest.mark.parametrize("namespace", [
        pytest.param("n\nevil: 1", id="newline-injects-key"),
        pytest.param("ns\n", id="trailing-newline"),
        pytest.param("Team", id="uppercase"),
        pytest.param("a.b", id="dot-not-in-label"),
        pytest.param("../x", id="dotdot"),
        pytest.param("a" * 64, id="len-64"),
    ])
    def test_invalid_namespace_is_caller_error(
            self, namespace, tmp_path, caplog):
        rc, new_files = self._run(
            tmp_path, f"  name: ok\n  namespace: {self._q(namespace)}\n")
        assert rc == EXIT_CALLER_ERROR
        assert new_files == []
        assert "is not a valid Kubernetes namespace name" in caplog.text

    @pytest.mark.parametrize("namespace, kind", [
        pytest.param("8", "int", id="int"),
        pytest.param("010", "int", id="int-octal"),
        pytest.param("true", "bool", id="bool-true"),
        pytest.param("yes", "bool", id="bool-yes"),
        pytest.param("1.5", "float", id="float"),
    ])
    def test_non_string_namespace_is_caller_error(
            self, namespace, kind, tmp_path, caplog):
        """未加引號、YAML 1.1 讀成數字／布林的 namespace 比照 name，rc 2。

        會讓本組轉紅的改動：拿掉 namespace 的 `_plain_tag` 型別檢查（`8`、
        `010` 是合法 label，只靠格式檢查會照收、檔頭寫 `8/ok`）。
        """
        rc, new_files = self._run(
            tmp_path, f"  name: ok\n  namespace: {namespace}\n")
        assert rc == EXIT_CALLER_ERROR
        assert new_files == []
        assert "metadata.namespace must be a string" in caplog.text
        assert f"read as {kind}" in caplog.text
        assert "Quoting makes it a string" in caplog.text

    @pytest.mark.parametrize("namespace", [
        pytest.param('"8"', id="quoted-int"),
        pytest.param("'yes'", id="quoted-bool"),
    ])
    def test_quoted_numeric_namespace_renders(self, namespace, tmp_path):
        """對照組：加了引號就是字串，且是合法 label，rc 0。"""
        rc, new_files = self._run(
            tmp_path, f"  name: ok\n  namespace: {namespace}\n")
        assert rc == 0
        assert new_files == ["work/out/ok.yaml"]

    @pytest.mark.parametrize("ns_line", [
        pytest.param("  namespace: null\n", id="null"),
        pytest.param("  namespace: ~\n", id="tilde"),
        pytest.param("  namespace:\n", id="empty-value"),
        pytest.param('  namespace: ""\n', id="empty-string"),
    ])
    def test_unset_namespace_renders_as_absent(
            self, ns_line, tmp_path, caplog):
        """null／空值／`""` 在 Kubernetes 是「未設」，CR 建得進叢集。

        比照沒寫 namespace：rc 0，輸出與缺鍵時逐位元組相同（檔頭 `?`），
        log 為 `default`。會讓本組轉紅的改動：拿掉 render_cr_file 裡把
        None／`""` 正規化成缺鍵的那一步（先前 rc 2；若只放行不正規化，
        檔頭會寫 `None/ok`、`/ok`）。
        """
        caplog.set_level("INFO")
        absent_dir = tmp_path / "absent"
        absent_dir.mkdir()
        rc, _ = self._run(absent_dir, "  name: ok\n")
        assert rc == 0
        want = (absent_dir / "work" / "out" / "ok.yaml").read_bytes()
        caplog.clear()

        rc, new_files = self._run(tmp_path, "  name: ok\n" + ns_line)
        assert rc == 0
        assert new_files == ["work/out/ok.yaml"]
        assert (tmp_path / "work" / "out" / "ok.yaml").read_bytes() == want
        assert "Rendered default/ok" in caplog.text

    @pytest.mark.parametrize("name, namespace", [
        pytest.param("ok", None, id="plain-no-namespace"),
        pytest.param("a.b-c", "team-1", id="dot-and-dash"),
        pytest.param("0-9.x", "0", id="digits"),
        pytest.param("x", "a" * 63, id="namespace-len-63"),
    ])
    def test_valid_names_still_render(self, name, namespace, tmp_path):
        """must-trigger 對照組：合法 name 照舊 rc 0，寫進 --config-dir。"""
        meta = f"  name: {self._q(name)}\n"
        if namespace is not None:
            meta += f"  namespace: {self._q(namespace)}\n"
        rc, new_files = self._run(tmp_path, meta)
        assert rc == 0
        assert new_files == [f"work/out/{name}.yaml"]
        header = (tmp_path / "work" / "out" / f"{name}.yaml").read_text(
            encoding="utf-8").split("\n")[0]
        # 缺 namespace 時檔頭沿用既有的 `?`（#2396 不改這條）。
        assert header.endswith(f" {namespace or '?'}/{name}"), header

    @staticmethod
    def _long_name(length):
        """`length` 字元、由 63 字元 label 以 `.` 串成的合法 subdomain。"""
        name = ".".join(["a" * 63] * 5)[:length - 1] + "b"
        assert len(name) == length
        return name

    @pytest.mark.parametrize("length, want", [
        pytest.param(253, True, id="len-253-accepted"),
        pytest.param(254, False, id="len-254-refused"),
    ])
    def test_name_length_boundary(self, length, want):
        """253 字元邊界，直接量驗證函式。

        不走 render_cr_file：`<253 字元>.yaml` 超過多數檔案系統的
        NAME_MAX（255），連 dry-run 的 `dest.exists()` 都會先丟
        ENAMETOOLONG，量到的就不是本檢查了。len-254 的 rc 2 由
        test_invalid_name_is_caller_error 端到端量。"""
        assert _is_dns1123_subdomain(self._long_name(length)) is want

    @pytest.mark.parametrize("length, want", [
        pytest.param(63, True, id="len-63-accepted"),
        pytest.param(64, False, id="len-64-refused"),
    ])
    def test_namespace_length_boundary(self, length, want):
        assert _is_dns1123_label("a" * length) is want

    def test_long_valid_name_renders(self, tmp_path):
        """端到端對照組：檔名塞得進 NAME_MAX 的最長合法 name（250）rc 0。"""
        name = self._long_name(250)
        rc, new_files = self._run(tmp_path, f"  name: {name}\n")
        assert rc == 0
        assert new_files == [f"work/out/{name}.yaml"]


class TestSignalHandler:
    """_signal_handler() 測試。"""

    def test_sets_shutdown_flag(self):
        import da_assembler
        original = da_assembler._shutdown
        try:
            da_assembler._shutdown = False
            _signal_handler(15, None)
            assert da_assembler._shutdown is True
        finally:
            da_assembler._shutdown = original


class TestUpdateCrStatus:
    """update_cr_status() 測試。"""

    def test_patches_status(self):
        mock_api = mock.MagicMock()
        cr = _make_cr(name="test-cr", namespace="ns1")
        update_cr_status(mock_api, cr, "Rendered", sha="abc123",
                         message="OK")
        mock_api.patch_namespaced_custom_object_status.assert_called_once()
        call_args = mock_api.patch_namespaced_custom_object_status.call_args
        body = call_args[1]["body"] if "body" in call_args[1] else call_args[0][5]
        assert body["status"]["phase"] == "Rendered"

    def test_handles_api_error(self):
        """API error should be logged, not raised."""
        mock_api = mock.MagicMock()
        mock_api.patch_namespaced_custom_object_status.side_effect = Exception("503")
        cr = _make_cr(name="t", namespace="ns")
        # Should not raise
        update_cr_status(mock_api, cr, "Error", message="fail")


class TestReconcileOne:
    """reconcile_one() 測試。"""

    def test_renders_and_writes(self):
        with tempfile.TemporaryDirectory() as d:
            cr = _make_cr(name="reconcile-test")
            reconcile_one(cr, Path(d))
            assert (Path(d) / "reconcile-test.yaml").exists()

    def test_with_api_updates_status(self):
        mock_api = mock.MagicMock()
        with tempfile.TemporaryDirectory() as d:
            cr = _make_cr(name="status-test")
            reconcile_one(cr, Path(d), api=mock_api)
            mock_api.patch_namespaced_custom_object_status.assert_called_once()

    def test_no_change_skips_status(self):
        mock_api = mock.MagicMock()
        with tempfile.TemporaryDirectory() as d:
            cr = _make_cr(name="nochange-test")
            # First write
            reconcile_one(cr, Path(d), api=mock_api)
            mock_api.reset_mock()
            # Second write — same content, no change
            reconcile_one(cr, Path(d), api=mock_api)
            # Status still updated (debug path)
            # Actually: no change → no update_cr_status call

    def test_dry_run_skips_api(self):
        mock_api = mock.MagicMock()
        with tempfile.TemporaryDirectory() as d:
            cr = _make_cr(name="dry-reconcile")
            reconcile_one(cr, Path(d), dry_run=True, api=mock_api)
            mock_api.patch_namespaced_custom_object_status.assert_not_called()
            assert not (Path(d) / "dry-reconcile.yaml").exists()

    def test_render_error_updates_status(self):
        """If render fails, status should be set to Error."""
        mock_api = mock.MagicMock()
        # CR with spec that causes render to fail (spec missing entirely)
        cr = {"metadata": {"name": "bad", "namespace": "ns"}}
        with tempfile.TemporaryDirectory() as d:
            # This should not raise even though spec is missing
            reconcile_one(cr, Path(d), api=mock_api)


    def test_cli_path_reraises_an_unusable_config_dir(self):
        """#1789: `cli=True` is the CLI (`--render-cr`) path.

        It used to log the OSError and let `render_cr_file` return EXIT_OK,
        so `da-assembler --render-cr` exited 0 having written nothing. The
        write-error class now leaves this function so `main`'s decorator can
        turn it into rc=2 naming `--config-dir`.
        """
        cr = _make_cr(name="db-a")
        with tempfile.TemporaryDirectory() as d:
            blocker = Path(d) / "blocker"
            blocker.write_text("not a directory\n", encoding="utf-8")
            with pytest.raises(OutputWriteError) as exc:
                reconcile_one(cr, blocker / "config-dir", cli=True)
        assert exc.value.flag == "--config-dir"

    def test_the_default_caller_is_the_controller_not_the_cli(self):
        """`cli` defaults to False, so only an explicit `cli=True` re-raises.

        A specific break that reddens this: put the re-raise back on
        `api is None`.
        """
        cr = _make_cr(name="db-a")
        with tempfile.TemporaryDirectory() as d:
            blocker = Path(d) / "blocker"
            blocker.write_text("not a directory\n", encoding="utf-8")
            reconcile_one(cr, blocker / "config-dir")  # no api, no raise

    def test_controller_path_still_only_logs_and_carries_on(self):
        """The other half, pinned so the fix cannot spread to the controller.

        In watch/once mode a reconcile is ONE item in a loop over every CR in
        the cluster: an unwritable config-dir must land on that CR's status
        and let the loop continue, or a single bad CR stops every other
        tenant from being rendered. So with an `api`, the same failure must
        NOT propagate — same behaviour as before #1789.
        """
        mock_api = mock.MagicMock()
        cr = _make_cr(name="db-a")
        with tempfile.TemporaryDirectory() as d:
            blocker = Path(d) / "blocker"
            blocker.write_text("not a directory\n", encoding="utf-8")
            reconcile_one(cr, blocker / "config-dir", api=mock_api)  # no raise
        mock_api.patch_namespaced_custom_object_status.assert_called_once()
        status = mock_api.patch_namespaced_custom_object_status.call_args
        assert "Error" in str(status)

    def test_the_controller_under_dry_run_also_only_logs(self):
        """⛔ The dry-run cell, which `api is None` got wrong.

        `run_once` / `run_watch` pass `api=None` whenever `--dry-run` is set,
        so keying the CLI branch off that inference put the CONTROLLER on it.
        The shape that reaches a raise under `--dry-run`: `write_rendered`'s
        idempotence read is wrapped and runs BEFORE the `if dry_run` early
        return, so a rendered path that is itself a DIRECTORY raises EISDIR
        even though the run would never have written anything. (A blocked
        PARENT does not: `Path.exists()` answers False on ENOTDIR instead of
        raising.)

        A specific break that reddens this: change the handler's condition
        back to `api is None`.
        """
        cr = _make_cr(name="db-a")
        with tempfile.TemporaryDirectory() as d:
            (Path(d) / "db-a.yaml").mkdir()
            # Exactly what run_once/run_watch pass under --dry-run.
            reconcile_one(cr, Path(d), dry_run=True, api=None)


class TestRunOnce:
    """run_once() 測試。"""

    def test_lists_and_renders(self):
        mock_api = mock.MagicMock()
        cr = _make_cr(name="once-test")
        mock_api.list_cluster_custom_object.return_value = {"items": [cr]}

        with tempfile.TemporaryDirectory() as d:
            rc = run_once(mock_api, Path(d))
            assert rc == 0
            assert (Path(d) / "once-test.yaml").exists()

    def test_namespace_filter(self):
        mock_api = mock.MagicMock()
        cr = _make_cr(name="ns-test", namespace="db-a")
        mock_api.list_namespaced_custom_object.return_value = {"items": [cr]}

        with tempfile.TemporaryDirectory() as d:
            rc = run_once(mock_api, Path(d), namespace="db-a")
            assert rc == 0
            mock_api.list_namespaced_custom_object.assert_called_once()

    def test_api_error_returns_caller_error(self):
        mock_api = mock.MagicMock()
        mock_api.list_cluster_custom_object.side_effect = Exception("timeout")

        with tempfile.TemporaryDirectory() as d:
            rc = run_once(mock_api, Path(d))
            assert rc == EXIT_CALLER_ERROR

    def test_empty_items(self):
        mock_api = mock.MagicMock()
        mock_api.list_cluster_custom_object.return_value = {"items": []}

        with tempfile.TemporaryDirectory() as d:
            rc = run_once(mock_api, Path(d))
            assert rc == 0

    def test_dry_run_over_an_unreadable_target_still_visits_every_cr(self):
        """#1789 F1: the loop must not be aborted by one unusable path.

        Under `--dry-run` the controller nulls `api`, which is what the first
        version of the CLI/controller split keyed on. With that inference the
        first CR raised OutputWriteError straight out of `run_once` and the
        second was never reached.

        A specific break that reddens this: change `reconcile_one`'s handler
        condition back to `api is None`.
        """
        mock_api = mock.MagicMock()
        crs = [_make_cr(name="first"), _make_cr(name="second")]
        mock_api.list_cluster_custom_object.return_value = {"items": crs}

        with tempfile.TemporaryDirectory() as d:
            (Path(d) / "first.yaml").mkdir()   # the wrapped idempotence read
            with mock.patch("da_assembler.reconcile_one",
                            wraps=reconcile_one) as spy:
                rc = run_once(mock_api, Path(d), dry_run=True)
            assert rc == 0
            assert [c.args[0]["metadata"]["name"] for c in spy.call_args_list] \
                == ["first", "second"]

    def test_dry_run(self):
        mock_api = mock.MagicMock()
        cr = _make_cr(name="dry-once")
        mock_api.list_cluster_custom_object.return_value = {"items": [cr]}

        with tempfile.TemporaryDirectory() as d:
            rc = run_once(mock_api, Path(d), dry_run=True)
            assert rc == 0
            assert not (Path(d) / "dry-once.yaml").exists()


class TestMain:
    """main() CLI entry point 測試。"""

    def test_render_cr_mode(self):
        import da_assembler
        cr = _make_cr(name="cli-test")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            with mock.patch("sys.argv", [
                "da_assembler.py",
                "--config-dir", str(out_dir),
                "--render-cr", str(cr_path),
            ]):
                rc = da_assembler.main()
            assert rc == 0
            assert (out_dir / "cli-test.yaml").exists()

    def test_render_cr_dry_run(self):
        import da_assembler
        cr = _make_cr(name="cli-dry")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            with mock.patch("sys.argv", [
                "da_assembler.py",
                "--config-dir", str(out_dir),
                "--render-cr", str(cr_path),
                "--dry-run",
            ]):
                rc = da_assembler.main()
            assert rc == 0

    @mock.patch("da_assembler.HAS_K8S", False)
    def test_no_k8s_client(self):
        import da_assembler
        with tempfile.TemporaryDirectory() as d:
            with mock.patch("sys.argv", [
                "da_assembler.py",
                "--config-dir", d,
                "--once",
            ]):
                rc = da_assembler.main()
            assert rc == EXIT_CALLER_ERROR
