#!/usr/bin/env python3
"""da_assembler.py 的 pytest 風格測試 — CRD → YAML 組合器。"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from unittest import mock

import pytest
import yaml

import da_assembler  # noqa: E402
from _lib_exitcodes import EXIT_CALLER_ERROR  # noqa: E402
from _lib_io import OutputWriteError  # noqa: E402  (#1789)
from da_assembler import (  # noqa: E402
    _content_sha256,
    _is_dns1123_label,
    _is_dns1123_subdomain,
    _output_filename,
    _signal_handler,
    reconcile_one,
    remove_rendered,
    render_cr_file,
    render_cr_to_yaml,
    run_once,
    update_cr_status,
    write_rendered,
)


@pytest.fixture(autouse=True)
def _crdecode(da_crdecode_env):
    """`--render-cr` 以 da-crdecode 解碼 CR（#2476）；本檔每支測試都可用。"""
    return da_crdecode_env


def _make_cr(name="db-a", namespace="db-a", tenants=None):
    """輔助函數：建立最小的 ThresholdConfig CR 字典。"""
    if tenants is None:
        tenants = {name: {"mysql_connections": "70"}}
    return {
        "apiVersion": "dynamicalerting.io/v1alpha1",
        "kind": "ThresholdConfig",
        "metadata": {"name": name, "namespace": namespace},
        "spec": {"tenants": tenants},
    }


class TestRenderCrToYaml:
    """render_cr_to_yaml() 測試。"""

    def test_basic_render(self):
        """測試基本渲染。"""
        cr = _make_cr()
        result = render_cr_to_yaml(cr)
        assert "# Auto-generated by da-assembler" in result
        assert "mysql_connections" in result
        # Should be valid YAML (skip header lines starting with #)
        body = "\n".join(
            ln for ln in result.splitlines() if not ln.startswith("#"))
        parsed = yaml.safe_load(body)
        assert "tenants" in parsed
        assert "db-a" in parsed["tenants"]

    def test_render_with_defaults(self):
        """測試含 defaults 的渲染。"""
        cr = _make_cr()
        cr["spec"]["defaults"] = {"mysql_connections": 80}
        result = render_cr_to_yaml(cr)
        parsed = yaml.safe_load(
            "\n".join(ln for ln in result.splitlines()
                      if not ln.startswith("#")))
        assert "defaults" in parsed

    def test_render_with_state_filters(self):
        """測試含 state filters 的渲染。"""
        cr = _make_cr()
        cr["spec"]["stateFilters"] = {
            "crashloop": {"reasons": ["CrashLoopBackOff"]}
        }
        result = render_cr_to_yaml(cr)
        parsed = yaml.safe_load(
            "\n".join(ln for ln in result.splitlines()
                      if not ln.startswith("#")))
        assert "state_filters" in parsed

    def test_empty_tenants(self):
        """測試空 tenants 的渲染。"""
        cr = _make_cr(tenants={})
        result = render_cr_to_yaml(cr)
        # Should still produce valid output (empty doc or {})
        assert "Auto-generated" in result


class TestOutputFilename:
    """_output_filename() 測試。"""

    def test_from_name(self):
        """測試從名稱產生輸出檔名。"""
        cr = _make_cr(name="payment-db")
        assert _output_filename(cr) == "payment-db.yaml"

    def test_missing_name(self):
        """測試缺失名稱時的預設檔名。"""
        cr = {"metadata": {}}
        assert _output_filename(cr) == "unknown.yaml"


class TestWriteRendered:
    """write_rendered() 測試。"""

    def test_writes_file(self):
        """測試寫入檔案。"""
        with tempfile.TemporaryDirectory() as d:
            changed = write_rendered(
                Path(d), "test.yaml", "tenants:\n  a: 1\n")
            assert changed
            assert (Path(d) / "test.yaml").exists()

    def test_no_change_skips_write(self):
        """測試無變更時跳過寫入。"""
        with tempfile.TemporaryDirectory() as d:
            content = "tenants:\n  a: 1\n"
            (Path(d) / "test.yaml").write_text(content, encoding="utf-8")
            changed = write_rendered(Path(d), "test.yaml", content)
            assert not changed

    def test_dry_run(self):
        """測試乾執行模式。"""
        with tempfile.TemporaryDirectory() as d:
            changed = write_rendered(
                Path(d), "test.yaml", "content", dry_run=True)
            assert changed
            assert not (Path(d) / "test.yaml").exists()


class TestRemoveRendered:
    """remove_rendered() 測試。"""

    def test_removes_existing(self):
        """測試刪除現存檔案。"""
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "test.yaml"
            p.write_text("data", encoding="utf-8")
            removed = remove_rendered(Path(d), "test.yaml")
            assert removed
            assert not p.exists()

    def test_nonexistent_noop(self):
        """測試不存在的檔案不執行操作。"""
        with tempfile.TemporaryDirectory() as d:
            removed = remove_rendered(Path(d), "nonexistent.yaml")
            assert not removed

    def test_dry_run(self):
        """測試乾執行模式不刪除檔案。"""
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "test.yaml"
            p.write_text("data", encoding="utf-8")
            removed = remove_rendered(Path(d), "test.yaml", dry_run=True)
            assert removed
            assert p.exists()  # not actually deleted


class TestContentSha256:
    """_content_sha256() 測試。"""

    def test_deterministic(self):
        """測試確定性雜湊。"""
        assert (
            _content_sha256("hello") ==
            _content_sha256("hello"))

    def test_different_content(self):
        """測試不同內容的不同雜湊。"""
        assert (
            _content_sha256("hello") !=
            _content_sha256("world"))


class TestRenderCrFile:
    """render_cr_file() 測試。"""

    def test_offline_render(self):
        """測試離線渲染。"""
        cr = _make_cr(name="offline-test")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            rc = render_cr_file(cr_path, out_dir)
            assert rc == 0
            assert (out_dir / "offline-test.yaml").exists()

    def test_invalid_kind(self):
        """測試無效的 kind。"""
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "bad.yaml"
            cr_path.write_text("kind: NotAThresholdConfig\nspec: {}",
                               encoding="utf-8")
            rc = render_cr_file(cr_path, Path(d))
            assert rc == EXIT_CALLER_ERROR

    def test_dry_run(self):
        """測試乾執行模式。"""
        cr = _make_cr(name="dry-test")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            rc = render_cr_file(cr_path, out_dir, dry_run=True)
            assert rc == 0
            assert not (out_dir / "dry-test.yaml").exists()

    def test_invalid_yaml(self):
        """測試無法解析的 YAML 檔案。"""
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "bad.yaml"
            cr_path.write_text(": : invalid yaml {{{", encoding="utf-8")
            rc = render_cr_file(cr_path, Path(d))
            assert rc == EXIT_CALLER_ERROR

    def test_nonexistent_file(self):
        """測試不存在的檔案。"""
        with tempfile.TemporaryDirectory() as d:
            rc = render_cr_file(Path(d) / "nonexistent.yaml", Path(d))
            assert rc == EXIT_CALLER_ERROR

    def test_empty_file(self):
        """測試空檔案。"""
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "empty.yaml"
            cr_path.write_text("", encoding="utf-8")
            rc = render_cr_file(cr_path, Path(d))
            assert rc == EXIT_CALLER_ERROR

    _K = "kind: ThresholdConfig\n"
    _T = "spec:\n  tenants:\n    t1: {}\n"
    _NOT_TC = "is not a ThresholdConfig resource"
    _BAD_NAME = "metadata.name must be a non-empty string"

    @staticmethod
    def _rendered(name: str, ns: str = "?") -> str:
        """A file as da-assembler (this or an earlier version) writes it."""
        return (f"# Auto-generated by da-assembler from ThresholdConfig "
                f"{ns}/{name}\n# DO NOT EDIT\ntenants: {{}}\n")
    _BAD_SPEC = "spec must be a mapping"

    @pytest.mark.parametrize("text, message", [
        pytest.param("- kind: ThresholdConfig\n", _NOT_TC,
                     id="non-empty-list"),
        pytest.param("just-a-string\n", _NOT_TC, id="scalar"),
        pytest.param("42\n", _NOT_TC, id="int"),
        pytest.param("null\n", _NOT_TC, id="null-document"),
        pytest.param("[]\n", _NOT_TC, id="empty-list"),
        pytest.param("kind: Foo\n", _NOT_TC, id="wrong-kind-control"),
        pytest.param(_K + _T, _BAD_NAME, id="metadata-missing"),
        pytest.param(_K + "metadata: [x]\n" + _T, _BAD_NAME,
                     id="metadata-list"),
        pytest.param(_K + "metadata: null\n" + _T, _BAD_NAME,
                     id="metadata-null"),
        pytest.param(_K + "metadata: {namespace: n}\n" + _T, _BAD_NAME,
                     id="name-missing"),
        pytest.param(_K + 'metadata: {name: ""}\n' + _T, _BAD_NAME,
                     id="name-empty"),
        pytest.param(_K + "metadata: {name: [a]}\n" + _T, _BAD_NAME,
                     id="name-list"),
        pytest.param(_K + "metadata: {name: null}\n" + _T, _BAD_NAME,
                     id="name-null"),
        pytest.param(_K + "metadata: {name: ~}\n" + _T, _BAD_NAME,
                     id="name-tilde"),
        pytest.param(_K + "metadata: {name: ok}\nspec: [x]\n", _BAD_SPEC,
                     id="spec-list"),
        pytest.param(_K + "metadata: {name: ok}\nspec: hello\n", _BAD_SPEC,
                     id="spec-scalar"),
        pytest.param(_K + "metadata: {name: ok}\nspec: null\n", _BAD_SPEC,
                     id="spec-null"),
    ])
    def test_malformed_cr_is_caller_error(
            self, text, message, tmp_path, caplog):
        """#2371 (b)：形狀不對的 CR 一律 rc 2、一行訊息、不寫任何檔案。

        先前頂層 list／純量在 `cr.get("kind")` 丟 AttributeError；缺
        metadata／name 在 reconcile_one 的 try 外丟 KeyError／TypeError，
        兩者都是 traceback rc 1。name 為空或不是字串時會寫出 `.yaml`、
        `42.yaml` 這類檔名。spec 不是 mapping 則被 reconcile_one 的
        except 吞掉，rc 0 卻什麼都沒寫。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(text, encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        rc = render_cr_file(cr_path, out_dir)
        assert rc == EXIT_CALLER_ERROR
        assert message in caplog.text
        assert list(out_dir.iterdir()) == []

    # #2476: an unquoted name is typed as Kubernetes clients type it
    # (da-crdecode, sigs.k8s.io/yaml YAMLToJSON): `kind` is what the decoded
    # JSON holds, "number" / "boolean", or None where it stays a string
    # (`1:30`) and the name-format check refuses it instead (#2396). The
    # rows `0o17` … `n` are the ones the earlier PyYAML reading let through
    # (YAML 1.1 types them as strings) although Kubernetes reads a number or
    # a boolean. `.inf` is refused by the decoder itself (no JSON for it):
    # TestRenderCrNameFormat.test_decoder_refusal_names_the_file.
    # `stale`: the file an earlier version (before #2399/#2400) rendered
    # this name to — measured against tools/v2.9.0, #2430. None where it
    # is the name as written and quoting saves it: quoting then overwrites
    # the same file. `fix`: "quote" when the quoted name is DNS-1123;
    # "rename" when it is not (#2396), and then even a same-spelling file
    # (`True` -> `True.yaml`, `-5` -> `-5.yaml`) is left behind.
    @pytest.mark.parametrize("name, kind, stale, fix", [
        pytest.param("42", "number", None, "quote", id="name-int"),
        pytest.param("8", "number", None, "quote", id="name-int-8"),
        pytest.param("010", "number", "8.yaml", "quote", id="name-int-octal"),
        pytest.param("0x1F", "number", "31.yaml", "rename", id="name-int-hex"),
        pytest.param("1:30", None, "90.yaml", "rename",
                     id="name-int-sexagesimal"),
        pytest.param("-5", "number", "-5.yaml", "rename",
                     id="name-int-negative"),
        pytest.param("1.5", "number", None, "quote", id="name-float"),
        pytest.param("1.50", "number", "1.5.yaml", "quote",
                     id="name-float-trailing-0"),
        pytest.param("true", "boolean", "True.yaml", "quote",
                     id="name-bool-true"),
        pytest.param("TRUE", "boolean", "True.yaml", "rename",
                     id="name-bool-upper"),
        pytest.param("True", "boolean", "True.yaml", "rename",
                     id="name-bool-title"),
        pytest.param("yes", "boolean", "True.yaml", "quote", id="name-bool-yes"),
        pytest.param("off", "boolean", "False.yaml", "quote", id="name-bool-off"),
        pytest.param("0o17", "number", None, "quote", id="name-0o17"),
        pytest.param("1e3", "number", None, "quote", id="name-1e3"),
        pytest.param("08", "number", None, "quote", id="name-08"),
        pytest.param("y", "boolean", None, "quote", id="name-y"),
        pytest.param("n", "boolean", None, "quote", id="name-n"),
    ])
    def test_non_string_name_is_caller_error(
            self, name, kind, stale, fix, tmp_path, caplog):
        """#2371／#2476：未加引號、Kubernetes 會解成數字／布林的 name 一律 rc 2。

        型別取自 da-crdecode（Kubernetes client 的 YAML→JSON），不是 YAML 1.1。
        訊息要指名型別，並說明加引號只讓它變成字串，仍須是合法的 Kubernetes
        名稱（DNS-1123）。`0o17`、`1e3`、`08`、`y`、`n` 先前以 PyYAML 讀成
        字串而 rc 0；會讓這幾列轉紅的改動：改回以 YAML 1.1 判型別。

        #2430：舊版（#2399／#2400 之前）把這個 name 寫成型別化後的拼法
        （`010` → `8.yaml`）。加引號重 render 後新檔是 `010.yaml`，舊檔
        若還在持久輸出目錄裡，同一租戶就有兩份。訊息只在那個舊檔**確實
        存在**於 --config-dir 時指名它（空目錄不提）；拼法相同（`42`）時
        加引號會覆寫同一個檔，不該提。本工具不刪檔。
        加引號仍非 DNS-1123（`TRUE`、`-5`，#2396）就得改名，舊檔即使拼法
        相同也會留下，要提。舊檔以 da-assembler 檔頭寫著這個舊拼法（舊版
        的寫法）。會讓本測試轉紅的改動：拿掉 `_stale_render_hint` 的存在
        檢查（空目錄也提），或整段不提。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(
            self._K + f"metadata: {{name: {name}}}\n" + self._T,
            encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        if kind is None:
            assert "is not a valid Kubernetes object name" in caplog.text
        else:
            assert "metadata.name must be a string" in caplog.text
            assert f"Kubernetes reads it as a {kind}" in caplog.text
            assert "Quoting makes it a string" in caplog.text
        assert "DNS-1123" in caplog.text
        # Empty --config-dir: nothing was ever rendered here, no hint.
        assert "earlier version" not in caplog.text
        assert "case-insensitive file system" not in caplog.text
        assert list(out_dir.iterdir()) == []
        if stale is None:
            return
        # The earlier version's file is there: the hint must name it.
        old = stale[:-len(".yaml")]
        (out_dir / stale).write_text(self._rendered(old), encoding="utf-8")
        caplog.clear()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert (f"{stale} exists in this --config-dir" in caplog.text), \
            caplog.text
        assert "confirm it is not the output of another CR" in caplog.text
        new_file = "quoted name's" if fix == "quote" else "renamed CR's"
        assert f"it and the {new_file} file both" in caplog.text, \
            caplog.text
        assert "do not delete it" not in caplog.text
        assert [p.name for p in out_dir.iterdir()] == [stale]

    def test_stale_hint_asks_to_rule_out_a_string_named_cr(
            self, tmp_path, caplog):
        """#2430：`8.yaml` 也可能是另一個 name 為 `"8"` 的合法 CR 的輸出。

        兩者檔頭同為 `ThresholdConfig ?/8`，工具分不出來，所以提示必須要求
        先確認再刪，且不得動那個檔。會讓本測試轉紅的改動：提示拿掉「確認」
        那句，或改成只看 name 推算、不看目錄。
        """
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        other = tmp_path / "other.yaml"
        other.write_text(self._K + 'metadata: {name: "8"}\n' + self._T,
                         encoding="utf-8")
        assert render_cr_file(other, out_dir) == 0
        rendered = (out_dir / "8.yaml").read_text(encoding="utf-8")
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + "metadata: {name: 010}\n" + self._T,
                           encoding="utf-8")
        caplog.clear()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "8.yaml exists in this --config-dir" in caplog.text
        assert ("confirm it is not the output of another CR whose "
                "metadata.name is the string '8'") in caplog.text
        assert "cannot tell them apart" in caplog.text
        assert [p.name for p in out_dir.iterdir()] == ["8.yaml"]
        assert (out_dir / "8.yaml").read_text(encoding="utf-8") == rendered

    # The file an earlier version (fb7acd71, measured for #2430) wrote for
    # a name refused now for not being a string / not DNS-1123.
    @pytest.mark.parametrize("name, stale", [
        pytest.param("~", "None.yaml", id="tilde"),
        pytest.param("null", "None.yaml", id="null"),
        pytest.param("", "None.yaml", id="empty-scalar"),
        pytest.param("2024-01-01T10:00:00Z", "2024-01-01 10:00:00+00:00.yaml",
                     id="datetime-utc"),
        pytest.param("2024-01-01 10:00:00", "2024-01-01 10:00:00.yaml",
                     id="datetime-space"),
        # Kubernetes clients decode every timestamp spelling to a string,
        # tagged or not, quoted or not: the DNS-1123 branch.
        pytest.param("!!timestamp 2024-01-01T10:00:00Z",
                     "2024-01-01 10:00:00+00:00.yaml",
                     id="tagged-plain-datetime"),
        pytest.param('!!timestamp "2024-01-01T10:00:00Z"',
                     "2024-01-01 10:00:00+00:00.yaml",
                     id="tagged-quoted-datetime"),
    ])
    def test_null_and_datetime_name_stale_hint(
            self, name, stale, tmp_path, caplog):
        """#2430：null 與 datetime name 舊版也會寫檔，舊檔存在才提示。

        舊版把 null（`~`、`null`、空值）寫成 `None.yaml`，datetime 寫成
        Python 的拼法。空目錄不提；舊檔存在就指名並要求先確認。null 另外
        提示：本意是字串 null 就加引號。
        提示分兩條路徑：null 走「不是字串」分支；datetime（Kubernetes
        client 一律解成字串，含帶 `!!timestamp` 標籤、加不加引號）走
        DNS-1123 分支，舊檔名由 `_legacy_name_hint` 以 PyYAML 重建。會讓本
        測試轉紅的改動：拿掉任一處的提示呼叫。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + f"metadata: {{name: {name}}}\n"
                           + self._T, encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        is_null = stale == "None.yaml"
        old = stale[:-len(".yaml")]
        non_string = is_null
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert (self._BAD_NAME in caplog.text) == non_string, caplog.text
        assert "exists in this --config-dir" not in caplog.text
        assert ('quote it ("null")' in caplog.text) == is_null, caplog.text
        (out_dir / stale).write_text(self._rendered(old, "ns"),
                                     encoding="utf-8")
        caplog.clear()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert f"{stale} exists in this --config-dir" in caplog.text, \
            caplog.text
        assert "confirm it is not the output of another CR" in caplog.text
        assert ('quote it ("null")' in caplog.text) == is_null
        assert [p.name for p in out_dir.iterdir()] == [stale]

    @pytest.mark.parametrize("name", [
        "2024-13-01T00:00:00Z", "2024-02-30 10:00:00",
        "2024-01-01T25:00:00Z",
    ])
    def test_unconstructable_datetime_name_is_caller_error(
            self, name, tmp_path, caplog):
        """#2430：YAML 判成 timestamp 卻建不出值的 name 仍是 rc 2 單行訊息。

        推算舊版檔名要以 PyYAML 建這個 name，月份／日期／小時超界時丟
        ValueError；舊版對它同樣 crash、沒寫過檔，所以不附舊檔提醒，也不得
        變成 traceback。會讓本測試轉紅的改動：拿掉 `_legacy_name_hint` 建值
        時的 except。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + f"metadata: {{name: {name}}}\n"
                           + self._T, encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        errors = [r for r in caplog.records if r.levelname == "ERROR"]
        assert len(errors) == 1, caplog.text
        assert "not a valid Kubernetes object name" in caplog.text
        assert "earlier version" not in caplog.text
        assert "Traceback" not in caplog.text
        assert list(out_dir.iterdir()) == []

    # `yes` was rendered by an earlier version to `True.yaml`, header
    # `?/True`; a valid CR named "true" renders to `true.yaml`, header
    # `?/true`. On a case-insensitive file system these are one file, and
    # opening `True.yaml` reads whichever was written: `header` models what
    # that open returns.
    _NO_SLASH = ("# Auto-generated by da-assembler from ThresholdConfig "
                 "True\ntenants: {}\n")

    @pytest.mark.parametrize("content, expect", [
        pytest.param(_rendered("True"), "stale", id="own-header"),
        # The name is after the LAST `/`: a `/` in the namespace is kept.
        pytest.param(_rendered("True", "ns/a"), "stale",
                     id="slash-in-namespace"),
        pytest.param(_rendered("true"), "other", id="case-folded-other-cr"),
        pytest.param("tenants: {}\n", "none", id="hand-written"),
        pytest.param(_NO_SLASH, "none", id="header-without-slash"),
        pytest.param(None, "none", id="directory"),
    ])
    def test_stale_hint_judges_by_the_header(
            self, content, expect, tmp_path, caplog):
        """#2430：舊檔提醒看 `<old_name>.yaml` 的 da-assembler 檔頭決定。

        不列目錄，只看那一個路徑。檔頭的 name 與舊拼法逐字相同 → 原提示
        （要求先排除字串 name 的 CR）；不同（大小寫不分的檔案系統上
        `True.yaml` 開到合法租戶 `"true"` 的 `true.yaml`）→ 說明它是另一個
        CR 的輸出、不要刪；沒有 da-assembler 檔頭（手寫檔）或是目錄 →
        不提示。Linux 上以寫入不同檔頭的 `True.yaml` 模擬開檔結果。
        會讓本測試轉紅的改動：不看檔頭、存在即提示（other／none 轉紅），
        或不分辨檔頭 name（other 轉紅）；以第一個 `/` 切 name
        （slash-in-namespace 轉紅）。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + "metadata: {name: yes}\n" + self._T,
                           encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        target = out_dir / "True.yaml"
        if content is None:
            target.mkdir()
        else:
            target.write_text(content, encoding="utf-8")
        before = target.read_bytes() if target.is_file() else None
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        text = caplog.text
        errors = [r for r in caplog.records if r.levelname == "ERROR"]
        assert len(errors) == 1, text
        stale_hint = "True.yaml exists in this --config-dir: an earlier"
        other_hint = ("True.yaml in this --config-dir resolves to a file "
                      "whose header comment shows it is the output of CR "
                      "'true', not an earlier version's file for this CR: "
                      "do not delete it")
        assert (stale_hint in text) == (expect == "stale"), text
        assert ("cannot tell them apart" in text) == (expect == "stale")
        assert (other_hint in text) == (expect == "other"), text
        if expect == "none":
            assert "True.yaml" not in text, text
        assert [p.name for p in out_dir.iterdir()] == ["True.yaml"]
        if before is not None:
            assert target.read_bytes() == before

    @pytest.mark.parametrize("name, stale", [
        pytest.param("010", "8.yaml", id="int-octal"),
        pytest.param("yes", "True.yaml", id="bool-yes"),
    ])
    def test_crlf_header_gets_the_stale_hint(
            self, name, stale, tmp_path, caplog):
        """#2430：CRLF 換行的舊檔（Windows 寫出或 core.autocrlf）照樣提示。

        檔頭行尾的 `\r` 不屬於 name；讀成 `8\r` 會被當成「另一個 CR 的
        檔、不要刪」，方向相反。會讓本測試轉紅的改動：拿掉
        `_rendered_cr_name` 去掉行尾 `\r` 的處理。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + f"metadata: {{name: {name}}}\n"
                           + self._T, encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        old = stale[:-len(".yaml")]
        (out_dir / stale).write_bytes(
            self._rendered(old).replace("\n", "\r\n").encode("utf-8"))
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert f"{stale} exists in this --config-dir" in caplog.text, \
            caplog.text
        assert "cannot tell them apart" in caplog.text
        assert "do not delete it" not in caplog.text
        assert [p.name for p in out_dir.iterdir()] == [stale]

    def test_undecodable_header_has_no_stale_hint(self, tmp_path, caplog):
        """#2430：檔頭解不出 UTF-8 時當作讀不到，不提示、不 traceback。"""
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + "metadata: {name: 010}\n" + self._T,
                           encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        (out_dir / "8.yaml").write_bytes(
            b"# Auto-generated by da-assembler from ThresholdConfig ?/8\xff\n")
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        errors = [r for r in caplog.records if r.levelname == "ERROR"]
        assert len(errors) == 1, caplog.text
        assert "8.yaml" not in caplog.text
        assert "Traceback" not in caplog.text

    def test_unreadable_config_dir_has_no_stale_hint(
            self, tmp_path, caplog):
        """#2430：--config-dir 不存在、探測 `<old_name>.yaml` 失敗時當作沒有舊檔。

        舊檔檢查探測 `<old_name>.yaml`，它的 OSError 必須當成不存在：rc 2、
        只有一筆 ERROR、無提示、無 traceback。會讓本測試轉紅的改動：拿掉
        `_rendered_cr_name` 的 OSError 處理。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + "metadata: {name: 010}\n" + self._T,
                           encoding="utf-8")
        out_dir = tmp_path / "missing"
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        errors = [r for r in caplog.records if r.levelname == "ERROR"]
        assert len(errors) == 1, caplog.text
        assert "Kubernetes reads it as a number" in caplog.text
        assert "exists in this --config-dir" not in caplog.text
        assert not out_dir.exists()

    def test_missing_name_has_no_stale_hint(self, tmp_path, caplog):
        """#2430：缺 name 時舊版 crash、沒寫檔，`None.yaml` 在也不提。"""
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + "metadata: {namespace: n}\n" + self._T,
                           encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        (out_dir / "None.yaml").write_text(self._rendered("None"),
                                           encoding="utf-8")
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert self._BAD_NAME in caplog.text
        assert "exists in this --config-dir" not in caplog.text
        assert "quote it" not in caplog.text

    def test_overlong_int_name_has_no_stale_hint(self, tmp_path, caplog):
        """#2430：name 太長、舊檔名超過檔名上限時不提示、不 traceback。

        300 位的 int name 加引號後也超過 DNS-1123 的 253 字元，走「須改名」
        分支；舊版寫 `<300 位>.yaml` 會因檔名過長失敗，目錄裡不可能有它。
        探測那個過長的路徑會丟 ENAMETOOLONG，須當成不存在。會讓本測試轉紅的
        改動：拿掉存在檢查（偽提示），或探測路徑卻不處理 OSError
        （ENAMETOOLONG → traceback）。
        """
        name = "1" * 300
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + f"metadata: {{name: {name}}}\n"
                           + self._T, encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        errors = [r for r in caplog.records if r.levelname == "ERROR"]
        assert len(errors) == 1, caplog.text
        assert "Kubernetes reads it as a number" in caplog.text
        assert "exists in this --config-dir" not in caplog.text
        assert list(out_dir.iterdir()) == []

    def test_int_name_past_str_digit_limit_is_caller_error(
            self, tmp_path, caplog):
        """#2430：超過 Python 4300 位 int↔str 上限的 int name 仍是 rc 2。

        推算舊版檔名時 int(...)／str(...) 會丟 ValueError；舊版對它同樣
        crash、沒寫過檔，所以不附舊檔提醒，也不得變成 traceback。Kubernetes
        client 把這麼長的數字解成字串，於是由名稱格式（長度）拒收。
        """
        name = "1" * 5000
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(
            self._K + f"metadata: {{name: {name}}}\n" + self._T,
            encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        errors = [r for r in caplog.records if r.levelname == "ERROR"]
        assert len(errors) == 1, caplog.text
        assert "is not a valid Kubernetes object name" in caplog.text
        assert "earlier version" not in caplog.text
        assert "4300" not in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("name", ["0b_", "0x_", "-0x_"])
    def test_unconstructable_int_name_is_caller_error(
            self, name, tmp_path, caplog):
        """#2430：YAML 判成 int 卻建不出值的 name 仍是 rc 2 單行訊息。

        推算舊版檔名要以 PyYAML 建這個 name，這些形狀會丟 ValueError；舊版
        對它們同樣 crash、沒寫過檔，所以不附舊檔提醒，也不得變成 traceback。
        Kubernetes client 把它們解成字串，由名稱格式拒收。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(
            self._K + f"metadata: {{name: {name}}}\n" + self._T,
            encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "is not a valid Kubernetes object name" in caplog.text
        assert "earlier version" not in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("spec", [
        pytest.param("", id="spec-missing"),
        pytest.param("spec: {}\n", id="spec-empty"),
    ])
    def test_absent_or_empty_spec_still_renders(self, spec, tmp_path):
        """#2371：缺 spec 維持既有行為，等同 `spec: {}`，只寫 header。

        只有「spec 存在但不是 mapping」算 caller error。缺 spec 與空 spec
        先前都是 rc 0 並寫出檔案，本次刻意不改。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + "metadata: {name: ok}\n" + spec,
                           encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == 0
        assert (out_dir / "ok.yaml").exists()

    @pytest.mark.parametrize("name, want", [
        pytest.param("2024-01-01", "2024-01-01", id="date"),
        # PyYAML's date resolver needs two-digit month/day: this one stays str.
        pytest.param("2024-1-1", "2024-1-1", id="date-short-is-str"),
        pytest.param('"2024-01-01"', "2024-01-01", id="quoted-date"),
        pytest.param('"010"', "010", id="quoted-int"),
        pytest.param("'0x1f'", "0x1f", id="quoted-hex"),
        pytest.param('"1.5"', "1.5", id="quoted-float"),
        pytest.param('"yes"', "yes", id="quoted-bool"),
        pytest.param('"null"', "null", id="quoted-null"),
        pytest.param("!!str 010", "010", id="tagged-str-int"),
        # Only a PLAIN scalar is RawPlain: an explicit tag still builds a
        # `date` object. Rendered `2024-01-01.yaml` before #2371 (rc 0).
        pytest.param('!!timestamp "2024-01-01"', "2024-01-01",
                     id="tagged-timestamp-date"),
    ])
    def test_string_name_renders_as_written(self, name, want, tmp_path):
        """#2371：字串 name 照原文收，檔名與檔頭用原文。

        未加引號的日期照原文收；加了引號（或 `!!str`）的值同理。明示
        `!!timestamp` 的日期是 `date` 物件，轉 isoformat 後照收。日期時間
        （含 `:`、大寫 `T`／`Z`、空白）不是 DNS-1123 名稱，#2396 起 rc 2，
        見 TestRenderCrNameFormat。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(
            self._K + f"metadata: {{name: {name}}}\n" + self._T,
            encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == 0
        assert [p.name for p in out_dir.iterdir()] == [f"{want}.yaml"]
        header = (out_dir / f"{want}.yaml").read_text(
            encoding="utf-8").split("\n")[0]
        assert header.endswith(f"/{want}"), header

    def test_a_non_write_exception_is_not_rc_0(self, tmp_path, caplog):
        """#2395：render 途中非 OutputWriteError 的例外一律 rc 2、不寫檔。

        先前 reconcile_one 只對 OutputWriteError 重拋，其餘例外只記一行
        `Failed to reconcile`，render_cr_file 照樣回 rc 0 卻一個檔都沒寫。
        會讓本測試轉紅的改動：把 reconcile_one 的重拋條件改回
        `cli and isinstance(e, OutputWriteError)`。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + "metadata: {name: ok}\n" + self._T,
                           encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        with mock.patch("da_assembler.dump_for_rewrite",
                        side_effect=RuntimeError("injected")):
            rc = render_cr_file(cr_path, out_dir)
        assert rc == EXIT_CALLER_ERROR
        assert "injected" in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("value", [
        pytest.param("0", id="int"),
        pytest.param("false", id="bool"),
        pytest.param("[x]", id="list"),
        pytest.param("x", id="scalar"),
    ])
    def test_a_non_mapping_tenant_is_caller_error(
            self, value, tmp_path, caplog):
        """#2395：租戶的值不是 mapping 時 rc 2、不寫檔。

        先前照原樣寫出，exporter 以 `cannot unmarshal !!int` 之類整份
        跳過該檔——連同一個檔裡其他合法租戶也不生效——而 rc 是 0。
        會讓本測試轉紅的改動：拿掉 `_spec_block_shape_error` 的租戶迴圈。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(
            self._K + "metadata: {name: ok}\nspec:\n  tenants:\n"
            "    t1: {mysql_connections: '70'}\n"
            f"    t2: {value}\n", encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "spec.tenants.t2 must be a mapping" in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("block", [
        pytest.param("defaults: [x]", id="defaults-list"),
        pytest.param("defaults: 1", id="defaults-int"),
        pytest.param("stateFilters: foo", id="stateFilters-scalar"),
        pytest.param("stateFilters: true", id="stateFilters-true"),
        pytest.param("tenants: [x]", id="tenants-list"),
        pytest.param("tenants: x", id="tenants-scalar"),
    ])
    def test_a_non_mapping_spec_block_is_caller_error(
            self, block, tmp_path, caplog):
        """#2395：spec 子區塊不是 mapping 時 rc 2、不寫檔。

        先前 render_cr_to_yaml 把它靜默丟掉、rc 0，CR 寫的內容沒有一項
        進到輸出。會讓本測試轉紅的改動：拿掉 `_spec_block_shape_error`
        的區塊迴圈。
        """
        key = block.split(":")[0]
        tenants = "" if key == "tenants" else "  tenants: {t1: {}}\n"
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(
            self._K + "metadata: {name: ok}\nspec:\n" + tenants
            + f"  {block}\n", encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert f"spec.{key} must be a mapping" in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("spec, body", [
        pytest.param("  tenants: {t1: {m: '1'}, t2: null}\n",
                     "tenants:\n  t1:\n    m: '1'\n  t2: null\n",
                     id="null-tenant"),
        pytest.param("  tenants: {t1: {m: '1'}}\n  defaults: null\n"
                     "  stateFilters: {}\n",
                     "tenants:\n  t1:\n    m: '1'\n",
                     id="null-and-empty-blocks"),
        pytest.param("  tenants: {t1: {m: '1'}}\n  defaults: 0\n"
                     "  stateFilters: []\n",
                     "tenants:\n  t1:\n    m: '1'\n",
                     id="falsy-blocks"),
    ])
    def test_null_or_empty_shapes_still_render(self, spec, body, tmp_path):
        """#2395 對照組：null 租戶與 null／空／falsy 區塊維持 rc 0、照舊寫出。

        exporter 把 null 租戶讀成空（da-guard served-values 實測 rc 0）。
        區塊值被 YAML 讀成 falsy（`defaults: 0`、`[]`）時當成空區塊丟掉，
        這是 #2331 釘住的行為（test_tenant_id_as_text.py），本票不改。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(self._K + "metadata: {name: ok}\nspec:\n" + spec,
                           encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == 0
        text = (out_dir / "ok.yaml").read_text(encoding="utf-8")
        assert text.split("\n", 2)[2] == body


# ── #2395 round 2: shapes below the blocks, judged against the exporter ──
#
# Each row is a CR `spec:` body and whether the exporter reads the file
# `render_cr_to_yaml` makes of it. The `oracle` test below re-measures every
# row with `da-guard served-values` (rc 3 = the exporter refused the file);
# the other tests pin the tool's rc for the same rows.

_T1 = "  tenants:\n    t1: {mysql_connections: '70'}\n"

# An explicitly tagged, quoted int (`!!int "…"`) is a Python int, dumped as
# its decimal digits; past 64 bits yaml.v3 reads those through ParseFloat.
# The float64 edge: (2^54-1)*2^970 is the halfway point above float64 max,
# rounded to even — i.e. up, to +Inf, which ParseFloat refuses (Go-measured).
_F64_EDGE = (2**54 - 1) * 2**970


def _tagged_int(n):
    return '  defaults: {cpu: !!int "%d"}\n' % n

#: (id, spec body below `_T1`) the exporter REFUSES once rendered.
_REFUSED = [
    ("defaults-true", "  defaults: {cpu: true}\n"),
    ("defaults-yes", "  defaults: {cpu: yes}\n"),
    ("defaults-word", "  defaults: {cpu: foo}\n"),
    ("defaults-quoted-number", "  defaults: {cpu: \"80\"}\n"),
    ("defaults-single-quoted", "  defaults: {cpu: '80'}\n"),
    ("defaults-quoted-empty", "  defaults: {cpu: ''}\n"),
    ("defaults-str-tag", "  defaults: {cpu: !!str 80}\n"),
    ("defaults-sexagesimal", "  defaults: {cpu: 1:30}\n"),
    ("defaults-date", "  defaults: {cpu: 2024-01-01}\n"),
    ("defaults-list", "  defaults: {cpu: [1]}\n"),
    ("defaults-map", "  defaults: {cpu: {a: 1}}\n"),
    # Number-looking texts yaml.v3 still refuses: digits outside the base,
    # overflow past float64 / uint64 / int64, a `_` not between digits.
    ("defaults-bad-octal-digit", "  defaults: {cpu: 0o8}\n"),
    ("defaults-bad-binary-digit", "  defaults: {cpu: 0b102}\n"),
    ("defaults-hex-digit-in-binary", "  defaults: {cpu: 0b1F}\n"),
    ("defaults-hex-digit-in-octal", "  defaults: {cpu: 0oF}\n"),
    ("defaults-float-overflow", "  defaults: {cpu: 1e400}\n"),
    ("defaults-negative-overflow", "  defaults: {cpu: -1e400}\n"),
    ("defaults-quoted-overflow", "  defaults: {cpu: \"1e400\"}\n"),
    ("defaults-hex-over-uint64", "  defaults: {cpu: 0x10000000000000000}\n"),
    ("defaults-negative-hex-over-int64",
     "  defaults: {cpu: -0xFFFFFFFFFFFFFFFF}\n"),
    ("defaults-octal-over-uint64",
     "  defaults: {cpu: 0o7777777777777777777777777}\n"),
    ("defaults-binary-65-bits", "  defaults: {cpu: 0b" + "1" * 65 + "}\n"),
    ("defaults-leading-underscore", "  defaults: {cpu: _1}\n"),
    ("defaults-underscore-dot", "  defaults: {cpu: _.5}\n"),
    ("defaults-dot-underscore", "  defaults: {cpu: ._5}\n"),
    ("defaults-dot-trailing-underscore", "  defaults: {cpu: .5_}\n"),
    # A non-ASCII letter whose lower() is two chars (U+0130); Go reads bytes.
    ("defaults-dotted-I", "  defaults: {cpu: 1İ}\n"),
    ("defaults-hex-dotted-I", "  defaults: {cpu: 0xİ}\n"),
    ("defaults-quoted-dotted-I", "  defaults: {cpu: \"73İ\"}\n"),
    ("defaults-kelvin-sign", "  defaults: {cpu: 1K}\n"),
    ("defaults-fullwidth-digit", "  defaults: {cpu: １}\n"),
    ("sf-reasons-omap", "  stateFilters: {x: {reasons: !!omap [a: 1]}}\n"),
    ("sf-reasons-pairs", "  stateFilters: {x: {reasons: !!pairs [a: 1]}}\n"),
    ("sf-int", "  stateFilters: {x: 1}\n"),
    ("sf-word", "  stateFilters: {x: foo}\n"),
    ("sf-empty-list", "  stateFilters: {x: []}\n"),
    ("sf-list", "  stateFilters: {x: [a]}\n"),
    ("sf-reasons-scalar", "  stateFilters: {x: {reasons: A}}\n"),
    ("sf-reasons-nested-list", "  stateFilters: {x: {reasons: [[a]]}}\n"),
    ("sf-reasons-map-item", "  stateFilters: {x: {reasons: [{a: 1}]}}\n"),
    ("sf-severity-list", "  stateFilters: {x: {severity: [a]}}\n"),
    ("sf-severity-map", "  stateFilters: {x: {severity: {a: 1}}}\n"),
    ("sf-default-state-list", "  stateFilters: {x: {default_state: [a]}}\n"),
]

#: (id, spec body below `_T1`) the exporter READS once rendered.
_READ = [
    ("defaults-int", "  defaults: {cpu: 80}\n"),
    ("defaults-float", "  defaults: {cpu: 80.5}\n"),
    ("defaults-negative", "  defaults: {cpu: -5}\n"),
    ("defaults-leading-dot", "  defaults: {cpu: .5}\n"),
    ("defaults-exponent", "  defaults: {cpu: 1e3}\n"),
    ("defaults-quoted-exponent", "  defaults: {cpu: \"1e3\"}\n"),
    ("defaults-underscore", "  defaults: {cpu: 1_000}\n"),
    ("defaults-hex", "  defaults: {cpu: 0x10}\n"),
    ("defaults-signed-hex", "  defaults: {cpu: +0x10}\n"),
    ("defaults-octal-0o", "  defaults: {cpu: 0o17}\n"),
    ("defaults-binary", "  defaults: {cpu: 0b101}\n"),
    ("defaults-leading-zero", "  defaults: {cpu: 010}\n"),
    ("defaults-leading-zero-8", "  defaults: {cpu: 08}\n"),
    ("defaults-null", "  defaults: {cpu: null}\n"),
    ("defaults-float-tag", "  defaults: {cpu: !!float 80}\n"),
    ("defaults-underflow", "  defaults: {cpu: 1e-400}\n"),
    ("defaults-max-uint64", "  defaults: {cpu: 0xFFFFFFFFFFFFFFFF}\n"),
    ("defaults-min-int64", "  defaults: {cpu: -0x8000000000000000}\n"),
    ("defaults-trailing-underscore", "  defaults: {cpu: 1_}\n"),
    ("defaults-dot-exponent-underscore", "  defaults: {cpu: .5e1_0}\n"),
    # yaml.v3's 0b / 0o fallback hands the rest to ParseInt(base 2 / 8),
    # which takes a sign there.
    ("defaults-binary-signed-digits", "  defaults: {cpu: 0b-1}\n"),
    ("defaults-octal-signed-digits", "  defaults: {cpu: 0o+7}\n"),
    ("defaults-tagged-int", _tagged_int(80)),
    ("sf-null", "  stateFilters: {x: null}\n"),
    ("sf-empty", "  stateFilters: {x: {}}\n"),
    ("sf-set", "  stateFilters: {x: !!set {reasons}}\n"),
    ("sf-reasons", "  stateFilters: {x: {reasons: [A]}}\n"),
    ("sf-reasons-scalars", "  stateFilters: {x: {reasons: [1, true, null]}}\n"),
    ("sf-reasons-null", "  stateFilters: {x: {reasons: null}}\n"),
    ("sf-severity-int", "  stateFilters: {x: {severity: 1}}\n"),
    ("sf-severity-bool", "  stateFilters: {x: {severity: true}}\n"),
    ("sf-default-state-int", "  stateFilters: {x: {default_state: 1}}\n"),
    ("sf-unknown-key", "  stateFilters: {x: {other: [a, {b: 1}]}}\n"),
    ("tenant-set", "    t2: !!set {cpu}\n"),
]

#: (id, spec body below `_T1`) Kubernetes clients' YAML→JSON conversion
#: (da-crdecode, #2476) refuses, so such a CR never reaches a cluster: an
#: explicit `!!int` past 64 bits (go-yaml), `.inf` / `.nan` (no JSON for
#: them). PyYAML read them, and the earlier rows judged them against the
#: exporter.
_DECODER_REFUSED = [
    ("defaults-inf", "  defaults: {cpu: .inf}\n"),
    ("defaults-nan", "  defaults: {cpu: .nan}\n"),
    ("defaults-tagged-int-20-digits", _tagged_int(2**64)),
    ("defaults-tagged-int-301-digits", _tagged_int(10**300)),
    ("defaults-tagged-int-401-digits", _tagged_int(10**400)),
    ("defaults-tagged-int-negative-401-digits", _tagged_int(-10**400)),
    ("defaults-tagged-int-f64-edge", _tagged_int(_F64_EDGE)),
    ("defaults-tagged-int-negative-f64-edge", _tagged_int(-_F64_EDGE)),
]

_CR_HEAD = "kind: ThresholdConfig\nmetadata: {name: ok}\nspec:\n"


def _write_cr(tmp_path, body):
    cr_path = tmp_path / "cr.yaml"
    cr_path.write_text(_CR_HEAD + _T1 + body, encoding="utf-8")
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    return cr_path, out_dir


@pytest.fixture(scope="module")
def da_guard(tmp_path_factory):
    """da-guard built from this checkout, or None when `go` is missing (the
    oracle test then skips; VIBE_REQUIRE_GO=1 fails instead)."""
    if shutil.which("go") is None:
        assert os.environ.get("VIBE_REQUIRE_GO") != "1", \
            "VIBE_REQUIRE_GO=1 but `go` is not on PATH"
        return None
    out = tmp_path_factory.mktemp("da-guard") / "da-guard"
    env = {**os.environ}
    env.setdefault("GOTOOLCHAIN", "auto")
    repo = Path(__file__).resolve().parents[2]
    subprocess.run(["go", "build", "-buildvcs=false", "-o", str(out),
                    "./cmd/da-guard"],
                   cwd=repo / "components" / "threshold-exporter" / "app",
                   env=env, check=True, timeout=600)
    return str(out)


class TestRenderCrExporterShapes:
    """#2395 第 2 輪：區塊以下、依 exporter 型別宣告深度的形狀。"""

    @pytest.mark.parametrize("block, key", [
        pytest.param("  tenants: ---\n", "tenants", id="tenants-doc-marker"),
        pytest.param("  defaults: ---\n", "defaults", id="defaults-doc-marker"),
        pytest.param("  stateFilters: ---\n", "stateFilters",
                     id="stateFilters-doc-marker"),
        pytest.param("  defaults: --- 0\n", "defaults", id="doc-marker-0"),
        pytest.param("  defaults: --- []\n", "defaults", id="doc-marker-list"),
        pytest.param("  defaults: --- no\n", "defaults", id="doc-marker-no"),
    ])
    def test_a_str_scalar_block_is_not_read_as_a_document(
            self, block, key, tmp_path, caplog):
        """F1：`---` 開頭的純量是字串（truthy 非 mapping），不是空文件。

        先前用 `yaml.safe_load(原文)` 判 falsy，把 `---` 讀成 None、
        `--- 0` 讀成 0，於是當空區塊丟掉、rc 0；`tenants: ---` 寫出 `{}`，
        租戶全部消失。會讓本測試轉紅的改動：把 `_FALSY_ABLE_TAGS` 的判斷
        換回對原文做 `yaml.safe_load`。
        """
        cr_path = tmp_path / "cr.yaml"
        tenants = "" if key == "tenants" else _T1
        cr_path.write_text(_CR_HEAD + tenants + block, encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert f"spec.{key} must be a mapping" in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("body", [pytest.param(b, id=i)
                                      for i, b in _REFUSED])
    def test_a_value_the_exporter_refuses_is_caller_error(
            self, body, tmp_path, caplog):
        """F2：exporter 會因值型別整份拒收的 defaults／stateFilters → rc 2。

        `defaults` 是 `map[string]float64`、`state_filters` 是
        `map[string]StateFilter`（pkg/config/types.go）。會讓本測試轉紅的
        改動：拿掉 `_default_value_error` 或 `_state_filter_error` 的呼叫。
        """
        cr_path, out_dir = _write_cr(tmp_path, body)
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "the exporter skips the whole rendered file" in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("body", [pytest.param(b, id=i)
                                      for i, b in _READ])
    def test_a_value_the_exporter_reads_still_renders(self, body, tmp_path):
        """F2／F3 對照組：exporter 讀得了的形狀維持 rc 0 並寫出檔案。

        含 F3 的 `t2: !!set {cpu}`：Python 讀成 set，yaml.v3 讀成
        mapping，exporter 照收。會讓本測試轉紅的改動：把數字判斷收緊成
        PyYAML 的型別（`1e3`、`0o17`、`08` 會被誤擋），或租戶層不收 set。
        """
        cr_path, out_dir = _write_cr(tmp_path, body)
        assert render_cr_file(cr_path, out_dir) == 0
        assert (out_dir / "ok.yaml").exists()

    @pytest.mark.parametrize("body", [pytest.param(b, id=i)
                                      for i, b in _DECODER_REFUSED])
    def test_a_value_the_decoder_refuses_is_caller_error(
            self, body, tmp_path, caplog):
        """#2476：Kubernetes client 的 YAML→JSON 拒收的值 → rc 2、不寫檔，
        da-crdecode 的 stderr 照轉、每行帶前綴。

        先前以 PyYAML 讀得到這些值，於是依 exporter 判定（`.inf` 照寫）。
        會讓本測試轉紅的改動：改回 PyYAML 讀 CR，或不轉 stderr。
        """
        cr_path, out_dir = _write_cr(tmp_path, body)
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert f"Failed to parse {cr_path}: da-crdecode exited 2" \
            in caplog.text
        assert "  da-crdecode| da-crdecode: " in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("body, refused", [
        *[pytest.param(b, True, id=i) for i, b in _REFUSED],
        *[pytest.param(b, False, id=i) for i, b in _READ],
    ])
    def test_the_rows_match_the_exporter(
            self, body, refused, tmp_path, da_guard):
        """上面兩張表的分類本身，以 exporter 的解碼器重量。

        把 CR 以 da-crdecode 解碼（與 --render-cr 同一個入口）、再以
        render_cr_to_yaml（不經 --render-cr 的檢查）寫成檔，餵
        `da-guard served-values`：拒收的列必須 rc 3，讀得了的列必須
        rc 0。表錯了（例如把 exporter 讀得了的形狀列進拒收）這裡會紅。
        """
        if da_guard is None:
            pytest.skip("go not on PATH (set VIBE_REQUIRE_GO=1 to fail)")
        import da_assembler
        cr_path, _ = _write_cr(tmp_path, body)
        cr, _ = da_assembler.decode_cr(cr_path)
        conf = tmp_path / "conf"
        conf.mkdir()
        (conf / "ok.yaml").write_text(
            da_assembler.render_cr_to_yaml(cr), encoding="utf-8")
        r = subprocess.run([da_guard, "served-values", "--config-dir",
                            str(conf)], capture_output=True, text=True,
                           encoding="utf-8", timeout=120)
        assert r.returncode == (3 if refused else 0), r.stdout + r.stderr

    def test_the_integer_parse_stops_at_the_first_overflow(self):
        """整數累加一超過 2^64 就返回，不掃到字串尾端（這支是確定性的守衛；
        它綁在 `for c in s` 逐字元迭代的實作形狀上，改成索引或 bytes 迭代時
        `seen` 會變 0，要一起改這支）。

        先前累加 bignum 到結尾才比較，極長數字是二次方時間（30 萬位端到端
        約 17.7 s）。2^64 有 20 位，20 個 9 已經溢位，所以只該讀 20 個字元。
        會讓本測試轉紅的改動：拿掉 `_go_parse_uint` 迴圈內的 cutoff 檢查。
        """
        import da_assembler

        class Counting(str):
            seen = 0

            def __iter__(self):
                for c in str.__iter__(self):
                    Counting.seen += 1
                    yield c

        text = Counting("9" * 1000)
        assert da_assembler._go_parse_uint(text, 10) is None
        assert Counting.seen == 20

    def test_a_very_long_number_is_refused_promptly(self, tmp_path, caplog):
        """端到端：30 萬位的整數 rc 2（超出 uint64，exporter 拒收）。

        計時上限刻意寬鬆（修前約 17.7 s，修後約 0.1–2 s，視 coverage 與 CPU
        搶佔而定）：它只擋「又退回二次方時間」這種量級的回歸；確定性的守衛是
        上一支 `test_the_integer_parse_stops_at_the_first_overflow`。"""
        import time
        cr_path, out_dir = _write_cr(
            tmp_path, "  defaults: {cpu: " + "9" * 300_000 + "}\n")
        start = time.monotonic()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert time.monotonic() - start < 12
        assert list(out_dir.iterdir()) == []


#: #2476: (id, text, spec) — `TestRenderCrNameFormat._render_text` input
#: whose null mapping key survives go-yaml v2's decode, so Kubernetes
#: refuses the document (each checked against sigs.k8s.io/yaml v1.6.0
#: YAMLToJSON). spec None is the class's default `_SPEC`.
NULL_KEY_REFUSED = [
    ("null", "metadata: {name: ok}\n", "spec:\n  tenants: {null: {}}\n"),
    ("tilde", "metadata: {name: ok}\n", "spec:\n  tenants: {~: {}}\n"),
    ("Null", "metadata: {name: ok}\n", "spec:\n  tenants:\n    t1: {Null: 1}\n"),
    ("empty-key", "metadata: {name: ok}\n",
     "spec:\n  tenants:\n    t1:\n      ? \n      : 1\n"),
    ("tagged-null-key", "metadata: {name: ok}\n",
     "spec:\n  tenants:\n    t1: {!!null ~: 1}\n"),
    ("in-metadata", "metadata:\n  name: ok\n  labels: {~: x}\n", None),
    ("through-alias", "x: &n ~\nmetadata: {name: ok}\n",
     "spec:\n  tenants: {*n : {}}\n"),
    ("merge-alias", "b: &b {~: 1}\nb: 0\nx: {<<: *b}\nmetadata: {name: ok}\n",
     None),
    ("merge-list", "b: &b {~: 1}\nb: 0\nx: {<<: [*b]}\nmetadata: {name: ok}\n",
     None),
    ("merge-then-same-key", "x: {<<: {~: 1}, ~: 2}\nmetadata: {name: ok}\n",
     None),
    ("merge-list-earlier-wins",
     "x: {<<: [{k: {~: 1}}, {k: 1}]}\nmetadata: {name: ok}\n", None),
    ("in-sequence", "x: [{~: 1}]\nmetadata: {name: ok}\n", None),
    ("two-null-keys", "x: {~: 1, null: 2}\nmetadata: {name: ok}\n", None),
    ("replaced-by-null-too", "x: {k: {~: 1}, k: {~: 2}}\nmetadata: {name: ok}\n",
     None),
]
#: Kubernetes ACCEPTS these (#2476): the null key sits in a value a later
#: duplicate key (or a `<<` merge, in go-yaml's order) replaces, so go-yaml
#: decodes it away; or the key has the non-specific `!` tag, which PyYAML
#: reads as null and go-yaml as a string. The PyYAML-based check refused
#: them on purpose (telling them apart in Python did not converge); decoded
#: by da-crdecode, they render, as they do in a cluster.
NULL_KEY_K8S_ACCEPTS = [
    ("replaced-duplicate", "metadata: {name: ok}\n",
     "spec:\n  tenants: {null: {}}\n  tenants: {t1: {}}\n"),
    ("replaced-top-level", "x: {~: 1}\nx: 2\nmetadata: {name: ok}\n", None),
    ("merge-source-replaced-and-overridden",
     "b: &b {k: {~: 1}}\nb: 0\nx: {<<: *b, k: 1}\nmetadata: {name: ok}\n",
     None),
    ("merge-after-explicit",
     "x: {k: {~: 1}, <<: {k: 2}}\nmetadata: {name: ok}\n", None),
    ("merge-list-earlier-wins",
     "x: {<<: [{k: 1}, {k: {~: 1}}]}\nmetadata: {name: ok}\n", None),
    ("int-spellings", "x: {1: {~: 1}, 0x1: 2}\nmetadata: {name: ok}\n", None),
    ("octal-spelling", "x: {010: {~: 1}, 8: 2}\nmetadata: {name: ok}\n", None),
    ("v2-bool-spellings", "x: {y: {~: 1}, yes: 2}\nmetadata: {name: ok}\n",
     None),
    # go-yaml reads `! ~` as the string "~".
    ("non-specific-tag", "x: {! ~: 1}\nmetadata: {name: ok}\n", None),
]
#: Keys and values that only LOOK null: Kubernetes accepts them and so
#: does the tool.
NULL_KEY_ACCEPTED = [
    ("quoted-null", "x: {\"null\": 1}\nmetadata: {name: ok}\n", None),
    ("quoted-tilde", "x: {\"~\": 1}\nmetadata: {name: ok}\n", None),
    ("str-tagged-null", "x: {!!str null: 1}\nmetadata: {name: ok}\n", None),
    ("null-value", "x: {k: null, j: ~}\nmetadata: {name: ok}\n", None),
    ("nUll-is-a-string", "x: {nUll: 1}\nmetadata: {name: ok}\n", None),
]


class TestRenderCrNameFormat:
    """#2396：`--render-cr` 以 Kubernetes 的規則驗 name／namespace。

    name 直接當輸出檔名、name 與 namespace 都寫進檔頭註解。先前不驗：
    `../escaped` rc 0 並寫到 `--config-dir` 之外；含換行的 name／namespace
    把檔頭註解斷行，輸出多出頂層鍵。現在 name 須是 RFC 1123 subdomain、
    namespace（有給時）須是 RFC 1123 label，否則 rc 2 且不寫任何檔案。

    會讓本組反例轉紅的改動：拿掉 render_cr_file 裡的
    `_is_dns1123_subdomain` / `_is_dns1123_label` 檢查。
    """

    @staticmethod
    def _run(tmp_path, metadata_yaml):
        """寫 CR、渲染，回傳 (rc, 渲染前後 tmp_path 下新增的檔案)。

        輸出目錄放兩層深，逃出 `--config-dir` 的檔案也還在 tmp_path 內，
        才量得到「目錄內外都沒有新檔」。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(
            "kind: ThresholdConfig\nmetadata:\n" + metadata_yaml
            + "spec:\n  tenants:\n    t1: {}\n", encoding="utf-8")
        out_dir = tmp_path / "work" / "out"
        out_dir.mkdir(parents=True)
        before = {p for p in tmp_path.rglob("*") if p.is_file()}
        rc = render_cr_file(cr_path, out_dir)
        after = {p for p in tmp_path.rglob("*") if p.is_file()}
        return rc, sorted(p.relative_to(tmp_path).as_posix()
                          for p in after - before)

    @staticmethod
    def _q(text):
        """YAML 雙引號字串（JSON 字串是合法的 YAML flow scalar）。"""
        return json.dumps(text)

    @pytest.mark.parametrize("name", [
        pytest.param("../escaped", id="dotdot-escape"),
        pytest.param("sub/x", id="slash"),
        pytest.param("x\nevil: 1", id="newline-injects-key"),
        pytest.param("ok\n", id="trailing-newline"),
        pytest.param("Foo", id="uppercase"),
        pytest.param("a_b", id="underscore"),
        pytest.param("-a", id="leading-dash"),
        pytest.param("a-", id="trailing-dash"),
        pytest.param("a..b", id="empty-label"),
        pytest.param(".a", id="leading-dot"),
        pytest.param("a" * 254, id="len-254"),
    ])
    def test_invalid_name_is_caller_error(self, name, tmp_path, caplog):
        rc, new_files = self._run(tmp_path, f"  name: {self._q(name)}\n")
        assert rc == EXIT_CALLER_ERROR
        assert new_files == []
        assert "is not a valid Kubernetes object name" in caplog.text

    @pytest.mark.parametrize("namespace", [
        pytest.param("n\nevil: 1", id="newline-injects-key"),
        pytest.param("ns\n", id="trailing-newline"),
        pytest.param("Team", id="uppercase"),
        pytest.param("a.b", id="dot-not-in-label"),
        pytest.param("../x", id="dotdot"),
        pytest.param("a" * 64, id="len-64"),
    ])
    def test_invalid_namespace_is_caller_error(
            self, namespace, tmp_path, caplog):
        rc, new_files = self._run(
            tmp_path, f"  name: ok\n  namespace: {self._q(namespace)}\n")
        assert rc == EXIT_CALLER_ERROR
        assert new_files == []
        assert "is not a valid Kubernetes namespace name" in caplog.text

    @pytest.mark.parametrize("namespace, kind", [
        pytest.param("8", "number", id="int"),
        pytest.param("010", "number", id="int-octal"),
        pytest.param("true", "boolean", id="bool-true"),
        pytest.param("yes", "boolean", id="bool-yes"),
        pytest.param("1.5", "number", id="float"),
        pytest.param("0o17", "number", id="0o17"),
        pytest.param("y", "boolean", id="y"),
    ])
    def test_non_string_namespace_is_caller_error(
            self, namespace, kind, tmp_path, caplog):
        """未加引號、Kubernetes 讀成數字／布林的 namespace 比照 name，rc 2。

        型別取自 da-crdecode（#2476）。會讓本組轉紅的改動：拿掉 namespace
        的型別檢查（`8` 經解碼是數字，只靠格式檢查會在 `_is_dns1123_label`
        丟 TypeError），或改回以 YAML 1.1 判型別（`0o17`、`y` 轉紅）。
        """
        rc, new_files = self._run(
            tmp_path, f"  name: ok\n  namespace: {namespace}\n")
        assert rc == EXIT_CALLER_ERROR
        assert new_files == []
        assert "metadata.namespace must be a string" in caplog.text
        assert f"Kubernetes reads it as a {kind}" in caplog.text
        assert "Quoting makes a scalar a string" in caplog.text

    @pytest.mark.parametrize("written", [
        pytest.param("team", id="word"),
        pytest.param('"team"', id="quoted-word"),
        pytest.param("0", id="zero"),
    ])
    def test_tagged_null_with_a_value_is_caller_error(
            self, written, tmp_path, caplog):
        """`!!null team`：PyYAML 建成 None，Kubernetes（YAML→JSON）拒收。

        只有原文為空或 null 字面時才算「未設」。由 da-crdecode 拒收（#2476），
        錯誤原文照轉。會讓本組轉紅的改動：改回以 PyYAML 讀 CR 並把 None
        一律正規化成缺鍵，此時 rc 0 並照寫。
        """
        rc, new_files = self._run(
            tmp_path, f"  name: ok\n  namespace: !!null {written}\n")
        assert rc == EXIT_CALLER_ERROR
        assert new_files == []
        assert "as a !!null" in caplog.text
        assert "  da-crdecode| " in caplog.text

    _SPEC = "spec:\n  tenants:\n    t1: {}\n"

    def _render_text(self, tmp_path, text, spec=None):
        """整份 CR 文字 → (rc, 輸出位元組或 None)。*spec* 預設 `_SPEC`。"""
        tmp_path.mkdir(parents=True, exist_ok=True)
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(
            "kind: ThresholdConfig\n" + text
            + (self._SPEC if spec is None else spec), encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        rc = render_cr_file(cr_path, out_dir)
        out = out_dir / "ok.yaml"
        files = list(out_dir.iterdir())
        assert files in ([], [out]), files
        return rc, (out.read_bytes() if files else None)

    @pytest.mark.parametrize("text", [
        pytest.param("base: &b {namespace: null}\n"
                     "metadata: {<<: *b, name: ok}\n", id="merge-alias-null"),
        pytest.param("base: &b {namespace: ~}\n"
                     "metadata: {<<: *b, name: ok}\n", id="merge-alias-tilde"),
        pytest.param("base: &b\n  namespace:\n"
                     "metadata:\n  <<: *b\n  name: ok\n",
                     id="merge-alias-empty"),
        pytest.param("base: &b {namespace: null}\n"
                     "metadata: {<<: [*b], name: ok}\n", id="merge-list"),
        pytest.param("metadata: {<<: {namespace: null}, name: ok}\n",
                     id="merge-inline"),
        pytest.param("<<: {metadata: {name: ok, namespace: null}}\n",
                     id="merge-top-level"),
    ])
    def test_namespace_unset_through_merge_renders_as_absent(
            self, text, tmp_path):
        """#2396：namespace 只經 `<<` merge 提供、值為 null 時也是「未設」。

        Kubernetes（YAML→JSON）同樣展開 merge，這些 CR 建得進叢集。會讓
        本組轉紅的改動：`!!null` 檢查改回只定位 namespace 節點原文（merge
        進來的節點找不到原文 → 被誤擋 rc 2）。
        """
        rc, want = self._render_text(tmp_path / "absent",
                                     "metadata: {name: ok}\n")
        assert rc == 0
        rc, got = self._render_text(tmp_path / "merged", text)
        assert rc == 0
        assert got == want

    @pytest.mark.parametrize("text, spec", [
        pytest.param("metadata:\n  name: ok\n  namespace: !!null team\n"
                     "  namespace: null\n", None, id="duplicate-key"),
        pytest.param("metadata:\n  name: ok\n  namespace: !!null team\n"
                     "metadata:\n  name: ok\n", None,
                     id="earlier-metadata-block"),
        pytest.param("metadata: {name: ok}\nextra: !!null team\n", None,
                     id="elsewhere-in-document"),
        # Key position / sequence item: each covers one branch of the
        # graph walk (mapping keys, sequence items).
        pytest.param("metadata: {name: ok}\n",
                     "spec:\n  tenants: {!!null team: {}}\n",
                     id="mapping-key"),
        pytest.param("metadata: {name: ok}\n",
                     "spec:\n  tenants:\n    t1: [!!null team]\n",
                     id="sequence-item"),
        pytest.param("metadata: {name: ok}\n",
                     "spec:\n  tenants: {!!null team}\n",
                     id="flow-lone-key"),
    ])
    def test_tagged_null_anywhere_is_caller_error(self, text, spec, tmp_path,
                                                   caplog):
        """go-yaml 對文件任何位置的 `!!null <值>` 都整份拒收。

        載入時「後者勝」會把前一個重複鍵或前一個 metadata 區塊丟掉，只看
        最後生效的 namespace 會放行。#2476 起由 da-crdecode 判定。會讓本組
        轉紅的改動：改回 PyYAML 讀 CR、只檢查 namespace 節點。
        """
        rc, got = self._render_text(tmp_path, text, spec)
        assert rc == EXIT_CALLER_ERROR
        assert got is None
        assert "cannot decode !!str `team` as a !!null" in caplog.text

    @pytest.mark.parametrize("text", [
        pytest.param("metadata: {name: ok\n", id="syntax"),
        pytest.param("metadata:\n  name: ok\x01\n", id="control-char"),
        pytest.param("metadata:\n  name: *nope\n", id="undefined-alias"),
    ])
    def test_yaml_error_names_the_file(self, text, tmp_path, caplog):
        """YAML 錯誤訊息點名 CR 檔路徑（da-crdecode 的 stderr 照轉，#2476）。

        會讓本組轉紅的改動：不轉 da-crdecode 的 stderr，或改由 stdin 餵它
        （訊息就不含路徑）。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text("kind: ThresholdConfig\n" + text,
                           encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert f"Failed to parse {cr_path}: da-crdecode exited 2" \
            in caplog.text
        assert f"  da-crdecode| da-crdecode: {cr_path}: yaml: " in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("body", [
        pytest.param(b"metadata: {name: ok}\nspec:\n  defaults:\n"
                     b'    cpu: "\xff"\n', id="not-utf8"),
        pytest.param(b"metadata: {name: ok}\n"
                     b"spec: {defaults: {cpu: !!int team}}\n",
                     id="int-tag-ValueError"),
        pytest.param(b"metadata: {name: ok}\n"
                     b"spec: {defaults: {cpu: !!bool team}}\n",
                     id="bool-tag-KeyError"),
        pytest.param(b"metadata: {name: ok}\n"
                     b"spec: {defaults: {cpu: !!timestamp team}}\n",
                     id="timestamp-tag-AttributeError"),
        pytest.param(b'metadata: {name: ok}\n'
                     b'spec: {defaults: {cpu: !!int ""}}\n',
                     id="empty-int-IndexError"),
        pytest.param(b'metadata:\n  name: !!timestamp "2024-13-01T00:00:00Z"\n',
                     id="bad-month-name"),
        pytest.param(b'metadata: {name: ok}\nspec: {defaults: {cpu: !!int "'
                     + b"9" * 5000 + b'"}}\n', id="quoted-over-4300-digits"),
        pytest.param(b"metadata: {name: ok}\nspec: {defaults: &a [1, *a]}\n",
                     id="self-referencing-anchor"),
        pytest.param(b"metadata: {name: ok}\nspec: {defaults: "
                     + b"[" * 3000 + b"]" * 3000 + b"}\n",
                     id="deep-nesting"),
    ])
    def test_value_that_cannot_be_read_is_caller_error(self, body, tmp_path,
                                                        caplog):
        """#2476：讀不出值的 CR → rc 2、錯誤點名檔案、不寫檔，不是 traceback。

        以 PyYAML 讀時，這些形狀丟的例外（`UnicodeDecodeError`／
        `ValueError`／`KeyError`／`AttributeError`／`IndexError`／
        `RecursionError`）曾穿出 `render_cr_file`（rc 1）。現在由
        da-crdecode 拒收，或 Python 的 JSON 讀取深度不夠（deep-nesting）。
        會讓本組轉紅的改動：拿掉 `CrDecodeError` 或 `RecursionError` 的
        except。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_bytes(b"kind: ThresholdConfig\n" + body)
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert f"Failed to parse {cr_path}" in caplog.text
        assert list(out_dir.iterdir()) == []

    def test_deep_nesting_message_names_the_tool_limit(self, tmp_path,
                                                       caplog):
        """#2476：巢狀過深是本工具（Python 的 JSON 讀取）的上限，不是 K8s
        拒收：da-crdecode 讀得了這份文件。

        訊息要能讓人分辨「量不到」與「拒收」。會讓本組轉紅的改動：拿掉
        `RecursionError` 的專屬分支（落到通用分支，訊息只剩例外原文）。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text("kind: ThresholdConfig\nmetadata: {name: ok}\n"
                           "spec: {defaults: " + "[" * 3000 + "]" * 3000
                           + "}\n", encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "nested too deeply for this tool to read" in caplog.text

    def test_deep_nesting_that_reads_names_the_tool_limit_at_render(
            self, tmp_path, caplog):
        """#2476：巢狀深到讀得進來、但 render 時用盡 stack（約 350–480
        層）時，訊息同樣註明是本工具的上限。400 層落在兩個上限之間，
        依賴 Python 的預設 recursion limit。

        會讓本組轉紅的改動：拿掉 render 階段 `RecursionError` 的專屬分支
        （落回 `Failed to render …: maximum recursion depth exceeded`）。
        """
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text("kind: ThresholdConfig\nmetadata: {name: ok}\n"
                           "spec: {tenants: {t1: {k: " + "{a: " * 400 + "1"
                           + "}" * 400 + "}}}\n", encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "Failed to parse" not in caplog.text
        assert "nested too deeply for this tool to render" in caplog.text

    @pytest.mark.parametrize("text, spec", [
        pytest.param(text, spec, id=case_id)
        for case_id, text, spec in NULL_KEY_REFUSED])
    def test_null_mapping_key_is_caller_error(self, text, spec, tmp_path,
                                              caplog):
        """#2476：K8s（sigs.k8s.io/yaml YAMLToJSON）對 decode 後仍在的 null
        mapping key 整份拒收（`unsupported map key of type: <nil>`）。

        先前 `--render-cr` rc 0 並寫出檔案。#2476 起由 da-crdecode（同一個
        YAMLToJSON）拒收。會讓本組轉紅的改動：改回以 PyYAML 讀 CR。
        """
        rc, got = self._render_text(tmp_path, text, spec)
        assert rc == EXIT_CALLER_ERROR
        assert got is None
        assert "unsupported map key of type" in caplog.text

    @pytest.mark.parametrize("text, spec", [
        pytest.param(text, spec, id=case_id)
        for case_id, text, spec in NULL_KEY_K8S_ACCEPTS])
    def test_null_key_kubernetes_accepts_renders(self, text, spec, tmp_path):
        """#2476：K8s 接受的 null key 寫法（重複鍵與 `<<` merge 解開後被其他
        鍵取代的值、非特定標籤 `!`；見 `NULL_KEY_K8S_ACCEPTS`）照常 rc 0。

        先前以 PyYAML 判 null key，只能一律 fail-closed 拒收。會讓本組轉紅的
        改動：改回以 PyYAML 讀 CR 並判 null key。
        """
        rc, got = self._render_text(tmp_path, text, spec)
        assert rc == 0
        assert got is not None

    @pytest.mark.parametrize("text, spec", [
        pytest.param(text, spec, id=case_id)
        for case_id, text, spec in NULL_KEY_ACCEPTED])
    def test_key_that_only_looks_null_renders(self, text, spec, tmp_path):
        """對照組：加引號、`!!str`、`nUll` 的鍵與 null 的值都不是 null key。

        會讓本組轉紅的改動：以原文而不是 tag 判 null（`"null"`、
        `!!str null` 會被誤擋），或把 null 值也當成 null key。
        """
        rc, got = self._render_text(tmp_path, text, spec)
        assert rc == 0
        assert got is not None

    def test_deep_merge_chain_does_not_traceback(self, tmp_path):
        """#2476：merge 鏈很深、compose 卻很淺（40 個 anchor，各自包 30 層
        `<<`）的文件不能 traceback：rc 0 或 rc 2 都可，不能丟例外。

        會讓本組轉紅的改動：在讀檔的 try 之外用遞迴展開 `<<` merge。實測
        本工具 rc 0（K8s 也接受）；結果依賴預設 recursion limit，所以兩種
        rc 都接受。
        """
        lines = ["a0: &a0 {k: 1}"]
        for i in range(1, 41):
            lines.append(f"a{i}: &a{i} " + "{<<: " * 30 + f"*a{i - 1}"
                         + "}" * 30)
        rc, _got = self._render_text(
            tmp_path, "\n".join(lines) + "\nmetadata: {name: ok}\n")
        assert rc in (0, EXIT_CALLER_ERROR)

    def test_mapping_as_key_is_caller_error(self, tmp_path):
        """key 本身是 mapping（內含 null key）：K8s 拒收，本工具讀檔即 rc 2。"""
        rc, got = self._render_text(
            tmp_path, "metadata: {name: ok}\nx: {? {~: 1} : 1}\n")
        assert rc == EXIT_CALLER_ERROR
        assert got is None

    def test_quoted_null_key_is_a_string(self, tmp_path):
        """對照組：加引號的 `"null":`／`"~":` 是字串鍵，K8s 接受，照常 rc 0。"""
        rc, got = self._render_text(
            tmp_path, "metadata: {name: ok}\n",
            "spec:\n  tenants:\n    t1: {\"null\": \"1\", \"~\": \"2\"}\n")
        assert rc == 0
        assert got is not None

    @pytest.mark.parametrize("namespace", [
        pytest.param('"8"', id="quoted-int"),
        pytest.param("'yes'", id="quoted-bool"),
    ])
    def test_quoted_numeric_namespace_renders(self, namespace, tmp_path):
        """對照組：加了引號就是字串，且是合法 label，rc 0。"""
        rc, new_files = self._run(
            tmp_path, f"  name: ok\n  namespace: {namespace}\n")
        assert rc == 0
        assert new_files == ["work/out/ok.yaml"]

    @pytest.mark.parametrize("ns_line", [
        pytest.param("  namespace: null\n", id="null"),
        pytest.param("  namespace: NULL\n", id="null-upper"),
        pytest.param("  namespace: Null\n", id="null-title"),
        pytest.param("  namespace: ~\n", id="tilde"),
        pytest.param("  namespace:\n", id="empty-value"),
        pytest.param('  namespace: ""\n', id="empty-string"),
        pytest.param("  namespace: !!null\n", id="tagged-null-empty"),
        pytest.param("  namespace: !!null null\n", id="tagged-null-null"),
    ])
    def test_unset_namespace_renders_as_absent(
            self, ns_line, tmp_path, caplog):
        """null／空值／`""` 在 Kubernetes 是「未設」，CR 建得進叢集。

        比照沒寫 namespace：rc 0，輸出與缺鍵時逐位元組相同（檔頭 `?`），
        log 為 `default`。會讓本組轉紅的改動：拿掉 render_cr_file 裡把
        None／`""` 正規化成缺鍵的那一步（先前 rc 2；若只放行不正規化，
        檔頭會寫 `None/ok`、`/ok`）。
        """
        caplog.set_level("INFO")
        absent_dir = tmp_path / "absent"
        absent_dir.mkdir()
        rc, _ = self._run(absent_dir, "  name: ok\n")
        assert rc == 0
        want = (absent_dir / "work" / "out" / "ok.yaml").read_bytes()
        caplog.clear()

        rc, new_files = self._run(tmp_path, "  name: ok\n" + ns_line)
        assert rc == 0
        assert new_files == ["work/out/ok.yaml"]
        assert (tmp_path / "work" / "out" / "ok.yaml").read_bytes() == want
        assert "Rendered default/ok" in caplog.text

    @pytest.mark.parametrize("name, namespace", [
        pytest.param("ok", None, id="plain-no-namespace"),
        pytest.param("a.b-c", "team-1", id="dot-and-dash"),
        pytest.param("0-9.x", "0", id="digits"),
        pytest.param("x", "a" * 63, id="namespace-len-63"),
    ])
    def test_valid_names_still_render(self, name, namespace, tmp_path):
        """must-trigger 對照組：合法 name 照舊 rc 0，寫進 --config-dir。"""
        meta = f"  name: {self._q(name)}\n"
        if namespace is not None:
            meta += f"  namespace: {self._q(namespace)}\n"
        rc, new_files = self._run(tmp_path, meta)
        assert rc == 0
        assert new_files == [f"work/out/{name}.yaml"]
        header = (tmp_path / "work" / "out" / f"{name}.yaml").read_text(
            encoding="utf-8").split("\n")[0]
        # 缺 namespace 時檔頭沿用既有的 `?`（#2396 不改這條）。
        assert header.endswith(f" {namespace or '?'}/{name}"), header

    @staticmethod
    def _long_name(length):
        """`length` 字元、由 63 字元 label 以 `.` 串成的合法 subdomain。"""
        name = ".".join(["a" * 63] * 5)[:length - 1] + "b"
        assert len(name) == length
        return name

    @pytest.mark.parametrize("length, want", [
        pytest.param(253, True, id="len-253-accepted"),
        pytest.param(254, False, id="len-254-refused"),
    ])
    def test_name_length_boundary(self, length, want):
        """253 字元邊界，直接量驗證函式。

        不走 render_cr_file：`<253 字元>.yaml` 超過多數檔案系統的
        NAME_MAX（255），連 dry-run 的 `dest.exists()` 都會先丟
        ENAMETOOLONG，量到的就不是本檢查了。len-254 的 rc 2 由
        test_invalid_name_is_caller_error 端到端量。"""
        assert _is_dns1123_subdomain(self._long_name(length)) is want

    @pytest.mark.parametrize("length, want", [
        pytest.param(63, True, id="len-63-accepted"),
        pytest.param(64, False, id="len-64-refused"),
    ])
    def test_namespace_length_boundary(self, length, want):
        assert _is_dns1123_label("a" * length) is want

    def test_long_valid_name_renders(self, tmp_path):
        """端到端對照組：檔名塞得進 NAME_MAX 的最長合法 name（250）rc 0。"""
        name = self._long_name(250)
        rc, new_files = self._run(tmp_path, f"  name: {name}\n")
        assert rc == 0
        assert new_files == [f"work/out/{name}.yaml"]


class TestRenderCrDecoder:
    """#2476：`--render-cr` 經 da-crdecode（Kubernetes client 的 YAML→JSON）
    解碼 CR 的契約：spec.profile、多文件、找不到／跑不起來的 binary、
    stderr 照轉、逾時。"""

    _CR = ("apiVersion: dynamicalerting.io/v1alpha1\nkind: ThresholdConfig\n"
           "metadata: {name: ok}\nspec:\n  tenants:\n    t1: {}\n")

    @staticmethod
    def _write(tmp_path, text):
        cr_path = tmp_path / "cr.yaml"
        cr_path.write_text(text, encoding="utf-8")
        out_dir = tmp_path / "out"
        out_dir.mkdir()
        return cr_path, out_dir

    @staticmethod
    def _fake_binary(tmp_path, monkeypatch, body):
        """一支冒充 da-crdecode 的 Python 腳本，`$DA_CRDECODE_BINARY` 指向它。"""
        fake = tmp_path / "fake-crdecode"
        fake.write_text(f"#!{sys.executable}\nimport sys, time\n{body}\n",
                        encoding="utf-8")
        fake.chmod(0o755)
        monkeypatch.setenv("DA_CRDECODE_BINARY", str(fake))

    def test_spec_profile_is_caller_error(self, tmp_path, caplog):
        """CRD 宣告了 `spec.profile`，但兩條路徑都不 render 它。

        先前 rc 0、輸出不含 profile。會讓本測試轉紅的改動：拿掉
        render_cr_file 的 spec.profile 檢查。
        """
        cr_path, out_dir = self._write(tmp_path,
                                       self._CR + "  profile: gold\n")
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "spec.profile is set, but it is not rendered" in caplog.text
        assert "Set _profile on each tenant" in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("line", ["  profile: null\n", "  profile: ~\n",
                                      "  profile:\n"])
    def test_null_spec_profile_renders(self, line, tmp_path):
        """對照組：null 的 profile 等於沒寫，照常 rc 0。"""
        cr_path, out_dir = self._write(tmp_path, self._CR + line)
        assert render_cr_file(cr_path, out_dir) == 0
        assert (out_dir / "ok.yaml").exists()

    @pytest.mark.parametrize("tail", [
        pytest.param("---\nkind: x\n", id="two-documents"),
        pytest.param("---\n", id="trailing-separator"),
    ])
    def test_more_than_one_document_is_caller_error(
            self, tail, tmp_path, caplog):
        """YAMLToJSON 只讀第一份文件、靜默丟掉其餘；da-crdecode 另外數文件，
        多於一份就拒收（與先前以 PyYAML 讀時同為 rc 2；#2529 另議）。

        會讓本測試轉紅的改動：拿掉 da-crdecode 的 countDocuments 檢查（rc 0，
        只 render 第一份）。
        """
        cr_path, out_dir = self._write(tmp_path, self._CR + tail)
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "more than one YAML document" in caplog.text
        assert list(out_dir.iterdir()) == []

    def test_missing_binary_is_caller_error(self, tmp_path, monkeypatch,
                                            caplog):
        """沒有 `$DA_CRDECODE_BINARY`、`$PATH` 上也沒有 → rc 2，說明怎麼建。"""
        monkeypatch.delenv("DA_CRDECODE_BINARY", raising=False)
        monkeypatch.setenv("PATH", str(tmp_path / "empty"))
        cr_path, out_dir = self._write(tmp_path, self._CR)
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "da-crdecode was not found" in caplog.text
        assert "DA_CRDECODE_BINARY" in caplog.text
        assert list(out_dir.iterdir()) == []

    def test_unrunnable_binary_is_caller_error(self, tmp_path, monkeypatch,
                                               caplog):
        """`$DA_CRDECODE_BINARY` 指向不存在的檔 → rc 2 一行錯誤，不 traceback。"""
        monkeypatch.setenv("DA_CRDECODE_BINARY", str(tmp_path / "nope"))
        cr_path, out_dir = self._write(tmp_path, self._CR)
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "cannot run" in caplog.text
        assert list(out_dir.iterdir()) == []

    def test_stderr_is_passed_on_whole_split_on_newline_only(
            self, tmp_path, monkeypatch, caplog):
        """stderr 每一個非空行都照轉、各帶前綴、只在 `\\n` 切行。

        NEL（U+0085）與 U+2028 留在行內；NEL 經 safe_label 印成 `?`。
        會讓本測試轉紅的改動：改用 `splitlines()`（在 NEL、U+2028 處斷行，
        3 行變 5 行），或只挑部分行轉。
        """
        self._fake_binary(
            tmp_path, monkeypatch,
            "sys.stderr.buffer.write('first\\u0085still\\nsecond\\u2028still"
            "\\n\\n  third\\n'.encode())\nsys.exit(2)")
        cr_path, out_dir = self._write(tmp_path, self._CR)
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        passed_on = [r.getMessage() for r in caplog.records
                     if r.getMessage().startswith("  da-crdecode| ")]
        assert passed_on == ["  da-crdecode| first?still",
                             "  da-crdecode| second still",
                             "  da-crdecode|   third"], passed_on
        assert "da-crdecode exited 2" in caplog.text

    def test_timeout_is_caller_error(self, tmp_path, monkeypatch, caplog):
        """da-crdecode 逾時 → rc 2、不寫檔（subprocess 帶 timeout）。

        會讓本測試轉紅的改動：拿掉 subprocess.run 的 timeout（本測試會
        等滿 30 秒且 rc 不是 2）。
        """
        self._fake_binary(tmp_path, monkeypatch, "time.sleep(30)")
        monkeypatch.setattr(da_assembler, "CRDECODE_TIMEOUT_SECONDS", 1)
        cr_path, out_dir = self._write(tmp_path, self._CR)
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "did not finish within 1s" in caplog.text
        assert list(out_dir.iterdir()) == []

    @pytest.mark.parametrize("stdout", [
        pytest.param("print('hello')", id="not-json"),
        pytest.param("print('{\"documents\": []}')", id="no-document"),
        pytest.param("print('[1]')", id="not-an-object"),
    ])
    def test_output_off_contract_is_caller_error(
            self, stdout, tmp_path, monkeypatch, caplog):
        """rc 0 但 stdout 不合 `{"documents": [<一份>]}` → rc 2，不 traceback。"""
        self._fake_binary(tmp_path, monkeypatch, stdout)
        cr_path, out_dir = self._write(tmp_path, self._CR)
        assert render_cr_file(cr_path, out_dir) == EXIT_CALLER_ERROR
        assert "Failed to parse" in caplog.text
        assert list(out_dir.iterdir()) == []


class TestSignalHandler:
    """_signal_handler() 測試。"""

    def test_sets_shutdown_flag(self):
        import da_assembler
        original = da_assembler._shutdown
        try:
            da_assembler._shutdown = False
            _signal_handler(15, None)
            assert da_assembler._shutdown is True
        finally:
            da_assembler._shutdown = original


class TestUpdateCrStatus:
    """update_cr_status() 測試。"""

    def test_patches_status(self):
        mock_api = mock.MagicMock()
        cr = _make_cr(name="test-cr", namespace="ns1")
        update_cr_status(mock_api, cr, "Rendered", sha="abc123",
                         message="OK")
        mock_api.patch_namespaced_custom_object_status.assert_called_once()
        call_args = mock_api.patch_namespaced_custom_object_status.call_args
        body = call_args[1]["body"] if "body" in call_args[1] else call_args[0][5]
        assert body["status"]["phase"] == "Rendered"

    def test_handles_api_error(self):
        """API error should be logged, not raised."""
        mock_api = mock.MagicMock()
        mock_api.patch_namespaced_custom_object_status.side_effect = Exception("503")
        cr = _make_cr(name="t", namespace="ns")
        # Should not raise
        update_cr_status(mock_api, cr, "Error", message="fail")


class TestReconcileOne:
    """reconcile_one() 測試。"""

    def test_renders_and_writes(self):
        with tempfile.TemporaryDirectory() as d:
            cr = _make_cr(name="reconcile-test")
            reconcile_one(cr, Path(d))
            assert (Path(d) / "reconcile-test.yaml").exists()

    def test_with_api_updates_status(self):
        mock_api = mock.MagicMock()
        with tempfile.TemporaryDirectory() as d:
            cr = _make_cr(name="status-test")
            reconcile_one(cr, Path(d), api=mock_api)
            mock_api.patch_namespaced_custom_object_status.assert_called_once()

    def test_no_change_skips_status(self):
        mock_api = mock.MagicMock()
        with tempfile.TemporaryDirectory() as d:
            cr = _make_cr(name="nochange-test")
            # First write
            reconcile_one(cr, Path(d), api=mock_api)
            mock_api.reset_mock()
            # Second write — same content, no change
            reconcile_one(cr, Path(d), api=mock_api)
            # Status still updated (debug path)
            # Actually: no change → no update_cr_status call

    def test_dry_run_skips_api(self):
        mock_api = mock.MagicMock()
        with tempfile.TemporaryDirectory() as d:
            cr = _make_cr(name="dry-reconcile")
            reconcile_one(cr, Path(d), dry_run=True, api=mock_api)
            mock_api.patch_namespaced_custom_object_status.assert_not_called()
            assert not (Path(d) / "dry-reconcile.yaml").exists()

    def test_render_error_updates_status(self):
        """If render fails, status should be set to Error."""
        mock_api = mock.MagicMock()
        # CR with spec that causes render to fail (spec missing entirely)
        cr = {"metadata": {"name": "bad", "namespace": "ns"}}
        with tempfile.TemporaryDirectory() as d:
            # This should not raise even though spec is missing
            reconcile_one(cr, Path(d), api=mock_api)


    def test_cli_path_reraises_an_unusable_config_dir(self):
        """#1789: `cli=True` is the CLI (`--render-cr`) path.

        It used to log the OSError and let `render_cr_file` return EXIT_OK,
        so `da-assembler --render-cr` exited 0 having written nothing. The
        write-error class now leaves this function so `main`'s decorator can
        turn it into rc=2 naming `--config-dir`.
        """
        cr = _make_cr(name="db-a")
        with tempfile.TemporaryDirectory() as d:
            blocker = Path(d) / "blocker"
            blocker.write_text("not a directory\n", encoding="utf-8")
            with pytest.raises(OutputWriteError) as exc:
                reconcile_one(cr, blocker / "config-dir", cli=True)
        assert exc.value.flag == "--config-dir"

    def test_the_default_caller_is_the_controller_not_the_cli(self):
        """`cli` defaults to False, so only an explicit `cli=True` re-raises.

        A specific break that reddens this: put the re-raise back on
        `api is None`.
        """
        cr = _make_cr(name="db-a")
        with tempfile.TemporaryDirectory() as d:
            blocker = Path(d) / "blocker"
            blocker.write_text("not a directory\n", encoding="utf-8")
            reconcile_one(cr, blocker / "config-dir")  # no api, no raise

    def test_controller_path_still_only_logs_and_carries_on(self):
        """The other half, pinned so the fix cannot spread to the controller.

        In watch/once mode a reconcile is ONE item in a loop over every CR in
        the cluster: an unwritable config-dir must land on that CR's status
        and let the loop continue, or a single bad CR stops every other
        tenant from being rendered. So with an `api`, the same failure must
        NOT propagate — same behaviour as before #1789.
        """
        mock_api = mock.MagicMock()
        cr = _make_cr(name="db-a")
        with tempfile.TemporaryDirectory() as d:
            blocker = Path(d) / "blocker"
            blocker.write_text("not a directory\n", encoding="utf-8")
            reconcile_one(cr, blocker / "config-dir", api=mock_api)  # no raise
        mock_api.patch_namespaced_custom_object_status.assert_called_once()
        status = mock_api.patch_namespaced_custom_object_status.call_args
        assert "Error" in str(status)

    def test_the_controller_under_dry_run_also_only_logs(self):
        """⛔ The dry-run cell, which `api is None` got wrong.

        `run_once` / `run_watch` pass `api=None` whenever `--dry-run` is set,
        so keying the CLI branch off that inference put the CONTROLLER on it.
        The shape that reaches a raise under `--dry-run`: `write_rendered`'s
        idempotence read is wrapped and runs BEFORE the `if dry_run` early
        return, so a rendered path that is itself a DIRECTORY raises EISDIR
        even though the run would never have written anything. (A blocked
        PARENT does not: `Path.exists()` answers False on ENOTDIR instead of
        raising.)

        A specific break that reddens this: change the handler's condition
        back to `api is None`.
        """
        cr = _make_cr(name="db-a")
        with tempfile.TemporaryDirectory() as d:
            (Path(d) / "db-a.yaml").mkdir()
            # Exactly what run_once/run_watch pass under --dry-run.
            reconcile_one(cr, Path(d), dry_run=True, api=None)

    @pytest.mark.parametrize("dry_run", [False, True])
    def test_controller_still_swallows_a_non_write_exception(self, dry_run):
        """#2395 只改 `--render-cr`：controller 對非寫出例外的語意不變。

        一個 CR render 失敗時 controller 記 log、（非 dry-run 時）把 CR
        status 設成 Error，然後繼續——不往外丟，run_once 也照樣走完每個
        CR、回 rc 0。會讓本測試轉紅的改動：把重拋條件寫成不看 `cli`。
        """
        mock_api = mock.MagicMock()
        mock_api.list_cluster_custom_object.return_value = {
            "items": [_make_cr(name="first"), _make_cr(name="second")]}
        with tempfile.TemporaryDirectory() as d, \
                mock.patch("da_assembler.dump_for_rewrite",
                           side_effect=RuntimeError("injected")), \
                mock.patch("da_assembler.reconcile_one",
                           wraps=reconcile_one) as spy:
            rc = run_once(mock_api, Path(d), dry_run=dry_run)
            assert list(Path(d).iterdir()) == []
        assert rc == 0
        assert [c.args[0]["metadata"]["name"] for c in spy.call_args_list] \
            == ["first", "second"]
        patch = mock_api.patch_namespaced_custom_object_status
        if dry_run:
            patch.assert_not_called()
        else:
            assert patch.call_count == 2
            assert all("'Error'" in str(c) for c in patch.call_args_list)


class TestRunOnce:
    """run_once() 測試。"""

    def test_lists_and_renders(self):
        mock_api = mock.MagicMock()
        cr = _make_cr(name="once-test")
        mock_api.list_cluster_custom_object.return_value = {"items": [cr]}

        with tempfile.TemporaryDirectory() as d:
            rc = run_once(mock_api, Path(d))
            assert rc == 0
            assert (Path(d) / "once-test.yaml").exists()

    def test_namespace_filter(self):
        mock_api = mock.MagicMock()
        cr = _make_cr(name="ns-test", namespace="db-a")
        mock_api.list_namespaced_custom_object.return_value = {"items": [cr]}

        with tempfile.TemporaryDirectory() as d:
            rc = run_once(mock_api, Path(d), namespace="db-a")
            assert rc == 0
            mock_api.list_namespaced_custom_object.assert_called_once()

    def test_api_error_returns_caller_error(self):
        mock_api = mock.MagicMock()
        mock_api.list_cluster_custom_object.side_effect = Exception("timeout")

        with tempfile.TemporaryDirectory() as d:
            rc = run_once(mock_api, Path(d))
            assert rc == EXIT_CALLER_ERROR

    def test_empty_items(self):
        mock_api = mock.MagicMock()
        mock_api.list_cluster_custom_object.return_value = {"items": []}

        with tempfile.TemporaryDirectory() as d:
            rc = run_once(mock_api, Path(d))
            assert rc == 0

    def test_dry_run_over_an_unreadable_target_still_visits_every_cr(self):
        """#1789 F1: the loop must not be aborted by one unusable path.

        Under `--dry-run` the controller nulls `api`, which is what the first
        version of the CLI/controller split keyed on. With that inference the
        first CR raised OutputWriteError straight out of `run_once` and the
        second was never reached.

        A specific break that reddens this: change `reconcile_one`'s handler
        condition back to `api is None`.
        """
        mock_api = mock.MagicMock()
        crs = [_make_cr(name="first"), _make_cr(name="second")]
        mock_api.list_cluster_custom_object.return_value = {"items": crs}

        with tempfile.TemporaryDirectory() as d:
            (Path(d) / "first.yaml").mkdir()   # the wrapped idempotence read
            with mock.patch("da_assembler.reconcile_one",
                            wraps=reconcile_one) as spy:
                rc = run_once(mock_api, Path(d), dry_run=True)
            assert rc == 0
            assert [c.args[0]["metadata"]["name"] for c in spy.call_args_list] \
                == ["first", "second"]

    def test_dry_run(self):
        mock_api = mock.MagicMock()
        cr = _make_cr(name="dry-once")
        mock_api.list_cluster_custom_object.return_value = {"items": [cr]}

        with tempfile.TemporaryDirectory() as d:
            rc = run_once(mock_api, Path(d), dry_run=True)
            assert rc == 0
            assert not (Path(d) / "dry-once.yaml").exists()


class TestMain:
    """main() CLI entry point 測試。"""

    def test_render_cr_mode(self):
        import da_assembler
        cr = _make_cr(name="cli-test")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            with mock.patch("sys.argv", [
                "da_assembler.py",
                "--config-dir", str(out_dir),
                "--render-cr", str(cr_path),
            ]):
                rc = da_assembler.main()
            assert rc == 0
            assert (out_dir / "cli-test.yaml").exists()

    def test_render_cr_dry_run(self):
        import da_assembler
        cr = _make_cr(name="cli-dry")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            with mock.patch("sys.argv", [
                "da_assembler.py",
                "--config-dir", str(out_dir),
                "--render-cr", str(cr_path),
                "--dry-run",
            ]):
                rc = da_assembler.main()
            assert rc == 0

    @mock.patch("da_assembler.HAS_K8S", False)
    def test_no_k8s_client(self):
        import da_assembler
        with tempfile.TemporaryDirectory() as d:
            with mock.patch("sys.argv", [
                "da_assembler.py",
                "--config-dir", d,
                "--once",
            ]):
                rc = da_assembler.main()
            assert rc == EXIT_CALLER_ERROR
