"""Python half of tests/shared/pyyaml_tagged_scalar_matrix.json (#2325).

`routingpolicy.DecodePyYAML` (Go) reads `require_critical_escalation` the way
the route generator reads it — PyYAML's `safe_load` — and its contract is:
for a scalar it returns an error exactly when `safe_load` refuses the
document, and otherwise the value PyYAML builds (a bool as that bool, None as
nil, anything else as some non-bool). The table holds scalars only: Go reads
any mapping or sequence as a non-bool without looking inside, a contract the
Go half asserts on its own (there is nothing to compare with PyYAML there).
The Go half (components/threshold-exporter/app/pkg/routingpolicy/tagged_scalar_oracle_test.go)
asserts that contract row by row; this half asserts every row IS what the
installed PyYAML says, so the table cannot drift from its oracle.

The rows are generated, never hand-edited:

    REGEN_PYYAML_TAGGED_SCALARS=1 python3 -m pytest \
        tests/shared/test_pyyaml_tagged_scalar_oracle.py -q -p no:cacheprovider
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import yaml

MATRIX_PATH = Path(__file__).parent / "pyyaml_tagged_scalar_matrix.json"

_KINDS = ("bool", "int", "float", "null", "timestamp", "str", "binary")
# Each kind in the short form, plus the verbatim long form, plus untagged.
TAGS = [""] + [f"!!{k}" for k in _KINDS] + [f"!<tag:yaml.org,2002:{k}>" for k in _KINDS]

VALUES = [
    # bool spellings
    "true", "True", "TRUE", "tRuE", "false", "yes", "Yes", "yEs", "no", "on",
    "OFF", "y", "n", "Y", "1", "0",
    # int spellings
    "5", "-5", "+5", "--5", "-", "1_000", "_1", "0x1F", "0X1F", "0x_1F",
    "0o17", "017", "08", "0b101", "0B101", "0b", "0x", "0b_", "0:30", "1:30",
    "190:20:30",
    # float spellings
    "1.5", "-1.5", "+1.5", ".5", "5.", "._", "1e3", "1.0e+3", "1_0.5", ".inf",
    "-.inf", "+.inf", ".Inf", ".INF", "inf", "infinity", ".nan", ".NaN", "nan",
    "1:30.5",
    # null spellings
    "null", "Null", "NULL", "~",
    # timestamp spellings
    "2001-12-14", "2001-1-2", "2001-12-14t21:59:43.10-05:00",
    "2001-12-14 21:59:43.10 -5", "2001-12-14 21:59:43 +23:59",
    "2001-12-14 21:59:43 +24", "2001-12-14 24:00:00", "2000-02-29",
    "1900-02-29", "0000-01-01", "2001-13-40", "nope",
    # binary spellings
    "SGVsbG8=", "SGVsbG8", "SGVsbA==", "ab=", "ab=c=", "abc=d", "a", "=ab",
    # mapping-key-only resolutions and unknown tags as values
    "<<", "=",
    # anything else
    "abc", "x",
    # quoted and block: whitespace, Unicode digits, embedded newline
    "''", '""', "'yes'", '"no"', "'5'", '"1.5"', "'abc'", "'~'", "'2001-12-14'",
    "' 5 '", "' 1.5'", '"\\u0665"', '"1\\u0660"', '"\\uff15.5"', '"yes\\n"',
    '"2001-12-14\\n"', "|\n  yes\n", ">\n  yes\n",
]

# Tags outside the seven kinds; they take the plain values only.
OTHER_TAGS = ["!", "!foo", "!!foo", "!!merge", "!!value", "!!seq", "!!map",
              "!!set", "!<tag:yaml.org,2002:omap>"]
OTHER_VALUES = ["yes", "5", "abc", "'yes'", "'5'", "~"]


def _nonspecific() -> list[str]:
    """The non-specific tag `!` on non-plain scalars (#2730 §6): PyYAML
    resolves the text as if plain — `! "true"` is True, `! "7\\n"` is 7 (its
    `$` matches before a final newline), `! "*"` has no constructor. The
    vendored yaml.v3 keeps the tag (third_party/yaml.v3-nonspecific-tag.patch),
    so Go reads these rows like any other."""
    out = []
    for v in VALUES:
        if v[:1] in ("'", '"', "|", ">"):
            out.append(f"! {v}")  # already quoted or a block scalar
            continue
        out.append("! " + json.dumps(v))
        out.append("! " + json.dumps(v + "\n"))
        out.append("! '" + v.replace("'", "''") + "'")
    out += ["! " + json.dumps(v) for v in ("", "\n", "*", "&", "!", " 5", "5 ", "a\nb")]
    out += ["! |-\n  yes\n", "! >-\n  7\n", "! |\n  7\n", "! |\n  true\n"]
    return out


def _source(tag: str, value: str) -> str:
    return f"{tag} {value}" if tag else value


def _measure(source: str) -> dict:
    """What `safe_load` makes of `a: <source>`."""
    row: dict = {"source": source}
    try:
        doc = yaml.safe_load(f"a: {source}\n")
    except Exception as e:  # noqa: BLE001 — any exception is a refusal
        row["refused"] = type(e).__name__
    else:
        v = doc["a"]
        row["type"] = type(v).__name__
        if isinstance(v, bool):
            row["bool"] = v
    return row


def _rows() -> list[dict]:
    sources = [_source(t, v) for t in TAGS for v in VALUES]
    sources += [f"{t} {v}" for t in OTHER_TAGS for v in OTHER_VALUES]
    sources += _nonspecific()
    seen: set = set()
    return [_measure(s) for s in sources if not (s in seen or seen.add(s))]


def _render(rows: list[dict]) -> str:
    comment = [
        "What PyYAML's safe_load (the route generator's reader) makes of",
        "`a: <source>` for explicit-tag and plain scalars (#2325). GENERATED by",
        "tests/shared/test_pyyaml_tagged_scalar_oracle.py — regenerate with",
        "REGEN_PYYAML_TAGGED_SCALARS=1; never edit by hand.",
        "`refused`: the exception class — safe_load rejects the whole document.",
        "Otherwise `type` is the Python type built and `bool` its value when it",
        "is a bool. The Go half (pkg/routingpolicy/tagged_scalar_oracle_test.go)",
        "asserts DecodePyYAML errors exactly on the refused rows, returns the",
        "same bool on bool rows, nil on NoneType rows and a non-bool otherwise.",
        "Rows `! <quoted or block>` carry the non-specific tag, which PyYAML",
        "resolves as if plain; the vendored yaml.v3 keeps it (#2730 §6).",
    ]
    body = ",\n".join("    " + json.dumps(r, ensure_ascii=False) for r in rows)
    return ("{\n  \"_comment\": " + json.dumps(comment, ensure_ascii=False, indent=4).replace("\n", "\n  ")
            + ",\n  \"pyyaml\": \"" + yaml.__version__ + "\",\n  \"rows\": [\n" + body + "\n  ]\n}\n")


def test_matrix_is_what_pyyaml_says() -> None:
    fresh = _render(_rows())
    if os.environ.get("REGEN_PYYAML_TAGGED_SCALARS"):
        MATRIX_PATH.write_text(fresh, encoding="utf-8")
    on_disk = MATRIX_PATH.read_text(encoding="utf-8")
    assert on_disk == fresh, (
        "pyyaml_tagged_scalar_matrix.json is not what the installed PyYAML says; "
        "regenerate with REGEN_PYYAML_TAGGED_SCALARS=1 and review the diff")


def test_matrix_is_not_vacuous() -> None:
    rows = json.loads(MATRIX_PATH.read_text(encoding="utf-8"))["rows"]
    refused = [r for r in rows if "refused" in r]
    bools = [r for r in rows if "bool" in r]
    others = [r for r in rows if "type" in r and "bool" not in r]
    # Every tag contributes a refusal or a construction of its own kind; the
    # three outcomes must all be present or the Go half proves nothing.
    assert refused and bools and others, (len(refused), len(bools), len(others))
    for needle in ("!!bool y", "!!int abc", "!!float x", "!!timestamp nope", "!!bool 1"):
        assert any(r["source"] == needle and "refused" in r for r in rows), needle
    # The non-specific tag on a non-plain scalar is held like any other row
    # (#2730 §6): all three outcomes occur among those rows too.
    ns = [r for r in rows if r["source"].startswith("! ") and r["source"][2] in "'\"|>"]
    assert any("refused" in r for r in ns) and any("bool" in r for r in ns), len(ns)
    assert any(r.get("type") == "int" for r in ns) and any(r.get("type") == "NoneType" for r in ns)
    assert not any("go_blind" in r for r in rows)
