"""Python reader of the tenant-id rule ↔ the schema and the Go / portal copies (ADR-035).

The rule is written once, as ``definitions.tenantId`` of
docs/schemas/tenant-config.schema.json. Python reads it at runtime through
``_lib_validation.tenant_id_rule``; Go (pkg/tenantid) and the portal read
copies generated by scripts/tools/dx/gen_tenant_id_json.py.

The case table
components/threshold-exporter/app/pkg/tenantid/testdata/tenant_id_cases.json
is also asserted by pkg/tenantid TestValid_SharedCases and the portal's
tenant-id-rule.test.ts, so a verdict that differs between Python
``re.fullmatch``, Go RE2 and ECMAScript RegExp reddens one side.
"""
from __future__ import annotations

import json
import os
import re

import pytest

import _lib_validation

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_SCHEMA = os.path.join(_REPO_ROOT, "docs", "schemas", "tenant-config.schema.json")
_CASES = os.path.join(_REPO_ROOT, "components", "threshold-exporter", "app", "pkg",
                      "tenantid", "testdata", "tenant_id_cases.json")


def _schema_definition() -> dict:
    with open(_SCHEMA, encoding="utf-8") as f:
        return json.load(f)["definitions"]["tenantId"]


def _cases() -> dict:
    with open(_CASES, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture
def fresh_rule(monkeypatch):
    """Drop the module cache so the test reads the schema again."""
    monkeypatch.setattr(_lib_validation, "_TENANT_ID_RULE", None)


def test_rule_is_read_from_the_schema(fresh_rule):
    pattern, description = _lib_validation.tenant_id_rule()
    definition = _schema_definition()
    assert pattern.pattern == definition["pattern"]
    assert description == definition["description"]


def test_schema_definition_is_a_string_rule():
    definition = _schema_definition()
    assert definition["type"] == "string"
    assert definition["description"].strip()


@pytest.mark.parametrize("tenant_id", _cases()["valid"])
def test_valid_cases_fullmatch(tenant_id):
    pattern, _ = _lib_validation.tenant_id_rule()
    assert pattern.fullmatch(tenant_id) is not None


@pytest.mark.parametrize("tenant_id", _cases()["invalid"])
def test_invalid_cases_do_not_fullmatch(tenant_id):
    pattern, _ = _lib_validation.tenant_id_rule()
    assert pattern.fullmatch(tenant_id) is None


def test_case_table_has_both_sides():
    cases = _cases()
    assert cases["valid"] and cases["invalid"]


def test_trailing_newline_needs_fullmatch():
    # Why callers must use fullmatch: Python's `$` also matches before a
    # trailing "\n", so a plain match would accept "abc\n" (Go RE2 does not).
    pattern, _ = _lib_validation.tenant_id_rule()
    assert pattern.match("abc\n") is not None
    assert pattern.fullmatch("abc\n") is None


def test_missing_schema_fails_closed(fresh_rule, monkeypatch):
    monkeypatch.setattr(_lib_validation, "_find_tenant_schema", lambda: None)
    with pytest.raises(RuntimeError, match="tenant ids cannot be checked"):
        _lib_validation.tenant_id_rule()


@pytest.mark.parametrize("definitions", [
    {},
    {"tenantId": {"type": "string"}},
    {"tenantId": {"type": "string", "pattern": "^[a-z]+$"}},
    {"tenantId": {"type": "string", "description": "no pattern"}},
    # Empty strings: the generator refuses them, so must this reader.
    {"tenantId": {"type": "string", "pattern": "", "description": "empty pattern"}},
    {"tenantId": {"type": "string", "pattern": "^[a-z]+$", "description": ""}},
])
def test_missing_definition_fails_closed(fresh_rule, monkeypatch, tmp_path, definitions):
    schema = tmp_path / "tenant-config.schema.json"
    schema.write_text(json.dumps({"definitions": definitions}), encoding="utf-8")
    monkeypatch.setattr(_lib_validation, "_find_tenant_schema", lambda: schema)
    with pytest.raises(RuntimeError, match="definitions.tenantId"):
        _lib_validation.tenant_id_rule()


@pytest.mark.parametrize("rel", [
    "components/threshold-exporter/app/pkg/tenantid/tenant_id.json",
    "tools/portal/src/interactive/tools/_common/data/tenant-id.json",
])
def test_generated_copies_carry_the_schema_rule(rel):
    with open(os.path.join(_REPO_ROOT, rel), encoding="utf-8") as f:
        copy = json.load(f)
    definition = _schema_definition()
    assert copy["pattern"] == definition["pattern"]
    assert copy["description"] == definition["description"]
    # The pattern stays inside the dialect subset all three engines agree on.
    re.compile(copy["pattern"])
