{{- if eq .Values.proxy.engine "vmauth" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "federation-proxy.name" . }}-vmauth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "federation-proxy.labels" . | nindent 4 }}
data:
  auth.yml: |
    {{- .Values.vmauth.authConfig | nindent 4 }}
{{- end }}
