{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "federation-proxy.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "federation-proxy.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "federation-proxy.selectorLabels" . | nindent 6 }}
{{- end }}
