apiVersion: v1
kind: Service
metadata:
  name: {{ include "federation-reconciler.name" . }}
  labels:
    {{- include "federation-reconciler.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    prometheus.io/port: {{ .Values.metricsPort | quote }}
spec:
  selector:
    {{- include "federation-reconciler.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: metrics
