---
title: "Notification Previewer — template engine"
purpose: |
  Pure template processing + export serialization for the notification
  previewer: brace-balance validation, {{.Var}} extraction, Go-template-style
  preview rendering against sample alert data, and YAML / JSON export.

  Pre-PR-portal-17 these were inline in notification-previewer.jsx (901 LOC)
  with 0% coverage. generateYAML/generateJSON were de-coupled from the
  RECEIVER_TYPES UI-metadata global: they now take receiverLabel as an arg
  (the orchestrator passes RECEIVER_TYPES[type].label), so the engine carries
  no UI config. generateJSON still stamps generated_at via Date (non-pure by
  design); tests assert structure, not the timestamp.

  Public API:
    validateTemplate(template)             -> [{ line, msg }]
    extractVariables(template)             -> string[] of {{.Var}}
    renderTemplatePreview(template, data)  -> rendered string
    generateYAML(receiverType, template, receiverLabel)  -> string
    generateJSON(receiverType, template, receiverLabel)  -> string

  Closure deps: window.__t for bilingual messages (falls back to English).
---

// i18n fallback (moved with the cluster from notification-previewer.jsx).
const t = window.__t || ((zh, en) => en);

/* ── Template variable validator ── */
function validateTemplate(template) {
  const braceRegex = /\{\{|\}\}/g;
  let openCount = 0;
  let errors = [];
  let lastPos = 0;

  let match;
  const regex = /\{\{|\}\}/g;
  while ((match = regex.exec(template)) !== null) {
    if (match[0] === '{{') openCount++;
    else openCount--;

    if (openCount < 0) {
      errors.push({
        line: template.substring(0, match.index).split('\n').length,
        msg: t('未配對的 }}', 'Unmatched }}'),
      });
      openCount = 0;
    }
  }

  if (openCount > 0) {
    errors.push({ line: 1, msg: t('未關閉的 {{', 'Unclosed {{') });
  }

  return errors;
}

function extractVariables(template) {
  const regex = /\{\{\.[\w\.]+\}\}/g;
  const found = new Set();
  let match;
  while ((match = regex.exec(template)) !== null) {
    found.add(match[0]);
  }
  return Array.from(found);
}

/* ── Template preview renderer ── */
function renderTemplatePreview(template, alertData) {
  try {
    let result = template;

    // Simple Go template variable substitution
    const vars = extractVariables(template);
    vars.forEach(varName => {
      const path = varName.slice(2, -2); // Remove {{ and }}
      const keys = path.split('.');
      let value = alertData;
      for (let key of keys) {
        if (key) value = value[key] || `[${key}?]`;
      }
      result = result.replace(new RegExp(varName.replace(/\./g, '\\.'), 'g'), value);
    });

    return result;
  } catch (e) {
    return t('[無法預覽 - 範本錯誤]', '[Preview failed - template error]');
  }
}

/* ── Export functionality ── */
function generateYAML(receiverType, template, receiverLabel) {
  const yaml = `# Notification Template for ${receiverLabel}
# Auto-generated by Notification Template Editor

${receiverType}:
  # Title/Subject template
  titleTemplate: |
    ${template.titleTemplate}

  # Body/Message template
  bodyTemplate: |
    ${template.bodyTemplate.split('\n').join('\n    ')}

  # Custom labels (if applicable)
  customLabels:
${Object.entries(template.customLabels).map(([k, v]) => `    ${k}: ${v}`).join('\n')}
`;
  return yaml;
}

function generateJSON(receiverType, template, receiverLabel) {
  return JSON.stringify(
    {
      receiver_type: receiverType,
      receiver_label: receiverLabel,
      template: {
        title_template: template.titleTemplate,
        body_template: template.bodyTemplate,
        custom_labels: template.customLabels,
      },
      generated_at: new Date().toISOString(),
    },
    null,
    2
  );
}

// Legacy jsx-loader path: expose as window globals (see PR-portal-12 / TD-030z).

export { validateTemplate, extractVariables, renderTemplatePreview, generateYAML, generateJSON };
