#!/usr/bin/env python3
"""da_assembler.py 的 pytest 風格測試 — CRD → YAML 組合器。"""

import tempfile
from pathlib import Path

# Make scripts/tools importable

import yaml

from da_assembler import (  # noqa: E402
    _content_sha256,
    _output_filename,
    remove_rendered,
    render_cr_file,
    render_cr_to_yaml,
    write_rendered,
)


def _make_cr(name="db-a", namespace="db-a", tenants=None):
    """輔助函數：建立最小的 ThresholdConfig CR 字典。"""
    if tenants is None:
        tenants = {name: {"mysql_connections": "70"}}
    return {
        "apiVersion": "dynamicalerting.io/v1alpha1",
        "kind": "ThresholdConfig",
        "metadata": {"name": name, "namespace": namespace},
        "spec": {"tenants": tenants},
    }


class TestRenderCrToYaml:
    """render_cr_to_yaml() 測試。"""

    def test_basic_render(self):
        """測試基本渲染。"""
        cr = _make_cr()
        result = render_cr_to_yaml(cr)
        assert "# Auto-generated by da-assembler" in result
        assert "mysql_connections" in result
        # Should be valid YAML (skip header lines starting with #)
        body = "\n".join(
            ln for ln in result.splitlines() if not ln.startswith("#"))
        parsed = yaml.safe_load(body)
        assert "tenants" in parsed
        assert "db-a" in parsed["tenants"]

    def test_render_with_defaults(self):
        """測試含 defaults 的渲染。"""
        cr = _make_cr()
        cr["spec"]["defaults"] = {"mysql_connections": 80}
        result = render_cr_to_yaml(cr)
        parsed = yaml.safe_load(
            "\n".join(ln for ln in result.splitlines()
                      if not ln.startswith("#")))
        assert "defaults" in parsed

    def test_render_with_state_filters(self):
        """測試含 state filters 的渲染。"""
        cr = _make_cr()
        cr["spec"]["stateFilters"] = {
            "crashloop": {"reasons": ["CrashLoopBackOff"]}
        }
        result = render_cr_to_yaml(cr)
        parsed = yaml.safe_load(
            "\n".join(ln for ln in result.splitlines()
                      if not ln.startswith("#")))
        assert "state_filters" in parsed

    def test_empty_tenants(self):
        """測試空 tenants 的渲染。"""
        cr = _make_cr(tenants={})
        result = render_cr_to_yaml(cr)
        # Should still produce valid output (empty doc or {})
        assert "Auto-generated" in result


class TestOutputFilename:
    """_output_filename() 測試。"""

    def test_from_name(self):
        """測試從名稱產生輸出檔名。"""
        cr = _make_cr(name="payment-db")
        assert _output_filename(cr) == "payment-db.yaml"

    def test_missing_name(self):
        """測試缺失名稱時的預設檔名。"""
        cr = {"metadata": {}}
        assert _output_filename(cr) == "unknown.yaml"


class TestWriteRendered:
    """write_rendered() 測試。"""

    def test_writes_file(self):
        """測試寫入檔案。"""
        with tempfile.TemporaryDirectory() as d:
            changed = write_rendered(
                Path(d), "test.yaml", "tenants:\n  a: 1\n")
            assert changed
            assert (Path(d) / "test.yaml").exists()

    def test_no_change_skips_write(self):
        """測試無變更時跳過寫入。"""
        with tempfile.TemporaryDirectory() as d:
            content = "tenants:\n  a: 1\n"
            (Path(d) / "test.yaml").write_text(content, encoding="utf-8")
            changed = write_rendered(Path(d), "test.yaml", content)
            assert not changed

    def test_dry_run(self):
        """測試乾執行模式。"""
        with tempfile.TemporaryDirectory() as d:
            changed = write_rendered(
                Path(d), "test.yaml", "content", dry_run=True)
            assert changed
            assert not (Path(d) / "test.yaml").exists()


class TestRemoveRendered:
    """remove_rendered() 測試。"""

    def test_removes_existing(self):
        """測試刪除現存檔案。"""
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "test.yaml"
            p.write_text("data", encoding="utf-8")
            removed = remove_rendered(Path(d), "test.yaml")
            assert removed
            assert not p.exists()

    def test_nonexistent_noop(self):
        """測試不存在的檔案不執行操作。"""
        with tempfile.TemporaryDirectory() as d:
            removed = remove_rendered(Path(d), "nonexistent.yaml")
            assert not removed

    def test_dry_run(self):
        """測試乾執行模式不刪除檔案。"""
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "test.yaml"
            p.write_text("data", encoding="utf-8")
            removed = remove_rendered(Path(d), "test.yaml", dry_run=True)
            assert removed
            assert p.exists()  # not actually deleted


class TestContentSha256:
    """_content_sha256() 測試。"""

    def test_deterministic(self):
        """測試確定性雜湊。"""
        assert (
            _content_sha256("hello") ==
            _content_sha256("hello"))

    def test_different_content(self):
        """測試不同內容的不同雜湊。"""
        assert (
            _content_sha256("hello") !=
            _content_sha256("world"))


class TestRenderCrFile:
    """render_cr_file() 測試。"""

    def test_offline_render(self):
        """測試離線渲染。"""
        cr = _make_cr(name="offline-test")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            rc = render_cr_file(cr_path, out_dir)
            assert rc == 0
            assert (out_dir / "offline-test.yaml").exists()

    def test_invalid_kind(self):
        """測試無效的 kind。"""
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "bad.yaml"
            cr_path.write_text("kind: NotAThresholdConfig\nspec: {}",
                               encoding="utf-8")
            rc = render_cr_file(cr_path, Path(d))
            assert rc == 2

    def test_dry_run(self):
        """測試乾執行模式。"""
        cr = _make_cr(name="dry-test")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            rc = render_cr_file(cr_path, out_dir, dry_run=True)
            assert rc == 0
            assert not (out_dir / "dry-test.yaml").exists()
