apiVersion: v1
kind: Service
metadata:
  name: {{ include "federation-gateway.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "federation-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "federation-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.listenPort }}
      protocol: TCP
