---
title: "Getting Started Wizard — static catalogs (roles, options, glossary, recommendations)"
purpose: |
  Static data tables for the getting-started onboarding wizard: the concept
  glossary, the three role definitions and their per-role option lists
  (platform goals / database types / tenant needs), the #811 lifecycle-axis
  bucketing, the grow-ops tool handoff targets, and the per-path curated
  RECOMMENDATIONS doc lists.

  Pre-this-split these were inline at the top of wizard.jsx (~290 LOC of the
  monolith). Splitting matches the deployment-wizard/fixtures + operator-setup-
  wizard/fixtures house pattern and leaves wizard.jsx as orchestrator + render.
  Behaviour is preserved verbatim: the tables are moved, not rewritten. t() is
  evaluated at module-eval time exactly as before (window.__t is set at
  bootstrap before this bundle evaluates).

  Public API (all consumed by wizard.jsx):
    GLOSSARY               inline concept glossary { term: definition }
    ROLES                  the three role cards
    GOALS/DATABASES/NEEDS  per-role option lists
    BUCKET_LABELS          lifecycle bucket <h4> labels
    ROLE_AXIS              per-role flat vs lifecycle axis config
    HANDOFF_TARGETS        per-role "Ready to act?" tool links
    RECOMMENDATIONS        per-path curated doc lists (keyed "<role>-<option>")

  Closure deps: reads window.__t / window.__PLATFORM_DATA at module-eval time.
---

const t = window.__t || ((zh, en) => en);

// Rule-pack count — derived from canonical platform data so the onboarding
// copy never drifts. SoT: docs/assets/platform-data.json (packOrder /
// totals.packs), regenerated by `make platform-data` and injected as
// window.__PLATFORM_DATA by jsx-loader.html. The `|| 16` offline/demo fallback
// tracks the committed SoT count (see the rule-pack canonicalize epic). Matches
// the (__PD.packOrder || []).length idiom in roi/cost/migration-roi calculators.
const __PD = window.__PLATFORM_DATA || {};
const PACK_COUNT = (__PD.packOrder || []).length || 16;

// Threshold-alert count for the ALERT-REFERENCE doc-link summary. SoT:
// rule-packs/ALERT-REFERENCE.md (auto-generated by generate_alert_reference.py
// from rule-pack-*.yaml; drift-gated by the "Alert reference drift" hook) — it
// counts USER-FACING threshold alerts only. This is deliberately NOT derived
// from window.__PLATFORM_DATA: totals.alertRules (146) counts ALL alert rules
// incl. operational/sentinel, which is a different figure. Keep in sync with the
// ALERT-REFERENCE row count when rule packs add/remove threshold alerts.
const ALERT_COUNT = 112;

// Inline concept glossary — helps newcomers understand platform terminology
const GLOSSARY = {
  "Rule Pack": t("針對特定技術（例如 MariaDB、Redis）預先打包好的 Prometheus recording rule 與 alert rule。挑你需要的即可 — 不需要 PromQL。", "A pre-built bundle of Prometheus recording rules and alert rules for a specific technology (e.g., MariaDB, Redis). You pick the ones you need — no PromQL required."),
  "Threshold": t("觸發告警的數值上限（例如「80% CPU」）。每個租戶用簡單 YAML 設定自己的值。", "A numeric limit (like \"80% CPU\") that triggers an alert. Each tenant sets their own values in simple YAML."),
  "Tenant": t("擁有一組服務的團隊或 namespace。每個租戶都有隔離的設定與告警路由。", "A team or namespace that owns a set of services. Each tenant has isolated config and alert routing."),
  "Three-State Mode": t("每個設定鍵支援三種狀態：自訂值、預設（省略該鍵）、或明確停用（設為「disable」）。", "Every config key supports three states: custom value, default (omit the key), or explicitly disabled (set to \"disable\")."),
  "Recording Rule": t("預先計算指標以加速查詢的 Prometheus 規則。Rule Pack 會自動包含這些。", "A Prometheus rule that pre-computes metrics for faster queries. Rule Packs include these automatically."),
  "Severity Dedup": t("當 Critical 告警觸發時，對應的 Warning 會自動被抑制以減少噪音。", "When a Critical alert fires, the matching Warning is automatically suppressed to reduce noise."),
};

const ROLES = [
  {
    id: "platform",
    label: t("平台工程師", "Platform Engineer"),
    icon: "⚙️",
    desc: t("部署、擴展並維運告警基礎設施", "Deploy, scale, and operate the alerting infrastructure"),
    hint: t("你在組織內管理 Kubernetes、Prometheus 或 Helm。", "You manage Kubernetes, Prometheus, or Helm in your org."),
  },
  {
    id: "domain",
    label: t("領域專家 (DBA)", "Domain Expert (DBA)"),
    icon: "🗄️",
    desc: t("定義你的資料庫怎樣算「不健康」", "Define what \"unhealthy\" means for your databases"),
    hint: t("你熟悉資料庫內部，想設定正確的閾值。", "You know your DB internals and want to set the right thresholds."),
  },
  {
    id: "tenant",
    label: t("租戶團隊", "Tenant Team"),
    icon: "👥",
    desc: t("為你團隊的服務取得告警 — 不需要 PromQL", "Get alerts for your team's services — no PromQL needed"),
    hint: t("你只想在對的頻道收到對的告警。", "You just want to receive the right alerts in the right channel."),
  },
];

const GOALS = {
  platform: [
    { id: "setup", label: t("初始部署", "Initial Setup"), desc: t("從零開始部署平台", "Deploy the platform from scratch") },
    { id: "migration", label: t("遷移", "Migration"), desc: t("從既有告警系統遷移", "Migrate from existing alerting systems") },
    { id: "federation", label: t("聯邦", "Federation"), desc: t("設定多叢集聯邦", "Set up multi-cluster federation") },
    { id: "monitoring", label: t("監控與擴展", "Monitoring & Scaling"), desc: t("監控並擴展平台", "Monitor and scale the platform") },
  ],
};

const DATABASES = {
  domain: [
    { id: "mariadb", label: "MariaDB", icon: "🗄️" },
    { id: "postgresql", label: "PostgreSQL", icon: "🗄️" },
    { id: "redis", label: "Redis", icon: "⚡" },
    { id: "mongodb", label: "MongoDB", icon: "📦" },
    { id: "other", label: t("其他", "Other"), icon: "❓" },
  ],
};

const NEEDS = {
  tenant: [
    { id: "onboard", label: t("加入平台", "Onboard to Platform"), desc: t("讓我的團隊開始上手", "Get my team started") },
    { id: "alerts", label: t("設定告警", "Configure Alerts"), desc: t("設定告警規則與閾值", "Set up alert rules and thresholds") },
    { id: "routing", label: t("設定告警路由", "Set Up Alert Routing"), desc: t("控制告警送往何處", "Control where alerts are sent") },
    { id: "maintenance", label: t("維護模式", "Maintenance Mode"), desc: t("管理告警抑制視窗", "Manage alert suppression windows") },
  ],
};

// ── Per-role lifecycle axis (#811) ───────────────────────────────────────
// step-1 groups a role's options into lifecycle buckets (Provision / Operate
// / Maintain) so a single role sees a focused, staged path instead of a flat
// dump. This is a DISPLAY-ONLY grouping layered over the option ids above —
// RECOMMENDATIONS data and the deep-link `option=` schema are unchanged, so a
// bookmarked #role=tenant&option=routing still resolves (bucketing never
// gates which options exist, only how they are headed).
//
// `axis: "flat"`  → render the current flat OptionCard grid (no sub-headings).
// `axis: "lifecycle"` → render each non-empty bucket as an <h4> + its grid.
//   `buckets` is ordered; each bucket lists the optionIds it contains.
//
// domain is deliberately FLAT: its branches (mariadb / postgresql / redis /
// mongodb / other) are TYPES, not lifecycle stages — forcing a stage axis on
// them would be a false taxonomy (#811 explicit requirement).
const BUCKET_LABELS = {
  provision: () => t("建置", "Provision"),
  operate: () => t("維運", "Operate"),
  maintain: () => t("維護", "Maintain"),
};

const ROLE_AXIS = {
  platform: {
    axis: "lifecycle",
    buckets: [
      // federation is filed under Provision (not its own stage): standing up
      // multi-cluster wiring is a build-time activity, so it groups with the
      // other "get it running" goals rather than day-2 operate/maintain.
      { id: "provision", optionIds: ["setup", "migration", "federation"] },
      { id: "operate", optionIds: ["monitoring"] },
    ],
  },
  tenant: {
    axis: "lifecycle",
    buckets: [
      { id: "provision", optionIds: ["onboard"] },
      { id: "operate", optionIds: ["alerts", "routing"] },
      { id: "maintain", optionIds: ["maintenance"] },
    ],
  },
  domain: {
    // FLAT — db-type branches are types, not stages (see note above).
    axis: "flat",
  },
};

// ── Grow-ops action handoff (#811) ───────────────────────────────────────
// After the curated reading list, point each role at the interactive tool(s)
// that are its natural next action. Link via the loader's `?component=<key>`
// form — the SAME form the Hub's quick-access chips + dynamic cards use
// (verified working). A bare `<tool>.html` does NOT resolve to the tool: no
// per-tool `.html` file exists, and da-portal's nginx
// `try_files $uri $uri/ /interactive/index.html` (components/da-portal/
// nginx.conf) falls a missing path back to the Hub HOME — so a `<tool>.html`
// link silently lands on the home page, not the tool. (master-onboarding.jsx
// still uses the bare form on `main` = a latent portal-wide bug, tracked
// separately — do NOT copy it.)
//
// DOC-ONLY SEAM: #811 deliberately ships links only. A future D2 "emit YAML
// skeleton" step (option 2) would slot in HERE — e.g. a button that hands the
// chosen role+option to recipe-builder pre-filled — but no emit/generate logic
// is built now (out of #811 scope). Keep this list link-only until then.
const LOADER = "../assets/jsx-loader.html?component=";
const HANDOFF_TARGETS = {
  tenant: [
    { href: `${LOADER}recipe-builder`, label: () => t("配方建構器", "Recipe Builder"), desc: () => t("用引導表單組出 custom alert 配方。", "Build a custom-alert recipe with a guided form.") },
    { href: `${LOADER}playground`, label: () => t("互動沙盒", "Playground"), desc: () => t("在沙盒中試玩 tenant 設定。", "Experiment with tenant config in a sandbox.") },
  ],
  platform: [
    { href: `${LOADER}deployment-wizard`, label: () => t("部署精靈", "Deployment Wizard"), desc: () => t("產出 Helm values 或 Kustomize patch。", "Generate Helm values or a Kustomize patch.") },
    { href: `${LOADER}cli-playground`, label: () => t("CLI 沙盒", "CLI Playground"), desc: () => t("試跑 da-tools 指令。", "Try da-tools commands interactively.") },
  ],
  domain: [
    { href: `${LOADER}rule-pack-selector`, label: () => t("Rule Pack 選擇器", "Rule Pack Selector"), desc: () => t("挑出你資料庫需要的 rule pack。", "Pick the rule packs your database needs.") },
    { href: `${LOADER}threshold-calculator`, label: () => t("閾值計算器", "Threshold Calculator"), desc: () => t("從觀測指標推算建議閾值。", "Derive suggested thresholds from observed metrics.") },
  ],
};

const RECOMMENDATIONS = {
  "platform-setup": {
    title: t("平台初始部署", "Platform Initial Setup"),
    docs: [
      { name: t("平台工程師快速上手", "Platform Engineer Quick Start"), path: "for-platform-engineers.md", priority: "start-here", summary: t("端到端部署平台：Helm 安裝、設定與驗證。", "Deploy the platform end-to-end: Helm install, config, and verify.") },
      { name: t("架構與設計", "Architecture & Design"), path: "../architecture-and-design.md", summary: t("核心概念：group_left 配對、三態模式、severity 去重。", "Core concepts: group_left matching, three-state mode, severity dedup.") },
      { name: t("自帶 Prometheus 整合", "BYO Prometheus Integration"), path: "../byo-prometheus-integration.md", summary: t("整合你既有的 Prometheus 或 Thanos。", "Integrate with your existing Prometheus or Thanos setup.") },
      { name: t("自帶 Alertmanager 整合", "BYO Alertmanager Integration"), path: "../byo-alertmanager-integration.md", summary: t("以動態路由連接既有的 Alertmanager。", "Connect to an existing Alertmanager with dynamic routing.") },
      { name: t("GitOps 部署指南", "GitOps Deployment Guide"), path: "../gitops-deployment.md", summary: t("ArgoCD / Flux 工作流、CI 漂移偵測。", "ArgoCD / Flux workflows, CI drift detection.") },
      { name: t("自訂規則治理", "Custom Rule Governance"), path: "../custom-rule-governance.md", summary: t("三層治理模型、CI 檢查、命名慣例。", "Three-tier governance model, CI linting, naming conventions.") },
    ],
  },
  "platform-migration": {
    title: t("從舊系統遷移", "Migration from Legacy Systems"),
    docs: [
      { name: t("平台工程師快速上手", "Platform Engineer Quick Start"), path: "for-platform-engineers.md", priority: "start-here", summary: t("端到端部署平台：Helm 安裝、設定與驗證。", "Deploy the platform end-to-end: Helm install, config, and verify.") },
      { name: t("遷移引擎指南", "Migration Engine Guide"), path: "../migration-engine.md", summary: t("以 AST 為基礎的 PromQL 轉 YAML 轉換器內部機制。", "AST-based PromQL-to-YAML converter internals.") },
      { name: t("遷移使用者指南", "Migration User Guide"), path: "../migration-guide.md", summary: t("逐步導入流程，搭配 scaffold 與 migrate 工具。", "Step-by-step onboarding flow with scaffold and migrate tools.") },
      { name: t("進階情境", "Advanced Scenarios"), path: "../internal/test-coverage-matrix.md", summary: t("Regex 閾值、排程值、跨午夜設定。", "Regex thresholds, scheduled values, cross-midnight configs.") },
      { name: t("Shadow Monitoring SOP", "Shadow Monitoring SOP"), path: "../shadow-monitoring-sop.md", summary: t("新舊規則雙軌並行、自動收斂偵測。", "Dual-track old/new rules, auto-convergence detection.") },
      { name: t("Shadow Monitoring 切換", "Shadow Monitoring Cutover"), path: "../scenarios/shadow-monitoring-cutover.md", summary: t("零風險切換：就緒檢查、一鍵切換、回滾。", "Zero-risk cutover: readiness check, one-click switch, rollback.") },
    ],
  },
  "platform-federation": {
    title: t("多叢集聯邦", "Multi-Cluster Federation"),
    docs: [
      { name: t("平台工程師快速上手", "Platform Engineer Quick Start"), path: "for-platform-engineers.md", priority: "start-here", summary: t("端到端部署平台：Helm 安裝、設定與驗證。", "Deploy the platform end-to-end: Helm install, config, and verify.") },
      { name: t("聯邦整合指南", "Federation Integration Guide"), path: "../federation-integration.md", summary: t("情境 A 藍圖：中央 exporter + 邊緣 Prometheus。", "Scenario A blueprint: central exporter + edge Prometheus.") },
      { name: t("多叢集聯邦情境", "Multi-Cluster Federation Scenarios"), path: "../scenarios/multi-cluster-federation.md", summary: t("邊緣到中央的指標流、跨叢集告警路由。", "Edge-to-central metric flow, cross-cluster alert routing.") },
      { name: t("架構與設計", "Architecture & Design"), path: "../architecture-and-design.md", summary: t("核心概念：group_left 配對、三態模式、severity 去重。", "Core concepts: group_left matching, three-state mode, severity dedup.") },
      { name: t("治理與安全", "Governance & Security"), path: "../governance-security.md", summary: t("RBAC、webhook 允許清單、cardinality 防護。", "RBAC, webhook allowlists, cardinality guards.") },
    ],
  },
  "platform-monitoring": {
    title: t("平台監控與擴展", "Platform Monitoring & Scaling"),
    docs: [
      { name: t("平台工程師快速上手", "Platform Engineer Quick Start"), path: "for-platform-engineers.md", priority: "start-here", summary: t("端到端部署平台：Helm 安裝、設定與驗證。", "Deploy the platform end-to-end: Helm install, config, and verify.") },
      { name: t("基準測試與效能", "Benchmarks & Performance"), path: "../benchmarks.md", summary: t("閒置、負載中、路由、alertmanager 與 reload 基準測試。", "Idle, under-load, routing, alertmanager, and reload benchmarks.") },
      { name: t("疑難排解指南", "Troubleshooting Guide"), path: "../troubleshooting.md", summary: t("常見問題、診斷指令、復原程序。", "Common issues, diagnostic commands, recovery procedures.") },
      { name: t("架構與設計", "Architecture & Design"), path: "../architecture-and-design.md", summary: t("核心概念：group_left 配對、三態模式、severity 去重。", "Core concepts: group_left matching, three-state mode, severity dedup.") },
      { name: t("治理與安全", "Governance & Security"), path: "../governance-security.md", summary: t("RBAC、webhook 允許清單、cardinality 防護。", "RBAC, webhook allowlists, cardinality guards.") },
    ],
  },
  "domain-mariadb": {
    title: t("MariaDB 閾值設定", "MariaDB Threshold Configuration"),
    docs: [
      { name: t("領域專家快速上手", "Domain Expert Quick Start"), path: "for-domain-experts.md", priority: "start-here", summary: t("理解三層 Rule Pack 架構並設定閾值。", "Learn the three-layer Rule Pack architecture and set thresholds.") },
      { name: t("租戶快速上手", "Tenant Quick Start"), path: "for-tenants.md", summary: t("每個租戶 30 秒內該知道的 3 件事。", "The 3 things every tenant needs to know in 30 seconds.") },
      { name: t("告警參考", "Alert Reference"), path: "../rule-packs/ALERT-REFERENCE.md", summary: t(`全部 ${ALERT_COUNT} 個告警，含 severity、意義與建議動作。`, `All ${ALERT_COUNT} alerts with severity, meaning, and suggested actions.`) },
      { name: t("Rule Pack 總覽", "Rule Packs Overview"), path: "../rule-packs/README.md", summary: t(`${PACK_COUNT} 個 rule pack：各自涵蓋哪些指標、exporter 需求。`, `${PACK_COUNT} rule packs: which metrics they cover, exporter requirements.`) },
      { name: t("架構與設計", "Architecture & Design"), path: "../architecture-and-design.md", summary: t("核心概念：group_left 配對、三態模式、severity 去重。", "Core concepts: group_left matching, three-state mode, severity dedup.") },
      { name: t("基線探勘工具", "Baseline Discovery Tool"), path: "../internal/testing-playbook.md", summary: t("觀測真實指標並計算 p50/p90/p99 閾值建議。", "Observe real metrics and compute p50/p90/p99 threshold suggestions.") },
    ],
  },
  "domain-postgresql": {
    title: t("PostgreSQL 閾值設定", "PostgreSQL Threshold Configuration"),
    docs: [
      { name: t("領域專家快速上手", "Domain Expert Quick Start"), path: "for-domain-experts.md", priority: "start-here", summary: t("理解三層 Rule Pack 架構並設定閾值。", "Learn the three-layer Rule Pack architecture and set thresholds.") },
      { name: t("租戶快速上手", "Tenant Quick Start"), path: "for-tenants.md", summary: t("每個租戶 30 秒內該知道的 3 件事。", "The 3 things every tenant needs to know in 30 seconds.") },
      { name: t("告警參考", "Alert Reference"), path: "../rule-packs/ALERT-REFERENCE.md", summary: t(`全部 ${ALERT_COUNT} 個告警，含 severity、意義與建議動作。`, `All ${ALERT_COUNT} alerts with severity, meaning, and suggested actions.`) },
      { name: t("Rule Pack 總覽", "Rule Packs Overview"), path: "../rule-packs/README.md", summary: t(`${PACK_COUNT} 個 rule pack：各自涵蓋哪些指標、exporter 需求。`, `${PACK_COUNT} rule packs: which metrics they cover, exporter requirements.`) },
      { name: t("架構與設計", "Architecture & Design"), path: "../architecture-and-design.md", summary: t("核心概念：group_left 配對、三態模式、severity 去重。", "Core concepts: group_left matching, three-state mode, severity dedup.") },
      { name: t("基線探勘工具", "Baseline Discovery Tool"), path: "../internal/testing-playbook.md", summary: t("觀測真實指標並計算 p50/p90/p99 閾值建議。", "Observe real metrics and compute p50/p90/p99 threshold suggestions.") },
    ],
  },
  "domain-redis": {
    title: t("Redis 閾值設定", "Redis Threshold Configuration"),
    docs: [
      { name: t("領域專家快速上手", "Domain Expert Quick Start"), path: "for-domain-experts.md", priority: "start-here", summary: t("理解三層 Rule Pack 架構並設定閾值。", "Learn the three-layer Rule Pack architecture and set thresholds.") },
      { name: t("租戶快速上手", "Tenant Quick Start"), path: "for-tenants.md", summary: t("每個租戶 30 秒內該知道的 3 件事。", "The 3 things every tenant needs to know in 30 seconds.") },
      { name: t("告警參考", "Alert Reference"), path: "../rule-packs/ALERT-REFERENCE.md", summary: t(`全部 ${ALERT_COUNT} 個告警，含 severity、意義與建議動作。`, `All ${ALERT_COUNT} alerts with severity, meaning, and suggested actions.`) },
      { name: t("Rule Pack 總覽", "Rule Packs Overview"), path: "../rule-packs/README.md", summary: t(`${PACK_COUNT} 個 rule pack：各自涵蓋哪些指標、exporter 需求。`, `${PACK_COUNT} rule packs: which metrics they cover, exporter requirements.`) },
      { name: t("架構與設計", "Architecture & Design"), path: "../architecture-and-design.md", summary: t("核心概念：group_left 配對、三態模式、severity 去重。", "Core concepts: group_left matching, three-state mode, severity dedup.") },
      { name: t("基線探勘工具", "Baseline Discovery Tool"), path: "../internal/testing-playbook.md", summary: t("觀測真實指標並計算 p50/p90/p99 閾值建議。", "Observe real metrics and compute p50/p90/p99 threshold suggestions.") },
    ],
  },
  "domain-mongodb": {
    title: t("MongoDB 閾值設定", "MongoDB Threshold Configuration"),
    docs: [
      { name: t("領域專家快速上手", "Domain Expert Quick Start"), path: "for-domain-experts.md", priority: "start-here", summary: t("理解三層 Rule Pack 架構並設定閾值。", "Learn the three-layer Rule Pack architecture and set thresholds.") },
      { name: t("租戶快速上手", "Tenant Quick Start"), path: "for-tenants.md", summary: t("每個租戶 30 秒內該知道的 3 件事。", "The 3 things every tenant needs to know in 30 seconds.") },
      { name: t("告警參考", "Alert Reference"), path: "../rule-packs/ALERT-REFERENCE.md", summary: t(`全部 ${ALERT_COUNT} 個告警，含 severity、意義與建議動作。`, `All ${ALERT_COUNT} alerts with severity, meaning, and suggested actions.`) },
      { name: t("Rule Pack 總覽", "Rule Packs Overview"), path: "../rule-packs/README.md", summary: t(`${PACK_COUNT} 個 rule pack：各自涵蓋哪些指標、exporter 需求。`, `${PACK_COUNT} rule packs: which metrics they cover, exporter requirements.`) },
      { name: t("架構與設計", "Architecture & Design"), path: "../architecture-and-design.md", summary: t("核心概念：group_left 配對、三態模式、severity 去重。", "Core concepts: group_left matching, three-state mode, severity dedup.") },
      { name: t("基線探勘工具", "Baseline Discovery Tool"), path: "../internal/testing-playbook.md", summary: t("觀測真實指標並計算 p50/p90/p99 閾值建議。", "Observe real metrics and compute p50/p90/p99 threshold suggestions.") },
    ],
  },
  "domain-other": {
    title: t("自訂閾值設定", "Custom Threshold Configuration"),
    docs: [
      { name: t("領域專家快速上手", "Domain Expert Quick Start"), path: "for-domain-experts.md", priority: "start-here", summary: t("理解三層 Rule Pack 架構並設定閾值。", "Learn the three-layer Rule Pack architecture and set thresholds.") },
      { name: t("租戶快速上手", "Tenant Quick Start"), path: "for-tenants.md", summary: t("每個租戶 30 秒內該知道的 3 件事。", "The 3 things every tenant needs to know in 30 seconds.") },
      { name: t("告警參考", "Alert Reference"), path: "../rule-packs/ALERT-REFERENCE.md", summary: t(`全部 ${ALERT_COUNT} 個告警，含 severity、意義與建議動作。`, `All ${ALERT_COUNT} alerts with severity, meaning, and suggested actions.`) },
      { name: t("自訂規則治理", "Custom Rule Governance"), path: "../custom-rule-governance.md", summary: t("三層治理模型、CI 檢查、命名慣例。", "Three-tier governance model, CI linting, naming conventions.") },
      { name: t("架構與設計", "Architecture & Design"), path: "../architecture-and-design.md", summary: t("核心概念：group_left 配對、三態模式、severity 去重。", "Core concepts: group_left matching, three-state mode, severity dedup.") },
      { name: t("進階情境", "Advanced Scenarios"), path: "../internal/test-coverage-matrix.md", summary: t("Regex 閾值、排程值、跨午夜設定。", "Regex thresholds, scheduled values, cross-midnight configs.") },
    ],
  },
  "tenant-onboard": {
    title: t("讓你的團隊上手", "Getting Your Team Onboarded"),
    docs: [
      { name: t("租戶快速上手", "Tenant Quick Start"), path: "for-tenants.md", priority: "start-here", summary: t("每個租戶 30 秒內該知道的 3 件事。", "The 3 things every tenant needs to know in 30 seconds.") },
      { name: t("租戶生命週期情境", "Tenant Lifecycle Scenarios"), path: "../scenarios/tenant-lifecycle.md", summary: t("Scaffold → 驗證 → 部署 → 下線的完整生命週期。", "Scaffold → validate → deploy → offboard full lifecycle.") },
      { name: t("告警參考", "Alert Reference"), path: "../rule-packs/ALERT-REFERENCE.md", summary: t(`全部 ${ALERT_COUNT} 個告警，含 severity、意義與建議動作。`, `All ${ALERT_COUNT} alerts with severity, meaning, and suggested actions.`) },
      { name: t("Rule Pack 總覽", "Rule Packs Overview"), path: "../rule-packs/README.md", summary: t(`${PACK_COUNT} 個 rule pack：各自涵蓋哪些指標、exporter 需求。`, `${PACK_COUNT} rule packs: which metrics they cover, exporter requirements.`) },
      { name: t("遷移指南", "Migration Guide"), path: "../migration-guide.md", summary: t("逐步導入流程，搭配 scaffold 與 migrate 工具。", "Step-by-step onboarding flow with scaffold and migrate tools.") },
    ],
  },
  "tenant-alerts": {
    title: t("為你的服務設定告警", "Configure Alerts for Your Services"),
    docs: [
      { name: t("租戶快速上手", "Tenant Quick Start"), path: "for-tenants.md", priority: "start-here", summary: t("每個租戶 30 秒內該知道的 3 件事。", "The 3 things every tenant needs to know in 30 seconds.") },
      { name: t("告警參考", "Alert Reference"), path: "../rule-packs/ALERT-REFERENCE.md", summary: t(`全部 ${ALERT_COUNT} 個告警，含 severity、意義與建議動作。`, `All ${ALERT_COUNT} alerts with severity, meaning, and suggested actions.`) },
      { name: t("Rule Pack 總覽", "Rule Packs Overview"), path: "../rule-packs/README.md", summary: t(`${PACK_COUNT} 個 rule pack：各自涵蓋哪些指標、exporter 需求。`, `${PACK_COUNT} rule packs: which metrics they cover, exporter requirements.`) },
      { name: t("架構與設計", "Architecture & Design"), path: "../architecture-and-design.md", summary: t("核心概念：group_left 配對、三態模式、severity 去重。", "Core concepts: group_left matching, three-state mode, severity dedup.") },
      { name: t("進階情境", "Advanced Scenarios"), path: "../internal/test-coverage-matrix.md", summary: t("Regex 閾值、排程值、跨午夜設定。", "Regex thresholds, scheduled values, cross-midnight configs.") },
      { name: t("疑難排解指南", "Troubleshooting Guide"), path: "../troubleshooting.md", summary: t("常見問題、診斷指令、復原程序。", "Common issues, diagnostic commands, recovery procedures.") },
    ],
  },
  "tenant-routing": {
    title: t("設定告警路由與通知", "Set Up Alert Routing & Notifications"),
    docs: [
      { name: t("租戶快速上手", "Tenant Quick Start"), path: "for-tenants.md", priority: "start-here", summary: t("每個租戶 30 秒內該知道的 3 件事。", "The 3 things every tenant needs to know in 30 seconds.") },
      { name: t("告警路由分流 (NOC vs 租戶)", "Alert Routing Split (NOC vs Tenant)"), path: "../scenarios/alert-routing-split.md", summary: t("雙視角通知：NOC 收到 platform_summary、租戶收到 summary。", "Dual-perspective notifications: NOC gets platform_summary, tenant gets summary.") },
      { name: t("租戶生命週期情境", "Tenant Lifecycle Scenarios"), path: "../scenarios/tenant-lifecycle.md", summary: t("Scaffold → 驗證 → 部署 → 下線的完整生命週期。", "Scaffold → validate → deploy → offboard full lifecycle.") },
      { name: t("疑難排解指南", "Troubleshooting Guide"), path: "../troubleshooting.md", summary: t("常見問題、診斷指令、復原程序。", "Common issues, diagnostic commands, recovery procedures.") },
      { name: t("架構與設計", "Architecture & Design"), path: "../architecture-and-design.md", summary: t("核心概念：group_left 配對、三態模式、severity 去重。", "Core concepts: group_left matching, three-state mode, severity dedup.") },
    ],
  },
  "tenant-maintenance": {
    title: t("管理維護視窗與靜音", "Manage Maintenance Windows & Silences"),
    docs: [
      { name: t("租戶快速上手", "Tenant Quick Start"), path: "for-tenants.md", priority: "start-here", summary: t("每個租戶 30 秒內該知道的 3 件事。", "The 3 things every tenant needs to know in 30 seconds.") },
      { name: t("租戶生命週期情境", "Tenant Lifecycle Scenarios"), path: "../scenarios/tenant-lifecycle.md", summary: t("Scaffold → 驗證 → 部署 → 下線的完整生命週期。", "Scaffold → validate → deploy → offboard full lifecycle.") },
      { name: t("架構與設計", "Architecture & Design"), path: "../architecture-and-design.md", summary: t("核心概念：group_left 配對、三態模式、severity 去重。", "Core concepts: group_left matching, three-state mode, severity dedup.") },
      { name: t("進階情境", "Advanced Scenarios"), path: "../internal/test-coverage-matrix.md", summary: t("Regex 閾值、排程值、跨午夜設定。", "Regex thresholds, scheduled values, cross-midnight configs.") },
      { name: t("疑難排解指南", "Troubleshooting Guide"), path: "../troubleshooting.md", summary: t("常見問題、診斷指令、復原程序。", "Common issues, diagnostic commands, recovery procedures.") },
    ],
  },
};

export { GLOSSARY, ROLES, GOALS, DATABASES, NEEDS, BUCKET_LABELS, ROLE_AXIS, HANDOFF_TARGETS, RECOMMENDATIONS };
