#!/usr/bin/env bash
# install_prepush_hook.sh — put this repo's pre-push guards on the push path.
#
# Usage:
#   bash scripts/ops/install_prepush_hook.sh
#
# ⛔ No `--check` here. "Are the guards on the push path?" is answered in ONE
#   place, `pr_preflight._prepush_guards_wired()`, in pure Python. It lived here
#   once and preflight shelled out; that gave WRONG verdicts, not loud ones —
#   `shutil.which("bash")` can resolve to WSL, and Git's `usr/bin/bash` under a
#   non-MSYS parent has no `grep`, which a `2>/dev/null` probe swallows. This
#   script is only ever run BY a shell, so it keeps to bash builtins plus
#   `mv`/`chmod`/`rm` and says so when those are missing.
#
# ⛔ IT CHAINS WHAT WAS ALREADY THERE — NOT A CONVENIENCE. This repo has
#   `filter=lfs` paths and `git lfs install` is global, so a fresh clone
#   arrives with .git/hooks/pre-push owned by git-lfs. Refusing it made the
#   shipped remedy a dead end on such a clone; `pre-commit install
#   --hook-type pre-push` instead migrates lfs's `#!/bin/sh` hook and then every
#   push dies on `/bin/sh not found`. The foreign hook is moved to
#   pre-push.chained and run by prepush_dispatch.sh with the same argv and stdin.
#
# ⛔ ONE WIRED STATE: the shim, byte for byte, at .git/hooks/pre-push.
#   `pre-commit install --hook-type pre-push` writes a template there and moves
#   what it found to pre-push.legacy. This repo's config declares no pre-push
#   stage, so that template does nothing but call pre-push.legacy: the
#   installer writes the shim over it, removes our own shim or a guard copy
#   from pre-push.legacy, and chains anything else found there (git-lfs, on a
#   clone where pre-commit ran first). ⛔ Not chaining the template instead:
#   after the next `pre-commit install` it calls the shim through
#   pre-push.legacy from inside the dispatcher, and pre-commit's own recursion
#   check then fails every push, feature branches included.
#
# ⚠️ It cannot stop a later `pre-commit install --hook-type pre-push` (with or
#   without -f) from taking the slot back. That is what preflight is for.
#
set -uo pipefail

CHAINED_NAME="pre-push.chained"

say()  { printf '[install_prepush_hook] %s\n' "$1"; }
warn() { printf '[install_prepush_hook] %s\n' "$1" >&2; }

case "${1:-}" in
    "") ;;
    -h|--help)
        printf '%s\n' \
            "usage: bash scripts/ops/install_prepush_hook.sh" \
            "" \
            "Installs the pre-push guard shim, chaining any hook already there." \
            "To ask whether the guards are wired, run: make pr-preflight" \
            "  (without make: python3 scripts/tools/dx/pr_preflight.py; on Windows, python)" >&2
        exit 0 ;;
    *)
        warn "unknown argument: $1 (there is no --check; use \`make pr-preflight\`, or without make \`python3 scripts/tools/dx/pr_preflight.py\` — on Windows, \`python\`)"
        exit 2 ;;
esac

root="$(git rev-parse --show-toplevel 2>/dev/null)" || {
    warn "⛔ not inside a git work tree"
    exit 2
}
# ⛔ --git-path, not --git-dir: inside a worktree the git dir is
# .git/worktrees/<name> but the hooks live in the MAIN repo's .git/hooks. It
# also follows core.hooksPath, which this repo sets.
hooks="$(git rev-parse --git-path hooks 2>/dev/null)" || {
    warn "⛔ cannot resolve the hooks directory"
    exit 2
}

hook="$hooks/pre-push"
legacy="$hooks/pre-push.legacy"
chained="$hooks/$CHAINED_NAME"

# ⛔ `#!/usr/bin/env bash`, never an absolute interpreter path: when pre-commit
# owns the hook it resolves this shebang itself, and an absolute one is not a
# Windows path — measured, it aborts the whole push before ANY hook runs, which
# is exactly how git-lfs's `#!/bin/sh` hook breaks pushes under pre-commit.
#
# ⛔ The shim says something useful when the dispatcher is missing. It resolves
# it from the CURRENT work tree, and .git/hooks is shared by every worktree, so
# any tree checked out before #1689 lands has no dispatcher. Without the guard
# below the whole message is one line of `bash: …: No such file or directory`
# under three green `Passed` lines, and the three cheapest ways out of that
# picture each disarm the guards: --no-verify for that push, main included;
# deleting or hand-writing the hook for every worktree at once.
# ⛔ A quoted heredoc read into a variable by the `read` BUILTIN, then written
# with `printf`. Not `cat <<EOF` (needs `cat`, which is the dependency this file
# just removed) and not a printf with per-line escapes (the shim itself contains
# quotes, `$`, and continuations — building it out of escapes is how the escape
# gets eaten and the generated file becomes subtly wrong while still parsing).
IFS= read -r -d '' SHIM_BODY <<'VIBE_SHIM_EOF'
#!/usr/bin/env bash
# vibe-prepush-shim — generated by scripts/ops/install_prepush_hook.sh (#1689).
# ⛔ Do not edit here; edit scripts/ops/prepush_dispatch.sh. This file is
# rewritten by the installer and lives outside version control.
set -uo pipefail
_root="$(git rev-parse --show-toplevel 2>/dev/null)"
_dispatch="$_root/scripts/ops/prepush_dispatch.sh"
if [ ! -r "$_dispatch" ]; then
    {
        echo ""
        echo "[prepush] ⛔ No scripts/ops/prepush_dispatch.sh under the work tree git"
        echo "reports for this push, so the pre-push guards cannot run."
        echo "Work tree looked in: '$_root'"
        echo ""
        echo "If that is a checkout of this repo from before #1689: rebase / switch it"
        echo "to a commit that has the dispatcher. .git/hooks is shared by every"
        echo "worktree, so one old tree hits this while the others are fine."
        echo "If it is empty or not the top of a worktree (a bare repo, or"
        echo "git --git-dir=... run from elsewhere): push from inside a worktree of"
        echo "this repo, without --git-dir."
        echo ""
        echo "⛔ Re-running the installer does NOT fix this: the shim resolves the"
        echo "dispatcher from the tree you push FROM."
        echo ""
        echo "⛔ Do not reach for --no-verify: it skips every guard for that push,"
        echo "the direct-push-to-main one included. Do not delete .git/hooks/pre-push:"
        echo "that turns them off for EVERY worktree at once."
        echo ""
    } >&2
    exit 1
fi
exec bash "$_dispatch" "$@"
VIBE_SHIM_EOF

# ⛔ Identity by a WHOLE LINE equal to the generated header, never a substring:
# a user's hook that mentions the shim or pre-commit's `--hook-type=pre-push`
# in a comment is still a user's hook (#2617). Taken for either, it is
# overwritten (in pre-push.legacy, removed) instead of chained. Any line, not
# a fixed one, and a trailing CR dropped: on Windows pre-commit puts `#!/bin/sh`
# above its template and writes it CRLF.
# Bash builtins only — `read` is one, so these keep working when PATH carries
# nothing but the interpreter.
has_line() {   # $1 = file, $2 = the line
    [ -f "$1" ] || return 1
    local line
    while IFS= read -r line || [ -n "$line" ]; do
        [ "${line%$'\r'}" = "$2" ] && return 0
    done < "$1"
    return 1
}
shim_header="${SHIM_BODY#*$'\n'}"
shim_header="${shim_header%%$'\n'*}"
is_ours()      { has_line "$1" "$shim_header"; }
is_precommit() { has_line "$1" "# File generated by pre-commit: https://pre-commit.com"; }
# ⛔ A hook byte-identical to a committed version of one of our guards is a
# single-file install from before #1689. It cannot run outside scripts/ops/, so
# chaining it keeps every push failing; the dispatcher already runs what it
# duplicates. Identity, not content: a hook of the user's own that happens to
# source the helper must still be chained. Removing an identical copy loses
# nothing, since git holds the same blob.
guard_blobs="$(git -C "$root" log --all --no-renames --format= --raw --no-abbrev -- \
    scripts/ops/protect_main_push.sh scripts/ops/require_preflight_pass.sh \
    scripts/ops/pre_push_mkdocs_strict.sh 2>/dev/null)"
is_guard_copy() {
    [ -f "$1" ] || return 1
    local id
    id="$(git hash-object -- "$1" 2>/dev/null)" || return 1
    case "$guard_blobs" in (*" $id "*) return 0 ;; esac
    return 1
}

# Move a foreign hook into the chained slot. Fails loudly: a silent failure here
# means either that hook stops running or ours never installs.
stash_foreign() {   # $1 = path to the foreign hook
    if [ -e "$chained" ]; then
        warn "⛔ refusing: $1 is not ours and $chained is already occupied."
        warn "   Two different hooks want the chained slot. Resolve by hand:"
        warn "   inspect both, keep one at $chained, then re-run."
        return 1
    fi
    command -v mv >/dev/null 2>&1 || {
        warn "⛔ \`mv\` is not on PATH, so the existing hook at $1 cannot be"
        warn "   moved aside. Refusing rather than deleting it."
        return 1
    }
    mv "$1" "$chained" || {
        warn "⛔ could not move $1 to $chained"
        return 1
    }
    say "moved $1 to $CHAINED_NAME; the dispatcher will keep running it"
    return 0
}

# An earlier install chained a guard copy (this installer did, before it knew
# better). Take it out of the slot, or the dispatcher keeps running it.
if is_guard_copy "$chained"; then
    command -v rm >/dev/null 2>&1 || {
        warn "⛔ \`rm\` is not on PATH, so $chained, a copy of a pre-push guard"
        warn "   that cannot run there, stays. Delete it by hand (git holds the same"
        warn "   content), then re-run."
        exit 1
    }
    rm -f "$chained" || {
        warn "⛔ could not remove $chained, a copy of a pre-push guard that"
        warn "   cannot run there. Delete it by hand, then re-run."
        exit 1
    }
    say "removed $CHAINED_NAME: identical to a committed version of a guard, which only runs from scripts/ops/"
fi

target="$hook"
replaced=""
drop_legacy=""
if is_ours "$hook" || is_guard_copy "$hook"; then
    :                                    # refresh, or replace a guard copy
elif is_precommit "$hook"; then
    # The template is overwritten below. What it was calling is a hook
    # pre-commit migrated (chain it rather than destroy it) or ours (removed
    # once the shim is in place, since nothing calls it after that).
    if is_ours "$legacy" || is_guard_copy "$legacy"; then
        drop_legacy=1
    elif [ -e "$legacy" ]; then
        stash_foreign "$legacy" || exit 1
    fi
    replaced=" (replacing pre-commit's template)"
elif [ -e "$hook" ]; then
    stash_foreign "$hook" || exit 1
fi

if [ ! -d "$hooks" ]; then
    command -v mkdir >/dev/null 2>&1 || { warn "⛔ no \`mkdir\` and $hooks does not exist"; exit 1; }
    mkdir -p "$hooks" || exit 1
fi

# ⛔ A guard copy is replaced by `mv`, never written into: a hook symlinked or
# hard-linked to a guard in scripts/ops is identical to it, and `>` would go
# through the link into the version-controlled guard. Until the `mv`, the old
# hook stays as it was, so a failure on the way leaves nothing worse.
out="$target"
if is_guard_copy "$target"; then
    replaced=" (replacing a copy of a guard that was there)"
    out="$target.vibe-new"
fi
printf '%s' "$SHIM_BODY" > "$out" || { warn "⛔ could not write $out"; exit 1; }

# ⛔ Not `|| true`. git SILENTLY IGNORES a hook without the executable bit — it
# prints one `hint:` line that `advice.ignoredHook=false` turns off — so a
# swallowed chmod failure leaves a hook file that looks installed and never
# runs. Measured: with the bit cleared, a direct push to main succeeded with the
# guard banner absent.
if ! chmod +x "$out"; then
    warn "⛔ could not make $out executable. git ignores non-executable hooks"
    warn "   with only a hint, so the guards would look installed and never run."
    exit 1
fi
if [ "$out" != "$target" ]; then
    command -v mv >/dev/null 2>&1 && mv -f "$out" "$target" || {
        warn "⛔ could not move $out over $target, a copy of a pre-push guard."
        warn "   $target is unchanged. Delete it by hand (git holds the same content),"
        warn "   then re-run."
        exit 1
    }
fi

say "installed guard shim at $target$replaced"
if [ -n "$drop_legacy" ]; then
    if rm -f "$legacy"; then
        say "removed $legacy: it carried the shim's header or a guard's content, and nothing calls it now"
    else
        warn "could not remove $legacy (the shim's header or a guard's content); nothing calls it now"
    fi
fi
exit 0
