#!/usr/bin/env python3
"""da-assembler-controller — Lightweight ThresholdConfig CRD → YAML renderer.

Watches ThresholdConfig custom resources across namespaces and renders each
into a YAML file under --config-dir that threshold-exporter hot-reloads.

This is NOT a full Operator — it does not manage the exporter lifecycle, does
not auto-scale, and does not compete with GitOps.  It does exactly one thing:
CRD → YAML translation.

Usage:
    da_assembler.py --config-dir /etc/threshold-exporter/conf.d   # watch + reconcile
    da_assembler.py --config-dir ./build/config-dir --once         # one-shot render
    da_assembler.py --config-dir ./build/config-dir --dry-run      # preview without writing
    da_assembler.py --render-cr example.yaml --config-dir ./out    # render a single CR file

Prerequisites:
    pip install kubernetes pyyaml
    (or run inside a pod with ServiceAccount + RBAC)
"""

import argparse
import hashlib
import logging
import math
import os
import re
import signal
import stat
import sys
import time
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Dict

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _THIS_DIR)  # Docker flat layout
sys.path.insert(0, os.path.join(_THIS_DIR, ".."))  # Repo subdir layout
from _lib_exitcodes import EXIT_OK, EXIT_CALLER_ERROR  # noqa: E402
from _lib_io import (  # noqa: E402  (#1789)
    OutputWriteError,
    exit_on_output_write_error,
    output_write,
)
from _lib_yaml_keys import (  # noqa: E402  (#2216, #2331)
    RawPlain,
    dump_for_rewrite,
    load_for_rewrite,
)

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required.  pip install pyyaml", file=sys.stderr)
    sys.exit(EXIT_CALLER_ERROR)

try:
    from kubernetes import client, config, watch
    HAS_K8S = True
except ImportError:
    HAS_K8S = False

LOG_FORMAT = "%(asctime)s [%(levelname)s] %(message)s"
logging.basicConfig(format=LOG_FORMAT, level=logging.INFO)
log = logging.getLogger("da-assembler")

CRD_GROUP = "dynamicalerting.io"
CRD_VERSION = "v1alpha1"
CRD_PLURAL = "thresholdconfigs"

# Graceful shutdown
_shutdown = False


def _signal_handler(signum, frame):
    global _shutdown
    log.info("Received signal %d, shutting down...", signum)
    _shutdown = True


signal.signal(signal.SIGTERM, _signal_handler)
signal.signal(signal.SIGINT, _signal_handler)


# ── CR → YAML rendering ─────────────────────────────────────────────

def render_cr_to_yaml(cr: dict) -> str:
    """Convert a ThresholdConfig CR spec into tenant YAML content.

    The output format matches hand-written conf.d/<tenant>.yaml exactly.

    Tenant ids must arrive as ``str`` (#2216): the dump quotes a text
    key YAML would retype (``'010':``), so the exporter reads back the same
    id. A non-str key (``8``) is already a renamed tenant and cannot be
    recovered here — the reader is where it is kept (``render_cr_file``;
    the API path hands over JSON, whose keys are strings).

    A VALUE read as :class:`RawPlain` (``render_cr_file``, #2331) is written
    back plain, as the CR wrote it: ``010`` stays ``010``, ``12:30`` stays
    ``12:30`` — the exporter reads the CR's value, not PyYAML's retyping of
    it (``8``, ``750``). Any other value dumps as ``yaml.safe_dump`` would.
    """
    spec = cr.get("spec", {})
    metadata = cr.get("metadata", {})

    doc: Dict[str, Any] = {}

    # Each block is written only when it is a non-empty MAPPING. ⛔ Not a
    # truthiness test: a RawPlain scalar is text, so `defaults: 0` /
    # `stateFilters: false` read as "0" / "false" are truthy, and writing
    # them out makes the exporter skip the whole file (YamlFileError,
    # ValueError). Read PyYAML-typed they were falsy and dropped; this keeps
    # that — and drops any other non-mapping block the same way.

    # Tenants block (required)
    tenants = spec.get("tenants")
    if isinstance(tenants, dict) and tenants:
        doc["tenants"] = tenants

    # Optional platform blocks
    defaults = spec.get("defaults")
    if isinstance(defaults, dict) and defaults:
        doc["defaults"] = defaults

    state_filters = spec.get("stateFilters")
    if isinstance(state_filters, dict) and state_filters:
        doc["state_filters"] = state_filters

    header = (
        f"# Auto-generated by da-assembler from ThresholdConfig "
        f"{metadata.get('namespace', '?')}/{metadata.get('name', '?')}\n"
        f"# DO NOT EDIT — changes will be overwritten on next reconcile.\n"
    )

    return header + dump_for_rewrite(
        doc, default_flow_style=False, allow_unicode=True, sort_keys=False,
    )


def _content_sha256(content: str) -> str:
    """Compute SHA-256 hex digest of string content."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _output_filename(cr: dict) -> str:
    """Derive the output filename from a CR's metadata.name."""
    name = cr.get("metadata", {}).get("name", "unknown")
    return f"{name}.yaml"


# ── File writing ─────────────────────────────────────────────────────

def write_rendered(
    config_dir: Path,
    filename: str,
    content: str,
    *,
    dry_run: bool = False,
) -> bool:
    """Write rendered YAML to config-dir.  Returns True if file changed."""
    dest = config_dir / filename

    # Skip write if content is identical.
    # #1789: the idempotence read is wrapped TOO, because it reads the very
    # file this function exists to produce — when `dest` is a directory this
    # is where the run actually dies (measured), and "cannot write <dest>: Is
    # a directory" is the true statement about it. Contrast
    # `ops/config_history._load_history`, whose read is left alone: that one
    # reads a DIFFERENT path (the history state) from the one being written.
    with output_write(dest, flag="--config-dir"):
        if dest.exists():
            existing = dest.read_text(encoding="utf-8")
            if existing == content:
                return False

    if dry_run:
        log.info("DRY-RUN: would write %s (%d bytes)", filename, len(content))
        return True

    # #1789: the wrapper is given the PARENT — the directory this mkdir
    # actually creates. Handing it the output FILE makes the message a
    # sentence about a path nobody was creating (worked example in
    # `_lib_io.output_write`). The ancestor rule still converts the
    # failure, and the write below keeps naming the file.
    with output_write(config_dir, flag="--config-dir", action="create directory"):
        config_dir.mkdir(parents=True, exist_ok=True)
    # The 0644 chmod is inside the same block as the write: the rendered file
    # is read by the exporter, and a chmod that failed would leave a mode the
    # tool did not choose.
    with output_write(dest, flag="--config-dir"):
        dest.write_text(content, encoding="utf-8", newline="\n")
        os.chmod(dest, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)
    return True


def remove_rendered(
    config_dir: Path,
    filename: str,
    *,
    dry_run: bool = False,
) -> bool:
    """Remove a rendered file (CR deleted).  Returns True if file existed."""
    dest = config_dir / filename
    if not dest.exists():
        return False
    if dry_run:
        log.info("DRY-RUN: would delete %s", filename)
        return True
    dest.unlink()
    return True


# ── Status update ────────────────────────────────────────────────────

def update_cr_status(
    api: Any,
    cr: dict,
    phase: str,
    sha: str = "",
    message: str = "",
) -> None:
    """Patch the CR's status subresource."""
    name = cr["metadata"]["name"]
    namespace = cr["metadata"]["namespace"]
    tenant_count = len(cr.get("spec", {}).get("tenants", {}))

    status_body = {
        "status": {
            "phase": phase,
            "lastRenderedHash": sha,
            "lastRenderedTime": datetime.now(timezone.utc).isoformat(),
            "message": message,
            "tenantCount": tenant_count,
        }
    }

    try:
        api.patch_namespaced_custom_object_status(
            CRD_GROUP, CRD_VERSION, namespace, CRD_PLURAL, name,
            body=status_body,
        )
    except Exception as e:
        log.warning("Failed to update status for %s/%s: %s",
                    namespace, name, e)


# ── Reconcile loop ───────────────────────────────────────────────────

def reconcile_one(
    cr: dict,
    config_dir: Path,
    *,
    dry_run: bool = False,
    api: Any = None,
    cli: bool = False,
) -> None:
    """Reconcile a single ThresholdConfig CR.

    *cli* says which of the two callers this is: ``render_cr_file``
    (``--render-cr``, one CR, the rc is the operator's answer) or the
    controller loop (``run_once`` / ``run_watch``, one item among many).
    ⛔ It is an EXPLICIT flag and not ``api is None``, because the controller
    passes ``api=None`` too whenever ``--dry-run`` is set — inferring the
    caller from it made a dry-run controller re-raise, which aborts
    ``run_once`` after the first bad CR and turns ``run_watch`` into an
    endless "Watch interrupted … Reconnecting" loop.
    """
    name = cr["metadata"]["name"]
    namespace = cr["metadata"].get("namespace", "default")
    filename = _output_filename(cr)

    try:
        content = render_cr_to_yaml(cr)
        sha = _content_sha256(content)
        changed = write_rendered(config_dir, filename, content,
                                 dry_run=dry_run)

        if changed:
            log.info("Rendered %s/%s → %s (sha256:%s)",
                     namespace, name, filename, sha[:12])
        else:
            log.debug("No change for %s/%s", namespace, name)

        if api and not dry_run:
            update_cr_status(api, cr, "Rendered", sha=sha,
                             message=f"Written to {filename}")

    except Exception as e:
        # #1789: an unusable `--config-dir` used to be logged here and then
        # forgotten — `render_cr_file` returned EXIT_OK unconditionally, so
        # the CLI exited 0 having written nothing at all (measured). Re-raise
        # so `main`'s decorator turns it into the standard one-line rc=2.
        #
        # ⛔ ONLY on the CLI path (`cli=True`, i.e. `--render-cr`). In the
        # CONTROLLER path a reconcile is one item in a watch loop: a write
        # failure has to be reported on the CR's status and the loop has to
        # keep going, or one bad CR stops every other tenant from being
        # rendered. That path is unchanged — it still logs, still sets the
        # Error status, still returns. ⚠️ `api is None` is NOT the test: the
        # controller nulls `api` under `--dry-run`, so it would take this
        # branch too (see the docstring).
        #
        # #2395: ANY exception on the CLI path, not only OutputWriteError —
        # anything else was logged here and `render_cr_file` still returned
        # EXIT_OK with nothing written. `render_cr_file` turns it into rc 2.
        if cli:
            raise
        log.error("Failed to reconcile %s/%s: %s", namespace, name, e)
        if api and not dry_run:
            update_cr_status(api, cr, "Error", message=str(e)[:200])


def run_once(
    api: Any,
    config_dir: Path,
    *,
    dry_run: bool = False,
    namespace: str = "",
) -> int:
    """One-shot: list all ThresholdConfig CRs and render them."""
    try:
        if namespace:
            result = api.list_namespaced_custom_object(
                CRD_GROUP, CRD_VERSION, namespace, CRD_PLURAL)
        else:
            result = api.list_cluster_custom_object(
                CRD_GROUP, CRD_VERSION, CRD_PLURAL)
    except Exception as e:
        log.error("Failed to list ThresholdConfig resources: %s", e)
        return EXIT_CALLER_ERROR

    items = result.get("items", [])
    log.info("Found %d ThresholdConfig resource(s)", len(items))

    for cr in items:
        reconcile_one(cr, config_dir, dry_run=dry_run,
                      api=None if dry_run else api)

    return EXIT_OK


def run_watch(
    api: Any,
    config_dir: Path,
    *,
    dry_run: bool = False,
    namespace: str = "",
) -> None:
    """Watch loop: react to ThresholdConfig changes in real time."""
    log.info("Starting watch loop (config-dir=%s, dry-run=%s)",
             config_dir, dry_run)

    w = watch.Watch()
    resource_version = ""

    while not _shutdown:
        try:
            if namespace:
                stream = w.stream(
                    api.list_namespaced_custom_object,
                    CRD_GROUP, CRD_VERSION, namespace, CRD_PLURAL,
                    resource_version=resource_version,
                    timeout_seconds=300,
                )
            else:
                stream = w.stream(
                    api.list_cluster_custom_object,
                    CRD_GROUP, CRD_VERSION, CRD_PLURAL,
                    resource_version=resource_version,
                    timeout_seconds=300,
                )

            for event in stream:
                if _shutdown:
                    break

                event_type = event["type"]
                cr = event["object"]
                resource_version = (
                    cr.get("metadata", {}).get("resourceVersion", ""))
                name = cr.get("metadata", {}).get("name", "?")
                ns = cr.get("metadata", {}).get("namespace", "?")

                if event_type in ("ADDED", "MODIFIED"):
                    reconcile_one(cr, config_dir, dry_run=dry_run,
                                  api=None if dry_run else api)
                elif event_type == "DELETED":
                    filename = _output_filename(cr)
                    removed = remove_rendered(config_dir, filename,
                                              dry_run=dry_run)
                    if removed:
                        log.info("Deleted %s (CR %s/%s removed)",
                                 filename, ns, name)

        except Exception as e:
            if _shutdown:
                break
            log.warning("Watch interrupted: %s. Reconnecting in 5s...", e)
            time.sleep(5)

    log.info("Watch loop stopped.")


# ── Offline render (no K8s required) ─────────────────────────────────

#: YAML 1.1 (PyYAML) implicit tags that make an unquoted name a caller
#: error: int / float / bool. `timestamp` is absent — an unquoted date is
#: kept as written. Close to what Kubernetes sees after YAML→JSON, NOT the
#: same: go-yaml v2 and PyYAML type `0o17`, `1e3`, `08`, `y`, `n`, `1:30`
#: differently (#2371 review). Kubernetes' name format (DNS-1123) is not
#: checked either.
_NON_STRING_NAME_TAGS = frozenset("tag:yaml.org,2002:" + t
                                  for t in ("int", "float", "bool"))


def _plain_tag(text: str) -> str:
    """The tag YAML gives *text* written unquoted."""
    return yaml.resolver.Resolver().resolve(
        yaml.ScalarNode, text, (True, False))


def _keys_as_plain_text(obj: Any) -> Any:
    """*obj* with every mapping key a plain ``str`` (values untouched).

    ``load_for_rewrite`` reads an unquoted key as :class:`RawPlain`, which
    would be dumped back unquoted (``010:``). A tenant id is written QUOTED
    wherever YAML would retype it (``'010':``, #2216), so a reader that still
    types keys reads the same id — and an unquoted and a quoted CR render
    the same body. Only VALUES keep their plain spelling (#2331).
    """
    if isinstance(obj, dict):
        return {(str(k) if isinstance(k, RawPlain) else k):
                _keys_as_plain_text(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_keys_as_plain_text(v) for v in obj]
    return obj


def render_cr_file(
    cr_path: Path,
    config_dir: Path,
    *,
    dry_run: bool = False,
) -> int:
    """Render a single CR YAML file to config-dir (offline mode)."""
    # #2216: keys as the exporter reads them (the scalar's source text,
    # #2114) — a `tenants:` key read as `010` → 8 was rendered as `8:`, a
    # tenant the CR never named. `render_cr_to_yaml` dumps the text back,
    # quoted wherever YAML would retype it. Not strict, as before (#2123).
    #
    # #2331 / #2372: VALUES as the CR wrote them too. A PyYAML-typed read
    # retyped every unquoted scalar before it was dumped back: a threshold
    # `010` rendered as `8`, `12:30` as `750` (its `:30` severity lost), a
    # timestamp in Python's spelling — and `metadata.name: 010` named the
    # output `8.yaml` (`yes` → `True.yaml`), which tenant-api cannot find.
    # `load_for_rewrite` keeps a plain scalar's text (RawPlain, a `str`), so
    # the file name, the log and the header name the CR as written.
    try:
        with open(cr_path, encoding="utf-8") as fh:
            cr = _keys_as_plain_text(load_for_rewrite(fh))
    except (OSError, yaml.YAMLError) as e:
        log.error("Failed to parse %s: %s", cr_path, e)
        return EXIT_CALLER_ERROR

    if not isinstance(cr, dict) or cr.get("kind") != "ThresholdConfig":
        log.error("%s is not a ThresholdConfig resource", cr_path)
        return EXIT_CALLER_ERROR

    # #2371: shape checks `reconcile_one` does not make. Its
    # `cr["metadata"]["name"]` sits outside its try (KeyError/TypeError
    # traceback, rc 1), a non-str/empty name became the filename (`.yaml`,
    # `42.yaml`), and a non-mapping `spec` failed inside the try and was
    # swallowed (rc 0, nothing written). An absent `spec` is left alone: it
    # renders as `spec: {}` did before.
    metadata = cr.get("metadata")
    name = metadata.get("name") if isinstance(metadata, dict) else None
    # An explicitly tagged `!!timestamp "2024-01-01"` is still a `date`
    # object (only a plain scalar is RawPlain); it rendered to
    # `2024-01-01.yaml` before #2371, so it stays accepted. A `datetime`
    # does not: its str() is not the text the CR wrote.
    if isinstance(name, date) and not isinstance(name, datetime):
        name = name.isoformat()
    if not isinstance(name, str) or not name:
        log.error("%s: metadata.name must be a non-empty string", cr_path)
        return EXIT_CALLER_ERROR
    # An unquoted name is RawPlain text. Judged by YAML 1.1 (PyYAML)
    # implicit typing: one read as int / float / bool is a caller error;
    # a date / datetime is kept as written (see _NON_STRING_NAME_TAGS for
    # where this differs from Kubernetes). Null was refused above.
    tag = _plain_tag(name) if isinstance(name, RawPlain) else None
    if tag in _NON_STRING_NAME_TAGS:
        log.error("%s: metadata.name must be a string, but unquoted %s is "
                  "read as %s (YAML 1.1). Quoting makes it a string; it "
                  "must still be a valid Kubernetes object name (DNS-1123), "
                  "which this tool does not check", cr_path, name,
                  tag.rsplit(":", 1)[-1])
        return EXIT_CALLER_ERROR
    if "spec" in cr and not isinstance(cr["spec"], dict):
        log.error("%s: spec must be a mapping", cr_path)
        return EXIT_CALLER_ERROR
    shape_error = _spec_block_shape_error(cr.get("spec") or {})
    if shape_error:
        log.error("%s: %s", cr_path, shape_error)
        return EXIT_CALLER_ERROR

    # #2395: `reconcile_one(cli=True)` re-raises whatever stopped the
    # render. OutputWriteError goes on to `main`'s decorator (#1789, rc 2
    # naming --config-dir); anything else is one line and rc 2 here. rc 0
    # only when the file was written (or, under --dry-run, would be) and
    # nothing raised. ⚠️ A failure BEFORE the write leaves no file; one after
    # it (e.g. in the log line that follows) is rc 2 with the file on disk.
    try:
        reconcile_one(cr, config_dir, dry_run=dry_run, cli=True)
    except OutputWriteError:
        raise
    except Exception as e:  # noqa: BLE001 — every cause is a failed render
        log.error("Failed to render %s: %s", cr_path, e)
        return EXIT_CALLER_ERROR
    return EXIT_OK


def _spec_block_shape_error(spec: dict) -> str:
    """Why *spec*'s blocks would not render as the CR wrote them, or ``""``.

    #2395. ``render_cr_to_yaml`` silently drops a block that is not a
    mapping (``defaults: [x]``, ``stateFilters: foo``), and writes a tenant
    whose value is not a mapping as-is — the exporter then refuses the WHOLE
    file (``cannot unmarshal !!int``), every tenant in it included. The CRD
    declares each of these ``type: object``.
    Left alone: null (a null tenant is read by the exporter as empty), and a
    BLOCK whose value YAML types as falsy (``defaults: 0``, ``tenants:
    false``, ``[]``) — dropped as an empty block, which #2331 pins (tests/
    ops/test_tenant_id_as_text.py). A TENANT value gets no such pass: it is
    written, not dropped, and the exporter refuses ``t2: 0`` too.
    A ``!!set`` is a mapping to the exporter (every value null), so it passes
    wherever a mapping is WRITTEN (a tenant, a state filter); a block that is
    a set is still refused, because ``render_cr_to_yaml`` would drop it.

    Below the blocks, only as deep as the exporter's types go
    (``pkg/config/types.go``): ``defaults`` is ``map[string]float64``
    (:func:`_default_value_error`) and ``state_filters`` is
    ``map[string]StateFilter`` (:func:`_state_filter_error`). Tenant values
    below the tenant (``ScheduledValue``) are not checked.
    Only ``--render-cr`` asks this; the controller path is unchanged.
    """
    for key in ("tenants", "defaults", "stateFilters"):
        block = spec.get(key)
        if block is None or isinstance(block, dict):
            continue
        # A plain scalar's text, as YAML types it — NOT re-parsed as a
        # document: `yaml.safe_load("---")` is None, and `--- 0`, `--- no`
        # would read as falsy too, dropping a block the CR wrote. Only a
        # null / bool / int / float can be falsy; any other tag is text.
        if isinstance(block, RawPlain):
            block = (yaml.safe_load(block)
                     if _plain_tag(block) in _FALSY_ABLE_TAGS else str(block))
        if block:
            return f"spec.{key} must be a mapping"
    tenants = spec.get("tenants")
    for tenant, values in (tenants if isinstance(tenants, dict) else {}).items():
        if values is not None and not isinstance(values, (dict, set)):
            return (f"spec.tenants.{tenant} must be a mapping; the exporter "
                    f"skips the whole rendered file otherwise")
    defaults = spec.get("defaults")
    for metric, value in (defaults if isinstance(defaults, dict) else {}).items():
        why = _default_value_error(value)
        if why:
            return (f"spec.defaults.{metric} {why}; the exporter skips the "
                    f"whole rendered file otherwise")
    filters = spec.get("stateFilters")
    for name, sf in (filters if isinstance(filters, dict) else {}).items():
        why = _state_filter_error(sf)
        if why:
            return (f"spec.stateFilters.{name}{why}; the exporter skips the "
                    f"whole rendered file otherwise")
    return ""


_FALSY_ABLE_TAGS = frozenset("tag:yaml.org,2002:" + t
                             for t in ("null", "bool", "int", "float"))

# ── yaml.v3's plain-scalar → number resolution (#2395) ──────────────
#
# The exporter decodes `defaults` with gopkg.in/yaml.v3 (v3.0.1): a plain
# scalar lands in a float64 only if `resolve()` (resolve.go) types it
# int / float. What follows is that function's number path, step for step,
# with the Go strconv calls it makes (internal/strconv/atoi.go, atof.go).
# `test_the_rows_match_the_exporter` re-measures it against da-guard.
# ⚠️ Not claimed for a mantissa thousands of digits long: Go's ParseFloat
# reads those differently from Python's `float()` (`1` + 5000 `0` +
# `e-1000` is 1e-201 in Go, inf here), so such a value may be refused.

_V3_NAMED_FLOATS = frozenset(
    p + w for w in (".inf", ".Inf", ".INF") for p in ("", "+", "-")
) | frozenset((".nan", ".NaN", ".NAN"))
# resolve.go `yamlStyleFloat`.
_V3_STYLE_FLOAT = re.compile(
    r"[-+]?(\.[0-9]+|[0-9]+(\.[0-9]*)?)([eE][-+]?[0-9]+)?")
# Go strconv's digit value of an ASCII byte; anything else is not a digit.
_GO_DIGIT_VALUE = {c: int(c, 36) for c in
                   "0123456789abcdefghijklmnopqrstuvwxyz"
                   "ABCDEFGHIJKLMNOPQRSTUVWXYZ"}
# What Go's ParseFloat accepts from a text starting with `.` (no sign, no
# 0x prefix, not inf/nan), once `_go_underscore_ok` has passed it.
_GO_DOT_FLOAT = re.compile(r"\.[0-9]+([eE][-+]?[0-9]+)?")


def _go_underscore_ok(s: str) -> bool:
    """Go ``strconv.underscoreOK``: each ``_`` sits between digits (or
    between a base prefix and a digit)."""
    if s[:1] in ("+", "-"):
        s = s[1:]
    saw, i, hexa = "^", 0, False
    if len(s) >= 2 and s[0] == "0" and s[1] in "bBoOxX":
        saw, i, hexa = "0", 2, s[1] in "xX"
    for c in s[i:]:
        if "0" <= c <= "9" or hexa and c in "abcdefABCDEF":
            saw = "0"
        elif c == "_":
            if saw != "0":
                return False
            saw = "_"
        elif saw == "_":
            return False
        else:
            saw = "!"
    return saw != "_"


def _go_parse_uint(s: str, base: int):
    """Go ``strconv.ParseUint(s, base, 64)`` on a text without ``_``:
    the value, or None on any error."""
    if not s:
        return None
    if base == 0:
        base = 10
        if s[0] == "0":
            prefix = {"b": 2, "B": 2, "o": 8, "O": 8,
                      "x": 16, "X": 16}.get(s[1:2])
            if len(s) >= 3 and prefix:
                base, s = prefix, s[2:]
            else:
                base, s = 8, s[1:]
    n = 0
    for c in s:
        # Go reads BYTES: only ASCII 0-9 / a-z / A-Z are digits. ⛔ No
        # `c.lower()` on the raw char — `"İ".lower()` is two chars.
        d = _GO_DIGIT_VALUE.get(c, 99)
        if d >= base:
            return None
        n = n * base + d
        # Go's cutoff: stop at the first overflow (ErrRange) instead of
        # carrying a bignum to the end of a very long text.
        if n >= 1 << 64:
            return None
    return n


def _go_parse_int(s: str, base: int):
    """Go ``strconv.ParseInt(s, base, 64)``: the value, or None."""
    neg = s[:1] == "-"
    un = _go_parse_uint(s[1:] if s[:1] in ("+", "-") else s, base)
    if un is None or un > (1 << 63 if neg else (1 << 63) - 1):
        return None
    return -un if neg else un


def _go_parse_float_ok(s: str) -> bool:
    """Go ``strconv.ParseFloat(s, 64)`` succeeds, for the two shapes
    resolve() hands it: a `.`-led text, or one `_V3_STYLE_FLOAT` matched.
    Overflow (±Inf) is an error; underflow is not. Judged by Python's
    `float()`, which matches Go except on a mantissa thousands of digits
    long (see the section comment)."""
    try:
        return not math.isinf(float(s.replace("_", "")))
    except ValueError:
        return False


def _v3_reads_as_number(text: str) -> bool:
    """yaml.v3 resolves the PLAIN scalar *text* to an int or a float."""
    if text in _V3_NAMED_FLOATS:
        return True
    head = text[:1]
    if head == ".":
        # `strconv.ParseFloat(in)` on the text as written, `_` included.
        return (_go_underscore_ok(text)
                and bool(_GO_DOT_FLOAT.fullmatch(text.replace("_", "")))
                and _go_parse_float_ok(text))
    if not head or head not in "+-0123456789":
        return False  # hint 'M' (only the named table) or none: a string
    plain = text.replace("_", "")
    if (_go_parse_int(plain, 0) is not None
            or _go_parse_uint(plain, 0) is not None):
        return True
    if _V3_STYLE_FLOAT.fullmatch(plain) and _go_parse_float_ok(plain):
        return True
    # Fallbacks after the float: an explicit base, where Go's ParseInt
    # takes a sign after the prefix (`0b-1`).
    for prefix, base in (("0b", 2), ("0o", 8)):
        if plain.startswith(prefix):
            rest = plain[2:]
            return (_go_parse_int(rest, base) is not None
                    or _go_parse_uint(rest, base) is not None)
        if plain.startswith("-" + prefix):
            return _go_parse_int("-" + plain[3:], base) is not None
    return False


def _default_value_error(value: Any) -> str:
    """Why *value* is not a ``defaults`` value the exporter decodes, or ``""``.

    The exporter reads ``defaults`` as ``map[string]float64``. Oracle
    (``da-guard served-values``, rc 3 = file refused): null and numbers are
    read; a bool, a date, a sequence / mapping, and ANY quoted scalar —
    ``"80"`` included — make it refuse the whole file.
    """
    if value is None:
        return ""
    if isinstance(value, bool):
        return "must be a number, not a boolean"
    if isinstance(value, (int, float)):
        return ""
    if not isinstance(value, str):
        return "must be a number"
    # A RawPlain is dumped back plain, as written. Any other str is dumped
    # plain only where PyYAML would not retype it; otherwise it is QUOTED,
    # and yaml.v3 does not decode a quoted scalar into a number.
    if (not isinstance(value, RawPlain)
            and _plain_tag(value) != "tag:yaml.org,2002:str"):
        return "must be a number, not a quoted string"
    if not _v3_reads_as_number(value):
        return f"must be a number, not {value!r}"
    return ""


def _state_filter_error(sf: Any) -> str:
    """Why *sf* is not a ``StateFilter`` the exporter decodes, or ``""``.

    ``StateFilter`` is ``{reasons: []string, severity: string,
    default_state: string}``, other keys ignored. Oracle-measured: a
    non-mapping filter, a non-sequence ``reasons`` or one holding a
    sequence / mapping, and a sequence / mapping ``severity`` /
    ``default_state`` are refused. Any scalar (null included) is a string.
    The returned text follows the filter's name.
    """
    if sf is None or isinstance(sf, set):
        return ""
    if not isinstance(sf, dict):
        return " must be a mapping"
    reasons = sf.get("reasons")
    if reasons is not None:
        if not isinstance(reasons, list):
            return ".reasons must be a list"
        # `tuple`: an item of `!!omap` / `!!pairs`, a one-key mapping to
        # the exporter.
        if any(isinstance(r, (list, tuple, dict, set)) for r in reasons):
            return ".reasons must be a list of strings"
    for key in ("severity", "default_state"):
        if isinstance(sf.get(key), (list, dict, set)):
            return f".{key} must be a string"
    return ""


# ── Main ─────────────────────────────────────────────────────────────

@exit_on_output_write_error
def main() -> int:
    """CLI entry point: Lightweight ThresholdConfig CRD → YAML renderer."""
    parser = argparse.ArgumentParser(
        description="Lightweight ThresholdConfig CRD → YAML assembler.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--config-dir", required=True,
        help="Output directory for rendered YAML files",
    )
    parser.add_argument(
        "--once", action="store_true",
        help="One-shot mode: render all CRs and exit",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Preview mode: show what would be written without writing",
    )
    parser.add_argument(
        "--namespace", type=str, default="",
        help="Watch only this namespace (default: all namespaces)",
    )
    parser.add_argument(
        "--render-cr", type=str, default="",
        help="Render a single CR YAML file (offline, no K8s required)",
    )
    parser.add_argument(
        "--kubeconfig", type=str, default="",
        help="Path to kubeconfig file (default: in-cluster or ~/.kube/config)",
    )
    parser.add_argument(
        "--verbose", action="store_true",
        help="Enable debug logging",
    )

    args = parser.parse_args()
    config_dir = Path(args.config_dir).resolve()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    # Offline render mode (no K8s client needed)
    if args.render_cr:
        return render_cr_file(
            Path(args.render_cr), config_dir, dry_run=args.dry_run)

    # K8s client required for watch/once modes
    if not HAS_K8S:
        log.error("kubernetes Python client is required.  "
                   "pip install kubernetes")
        return EXIT_CALLER_ERROR

    # Load kubeconfig
    try:
        if args.kubeconfig:
            config.load_kube_config(config_file=args.kubeconfig)
        else:
            try:
                config.load_incluster_config()
                log.info("Using in-cluster config")
            except config.ConfigException:
                config.load_kube_config()
                log.info("Using kubeconfig")
    except Exception as e:
        log.error("Failed to load Kubernetes config: %s", e)
        return EXIT_CALLER_ERROR

    api = client.CustomObjectsApi()

    if args.once:
        return run_once(api, config_dir, dry_run=args.dry_run,
                        namespace=args.namespace)

    # Default: watch mode
    # Do initial sync first
    rc = run_once(api, config_dir, dry_run=args.dry_run,
                  namespace=args.namespace)
    if rc != 0:
        return rc

    run_watch(api, config_dir, dry_run=args.dry_run,
              namespace=args.namespace)
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
