package policy

// merge_key_corpus_test.go — tenant-api's half of
// tests/shared/merge_key_policy_corpus.json (#2677): `_domain_policy.yaml`
// documents built around YAML merge keys, each with what the route
// generator's reader (PyYAML) makes of it, generated by
// tests/shared/test_merge_key_policy_corpus.py, then the deterministic
// `shape` rows of hub #2486 (PR-7c/7d) and #2759 (A, F, K1, N).
//
// parseConfig must read what PyYAML reads, or exactly what
// tests/shared/merge_key_go_verdicts.json records for that row under
// "tenant-api" (ADR-036 step 2), or refuse the file — for every row, a
// `nonspecific_tag` row included. Refusing is still excused wholesale (the
// watcher keeps the last good file) and is not recorded; refusals get a
// direction of their own in a later step (ADR-036 step 2, PR-C). Every row
// parseConfig READS differently from PyYAML is recorded, and which way it
// leans and which catalog entry accepts it is decided once, in Python:
// tests/shared/test_reader_divergence_catalog.py against
// tests/shared/reader_divergence_catalog.yaml. A changed verdict — a new
// difference, or a recorded one that healed or is now refused — is red
// here until the snapshot is regenerated (which rewrites only the
// "tenant-api" entries):
//
//	UPDATE_GO_VERDICTS=1 go test ./internal/policy/ -run TestMergeKeyCorpus -count=1
//
// and the regenerated diff then has to pass the catalog test. da-guard's
// half is components/threshold-exporter/app/pkg/routingpolicy/merge_key_corpus_test.go.

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"
	"unicode/utf16"
)

// goVerdictsReader is this test's key in merge_key_go_verdicts.json.
const goVerdictsReader = "tenant-api"

// corpusPolicy is one domain in the corpus's verdict shape: `allowed` only
// when allowed_receiver_types is a non-empty list, `escalation` only when
// true.
type corpusPolicy struct {
	Tenants   []string `json:"tenants"`
	Forbidden []string `json:"forbidden"`
	// Allowed is set when allowed_receiver_types is a non-empty list: the
	// types it allows (none, for a list of only non-string entries — it
	// still restricts every type).
	Allowed    *[]string `json:"allowed,omitempty"`
	Escalation bool      `json:"escalation,omitempty"`
}

type corpusRow struct {
	Doc         string          `json:"doc"`
	ID          string          `json:"id"`
	PyYAML      json.RawMessage `json:"pyyaml"`
	Nonspecific string          `json:"nonspecific_tag"`
	Shape       string          `json:"shape"`
	Encoding    string          `json:"encoding"`
	// PyYAMLStrictBlocks lists the generator's own blocking findings for a
	// file it reads but blocks on as production runs it (`--validate
	// --strict`). Such a row's verdict, for a Go reader, is "unusable":
	// parseConfig must refuse it (pyEffectiveVerdict).
	PyYAMLStrictBlocks []json.RawMessage `json:"pyyaml_strict_blocks"`
}

// corpusBytes is the file a row stands for: its doc as UTF-8, or, for an
// `encoding` row, written in that encoding (the byte order mark, then
// UTF-16; Latin-1) — a file the generator, UTF-8 only, cannot read.
func corpusBytes(t *testing.T, doc, encoding string) []byte {
	t.Helper()
	switch encoding {
	case "":
		return []byte(doc)
	case "utf-16-le-bom", "utf-16-be-bom":
		var order binary.ByteOrder = binary.LittleEndian
		if encoding == "utf-16-be-bom" {
			order = binary.BigEndian
		}
		units := append([]uint16{0xFEFF}, utf16.Encode([]rune(doc))...)
		out := make([]byte, 2*len(units))
		for i, u := range units {
			order.PutUint16(out[2*i:], u)
		}
		return out
	case "latin-1":
		out := make([]byte, 0, len(doc))
		for _, r := range doc {
			if r > 0xFF {
				t.Fatalf("corpus row: %q is not Latin-1", r)
			}
			out = append(out, byte(r))
		}
		return out
	}
	t.Fatalf("corpus row: unknown encoding %q", encoding)
	return nil
}

// corpusRowID is a row's id as the corpus spells it: the first 16 hex
// digits of the sha256 of the file it stands for.
func corpusRowID(file []byte) string {
	sum := sha256.Sum256(file)
	return hex.EncodeToString(sum[:])[:16]
}

// sharedTestFile is a file under tests/shared/.
func sharedTestFile(name string) string {
	_, thisFile, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..", "tests", "shared", name)
}

// canonicalVerdict renders a verdict as compact JSON, map keys sorted, `<`
// and `>` unescaped (tenant ids such as `<<` stay readable): the form the
// snapshot holds and the form two verdicts are compared in. da-guard's
// half renders the same.
func canonicalVerdict(t *testing.T, v any) string {
	t.Helper()
	raw, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("verdict %v: %v", v, err)
	}
	var generic any
	if err := json.Unmarshal(raw, &generic); err != nil {
		t.Fatalf("verdict %s: %v", raw, err)
	}
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(generic); err != nil {
		t.Fatalf("verdict %s: %v", raw, err)
	}
	return strings.TrimSuffix(b.String(), "\n")
}

// pyEffectiveVerdict is the verdict a Go reader is held to: PyYAML's, or
// "unusable" when the generator reads the file but blocks on it under
// --validate --strict (`pyyaml_strict_blocks`) — enforcing nothing there
// and reporting nothing would let through a file production refuses.
// da-guard's half holds the same.
func pyEffectiveVerdict(t *testing.T, raw json.RawMessage, strictBlocks []json.RawMessage, i int) string {
	t.Helper()
	if len(strictBlocks) > 0 {
		return canonicalVerdict(t, "unusable")
	}
	var py any
	if err := json.Unmarshal(raw, &py); err != nil {
		t.Fatalf("row %d: verdict %s: %v", i, raw, err)
	}
	return canonicalVerdict(t, py)
}

// goVerdictsFile is merge_key_go_verdicts.json: per reader, row id to that
// reader's verdict, for the rows where it differs from PyYAML.
type goVerdictsFile struct {
	Comment []string
	Readers map[string]map[string]json.RawMessage
}

func readGoVerdicts(t *testing.T) goVerdictsFile {
	t.Helper()
	raw, err := os.ReadFile(sharedTestFile("merge_key_go_verdicts.json"))
	if err != nil {
		t.Fatalf("read snapshot: %v", err)
	}
	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		t.Fatalf("parse snapshot: %v", err)
	}
	f := goVerdictsFile{Readers: map[string]map[string]json.RawMessage{}}
	for k, v := range top {
		if k == "_comment" {
			if err := json.Unmarshal(v, &f.Comment); err != nil {
				t.Fatalf("snapshot _comment: %v", err)
			}
			continue
		}
		var entries map[string]json.RawMessage
		if err := json.Unmarshal(v, &entries); err != nil {
			t.Fatalf("snapshot %q: %v", k, err)
		}
		f.Readers[k] = entries
	}
	return f
}

// writeGoVerdicts renders the snapshot deterministically: `_comment`, then
// each reader sorted by name, its rows sorted by id, one row a line —
// exactly as da-guard's half does, so either rewrites the other's entries
// byte for byte.
func writeGoVerdicts(t *testing.T, f goVerdictsFile) {
	t.Helper()
	var b strings.Builder
	var comment bytes.Buffer
	enc := json.NewEncoder(&comment)
	enc.SetEscapeHTML(false)
	enc.SetIndent("  ", "  ")
	if err := enc.Encode(f.Comment); err != nil {
		t.Fatalf("render snapshot comment: %v", err)
	}
	b.WriteString("{\n  \"_comment\": " + strings.TrimSuffix(comment.String(), "\n"))
	readers := make([]string, 0, len(f.Readers))
	for k := range f.Readers {
		readers = append(readers, k)
	}
	sort.Strings(readers)
	for _, reader := range readers {
		fmt.Fprintf(&b, ",\n  %q: {", reader)
		ids := make([]string, 0, len(f.Readers[reader]))
		for id := range f.Readers[reader] {
			ids = append(ids, id)
		}
		sort.Strings(ids)
		for i, id := range ids {
			var v any
			if err := json.Unmarshal(f.Readers[reader][id], &v); err != nil {
				t.Fatalf("snapshot %s %s: %v", reader, id, err)
			}
			sep := ","
			if i == 0 {
				sep = ""
			}
			fmt.Fprintf(&b, "%s\n    %q: %s", sep, id, canonicalVerdict(t, v))
		}
		if len(ids) > 0 {
			b.WriteString("\n  ")
		}
		b.WriteString("}")
	}
	b.WriteString("\n}\n")
	if err := os.WriteFile(sharedTestFile("merge_key_go_verdicts.json"), []byte(b.String()), 0o644); err != nil {
		t.Fatalf("write snapshot: %v", err)
	}
}

// corpusClass names a row's kind for the per-kind tally: its `shape`, or
// "seeded", with "/nonspecific" when it carries the non-specific tag `!` on a
// quoted scalar (read through the vendored yaml.v3 patch, #2730 §6).
func corpusClass(row corpusRow) string {
	c := row.Shape
	if c == "" {
		c = "seeded"
	}
	if row.Nonspecific != "" {
		c += "/nonspecific"
	}
	return c
}

// tenantAPIVerdict is what parseConfig reads, in the corpus's shape: each
// domain with forbidden types or a non-empty allowed list.
func tenantAPIVerdict(t *testing.T, cfg *DomainPolicyConfig) string {
	t.Helper()
	got := map[string]corpusPolicy{}
	for name, p := range cfg.DomainPolicies {
		allowed := p.Constraints.AllowedReceiverTypes
		if len(p.Constraints.ForbiddenReceiverTypes) == 0 && len(allowed) == 0 {
			continue
		}
		f := append([]string{}, p.Constraints.ForbiddenReceiverTypes...)
		sort.Strings(f)
		// The escalation as RoutingPolicies enforces it: a boolean true.
		cp := corpusPolicy{Tenants: append([]string{}, p.Tenants...), Forbidden: f,
			Escalation: p.Constraints.RequireCriticalEscalation.Value == true}
		if len(allowed) > 0 {
			// A non-string entry (NotAReceiverType) allows no type: the
			// corpus lists the string entries only.
			a := []string{}
			for _, s := range allowed {
				if s != NotAReceiverType {
					a = append(a, s)
				}
			}
			sort.Strings(a)
			cp.Allowed = &a
		}
		got[name] = cp
	}
	return canonicalVerdict(t, got)
}

func TestMergeKeyCorpus_ParseConfigIsPyYAMLsOrRecordedOrRefuses(t *testing.T) {
	t.Parallel()
	raw, err := os.ReadFile(sharedTestFile("merge_key_policy_corpus.json"))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var c struct {
		Comment []string    `json:"_comment"`
		PyYAML  string      `json:"pyyaml"`
		Rows    []corpusRow `json:"rows"`
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&c); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	if len(c.Rows) < 400 {
		t.Fatalf("corpus has %d rows — a near-empty corpus proves nothing", len(c.Rows))
	}
	snap := readGoVerdicts(t)
	recorded := snap.Readers[goVerdictsReader]
	update := os.Getenv("UPDATE_GO_VERDICTS") != ""
	// No row is skipped (hub #2486 Q7-2): a `nonspecific_tag` row — the
	// non-specific tag `!` the vendored yaml.v3 keeps — must be read as PyYAML
	// reads it or as recorded, or refused.
	differ := map[string]json.RawMessage{}
	seen := map[string]bool{}
	refused, bad, matched := 0, 0, 0
	badBy, refusedBy, allBy := map[string]int{}, map[string]int{}, map[string]int{}
	for i, row := range c.Rows {
		class := corpusClass(row)
		allBy[class]++
		file := corpusBytes(t, row.Doc, row.Encoding)
		if id := corpusRowID(file); id != row.ID {
			t.Fatalf("row %d: id %q, the file's sha256 says %q", i, row.ID, id)
		}
		seen[row.ID] = true
		pyVerdict := pyEffectiveVerdict(t, row.PyYAML, row.PyYAMLStrictBlocks, i)
		start := time.Now()
		cfg, err := parseConfig(file)
		if strings.HasPrefix(row.Shape, "merge-chain-") || strings.HasPrefix(row.Shape, "2715-") {
			t.Logf("row %d (%s, %d bytes): parseConfig took %v, err = %v",
				i, row.Shape, len(row.Doc), time.Since(start), err)
		}
		rec, isRecorded := recorded[row.ID]
		if err != nil {
			refused++
			refusedBy[class]++
			// Refusing is excused (the watcher keeps the last good file) —
			// but a recorded read that is now a refusal is a stale entry.
			if isRecorded && !update {
				bad++
				badBy[class]++
				t.Errorf("row %d %s [%s]: parseConfig refuses the file, the snapshot records a read %s;"+
					" regenerate with UPDATE_GO_VERDICTS=1", i, row.ID, class, rec)
			}
			continue
		}
		got := tenantAPIVerdict(t, cfg)
		if got != pyVerdict {
			differ[row.ID] = json.RawMessage(got)
		} else if pyVerdict != `{}` {
			matched++
		}
		want := pyVerdict
		if isRecorded {
			var v any
			if err := json.Unmarshal(rec, &v); err != nil {
				t.Fatalf("snapshot %s: %v", row.ID, err)
			}
			want = canonicalVerdict(t, v)
		}
		if update || got == want {
			continue
		}
		bad++
		badBy[class]++
		if badBy[class] <= 2 {
			what := "PyYAML"
			if isRecorded {
				what = "the snapshot"
			}
			t.Errorf("row %d %s [%s]: parseConfig = %s, %s = %s (PyYAML %s)\n%q",
				i, row.ID, class, got, what, want, pyVerdict, row.Doc)
		}
	}
	if update {
		snap.Readers[goVerdictsReader] = differ
		writeGoVerdicts(t, snap)
		t.Logf("UPDATE_GO_VERDICTS: wrote %d %q rows to merge_key_go_verdicts.json", len(differ), goVerdictsReader)
		return
	}
	for id := range recorded {
		if !seen[id] {
			bad++
			t.Errorf("snapshot row %s (%s) is in no corpus row: regenerate with UPDATE_GO_VERDICTS=1", id, goVerdictsReader)
		}
	}
	classes := make([]string, 0, len(allBy))
	for k := range allBy {
		classes = append(classes, k)
	}
	sort.Strings(classes)
	var b strings.Builder
	for _, k := range classes {
		fmt.Fprintf(&b, "\n  %-46s %3d of %3d differ from PyYAML and the snapshot (%d refused)",
			k, badBy[k], allBy[k], refusedBy[k])
	}
	t.Logf("per class:%s", b.String())
	if bad > 0 {
		t.Errorf("%d of %d rows: parseConfig differs from merge_key_go_verdicts.json (absent = PyYAML's verdict);"+
			" if the change is intended, regenerate with UPDATE_GO_VERDICTS=1 and run"+
			" tests/shared/test_reader_divergence_catalog.py", bad, len(c.Rows))
	}
	// Refusing every file would pass the loop above: count the rows that
	// enforce something and that parseConfig read, and read the same.
	if matched < 80 {
		t.Errorf("only %d of %d rows enforce a policy parseConfig reads the same — near-vacuous", matched, len(c.Rows))
	}
	t.Logf("%d rows compared, %d refused by parseConfig, %d enforcing rows read the same, %d read differently (recorded)",
		len(c.Rows), refused, matched, len(differ))
}
