package policy

// merge_key_corpus_test.go — tenant-api's half of
// tests/shared/merge_key_policy_corpus.json (#2677): `_domain_policy.yaml`
// documents built around YAML merge keys, each with what the route
// generator's reader (PyYAML) makes of it, generated by
// tests/shared/test_merge_key_policy_corpus.py. parseConfig must read the
// same policies or refuse the file: never a policy PyYAML does not read, and
// never miss one it does. da-guard's half is
// components/threshold-exporter/app/pkg/routingpolicy/merge_key_corpus_test.go.

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"testing"
)

type corpusPolicy struct {
	Tenants   []string `json:"tenants"`
	Forbidden []string `json:"forbidden"`
}

func TestMergeKeyCorpus_ParseConfigIsPyYAMLsOrRefuses(t *testing.T) {
	t.Parallel()
	_, thisFile, _, _ := runtime.Caller(0)
	raw, err := os.ReadFile(filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..",
		"tests", "shared", "merge_key_policy_corpus.json"))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var c struct {
		Comment []string `json:"_comment"`
		PyYAML  string   `json:"pyyaml"`
		Rows    []struct {
			Doc     string          `json:"doc"`
			PyYAML  json.RawMessage `json:"pyyaml"`
			GoBlind string          `json:"go_blind"`
		} `json:"rows"`
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&c); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	if len(c.Rows) < 400 {
		t.Fatalf("corpus has %d rows — a near-empty corpus proves nothing", len(c.Rows))
	}
	compared, refused, bad, matched := 0, 0, 0, 0
	for i, row := range c.Rows {
		if row.GoBlind != "" {
			continue
		}
		compared++
		cfg, err := parseConfig([]byte(row.Doc))
		if err != nil {
			refused++
			continue // refusing is always allowed: the watcher keeps the last good file
		}
		if string(row.PyYAML) == `"unusable"` {
			bad++
			if bad <= 5 {
				t.Errorf("row %d: parseConfig reads %d domains, PyYAML drops the file\n%s", i, len(cfg.DomainPolicies), row.Doc)
			}
			continue
		}
		var want map[string]corpusPolicy
		if err := json.Unmarshal(row.PyYAML, &want); err != nil {
			t.Fatalf("row %d: verdict %s: %v", i, row.PyYAML, err)
		}
		got := map[string]corpusPolicy{}
		for name, p := range cfg.DomainPolicies {
			if len(p.Constraints.ForbiddenReceiverTypes) == 0 {
				continue
			}
			f := append([]string{}, p.Constraints.ForbiddenReceiverTypes...)
			sort.Strings(f)
			got[name] = corpusPolicy{Tenants: append([]string{}, p.Tenants...), Forbidden: f}
		}
		if !reflect.DeepEqual(got, want) {
			bad++
			if bad <= 5 {
				t.Errorf("row %d: parseConfig = %+v, PyYAML = %+v\n%s", i, got, want, row.Doc)
			}
		} else if len(want) > 0 {
			matched++
		}
	}
	if bad > 0 {
		t.Errorf("%d of %d rows: parseConfig reads a policy PyYAML does not", bad, compared)
	}
	// Refusing every file would pass the loop above: count the rows that
	// enforce something and that parseConfig read, and read the same.
	if matched < 80 {
		t.Errorf("only %d of %d rows enforce a policy parseConfig reads the same — near-vacuous", matched, compared)
	}
	t.Logf("%d rows compared, %d refused by parseConfig, %d enforcing rows read the same", compared, refused, matched)
}
