package policy

// merge_key_corpus_test.go — tenant-api's half of
// tests/shared/merge_key_policy_corpus.json (#2677): `_domain_policy.yaml`
// documents built around YAML merge keys, each with what the route
// generator's reader (PyYAML) makes of it, generated by
// tests/shared/test_merge_key_policy_corpus.py, then the deterministic
// `shape` rows of hub #2486 (PR-7c/7d). parseConfig must read the same
// policies or refuse the file: never a policy PyYAML does not read, and
// never miss one it does — for every row, a `nonspecific_tag` row included. da-guard's half is
// components/threshold-exporter/app/pkg/routingpolicy/merge_key_corpus_test.go.

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"
	"unicode/utf16"
)

type corpusPolicy struct {
	Tenants   []string `json:"tenants"`
	Forbidden []string `json:"forbidden"`
	// Allowed is set when allowed_receiver_types is a non-empty list: the
	// types it allows (none, for a list of only non-string entries — it
	// still restricts every type).
	Allowed    *[]string `json:"allowed"`
	Escalation bool      `json:"escalation"`
}

// String prints Allowed's list, not its address, in a failure message.
func (p corpusPolicy) String() string {
	allowed := "-"
	if p.Allowed != nil {
		allowed = fmt.Sprint(*p.Allowed)
	}
	return fmt.Sprintf("{tenants %v forbidden %v allowed %s escalation %v}", p.Tenants, p.Forbidden, allowed, p.Escalation)
}

type corpusRow struct {
	Doc         string          `json:"doc"`
	PyYAML      json.RawMessage `json:"pyyaml"`
	Nonspecific string          `json:"nonspecific_tag"`
	Shape       string          `json:"shape"`
	Encoding    string          `json:"encoding"`
	// Known is "stricter" for a row a Go reader may refuse although PyYAML
	// reads it (#2759). parseConfig may refuse any row; a known row is held
	// to the rest like any other: never a policy PyYAML drops, the same
	// values when both read.
	Known string `json:"known"`
}

// corpusBytes is the file a row stands for: its doc as UTF-8, or, for an
// `encoding` row, written in that encoding (the byte order mark, then
// UTF-16; Latin-1) — a file the generator, UTF-8 only, cannot read.
func corpusBytes(t *testing.T, doc, encoding string) []byte {
	t.Helper()
	switch encoding {
	case "":
		return []byte(doc)
	case "utf-16-le-bom", "utf-16-be-bom":
		var order binary.ByteOrder = binary.LittleEndian
		if encoding == "utf-16-be-bom" {
			order = binary.BigEndian
		}
		units := append([]uint16{0xFEFF}, utf16.Encode([]rune(doc))...)
		out := make([]byte, 2*len(units))
		for i, u := range units {
			order.PutUint16(out[2*i:], u)
		}
		return out
	case "latin-1":
		out := make([]byte, 0, len(doc))
		for _, r := range doc {
			if r > 0xFF {
				t.Fatalf("corpus row: %q is not Latin-1", r)
			}
			out = append(out, byte(r))
		}
		return out
	}
	t.Fatalf("corpus row: unknown encoding %q", encoding)
	return nil
}

// corpusClass names a row's kind for the per-kind tally: its `shape`, or
// "seeded", with "/nonspecific" when it carries the non-specific tag `!` on a
// quoted scalar (read through the vendored yaml.v3 patch, #2730 §6).
func corpusClass(row corpusRow) string {
	c := row.Shape
	if c == "" {
		c = "seeded"
	}
	if row.Nonspecific != "" {
		c += "/nonspecific"
	}
	return c
}

func TestMergeKeyCorpus_ParseConfigIsPyYAMLsOrRefuses(t *testing.T) {
	t.Parallel()
	_, thisFile, _, _ := runtime.Caller(0)
	raw, err := os.ReadFile(filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..",
		"tests", "shared", "merge_key_policy_corpus.json"))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var c struct {
		Comment []string    `json:"_comment"`
		PyYAML  string      `json:"pyyaml"`
		Rows    []corpusRow `json:"rows"`
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&c); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	if len(c.Rows) < 400 {
		t.Fatalf("corpus has %d rows — a near-empty corpus proves nothing", len(c.Rows))
	}
	// No row is skipped (hub #2486 Q7-2): a `nonspecific_tag` row — the
	// non-specific tag `!` the vendored yaml.v3 keeps — must be read as PyYAML reads it, or refused.
	compared, refused, bad, matched := 0, 0, 0, 0
	badBy, refusedBy, allBy := map[string]int{}, map[string]int{}, map[string]int{}
	for i, row := range c.Rows {
		compared++
		class := corpusClass(row)
		allBy[class]++
		if row.Known != "" && row.Known != "stricter" {
			t.Fatalf("row %d: unknown `known` %q", i, row.Known)
		}
		start := time.Now()
		cfg, err := parseConfig(corpusBytes(t, row.Doc, row.Encoding))
		if strings.HasPrefix(row.Shape, "merge-chain-") || strings.HasPrefix(row.Shape, "2715-") {
			t.Logf("row %d (%s, %d bytes): parseConfig took %v, err = %v",
				i, row.Shape, len(row.Doc), time.Since(start), err)
		}
		if err != nil {
			refused++
			refusedBy[class]++
			continue // refusing is always allowed: the watcher keeps the last good file
		}
		if string(row.PyYAML) == `"unusable"` {
			bad++
			badBy[class]++
			if badBy[class] <= 2 {
				t.Errorf("row %d [%s]: parseConfig reads %d domains, PyYAML drops the file\n%q",
					i, class, len(cfg.DomainPolicies), row.Doc)
			}
			continue
		}
		var want map[string]corpusPolicy
		if err := json.Unmarshal(row.PyYAML, &want); err != nil {
			t.Fatalf("row %d: verdict %s: %v", i, row.PyYAML, err)
		}
		got := map[string]corpusPolicy{}
		for name, p := range cfg.DomainPolicies {
			allowed := p.Constraints.AllowedReceiverTypes
			if len(p.Constraints.ForbiddenReceiverTypes) == 0 && len(allowed) == 0 {
				continue
			}
			f := append([]string{}, p.Constraints.ForbiddenReceiverTypes...)
			sort.Strings(f)
			// The escalation as RoutingPolicies enforces it: a boolean true.
			cp := corpusPolicy{Tenants: append([]string{}, p.Tenants...), Forbidden: f,
				Escalation: p.Constraints.RequireCriticalEscalation.Value == true}
			if len(allowed) > 0 {
				// A non-string entry (NotAReceiverType) allows no type: the
				// corpus lists the string entries only.
				a := []string{}
				for _, s := range allowed {
					if s != NotAReceiverType {
						a = append(a, s)
					}
				}
				sort.Strings(a)
				cp.Allowed = &a
			}
			got[name] = cp
		}
		if !reflect.DeepEqual(got, want) {
			bad++
			badBy[class]++
			if badBy[class] <= 2 {
				t.Errorf("row %d [%s]: parseConfig = %+v, PyYAML = %+v\n%q", i, class, got, want, row.Doc)
			}
		} else if len(want) > 0 {
			matched++
		}
	}
	classes := make([]string, 0, len(allBy))
	for k := range allBy {
		classes = append(classes, k)
	}
	sort.Strings(classes)
	var b strings.Builder
	for _, k := range classes {
		fmt.Fprintf(&b, "\n  %-46s %3d of %3d read a policy PyYAML does not (%d refused)",
			k, badBy[k], allBy[k], refusedBy[k])
	}
	t.Logf("per class:%s", b.String())
	if bad > 0 {
		t.Errorf("%d of %d rows: parseConfig reads a policy PyYAML does not", bad, compared)
	}
	// Refusing every file would pass the loop above: count the rows that
	// enforce something and that parseConfig read, and read the same.
	if matched < 80 {
		t.Errorf("only %d of %d rows enforce a policy parseConfig reads the same — near-vacuous", matched, compared)
	}
	t.Logf("%d rows compared, %d refused by parseConfig, %d enforcing rows read the same", compared, refused, matched)
}
