apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-api
  namespace: tenant-api
  labels:
    app: tenant-api
    app.kubernetes.io/part-of: dynamic-alerting
automountServiceAccountToken: false
