#!/usr/bin/env python3
"""check_changelog_no_tbd.py — Detect TBD/TODO placeholders in CHANGELOG (Self-review Gap A.c).

Why this exists
---------------
CHANGELOG entries shipped with placeholder text three sessions in a row
(PR #168 / PR #171 / PR #172, S#79-S#82) — the same `[TBD]` /
`<!-- TODO -->` / `commit (TBD)` shape leaked through self-review and
the v2.8.0 LL §5 case (i) explicitly flagged this pattern as worth
lint-ifying.

Read-time docs (testing-playbook §5/§6) and decision-time UI (PR
template Pre-merge Self-Review section) shipped first; this lint is
the action-completion-time gate for one specific failure mode:
"committed CHANGELOG with placeholder text".

What it flags
-------------
On any non-fenced, non-comment-suppressed line in ``CHANGELOG.md`` /
``CHANGELOG-archive.md``:

- Bare ``TBD`` (word boundary, all-caps, not part of identifier).
- Bracketed forms: ``[TBD]`` / ``(TBD)``.
- HTML / Markdown placeholder comments: ``<!-- TODO -->`` /
  ``<!-- TBD -->`` / ``<!-- FIXME -->`` / ``<!-- XXX -->``.

Allowed (deliberately NOT flagged):
- Lower-case ``tbd`` (often part of prose, e.g. "to be determined").
- ``TBDDDDDDD`` etc — must be word-boundary exact match.
- Inside fenced code blocks ` ``` ` (illustrative).
- Inside backticks (`` `TBD` ``).
- Lines with the per-line ignore marker.

Severity model
--------------
Auto-stage FATAL on any finding. Audit at scaffold time (2026-05-01)
showed 0 violations — ship strict-from-day-1.

Per-line ignore: ``<!-- changelog-no-tbd: ignore -->`` (3-line
lookback for multi-line rationale).

Generated by ``scripts/tools/dx/scaffold_lint.py`` (text kind).
See https://github.com/vencil/Dynamic-Alerting-Integrations/pull/171
for the scaffold tool's design rationale.
Lint class & scope (lint-policy.md §3)
--------------------------------------
Class **(b)** — negative pattern + false-positive escape (ignore marker).
Default scope: **diff-only** — only ADDED lines in current diff get
emitted as findings. This avoids the collateral-damage scenario where
PR A's already-shipped TBD (in a previous release section) re-flags
on every subsequent CHANGELOG-touching PR.

Per-line ignore + fenced-block context still uses the FULL file content,
so multi-line invariants (3-line lookback, fence boundaries) are preserved.
Override with --full-scan for periodic manual audit.

Bypass (per lint-policy.md §4):
    Add to PR description body:
        bypass-lint: changelog-no-tbd
        reason: <≥30 words explaining why this case is legitimate>
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]

# Helpers from this lint family
sys.path.insert(0, str(Path(__file__).parent))
from _lint_helpers import (  # noqa: E402
    DiffBaseMissingError,
    get_diff_added_lines,
    parse_bypass_tag,
    resolve_diff_base,
)

# Pull `try_utf8_stdout` from the shared compat lib at scripts/tools/.
# Migrated in #489 Phase B (was missing encoding setup → would crash on
# legacy Windows cp950/cp936 consoles when printing emoji to stdout).
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, str(_THIS_DIR))
sys.path.insert(0, os.path.join(str(_THIS_DIR), ".."))
from _lib_compat import try_utf8_stdout  # noqa: E402

_IGNORE_MARKER = "<!-- changelog-no-tbd: ignore -->"
_IGNORE_LOOKBACK_LINES = 3

_DEFAULT_TARGET_FILES = ("CHANGELOG.md", "CHANGELOG-archive.md")

# Bare TBD with word boundary so `TBDDD` or identifiers like `myTBD`
# don't match. Case-sensitive uppercase only. Lookbehind/lookahead
# excludes bracketed forms so they're attributed to BRACKET_RE only
# (avoids double-counting).
_BARE_TBD_RE = re.compile(r"(?<![\[\(])\bTBD\b(?![\]\)])")
# Bracketed forms (TBD)/[TBD] — capture as-is.
_BRACKET_TBD_RE = re.compile(r"[\(\[]TBD[\)\]]")
# HTML comment placeholders.
_HTML_PLACEHOLDER_RE = re.compile(
    r"<!--\s*(TODO|TBD|FIXME|XXX)\s*-->",
    re.IGNORECASE,
)


@dataclass
class ChangelogNoTbdFinding:
    path: Path
    line: int
    col: int
    snippet: str

    def render(self) -> str:
        if self.path.is_absolute():
            try:
                rel = self.path.relative_to(PROJECT_ROOT)
            except ValueError:
                rel = self.path
        else:
            rel = self.path
        return f"{rel}:{self.line}:{self.col} {self.snippet[:120]}"


def _line_has_ignore(source_lines: list[str], line_no: int) -> bool:
    for offset in range(_IGNORE_LOOKBACK_LINES + 1):
        candidate = line_no - offset
        if 1 <= candidate <= len(source_lines):
            if _IGNORE_MARKER in source_lines[candidate - 1]:
                return True
    return False


def _build_fenced_block_set(lines: list[str]) -> set[int]:
    """Return set of 1-based line numbers that are inside ``` fences."""
    fenced: set[int] = set()
    in_fence = False
    for idx, line in enumerate(lines, start=1):
        stripped = line.lstrip()
        if stripped.startswith("```"):
            in_fence = not in_fence
            fenced.add(idx)
            continue
        if in_fence:
            fenced.add(idx)
    return fenced


def _is_within_code_span(line: str, col: int) -> bool:
    """True if column ``col`` (1-based) is inside backticks on this line.

    Counts backticks before the position; odd count means inside.
    """
    pre = line[: col - 1]
    return pre.count("`") % 2 == 1


def _scan_with_re(
    pattern: re.Pattern[str],
    line: str,
    line_no: int,
    path: Path,
    findings: list[ChangelogNoTbdFinding],
) -> None:
    for match in pattern.finditer(line):
        col = match.start() + 1
        if _is_within_code_span(line, col):
            continue
        findings.append(
            ChangelogNoTbdFinding(
                path=path,
                line=line_no,
                col=col,
                snippet=line.strip(),
            )
        )


def scan_source(path: Path, source: str) -> list[ChangelogNoTbdFinding]:
    """Walk a CHANGELOG file and return all findings.

    Skips fenced code blocks + inline backticks + lines suppressed by
    ignore marker (current line or up to 3 lines above).
    """
    findings: list[ChangelogNoTbdFinding] = []
    lines = source.splitlines()
    fenced = _build_fenced_block_set(lines)

    for idx, line in enumerate(lines, start=1):
        if idx in fenced:
            continue
        if _line_has_ignore(lines, idx):
            continue
        _scan_with_re(_BARE_TBD_RE, line, idx, path, findings)
        _scan_with_re(_BRACKET_TBD_RE, line, idx, path, findings)
        _scan_with_re(_HTML_PLACEHOLDER_RE, line, idx, path, findings)

    return findings


def _resolve_target_paths(args: argparse.Namespace) -> list[Path]:
    if args.paths:
        return [
            Path(p) if Path(p).is_absolute() else PROJECT_ROOT / p
            for p in args.paths
        ]
    return [
        PROJECT_ROOT / name
        for name in _DEFAULT_TARGET_FILES
        if (PROJECT_ROOT / name).is_file()
    ]


def filter_to_diff_added(
    findings: list[ChangelogNoTbdFinding], path: Path, base: str
) -> list[ChangelogNoTbdFinding]:
    """Return only findings whose line number was ADDED in current diff vs base.

    Multi-line context (fenced blocks + ignore lookback) is computed on the
    full file before this filter runs, so invariants are preserved; this just
    restricts WHAT we emit.
    """
    try:
        added = {ln for ln, _ in get_diff_added_lines(path, base)}
    except subprocess.CalledProcessError:
        # Git error — emit all findings (safer than silent suppression)
        return findings
    return [f for f in findings if f.line in added]


def _read_pr_body(pr_body_file: str | None) -> str | None:
    """Read PR body from --pr-body-file or $PR_BODY env var."""
    if pr_body_file:
        try:
            return Path(pr_body_file).read_text(encoding="utf-8")
        except (FileNotFoundError, PermissionError) as e:
            print(f"WARN: cannot read --pr-body-file {pr_body_file}: {e}", file=sys.stderr)
    return os.environ.get("PR_BODY") or None


def _compute_exit_code(*, ci: bool, n_findings: int) -> int:
    """Pure helper for severity routing.

    | --ci  | n_findings | exit |
    |-------|------------|------|
    | False | *          | 0    |
    | True  | 0          | 0    |
    | True  | >0         | 1    |
    """
    if not ci:
        return 0
    return 1 if n_findings > 0 else 0


def main(argv: list[str] | None = None) -> int:
    try_utf8_stdout()
    parser = argparse.ArgumentParser(
        description="Detect TBD/TODO placeholders in CHANGELOG (Self-review Gap A.c)",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        help="Files or directories to scan. Defaults to CHANGELOG.md + CHANGELOG-archive.md.",
    )
    parser.add_argument(
        "--ci",
        action="store_true",
        help="Exit 1 on findings (default: report only).",
    )
    parser.add_argument(
        "--full-scan",
        action="store_true",
        help="Emit findings on ALL existing TBD/TODO (default: diff-only — only added lines).",
    )
    parser.add_argument(
        "--diff-base",
        default=None,
        help="Override diff base (default: $LINT_DIFF_BASE / $GITHUB_BASE_REF / origin/main).",
    )
    parser.add_argument(
        "--pr-body-file",
        default=None,
        help="Path to file containing PR body for bypass tag check.",
    )
    args = parser.parse_args(argv)

    paths = _resolve_target_paths(args)
    if not paths:
        if args.ci:
            print("✓ no files matched scan target")
        return 0

    # Resolve scan mode
    scan_mode = "full-scan"
    base = None
    if not args.full_scan:
        try:
            base = args.diff_base or resolve_diff_base()
        except DiffBaseMissingError as e:
            print(f"ERROR: {e}", file=sys.stderr)
            return 2
        scan_mode = f"diff vs {base}"

    all_findings: list[ChangelogNoTbdFinding] = []
    for path in paths:
        try:
            source = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            print(f"⚠ cannot read {path}: {exc}", file=sys.stderr)
            continue
        # Always scan full source for context (fenced blocks + ignore lookback)
        file_findings = scan_source(path, source)
        if not args.full_scan:
            file_findings = filter_to_diff_added(file_findings, path, base)
        all_findings.extend(file_findings)

    if not all_findings:
        if args.ci:
            print(f"✓ no findings across {len(paths)} file(s) (mode={scan_mode})")
        return 0

    # Bypass check (lint-policy.md §4)
    pr_body = _read_pr_body(args.pr_body_file)
    bypass_reason = parse_bypass_tag(pr_body, "changelog-no-tbd")

    print(
        f"✗ {len(all_findings)} placeholder(s) in "
        f"{len({f.path for f in all_findings})} file(s) (mode={scan_mode}):",
        file=sys.stderr,
    )
    for f in all_findings:
        print(f"  {f.render()}", file=sys.stderr)

    if bypass_reason:
        print(
            f"\n⚠️  BYPASSED via PR body: {bypass_reason}\n"
            f"   {len(all_findings)} finding(s) above are author-acknowledged.\n"
            f"   Reviewer must confirm bypass is justified.",
            file=sys.stderr,
        )
        return 0

    print(
        "\nFix: replace placeholder with the real value (PR # / commit "
        f"hash / final wording), OR add `{_IGNORE_MARKER}` if intentional.\n"
        "Or add to PR description (per lint-policy.md §4):\n"
        "  bypass-lint: changelog-no-tbd\n"
        "  reason: <≥30 words explaining why this is legitimate>",
        file=sys.stderr,
    )

    return _compute_exit_code(ci=args.ci, n_findings=len(all_findings))


if __name__ == "__main__":
    raise SystemExit(main())
