#!/usr/bin/env python3
"""check_hardcode_tenant.py — Detect hardcoded tenant literals in PromQL label selectors (Rule #2).

Why this exists
---------------
dev-rules.md Rule #2 ("Tenant-Agnostic") forbids baking tenant ids into
production code, PromQL label selectors, or rule-pack expressions —
all tenants must come from config / fixture injection.

Until S#83 the rule was a reviewer convention. The audit in PR #169
(check_dev_rules_enforcement.py) flagged Rule #2 as a "reviewer
convention" candidate for code-driven enforcement. This lint is the
narrow code-driven layer for the most common sin: PromQL `tenant=` /
`tenant_id=` label selectors with a literal value baked in production
files.

What it flags
-------------
A literal PromQL-style label match where the label key is one of
``tenant`` / ``tenant_id`` / ``tenantId`` and the value is a quoted
non-template literal. Examples (FATAL): hard-coded `tenant=` or
`tenant_id=` exact-match selectors with literal values like `db-a` /
`prod-a`. Examples (OK): template substitution variables (``$var``,
``{{var}}``, ``<TENANT>``, ``{var}``); regex / negation operators
(``=~`` / ``!=`` / ``!~``); empty-value placeholders (``tenant=""``).

See ``tests/lint/test_check_hardcode_tenant.py::TestDetection`` for
the executable contract.

Scope (files): ``components/``, ``cmd/``, ``internal/``, ``pkg/``,
``scripts/``, ``rule-packs/``, ``helm/templates/`` — production code
paths only. Tests and fixtures are excluded by the pre-commit
``files:`` pattern (no ``_test.go`` / ``testdata/`` / ``tests/`` /
``examples/``).

Severity model
--------------
Auto-stage FATAL on any finding. Codebase audit at scaffold time
(2026-05-01) showed 0 violations after file-path scope, so we ship
strict-from-day-1 (per PR #169 / PR #170 pattern). If a legitimate
case appears, suppress with the per-line ignore marker.

Per-line ignore: ``<!-- hardcode-tenant: ignore -->`` on the offending
line OR up to 3 lines above (multi-line rationale comments).

Generated by ``scripts/tools/dx/scaffold_lint.py`` (text kind).
See https://github.com/vencil/Dynamic-Alerting-Integrations/pull/171
for the scaffold tool's design rationale.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]

_IGNORE_MARKER = "<!-- hardcode-tenant: ignore -->"
_IGNORE_LOOKBACK_LINES = 3

# Default scan roots (production code only — tests / fixtures excluded
# at pre-commit `files:` regex layer; this list is for `--ci` runs
# without explicit paths).
_DEFAULT_SCAN_ROOTS = (
    "components",
    "cmd",
    "internal",
    "pkg",
    "scripts",
    "rule-packs",
)
_DEFAULT_SCAN_EXTS = (".go", ".py", ".yaml", ".yml", ".tpl")
# Path segments (matched as POSIX directory names) that mark a file as
# test / fixture / example and should be skipped even under default
# scan. Aligned with the Rule #2 statement "Go / PromQL / fixture 禁止
# hardcode tenant id" — `fixture` here means production-default
# fallback, not test fixtures.
_PATH_SKIP_DIR_SEGMENTS = frozenset(
    {"tests", "testdata", "examples", "fixtures"}
)
_PATH_SKIP_FILE_PREFIXES = ("test_",)
_PATH_SKIP_FILE_INFIXES = ("_test.",)


@dataclass
class HardcodeTenantFinding:
    path: Path
    line: int
    col: int
    snippet: str

    def render(self) -> str:
        if self.path.is_absolute():
            try:
                rel = self.path.relative_to(PROJECT_ROOT)
            except ValueError:
                rel = self.path
        else:
            rel = self.path
        return f"{rel}:{self.line}:{self.col} {self.snippet[:120]}"


def _line_has_ignore(source_lines: list[str], line_no: int) -> bool:
    for offset in range(_IGNORE_LOOKBACK_LINES + 1):
        candidate = line_no - offset
        if 1 <= candidate <= len(source_lines):
            if _IGNORE_MARKER in source_lines[candidate - 1]:
                return True
    return False


# Match a PromQL label selector for tenant key with a quoted literal
# value. Captures the value so we can filter out template variables.
#
# - Label key: `tenant` / `tenant_id` / `tenantId` (case-insensitive)
# - Operator: only `=` (exact equality); `=~` regex / `!=` / `!~` are
#   common for "any tenant" patterns and not in scope.
# - Quote: double or single (Go raw strings, YAML, Python all use
#   double; PromQL also accepts single).
# - Value: anything not a quote.
#
# The label key must be preceded by `{` or `,` (label-list context) to
# avoid false matching `// tenant="db-a"` style natural-language prose
# in comments outside braces.
_PROMQL_TENANT_RE = re.compile(
    r'[{,]\s*(tenant_id|tenantId|tenant)\s*=\s*(["\'])([^"\']*)\2',
    re.IGNORECASE,
)

# A value is a "template variable" (legit) if it starts with `$`, is
# wrapped in `{{ }}` (mustache / Helm), looks like an env var
# `${...}`, contains a Python-format placeholder `{name}` that spans
# the whole value, or is empty / surrounded by `<>` / `__` markers.
_TEMPLATE_VALUE_RE = re.compile(
    r"^(\$|\{)",
)


def _is_template_value(value: str) -> bool:
    """True if the captured tenant value is a template variable."""
    if not value:
        return True
    if _TEMPLATE_VALUE_RE.match(value):
        return True
    if value.startswith("<") and value.endswith(">"):
        return True
    if value.startswith("__") and value.endswith("__"):
        return True
    return False


# Lines whose first non-whitespace token marks the line as a comment.
# Captures Go/JS `//`, Python/YAML/shell `#`, Java-doc / C-block ` *`.
# Hash inside a string literal would be a false-skip, but the only
# in-scope file-types that use `#` for non-comments are YAML keys —
# YAML keys never contain `tenant=` patterns, so this is safe.
_COMMENT_LINE_RE = re.compile(r"^\s*(//|#|\*\s)")


def scan_source(path: Path, source: str) -> list[HardcodeTenantFinding]:
    """Walk a text file and return all findings.

    Skips lines with the ignore marker (or marker within 3 lines above).
    Does NOT skip fenced code blocks because PromQL examples in
    ``components/*/README.md`` are NOT in scope (READMEs aren't matched
    by the pre-commit `files:` pattern), and Go/Python files don't have
    fences. The fence helper is omitted for narrowness.
    """
    findings: list[HardcodeTenantFinding] = []
    lines = source.splitlines()

    for idx, line in enumerate(lines, start=1):
        if _line_has_ignore(lines, idx):
            continue
        if _COMMENT_LINE_RE.match(line):
            continue
        for match in _PROMQL_TENANT_RE.finditer(line):
            value = match.group(3)
            if _is_template_value(value):
                continue
            findings.append(
                HardcodeTenantFinding(
                    path=path,
                    line=idx,
                    col=match.start() + 1,
                    snippet=line.strip(),
                )
            )

    return findings


def _is_excluded_path(path: Path) -> bool:
    """True if the path looks like a test / fixture / example file.

    Match by directory segment (so ``examples/foo.py`` and
    ``components/foo/examples/bar.py`` both count) plus filename
    prefix / infix patterns.
    """
    parts = path.parts
    if any(seg in _PATH_SKIP_DIR_SEGMENTS for seg in parts):
        return True
    name = path.name
    if any(name.startswith(p) for p in _PATH_SKIP_FILE_PREFIXES):
        return True
    if any(infix in name for infix in _PATH_SKIP_FILE_INFIXES):
        return True
    return False


def _resolve_target_paths(args: argparse.Namespace) -> list[Path]:
    """Resolve --paths args or fall back to default scan."""
    if args.paths:
        out: list[Path] = []
        for p in args.paths:
            candidate = Path(p) if Path(p).is_absolute() else PROJECT_ROOT / p
            if candidate.is_file():
                out.append(candidate)
            elif candidate.is_dir():
                for ext in _DEFAULT_SCAN_EXTS:
                    out.extend(candidate.rglob(f"*{ext}"))
        return [p for p in out if not _is_excluded_path(p)]

    out = []
    for root in _DEFAULT_SCAN_ROOTS:
        root_path = PROJECT_ROOT / root
        if not root_path.is_dir():
            continue
        for ext in _DEFAULT_SCAN_EXTS:
            out.extend(root_path.rglob(f"*{ext}"))
    return sorted(p for p in out if not _is_excluded_path(p))


def _compute_exit_code(*, ci: bool, n_findings: int) -> int:
    """Pure helper for severity routing.

    | --ci  | n_findings | exit |
    |-------|------------|------|
    | False | *          | 0    |
    | True  | 0          | 0    |
    | True  | >0         | 1    |
    """
    if not ci:
        return 0
    return 1 if n_findings > 0 else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Detect hardcoded tenant literals in PromQL label selectors (Rule #2)",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        help="Files or directories to scan. Defaults to production code roots.",
    )
    parser.add_argument(
        "--ci",
        action="store_true",
        help="Exit 1 on findings (default: report only).",
    )
    args = parser.parse_args(argv)

    paths = _resolve_target_paths(args)
    if not paths:
        if args.ci:
            print("✓ no files matched scan target")
        return 0

    all_findings: list[HardcodeTenantFinding] = []
    for path in paths:
        try:
            source = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            print(f"⚠ cannot read {path}: {exc}", file=sys.stderr)
            continue
        all_findings.extend(scan_source(path, source))

    if not all_findings:
        if args.ci:
            print(f"✓ no findings across {len(paths)} file(s)")
        return 0

    print(
        f"✗ {len(all_findings)} finding(s) in "
        f"{len({f.path for f in all_findings})} file(s):",
        file=sys.stderr,
    )
    for f in all_findings:
        print(f"  {f.render()}", file=sys.stderr)
    print(
        "\nFix: lift the literal into config / fixture injection, OR add "
        f"`{_IGNORE_MARKER}` on the line if illustrative.",
        file=sys.stderr,
    )

    return _compute_exit_code(ci=args.ci, n_findings=len(all_findings))


if __name__ == "__main__":
    raise SystemExit(main())
