#!/usr/bin/env python3
"""check_jsx_loader_compat.py — Detect JSX-loader-incompatible module syntax (named exports / non-allowlist imports / require() calls).

Why this exists (origin: legacy Babel-standalone era)
------------------------------------------------------
S#92 PR #182 first CI E2E run failed: `routing-trace.jsx` had
``export function computeTrace(...)`` (named export). In the then-current
jsx-loader Babel-standalone (script-mode, not module-mode) context,
Babel transformed named exports into ``exports.computeTrace = ...``,
which failed at runtime with ``ReferenceError: exports is not defined``
because ``exports`` is not a global in script mode. The React tree
never mounted → all 4 testid lookups in the spec failed → CI failed.

`pre-commit run jsx-babel-check` PARSES JSX successfully (`export
function` is a valid AST node), so the syntactic gate did not catch
this. Local pre-commit doesn't run E2E. Only CI runtime caught it.

This lint shifted catch-time from CI to commit, mechanically.

Status after TD-030z + TRK-242
------------------------------
jsx-loader.html now only loads esbuild ESM dist bundles
(``docs/assets/dist/<tool>.js``); the Babel-standalone path
(``transformImports`` / ``parseDependencies`` / ``loadDependencies``)
was removed (see git history pre-#264), and portal source moved to
``tools/portal/src/`` (TRK-242). Named exports and relative imports
are legal at runtime now — the lint is kept as a commit-time
CONVENTION gate: components export via ``export default``, shared
symbols via a tail ``export { A, B };`` clause (which rule 1's
declarative-form regex deliberately does NOT match), and bare
specifiers stay pinned to the two the build harness handles.

What it flags
-------------
On any `.jsx` file under ``tools/portal/src/interactive/``:

1. **Declarative named exports** — ``^export (function|const|let|var|class) ...``
   (NOT ``export default ...``, NOT the ``export { A, B };`` clause
   form). Convention: keep helpers at module scope, export once at
   file tail.
2. **Non-allowlist bare imports** — ``import ... from '<X>'`` where
   ``<X>`` is a bare specifier other than ``react`` or
   ``lucide-react``. The allowlist is pinned by
   ``tools/portal/build.mjs``: ``react`` is bundled into each dist;
   ``lucide-react`` is virtualized to a ``window.lucideReact`` read
   (TD-030f). Anything else would silently bloat the bundle or fail
   to resolve.
3. **`require(...)` calls** — CommonJS; not part of the ESM build.

Allowed (deliberately NOT flagged):
- ``import React from 'react'`` / ``import { useState } from 'react'``
  / ``import React, { useState } from 'react'``
- ``import { Icon } from 'lucide-react'``
- Relative imports (``./`` / ``../``) — the standard cross-file path;
  esbuild resolves them natively
- ``export default function Component()`` / ``export default
  Component;`` — the component-export convention
- ``export { A, B };`` clause form — the shared-symbol convention
- Module-scope helpers (no ``export`` keyword) — fine; component
  closure can reach them
- Per-line ``<!-- jsx-loader-compat: ignore -->`` (3-line lookback)

Severity model
--------------
Auto-stage FATAL on any finding. Codebase audit at scaffold time
(2026-05-02): 0 violations after S#92 fix. Ship strict-from-day-1.

Cross-refs
----------
- S#92 PR #182 amend commit `6e16a65` — root cause + reproduce
- testing-playbook §v2.8.0 LL §9 — legacy constraints + post-TD-030z 現況
- ``tools/portal/build.mjs`` — bundling + lucide-react virtualization
  (the thing that pins the bare-import allowlist today)
- ``docs/internal/jsx-multi-file-pattern.md`` — multi-file split pattern

Generated by ``scripts/tools/dx/scaffold_lint.py`` (text kind).
See https://github.com/vencil/Dynamic-Alerting-Integrations/pull/171
for the scaffold tool's design rationale.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
import os

# Pull `try_utf8_stdout` from the shared compat lib at scripts/tools/.
# Migrated in #489 Phase B (was missing encoding setup → would crash on
# legacy Windows cp950/cp936 consoles when printing emoji to stdout).
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, str(_THIS_DIR))
sys.path.insert(0, os.path.join(str(_THIS_DIR), ".."))
from _lib_compat import try_utf8_stdout  # noqa: E402
from _lib_exitcodes import EXIT_OK, EXIT_VIOLATION  # noqa: E402

PROJECT_ROOT = Path(__file__).resolve().parents[3]

_IGNORE_MARKER = "<!-- jsx-loader-compat: ignore -->"
_IGNORE_LOOKBACK_LINES = 3

_DEFAULT_SCAN_DIR = PROJECT_ROOT / "tools" / "portal" / "src" / "interactive"  # TRK-242
_DEFAULT_SCAN_EXTS = (".jsx",)

# Allowlist of bare import specifiers the build harness handles:
# `react` is bundled into each dist by build.mjs; `lucide-react` is
# virtualized to a `window.lucideReact` read (build.mjs, TD-030f).
_ALLOWED_IMPORT_SOURCES = frozenset({"react", "lucide-react"})

# Rule 1: named export (not default).
_NAMED_EXPORT_RE = re.compile(
    r"^\s*export\s+(function|const|let|var|class)\b",
)
_EXPORT_DEFAULT_RE = re.compile(r"^\s*export\s+default\b")

# Rule 2: any `import ... from 'X'` line. The capture group is the
# source string. Matches both `import X from 'pkg'` and
# `import { X } from 'pkg'` and `import X, { Y } from 'pkg'`.
_IMPORT_RE = re.compile(
    r"""^\s*import\b[^'"]*from\s*['"]([^'"]+)['"]""",
)

# Rule 3: `require(` call.
_REQUIRE_CALL_RE = re.compile(r"\brequire\s*\(")


@dataclass
class JsxLoaderCompatFinding:
    path: Path
    line: int
    col: int
    rule: str  # "named-export" | "non-allowlist-import" | "require-call"
    snippet: str

    def render(self) -> str:
        if self.path.is_absolute():
            try:
                rel = self.path.relative_to(PROJECT_ROOT)
            except ValueError:
                rel = self.path
        else:
            rel = self.path
        return f"{rel}:{self.line}:{self.col} [{self.rule}] {self.snippet[:120]}"


def _line_has_ignore(source_lines: list[str], line_no: int) -> bool:
    for offset in range(_IGNORE_LOOKBACK_LINES + 1):
        candidate = line_no - offset
        if 1 <= candidate <= len(source_lines):
            if _IGNORE_MARKER in source_lines[candidate - 1]:
                return True
    return False


def _is_comment_line(line: str) -> bool:
    """True if the line is a JS line comment (`// ...`) or block-comment
    body (`* ...`). Approximate — does not handle multi-line strings or
    template literals. Acceptable for this lint's scope (false positives
    suppressible by ignore marker)."""
    stripped = line.lstrip()
    return stripped.startswith("//") or stripped.startswith("*")


def scan_source(path: Path, source: str) -> list[JsxLoaderCompatFinding]:
    """Walk a JSX file and return all findings."""
    findings: list[JsxLoaderCompatFinding] = []
    lines = source.splitlines()

    for idx, line in enumerate(lines, start=1):
        if _line_has_ignore(lines, idx):
            continue
        if _is_comment_line(line):
            continue

        # Rule 1: named export (skip if export default)
        if not _EXPORT_DEFAULT_RE.match(line):
            m = _NAMED_EXPORT_RE.match(line)
            if m:
                findings.append(
                    JsxLoaderCompatFinding(
                        path=path,
                        line=idx,
                        col=m.start() + 1,
                        rule="named-export",
                        snippet=line.strip(),
                    )
                )

        # Rule 2: non-allowlist import
        m = _IMPORT_RE.match(line)
        if m:
            source_name = m.group(1)
            # Relative imports (`./` or `../`) are the standard
            # cross-file path since TD-030z (esbuild resolves them
            # natively); this rule reduces to "no bare specifiers
            # other than the React allowlist".
            is_relative = source_name.startswith("./") or source_name.startswith("../")
            if source_name not in _ALLOWED_IMPORT_SOURCES and not is_relative:
                findings.append(
                    JsxLoaderCompatFinding(
                        path=path,
                        line=idx,
                        col=m.start() + 1,
                        rule="non-allowlist-import",
                        snippet=line.strip(),
                    )
                )

        # Rule 3: require( call
        for rm in _REQUIRE_CALL_RE.finditer(line):
            findings.append(
                JsxLoaderCompatFinding(
                    path=path,
                    line=idx,
                    col=rm.start() + 1,
                    rule="require-call",
                    snippet=line.strip(),
                )
            )

    return findings


def _resolve_target_paths(args: argparse.Namespace) -> list[Path]:
    """Resolve --paths args or fall back to default scan."""
    if args.paths:
        out: list[Path] = []
        for p in args.paths:
            candidate = Path(p) if Path(p).is_absolute() else PROJECT_ROOT / p
            if candidate.is_file():
                out.append(candidate)
            elif candidate.is_dir():
                for ext in _DEFAULT_SCAN_EXTS:
                    out.extend(candidate.rglob(f"*{ext}"))
        return sorted(set(out))
    out: list[Path] = []
    if _DEFAULT_SCAN_DIR.is_dir():
        for ext in _DEFAULT_SCAN_EXTS:
            out.extend(_DEFAULT_SCAN_DIR.rglob(f"*{ext}"))
    return sorted(set(out))


def _compute_exit_code(*, ci: bool, n_findings: int) -> int:
    """Pure helper for severity routing.

    | --ci  | n_findings | exit |
    |-------|------------|------|
    | False | *          | 0    |
    | True  | 0          | 0    |
    | True  | >0         | 1    |
    """
    if not ci:
        return EXIT_OK
    return EXIT_VIOLATION if n_findings > 0 else EXIT_OK


def main(argv: list[str] | None = None) -> int:
    try_utf8_stdout()
    parser = argparse.ArgumentParser(
        description="Detect JSX-loader-incompatible module syntax (named exports / non-allowlist imports / require() calls)",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        help="Files or directories to scan. Defaults to tools/portal/src/interactive/ recursively (jsx).",
    )
    parser.add_argument(
        "--ci",
        action="store_true",
        help="Exit 1 on findings (default: report only).",
    )
    args = parser.parse_args(argv)

    paths = _resolve_target_paths(args)
    if not paths:
        if args.ci:
            print("✓ no files matched scan target")
        return EXIT_OK

    all_findings: list[JsxLoaderCompatFinding] = []
    for path in paths:
        try:
            source = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            print(f"⚠ cannot read {path}: {exc}", file=sys.stderr)
            continue
        all_findings.extend(scan_source(path, source))

    if not all_findings:
        if args.ci:
            print(f"✓ no findings across {len(paths)} file(s)")
        return EXIT_OK

    print(
        f"✗ {len(all_findings)} jsx-loader-compat violation(s) in "
        f"{len({f.path for f in all_findings})} file(s):",
        file=sys.stderr,
    )
    for f in all_findings:
        print(f"  {f.render()}", file=sys.stderr)
    print(
        "\nFix:\n"
        "  - named-export         → keep helper at module scope; export via a tail\n"
        "                           `export { A, B };` clause (or `export default`)\n"
        "  - non-allowlist-import → bare specifiers limited to react / lucide-react;\n"
        "                           cross-file reuse = relative ESM import\n"
        "                           (see jsx-multi-file-pattern.md)\n"
        "  - require-call         → CommonJS; use ESM import\n"
        f"  - intentional?         → add `{_IGNORE_MARKER}` (3-line lookback)",
        file=sys.stderr,
    )

    return _compute_exit_code(ci=args.ci, n_findings=len(all_findings))


if __name__ == "__main__":
    raise SystemExit(main())
