#!/usr/bin/env python3
"""check_undefined_tokens.py — Detect JSX/CSS references to --da-* tokens not defined in design-tokens.css.

Why this exists
---------------
S#85 PR #175 shipped a colour-only version (`--da-color-*` only) and
caught a real pre-existing drift bug (`var(--da-color-text)` instead
of `var(--da-color-fg)` in OverflowBanner.jsx). S#86 generalises to
ALL `--da-*` categories (color / space / font / line / shadow /
radius / transition) since the same drift class applies — silent
CSS fallback (transparent / inherit / browser-default) that's
invisible in code review.

Live audit at S#86 codify time: 0 violations across all 7 categories
(112 token definitions in design-tokens.css; all references resolve).

What it flags
-------------
Any reference of the form `var(--da-<category>-<name>)` in JSX
(`.jsx`), JS (`.js`), or CSS (`.css`) files under `docs/` whose
`<category>-<name>` does not appear as a `--da-<category>-<name>:`
definition in `docs/assets/design-tokens.css` (light or dark `:root`
block).

Examples (FATAL): `var(--da-color-typo)` referenced but not defined,
`var(--da-space-99)` references a non-existent spacing slot,
`var(--da-font-zzz)` references a stale font token name,
arbitrary-value Tailwind `bg-[color:var(--da-color-mybg)]` where
`--da-color-mybg` is missing.

Allowed (NOT flagged):
- `var(--my-other-color)` / `var(--bs-primary)` (3rd-party / non-`--da-`
  namespace — out of scope)
- `var(--da-foo-bar, fallback)` where `--da-foo-bar` IS defined
- Per-line ignore via `# undefined-tokens: ignore` (3-line lookback)

Severity model
--------------
Auto-stage FATAL on findings (live JSX has 0 violations after S#85+S#86
token additions; ship strict-from-day-1 per PR #169 / #173 pattern).

Cross-file source of truth
--------------------------
`docs/assets/design-tokens.css` is the SSOT for `--da-*` definitions.
Both light (default `:root`) and dark (`[data-theme="dark"]`) blocks
contribute names to the known set — if a token is light-only or
dark-only it still counts as defined (one block declaring it satisfies
the lint, the other serves as theme fallback when missing).

Generated by ``scripts/tools/dx/scaffold_lint.py`` (meta kind).
See https://github.com/vencil/Dynamic-Alerting-Integrations/pull/171
for the scaffold tool's design rationale.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]

_IGNORE_MARKER = "# undefined-tokens: ignore"
_IGNORE_LOOKBACK_LINES = 3

_TOKENS_CSS = PROJECT_ROOT / "docs" / "assets" / "design-tokens.css"
_DEFAULT_SCAN_DIR = PROJECT_ROOT / "docs"
_DEFAULT_SCAN_EXTS = (".jsx", ".js", ".css", ".html")

# Match a `var(--da-<full-name>)` reference. The full-name part
# (category-name e.g. `color-fg` / `space-3` / `font-md`) allows
# alphanumeric + dash + underscore; stops at `,` (CSS fallback comma)
# or `)`. Captures the full `--da-` suffix for set-membership check.
_VAR_REF_RE = re.compile(r"var\(\s*--da-([a-zA-Z0-9_-]+)\s*[,\)]")

# Match a `--da-<full-name>:` definition in CSS. Captures full suffix.
_TOKEN_DEF_RE = re.compile(r"--da-([a-zA-Z0-9_-]+)\s*:")


@dataclass
class UndefinedTokensFinding:
    path: Path
    line: int
    col: int
    snippet: str
    token_name: str

    def render(self) -> str:
        if self.path.is_absolute():
            try:
                rel = self.path.relative_to(PROJECT_ROOT)
            except ValueError:
                rel = self.path
        else:
            rel = self.path
        return (
            f"{rel}:{self.line}:{self.col} undefined --da-{self.token_name} | "
            f"{self.snippet[:100]}"
        )


def load_known_tokens(tokens_css: Path) -> set[str]:
    """Return the set of full `<category>-<name>` strings defined as
    `--da-<category>-<name>:` in the given design-tokens.css (light +
    dark blocks combined)."""
    if not tokens_css.is_file():
        return set()
    source = tokens_css.read_text(encoding="utf-8", errors="replace")
    return {m.group(1) for m in _TOKEN_DEF_RE.finditer(source)}


def _line_has_ignore(source_lines: list[str], line_no: int) -> bool:
    for offset in range(_IGNORE_LOOKBACK_LINES + 1):
        candidate = line_no - offset
        if 1 <= candidate <= len(source_lines):
            if _IGNORE_MARKER in source_lines[candidate - 1]:
                return True
    return False


def scan_source(
    path: Path,
    source: str,
    *,
    known_set: set[str] | None = None,
) -> list[UndefinedTokensFinding]:
    """Walk source line-by-line, find `var(--da-<name>)` refs whose
    `<name>` is not in known_set."""
    if known_set is None:
        known_set = set()

    findings: list[UndefinedTokensFinding] = []
    lines = source.splitlines()

    for idx, line in enumerate(lines, start=1):
        if _line_has_ignore(lines, idx):
            continue
        for m in _VAR_REF_RE.finditer(line):
            name = m.group(1)
            if name in known_set:
                continue
            findings.append(
                UndefinedTokensFinding(
                    path=path,
                    line=idx,
                    col=m.start() + 1,
                    snippet=line.strip(),
                    token_name=name,
                )
            )

    return findings


def collect_referenced_tokens(paths: list[Path]) -> set[str]:
    """Walk every path and return the set of `<category>-<name>` strings
    referenced via `var(--da-<full-name>)`. Used by orphan detection
    (S#88) — opposite direction from scan_source: we want the union of
    refs across the codebase, not a per-file finding list.

    Skips files that fail to read (OSError) silently, matching the
    forgiving behaviour of `main()`'s scan loop.
    """
    referenced: set[str] = set()
    for p in paths:
        try:
            source = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for line_idx, line in enumerate(source.splitlines(), start=1):
            if _line_has_ignore(source.splitlines(), line_idx):
                continue
            for m in _VAR_REF_RE.finditer(line):
                referenced.add(m.group(1))
    return referenced


def find_orphan_tokens(
    *, known: set[str], referenced: set[str]
) -> list[str]:
    """Return sorted list of tokens defined but never referenced.

    A token is "orphan" if its `<category>-<name>` appears in known
    (loaded from design-tokens.css) but not in referenced (collected
    from JSX/JS/CSS scan). Sort lexically so output is deterministic.
    """
    return sorted(known - referenced)


def _resolve_target_paths(args: argparse.Namespace) -> list[Path]:
    if args.paths:
        out: list[Path] = []
        for p in args.paths:
            candidate = Path(p) if Path(p).is_absolute() else PROJECT_ROOT / p
            if candidate.is_file():
                out.append(candidate)
            elif candidate.is_dir():
                for ext in _DEFAULT_SCAN_EXTS:
                    out.extend(candidate.rglob(f"*{ext}"))
        return sorted(set(out))
    out = []
    if _DEFAULT_SCAN_DIR.is_dir():
        for ext in _DEFAULT_SCAN_EXTS:
            out.extend(_DEFAULT_SCAN_DIR.rglob(f"*{ext}"))
    return sorted(set(out))


def _compute_exit_code(*, ci: bool, n_findings: int) -> int:
    """Pure helper for severity routing.

    | --ci  | n_findings | exit |
    |-------|------------|------|
    | False | *          | 0    |
    | True  | 0          | 0    |
    | True  | >0         | 1    |
    """
    if not ci:
        return 0
    return 1 if n_findings > 0 else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Detect JSX/CSS references to --da-color-* tokens not defined in design-tokens.css",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        help="Files or directories to scan. Defaults to docs/ recursively (jsx/js/css).",
    )
    parser.add_argument(
        "--ci",
        action="store_true",
        help="Exit 1 on findings (default: report only).",
    )
    parser.add_argument(
        "--tokens-css",
        type=Path,
        default=_TOKENS_CSS,
        help="Path to design-tokens.css (overrides default).",
    )
    parser.add_argument(
        "--report-orphans",
        action="store_true",
        help=(
            "Report tokens defined in design-tokens.css but never "
            "referenced anywhere (warn-only, exit 0 even with findings). "
            "Discovery tool — orphans may be intentional reserve; "
            "removal needs case-by-case review (S#88)."
        ),
    )
    args = parser.parse_args(argv)

    known = load_known_tokens(args.tokens_css)
    if not known:
        print(
            f"⚠ no token definitions found in {args.tokens_css} — every "
            f"reference will appear undefined. Aborting (probable misconfig).",
            file=sys.stderr,
        )
        return 2

    paths = _resolve_target_paths(args)
    # Filter out the tokens-css itself from scanned paths (definitions
    # don't reference, so they wouldn't trigger the var() regex anyway,
    # but be explicit).
    paths = [p for p in paths if p != args.tokens_css]

    # ── Orphan-detection mode (warn-only discovery, S#88) ───────────
    # Collects refs across all scanned paths PLUS design-tokens.css
    # itself (the SOT may self-reference tokens for utility classes;
    # those count as live usage). Reports tokens never referenced.
    if args.report_orphans:
        ref_paths = list(paths)
        if args.tokens_css.is_file():
            ref_paths.append(args.tokens_css)
        referenced = collect_referenced_tokens(ref_paths)
        orphans = find_orphan_tokens(known=known, referenced=referenced)
        if not orphans:
            print(
                f"✓ no orphan tokens across {len(known)} definition(s)",
                file=sys.stderr,
            )
            return 0
        print(
            f"⚠ {len(orphans)} orphan token(s) defined in "
            f"design-tokens.css but never referenced (warn-only):",
            file=sys.stderr,
        )
        for name in orphans:
            print(f"  --da-{name}", file=sys.stderr)
        print(
            "\nReview each: may be intentional reserve (e.g. token "
            "pair half), planned upcoming usage, or genuinely dead. "
            "Removal is a separate user-judgment PR.",
            file=sys.stderr,
        )
        # Always exit 0 in orphan mode — discovery, not enforcement.
        return 0

    if not paths:
        if args.ci:
            print("✓ no files matched scan target")
        return 0

    all_findings: list[UndefinedTokensFinding] = []
    for path in paths:
        try:
            source = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            print(f"⚠ cannot read {path}: {exc}", file=sys.stderr)
            continue
        all_findings.extend(scan_source(path, source, known_set=known))

    if not all_findings:
        if args.ci:
            print(f"✓ no findings across {len(paths)} file(s)")
        return 0

    print(
        f"✗ {len(all_findings)} undefined-token reference(s) in "
        f"{len({f.path for f in all_findings})} file(s):",
        file=sys.stderr,
    )
    for f in all_findings:
        print(f"  {f.render()}", file=sys.stderr)
    # Render tokens-css path defensively (tmp_path fixtures or absolute
    # CLI args may live outside PROJECT_ROOT — same lesson as PR #166
    # amend's BlobViolation.render() crash on tmp_path).
    tokens_css_str: object
    if args.tokens_css.is_absolute():
        try:
            tokens_css_str = args.tokens_css.relative_to(PROJECT_ROOT)
        except ValueError:
            tokens_css_str = args.tokens_css
    else:
        tokens_css_str = args.tokens_css
    print(
        "\nFix: define the missing token in "
        f"{tokens_css_str} (both light + dark blocks), OR rename the "
        f"reference to an existing token, OR add `{_IGNORE_MARKER}` "
        "if intentional.",
        file=sys.stderr,
    )

    return _compute_exit_code(ci=args.ci, n_findings=len(all_findings))


if __name__ == "__main__":
    raise SystemExit(main())
