package profile

// Decisions — PR-4 accept/reject filter primitive for the C-9
// Profile Builder's emission stage.
//
// Why a decisions layer at all
// ----------------------------
// PR-1 / PR-2 / PR-3 ship a deterministic pipeline:
//
//     ParsedRule corpus
//        └→ BuildProposals (cluster engine)
//             └→ ProposalSet
//                  └→ EmitProposals
//                       └→ map[path][]byte (per-proposal artifacts)
//
// Today (without PR-4) `EmitProposals` emits every proposal. That's
// a fine "preview shape of the customer's corpus" mode but it
// doesn't model the human-in-the-loop step ADR-019 §non-goals
// explicitly defers to: a reviewer SHOULD be able to accept some
// clusters and reject others before any conf.d/ commit lands.
//
// PR-4 adds that loop without forcing the caller to invent a UI.
// The accept/reject decision is just a small YAML file — the
// `proposal-decisions.yaml` scaffold the emitter can drop next to
// PROPOSAL.md, edit-in-place by a reviewer, then fed back into a
// second EmitProposals call as a filter:
//
//     # First run: emit scaffold + PROPOSAL.md for review
//     out1, _ := EmitProposals(input)            // Decisions=nil
//     // (... reviewer edits proposal-decisions.yaml
//     //  changing decision: pending → accept|reject ...)
//
//     // Second run: filter emission based on decisions
//     decisions, _ := ParseDecisions(diskBytes)
//     input.Decisions = decisions
//     out2, _ := EmitProposals(input)            // accepted-only
//
// The decisions file is the boring, durable contract. Any future
// CLI ("da-tools profile decide --interactive"), JSX UI, or
// scripted integration writes the SAME file; emission consumes the
// SAME file. No coupling between UI surfaces and the emitter.
//
// Stable proposal identity
// ------------------------
// Decisions reference proposals by Key — a SHA-256 over the cluster
// signature (sorted MemberRuleIDs + SharedExprTemplate). Stable
// across runs as long as the cluster's identity hasn't shifted
// (members added / dropped or expression template changed). When a
// shift happens, EmitProposals emits a warning so the reviewer
// notices "this decision references a cluster that no longer
// exists" — better than silently honouring or silently dropping.

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// DecisionVerdict is the reviewer's call on one proposal.
//
// "accept" / "reject" are the human verdicts. "pending" is the
// scaffold state — emitted by ScaffoldDecisions so the file always
// round-trips cleanly even if the reviewer hasn't touched it yet.
type DecisionVerdict string

const (
	DecisionAccept  DecisionVerdict = "accept"
	DecisionReject  DecisionVerdict = "reject"
	DecisionPending DecisionVerdict = "pending"
)

// UndecidedPolicy controls how EmitProposals treats proposals that
// have no decision at all (no match for their Key in the decisions
// file, or matched with verdict="pending").
type UndecidedPolicy string

const (
	// UndecidedEmit treats undecided proposals as emit-by-default.
	// This is the backward-compatible default — a partially-reviewed
	// decisions file still produces useful output for the parts the
	// reviewer accepted, while leaving pending clusters visible.
	UndecidedEmit UndecidedPolicy = "emit"

	// UndecidedSkip drops undecided proposals from emission. Useful
	// when the reviewer has explicitly worked through every cluster
	// and wants only the accepted set in the output.
	UndecidedSkip UndecidedPolicy = "skip"
)

// ProposalDecision is one reviewer decision row in the decisions
// file. Decision is the only field a reviewer needs to flip;
// Key/MemberRuleIDs/Summary are auto-populated by ScaffoldDecisions
// for human cross-reference + round-trip stability.
type ProposalDecision struct {
	// Key matches ExtractionProposal.Key() — the SHA-256 over the
	// cluster's stable identity fields. EmitProposals filters by
	// this key.
	Key string `yaml:"key" json:"key"`

	// Decision is the reviewer's verdict. Values outside
	// {accept, reject, pending} are tolerated as "pending"
	// (forward-compat for future verdict labels), but EmitProposals
	// emits a warning when it sees an unknown value so typos
	// surface.
	Decision DecisionVerdict `yaml:"decision" json:"decision"`

	// MemberRuleIDs is a copy of the proposal's MemberRuleIDs at
	// scaffold time. Used as a cross-check: when the live cluster's
	// member list differs from the recorded list, EmitProposals
	// warns so the reviewer can re-decide on the new shape.
	MemberRuleIDs []string `yaml:"member_rule_ids,omitempty" json:"member_rule_ids,omitempty"`

	// Summary is a one-line human reminder of what this cluster
	// covers. Generated by ScaffoldDecisions; not used by the
	// filter logic. Round-tripped so external tools can edit the
	// file without losing context.
	Summary string `yaml:"summary,omitempty" json:"summary,omitempty"`

	// Note is a free-form reviewer field. Round-tripped; not used
	// by the filter logic. Useful for "rejected because cluster
	// includes legacy alerts that need their own thresholds" style
	// audit trails.
	Note string `yaml:"note,omitempty" json:"note,omitempty"`
}

// ProposalDecisions is the top-level decisions-file shape — one
// entry per proposal plus the Undecided policy.
type ProposalDecisions struct {
	// UndecidedPolicy applies to proposals present in the live
	// ProposalSet but missing from Proposals (or matched with
	// pending verdict). Empty string is treated as UndecidedEmit
	// (backward-compat default).
	UndecidedPolicy UndecidedPolicy `yaml:"undecided_policy,omitempty" json:"undecided_policy,omitempty"`

	// Proposals lists one decision per cluster. Order matches the
	// originating ProposalSet at scaffold time but isn't used as a
	// lookup key — Key is. Entries with empty Key are tolerated
	// (just ignored) so callers stitching multiple decision files
	// together don't fail on stray YAML noise.
	Proposals []ProposalDecision `yaml:"proposals" json:"proposals"`
}

// Key returns a stable identifier for this proposal usable as the
// reference key in a ProposalDecisions file.
//
// Derivation:
//
//	SHA-256( SharedExprTemplate || \x00 || MemberRuleIDs joined "\x00" )
//
// The two fields together define the cluster's "what it computes"
// and "which rules participate" identity. If either changes — the
// expression normalisation shifts, or members enter/leave the
// cluster — the Key changes, and EmitProposals will treat any old
// decision as referring to a now-missing proposal.
//
// MemberRuleIDs are pre-sorted by BuildProposals (see cluster.go),
// so we don't re-sort here. The returned key is the lowercase hex
// digest (64 chars) — long enough to be globally unique, short
// enough to fit one line in a YAML file.
func (p ExtractionProposal) Key() string {
	h := sha256.New()
	h.Write([]byte(p.SharedExprTemplate))
	h.Write([]byte{0x00})
	for i, id := range p.MemberRuleIDs {
		if i > 0 {
			h.Write([]byte{0x00})
		}
		h.Write([]byte(id))
	}
	return hex.EncodeToString(h.Sum(nil))
}

// ScaffoldDecisions builds a ProposalDecisions from a ProposalSet
// with every decision marked Pending. Useful for emitting a starter
// file alongside PROPOSAL.md so reviewers see the file format up-
// front and edit in place.
//
// The returned ProposalDecisions is order-stable: entries match the
// ProposalSet's iteration order (which BuildProposals already sorts
// by MemberRuleIDs[0]). Reviewers reading the file top-to-bottom
// see the same cluster ordering as PROPOSAL.md generation.
func ScaffoldDecisions(set *ProposalSet) *ProposalDecisions {
	if set == nil {
		return &ProposalDecisions{
			UndecidedPolicy: UndecidedEmit,
			Proposals:       nil,
		}
	}
	out := &ProposalDecisions{
		UndecidedPolicy: UndecidedEmit,
		Proposals:       make([]ProposalDecision, 0, len(set.Proposals)),
	}
	for _, p := range set.Proposals {
		// Defensive copy of MemberRuleIDs so the scaffold output
		// can't be mutated by a caller modifying the proposal slice
		// later.
		members := make([]string, len(p.MemberRuleIDs))
		copy(members, p.MemberRuleIDs)
		out.Proposals = append(out.Proposals, ProposalDecision{
			Key:           p.Key(),
			Decision:      DecisionPending,
			MemberRuleIDs: members,
			Summary:       summariseProposal(p),
		})
	}
	return out
}

// summariseProposal renders a one-line human summary for the
// scaffold's `summary:` field. Mirrors the heading line in
// PROPOSAL.md so reviewers reading the decisions file alongside
// PROPOSAL.md see consistent text.
func summariseProposal(p ExtractionProposal) string {
	tmpl := strings.TrimSpace(p.SharedExprTemplate)
	if len(tmpl) > 80 {
		tmpl = tmpl[:77] + "..."
	}
	return fmt.Sprintf("%d rules; dialect=%s; expr=%s",
		len(p.MemberRuleIDs), p.Dialect, tmpl)
}

// ParseDecisions parses a ProposalDecisions from YAML bytes.
//
// Returns an error only on YAML parse failure. Empty input is
// treated as `&ProposalDecisions{}` rather than an error — a
// caller that just wrote a fresh scaffold then read it back should
// not have to special-case "the file is empty".
func ParseDecisions(b []byte) (*ProposalDecisions, error) {
	if len(bytes.TrimSpace(b)) == 0 {
		return &ProposalDecisions{}, nil
	}
	var d ProposalDecisions
	if err := yaml.Unmarshal(b, &d); err != nil {
		return nil, fmt.Errorf("decisions: parse YAML: %w", err)
	}
	return &d, nil
}

// EncodeDecisions serialises a ProposalDecisions to YAML bytes
// suitable for writing to disk. The output is deterministic given
// the same input (yaml.v3 sorts map keys; we don't insert any
// timestamp / random data).
//
// A small header comment is prepended so reviewers opening the
// file see the "what / how to edit" guidance up-front.
func EncodeDecisions(d *ProposalDecisions) ([]byte, error) {
	if d == nil {
		return nil, fmt.Errorf("decisions: encode nil")
	}
	body, err := yaml.Marshal(d)
	if err != nil {
		return nil, fmt.Errorf("decisions: marshal: %w", err)
	}
	const header = `# C-9 Profile Builder — proposal decisions.
#
# This file is a reviewer artifact: each entry under proposals: is
# one cluster the builder identified. Edit "decision:" to one of
#   accept   — emit this cluster on the next EmitProposals run
#   reject   — skip this cluster
#   pending  — leave the decision for later
#
# undecided_policy controls what happens to proposals with
#   pending verdict (or that don't appear here at all):
#     emit (default) — emit anyway; useful for incremental review
#     skip           — only emit the explicitly-accepted set
#
# Do not edit "key:" or "member_rule_ids:" — they identify the
# cluster the decision attaches to. EmitProposals emits a warning
# if the live cluster's members no longer match the recorded list.

`
	return append([]byte(header), body...), nil
}

// applyDecisions filters a slice of proposals against a
// ProposalDecisions. Returns the indices of proposals that should
// emit, plus per-proposal warnings (mismatched member lists, unknown
// verdict values, etc).
//
// nil decisions = pass-through (emit all indices, no warnings) —
// the backward-compat path for callers that don't yet use the
// decisions feature.
func applyDecisions(props []ExtractionProposal, decisions *ProposalDecisions) (emitIdx []int, warnings []string) {
	if decisions == nil {
		emitIdx = make([]int, len(props))
		for i := range props {
			emitIdx[i] = i
		}
		return emitIdx, nil
	}
	policy := decisions.UndecidedPolicy
	if policy == "" {
		policy = UndecidedEmit
	}

	// Index decisions by key for O(1) lookup. Duplicate keys are
	// surfaced as a warning — silently letting the last entry win
	// would mask a misedit (reviewer copy-pasted a row and only
	// changed the verdict, not the key).
	byKey := make(map[string]ProposalDecision, len(decisions.Proposals))
	dupes := make([]string, 0)
	for _, d := range decisions.Proposals {
		if d.Key == "" {
			continue
		}
		if _, exists := byKey[d.Key]; exists {
			dupes = append(dupes, d.Key)
		}
		byKey[d.Key] = d
	}
	sort.Strings(dupes)
	for _, k := range dupes {
		warnings = append(warnings, fmt.Sprintf(
			"decisions: duplicate key %q in decisions file (last entry wins; check for misedit)", k))
	}

	// Warn on decisions that reference clusters not present in the
	// current ProposalSet (cluster shape shifted between scaffold
	// time and emission time). Detected as decisions whose Key
	// doesn't appear in any current proposal.
	livKeys := make(map[string]struct{}, len(props))
	for _, p := range props {
		livKeys[p.Key()] = struct{}{}
	}
	stale := make([]string, 0)
	for k := range byKey {
		if _, ok := livKeys[k]; !ok {
			stale = append(stale, k)
		}
	}
	sort.Strings(stale)
	for _, k := range stale {
		warnings = append(warnings, fmt.Sprintf(
			"decisions: key %q references a proposal not present in the current ProposalSet (cluster shape may have shifted; verdict=%q ignored)",
			k, byKey[k].Decision))
	}

	for i, p := range props {
		key := p.Key()
		dec, ok := byKey[key]
		if !ok {
			// No decision recorded for this proposal at all.
			if policy == UndecidedSkip {
				warnings = append(warnings, fmt.Sprintf(
					"proposal[%d]: no decision recorded; undecided_policy=skip → emission skipped",
					i))
				continue
			}
			emitIdx = append(emitIdx, i)
			warnings = append(warnings, fmt.Sprintf(
				"proposal[%d]: no decision recorded; undecided_policy=emit → emitted by default",
				i))
			continue
		}

		// Member-list cross-check: warn if recorded != live, but
		// still honour the verdict (the reviewer's intent is to
		// accept/reject the cluster identified by Key; member drift
		// surfaces but doesn't override the verdict).
		if !sameStringSlice(dec.MemberRuleIDs, p.MemberRuleIDs) {
			warnings = append(warnings, fmt.Sprintf(
				"proposal[%d] (key=%s): decision was recorded against %d members; cluster now has %d members — re-review recommended",
				i, key, len(dec.MemberRuleIDs), len(p.MemberRuleIDs)))
		}

		switch dec.Decision {
		case DecisionAccept:
			emitIdx = append(emitIdx, i)
		case DecisionReject:
			// Drop silently — explicit reject doesn't need a
			// warning; the reviewer wanted this.
		case DecisionPending, "":
			if policy == UndecidedSkip {
				warnings = append(warnings, fmt.Sprintf(
					"proposal[%d]: decision=pending; undecided_policy=skip → emission skipped",
					i))
				continue
			}
			emitIdx = append(emitIdx, i)
			warnings = append(warnings, fmt.Sprintf(
				"proposal[%d]: decision=pending; undecided_policy=emit → emitted by default",
				i))
		default:
			// Unknown verdict — treat as pending + warn so typos
			// surface. Keeps the door open for future verdicts
			// without breaking deployed callers.
			warnings = append(warnings, fmt.Sprintf(
				"proposal[%d]: unknown decision verdict %q; treating as pending",
				i, dec.Decision))
			if policy == UndecidedSkip {
				continue
			}
			emitIdx = append(emitIdx, i)
		}
	}
	return emitIdx, warnings
}

// sameStringSlice returns true iff a and b have identical elements
// in identical order. We don't sort first because both
// MemberRuleIDs slices are pre-sorted by BuildProposals — a
// difference in order indicates a real cluster shape change.
func sameStringSlice(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
