{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: threshold-exporter-pdb
  namespace: monitoring
  labels:
    app: threshold-exporter
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: threshold-exporter
{{- end }}
