apiVersion: v1
kind: Service
metadata:
  name: {{ include "recipe-preview.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "recipe-preview.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "recipe-preview.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
