#!/usr/bin/env python3
"""Tests for da_assembler.py — CRD → YAML assembler."""

import os
import tempfile
import unittest
from pathlib import Path

import yaml

from da_assembler import (
    _content_sha256,
    _output_filename,
    remove_rendered,
    render_cr_file,
    render_cr_to_yaml,
    write_rendered,
)


def _make_cr(name="db-a", namespace="db-a", tenants=None):
    """Helper: build a minimal ThresholdConfig CR dict."""
    if tenants is None:
        tenants = {name: {"mysql_connections": "70"}}
    return {
        "apiVersion": "dynamicalerting.io/v1alpha1",
        "kind": "ThresholdConfig",
        "metadata": {"name": name, "namespace": namespace},
        "spec": {"tenants": tenants},
    }


class TestRenderCrToYaml(unittest.TestCase):
    def test_basic_render(self):
        cr = _make_cr()
        result = render_cr_to_yaml(cr)
        self.assertIn("# Auto-generated by da-assembler", result)
        self.assertIn("mysql_connections", result)
        # Should be valid YAML (skip header lines starting with #)
        body = "\n".join(
            ln for ln in result.splitlines() if not ln.startswith("#"))
        parsed = yaml.safe_load(body)
        self.assertIn("tenants", parsed)
        self.assertIn("db-a", parsed["tenants"])

    def test_render_with_defaults(self):
        cr = _make_cr()
        cr["spec"]["defaults"] = {"mysql_connections": 80}
        result = render_cr_to_yaml(cr)
        parsed = yaml.safe_load(
            "\n".join(ln for ln in result.splitlines()
                      if not ln.startswith("#")))
        self.assertIn("defaults", parsed)

    def test_render_with_state_filters(self):
        cr = _make_cr()
        cr["spec"]["stateFilters"] = {
            "crashloop": {"reasons": ["CrashLoopBackOff"]}
        }
        result = render_cr_to_yaml(cr)
        parsed = yaml.safe_load(
            "\n".join(ln for ln in result.splitlines()
                      if not ln.startswith("#")))
        self.assertIn("state_filters", parsed)

    def test_empty_tenants(self):
        cr = _make_cr(tenants={})
        result = render_cr_to_yaml(cr)
        # Should still produce valid output (empty doc or {})
        self.assertIn("Auto-generated", result)


class TestOutputFilename(unittest.TestCase):
    def test_from_name(self):
        cr = _make_cr(name="payment-db")
        self.assertEqual(_output_filename(cr), "payment-db.yaml")

    def test_missing_name(self):
        cr = {"metadata": {}}
        self.assertEqual(_output_filename(cr), "unknown.yaml")


class TestWriteRendered(unittest.TestCase):
    def test_writes_file(self):
        with tempfile.TemporaryDirectory() as d:
            changed = write_rendered(
                Path(d), "test.yaml", "tenants:\n  a: 1\n")
            self.assertTrue(changed)
            self.assertTrue((Path(d) / "test.yaml").exists())

    def test_no_change_skips_write(self):
        with tempfile.TemporaryDirectory() as d:
            content = "tenants:\n  a: 1\n"
            (Path(d) / "test.yaml").write_text(content, encoding="utf-8")
            changed = write_rendered(Path(d), "test.yaml", content)
            self.assertFalse(changed)

    def test_dry_run(self):
        with tempfile.TemporaryDirectory() as d:
            changed = write_rendered(
                Path(d), "test.yaml", "content", dry_run=True)
            self.assertTrue(changed)
            self.assertFalse((Path(d) / "test.yaml").exists())


class TestRemoveRendered(unittest.TestCase):
    def test_removes_existing(self):
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "test.yaml"
            p.write_text("data", encoding="utf-8")
            removed = remove_rendered(Path(d), "test.yaml")
            self.assertTrue(removed)
            self.assertFalse(p.exists())

    def test_nonexistent_noop(self):
        with tempfile.TemporaryDirectory() as d:
            removed = remove_rendered(Path(d), "nonexistent.yaml")
            self.assertFalse(removed)

    def test_dry_run(self):
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "test.yaml"
            p.write_text("data", encoding="utf-8")
            removed = remove_rendered(Path(d), "test.yaml", dry_run=True)
            self.assertTrue(removed)
            self.assertTrue(p.exists())  # not actually deleted


class TestContentSha256(unittest.TestCase):
    def test_deterministic(self):
        self.assertEqual(
            _content_sha256("hello"),
            _content_sha256("hello"))

    def test_different_content(self):
        self.assertNotEqual(
            _content_sha256("hello"),
            _content_sha256("world"))


class TestRenderCrFile(unittest.TestCase):
    def test_offline_render(self):
        cr = _make_cr(name="offline-test")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            rc = render_cr_file(cr_path, out_dir)
            self.assertEqual(rc, 0)
            self.assertTrue((out_dir / "offline-test.yaml").exists())

    def test_invalid_kind(self):
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "bad.yaml"
            cr_path.write_text("kind: NotAThresholdConfig\nspec: {}",
                               encoding="utf-8")
            rc = render_cr_file(cr_path, Path(d))
            self.assertEqual(rc, 2)

    def test_dry_run(self):
        cr = _make_cr(name="dry-test")
        with tempfile.TemporaryDirectory() as d:
            cr_path = Path(d) / "cr.yaml"
            cr_path.write_text(
                yaml.dump(cr, default_flow_style=False), encoding="utf-8")
            out_dir = Path(d) / "out"
            out_dir.mkdir()
            rc = render_cr_file(cr_path, out_dir, dry_run=True)
            self.assertEqual(rc, 0)
            self.assertFalse((out_dir / "dry-test.yaml").exists())


if __name__ == "__main__":
    unittest.main()
