apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenant-api.labels" . | nindent 4 }}
data:
  _rbac.yaml: |
    {{- .Values.rbac._rbacYaml | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tenant-api.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenant-api.labels" . | nindent 4 }}
data:
  GIT_REPO_URL: {{ .Values.gitRepoUrl | quote }}
