apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "da-portal.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "da-portal.labels" . | nindent 4 }}
automountServiceAccountToken: false
