---
title: "Platform Demo — recorded da-tools transcripts"
purpose: |
  The command, terminal playback and sample file for each phase of
  platform-demo.jsx. Data only — titles/descriptions (bilingual) stay in
  the orchestrator.

  Every `command` is a real da-tools invocation and every `terminal` is
  that command's captured stdout/stderr (DA_LANG=en; tools whose run
  output is not localised still print Chinese), mechanically transcribed:
  a `\r`-redrawn progress line keeps only its last frame. `sample` is
  the file the command wrote. One continuous session: scaffold's
  demo-out/_defaults.yaml + demo-tenant.yaml were copied into conf.d/,
  which validate-config and generate-routes read; migrate ran on
  tests/fixtures/legacy-dummy.yml saved as legacy_rules.yaml; baseline
  ran against a local stub Prometheus, so its numbers are synthetic.

  When a CLI flag or message changes, re-run and re-capture — do not
  hand-edit the output. Guard (argv accepted by each tool's own
  argparse): tests/dx/test_platform_demo_commands.py.

  Public API:
    DEMO_TRANSCRIPTS   { [phaseId]: { command, terminal[], sample? } }
---

const DEMO_TRANSCRIPTS = {
  scaffold: {
    command: 'da-tools scaffold --tenant demo-tenant --db mariadb,redis --non-interactive --routing-receiver https://incident.example.com/hook -o demo-out',
    terminal: [
      '$ da-tools scaffold --tenant demo-tenant --db mariadb,redis --non-interactive --routing-receiver https://incident.example.com/hook -o demo-out',
      '',
      '⚙️  生成 demo-tenant config (DBs: kubernetes, mariadb, redis)...',
      '',
      '📁 輸出至 demo-out/',
      '  📄 demo-out/_defaults.yaml',
      '  📄 demo-out/demo-tenant.yaml',
      '  📄 demo-out/scaffold-report.txt',
      '',
      '✅ 完成 (所有核心 Rule Packs (包含自我監控) 已透過 Projected Volume 預載於平台，無需額外掛載)',
    ],
    sample: `# demo-tenant.yaml — Tenant-managed thresholds
# Generated by scaffold_tenant.py
# 三態（限 _defaults.yaml 的 defaults: 有值的 key）: 數值=Custom, 省略=Default, "disable"=停用
# 宣告層（_defaults.yaml 的 optional_overrides: 清單）沒有值可繼承 ⇒ 省略＝沒有值＝靜默，
# 不是「用預設」；那一格只有「填值」與「不填」兩態。本次選的 pack 一個這種 key 都沒有，
# 所以本檔沒有那一段可看（換 pack 時會有）。
# 第三類 <base>_critical：本次一起產出的 _defaults.yaml 的 defaults: 一個都沒有列，
# 平台不供給 critical 值 ⇒ 你在這裡填一個，只要 <base> 在 defaults: 有值，就會
# 產生一條真的 critical 閾值（不填則無此列，base 的 warning 列不受影響）。
tenants:
  demo-tenant:
    _routing:
      receiver:
        type: webhook
        url: https://incident.example.com/hook
      group_by:
      - alertname
      - tenant
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h`,
  },
  migrate: {
    command: 'da-tools migrate legacy_rules.yaml -o migration_output',
    terminal: [
      '$ da-tools migrate legacy_rules.yaml -o migration_output',
      '',
      '[🔗] Auto-Suppression: 1 組 warning↔critical 配對完成',
      '[✓] 成功轉換 3 條規則 (✅ 2 完美, ⚠️ 1 已猜測)',
      '[!] 1 條需人工處理 (LLM Prompt 已寫入報告)',
      '📁 檔案已輸出至 migration_output/',
      '🏷️  前綴: custom_ (Prefix Mapping 已輸出)',
    ],
    sample: `# ============================================================
# Tenant Config — 複製到 conf.d/<tenant>.yaml
# ============================================================
# 請將以下內容縮排並貼入您專屬的 tenant 設定中，例如：
# tenants:
#   my-tenant-name:
#     custom_mysql_global_status_threads_connected: "150"
#     custom_mysql_global_status_slow_queries: "0.5"
#     custom_mysql_global_status_threads_connected_critical: "200"

# --- From: MySQLTooManyConnections (severity: warning) ---
# 📖 Severity Dedup: 已配對 critical (MySQLTooManyConnectionsCritical)，metric_group="connected"。Alertmanager inhibit 預設壓制 warning 通知 (tenant 可設 _severity_dedup: "disable" 取消)
custom_mysql_global_status_threads_connected: "150"

# --- From: MySQLHighSlowQueries (severity: warning) ---
custom_mysql_global_status_slow_queries: "0.5"

# --- From: MySQLTooManyConnectionsCritical (severity: critical) ---
custom_mysql_global_status_threads_connected_critical: "200"`,
  },
  validate: {
    command: 'da-tools validate-config --config-dir conf.d/',
    terminal: [
      '$ da-tools validate-config --config-dir conf.d/',
      '',
      '============================================================',
      '  validate-config — Unified Validation Report',
      '============================================================',
      '',
      '[PASS] yaml_syntax',
      '       2 files parsed successfully',
      '',
      '[PASS] schema',
      '       No schema warnings',
      '',
      '[PASS] routes',
      '       1 routes, 1 receivers, 1 inhibit_rules',
      '',
      '[PASS] profiles',
      '       1 tenants scanned, 0 profile refs, 0 profiles defined',
      '',
      '[PASS] policy_dsl',
      '       No _policies defined — skipped',
      '',
      '[PASS] tenant_uniqueness',
      '       1 tenant(s), each declared in exactly one file',
      '',
      '------------------------------------------------------------',
      '  Total: 6 checks | 6 pass | 0 warn | 0 fail',
      '------------------------------------------------------------',
      '  Result: PASS',
    ],
  },
  routes: {
    command: 'da-tools generate-routes --config-dir conf.d/ -o am-config.yaml',
    terminal: [
      '$ da-tools generate-routes --config-dir conf.d/ -o am-config.yaml',
      '',
      'Config files: 2 read, 0 skipped',
      'Found 1 tenant(s) with routing config: demo-tenant',
      'Found 1 tenant(s) for severity dedup: demo-tenant',
      'Written to am-config.yaml (1 routes, 1 receivers, 1 inhibit rules)',
    ],
    sample: `# ============================================================
# Alertmanager Route + Receiver + Inhibit Rules Fragment
# Generated by: generate_alertmanager_routes.py
# Merge into your Alertmanager config:
#   - route.routes: append the routes below
#   - receivers: append the receivers below
#   - inhibit_rules: append the severity dedup inhibit rules below
# ============================================================
route:
  routes:
  - matchers:
    - tenant="demo-tenant"
    receiver: tenant-demo-tenant
    group_by:
    - alertname
    - tenant
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
receivers:
- name: tenant-demo-tenant
  webhook_configs:
  - url: https://incident.example.com/hook
inhibit_rules:
- source_matchers:
  - severity="critical"
  - metric_group=~".+"
  - tenant="demo-tenant"
  target_matchers:
  - severity="warning"
  - metric_group=~".+"
  - tenant="demo-tenant"
  equal:
  - metric_group`,
  },
  baseline: {
    command: 'da-tools baseline --tenant demo-tenant --prometheus http://localhost:9090 --duration 60 --interval 5',
    terminal: [
      '$ da-tools baseline --tenant demo-tenant --prometheus http://localhost:9090 --duration 60 --interval 5',
      '',
      '',
      '🔍 Baseline Discovery — 開始觀測',
      '   Tenant: demo-tenant',
      '   Prometheus: http://localhost:9090',
      '   Duration: 60s, Interval: 5s',
      '   Expected samples: 12',
      '   Metrics: connections, cpu, slow_queries, memory, disk_io',
      '',
      '',
      '  採樣 1/12 (2026-09-25 10:49:50)',
      '  採樣 2/12 (2026-09-25 10:49:55)',
      '  採樣 3/12 (2026-09-25 10:50:00)',
      '  採樣 4/12 (2026-09-25 10:50:05)',
      '  採樣 5/12 (2026-09-25 10:50:10)',
      '  採樣 6/12 (2026-09-25 10:50:15)',
      '  採樣 7/12 (2026-09-25 10:50:20)',
      '  採樣 8/12 (2026-09-25 10:50:25)',
      '  採樣 9/12 (2026-09-25 10:50:30)',
      '  採樣 10/12 (2026-09-25 10:50:35)',
      '  採樣 11/12 (2026-09-25 10:50:40)',
      '  採樣 12/12 (2026-09-25 10:50:45)',
      '',
      '✅ 觀測完成：共 12 個採樣點',
      '',
      '======================================================================',
      '📊 Baseline Discovery Report — demo-tenant',
      '======================================================================',
      '',
      '■ connections (MariaDB active connections)',
      '  Unit: connections',
      '  Samples: 12',
      '  Range: 25.89 ~ 53.52',
      '  Average: 40.67',
      '  Percentiles: p50=40.03  p90=52.17  p95=52.86  p99=53.39',
      '  💡 建議 warning: 64  critical: 81  (基於 p95×1.2 / p99×1.5)',
      '',
      '■ cpu (Container CPU usage rate)',
      '  Unit: %',
      '  Samples: 12',
      '  Range: 22.81 ~ 45.31',
      '  Average: 34.35',
      '  Percentiles: p50=35.41  p90=40.59  p95=42.86  p99=44.82',
      '  💡 建議 warning: 51.44  critical: 67.23  (基於 p95×1.2 / p99×1.5)',
      '',
      '■ slow_queries (Slow queries per minute)',
      '  Unit: queries/min',
      '  Samples: 12',
      '  Range: 0.35 ~ 1.13',
      '  Average: 0.70',
      '  Percentiles: p50=0.67  p90=1.10  p95=1.12  p99=1.13',
      '  💡 建議 warning: 1.34  critical: 1.69  (基於 p95×1.2 / p99×1.5)',
      '',
      '■ memory (Container memory working set)',
      '  Unit: MiB',
      '  Samples: 12',
      '  Range: 577.52 ~ 640.52',
      '  Average: 607.79',
      '  Percentiles: p50=612.57  p90=637.70  p95=640.19  p99=640.46',
      '  💡 建議 warning: 768.23  critical: 960.69  (基於 p95×1.2 / p99×1.5)',
      '',
      '■ disk_io (Disk read throughput)',
      '  Unit: KiB/s',
      '  Samples: 12',
      '  Range: 147.68 ~ 237.73',
      '  Average: 190.10',
      '  Percentiles: p50=193.99  p90=229.49  p95=234.72  p99=237.13',
      '  💡 建議 warning: 281.66  critical: 355.7  (基於 p95×1.2 / p99×1.5)',
      '',
      '📁 輸出:',
      '  時間序列: baseline_output/baseline-demo-tenant-timeseries.csv',
      '  統計摘要: baseline_output/baseline-demo-tenant-summary.csv',
      '',
      '======================================================================',
      '💡 建議的閾值（下面用 patch-config 的寫法表示，先決條件見下方 ⛔）:',
      '======================================================================',
      '（`da-tools` 的取得方式見 https://vencil.github.io/Dynamic-Alerting-Integrations/migration-toolkit-installation/）',
      '⛔ patch-config 改的是叢集裡的 ConfigMap，需要 kubectl 與叢集存取權，而 da-tools 映像本身不含 kubectl。',
      '   走 GitOps 的話請直接把下面的值寫進你 repo 的 conf.d/<tenant>.yaml，再 commit。',
      '',
      '  # connections: warning=64',
      '  da-tools patch-config demo-tenant mysql_connections 64',
      '  da-tools patch-config demo-tenant mysql_connections_critical 81',
      '',
      '  # cpu: warning=51.44',
      '  da-tools patch-config demo-tenant mysql_cpu 51.44',
      '  da-tools patch-config demo-tenant mysql_cpu_critical 67.23',
      '',
      '  # slow_queries: warning=1.34',
      '  da-tools patch-config demo-tenant mysql_slow_queries 1.34',
      '  da-tools patch-config demo-tenant mysql_slow_queries_critical 1.69',
      '',
      '  # memory: warning=768.23',
      '  da-tools patch-config demo-tenant mysql_memory 768.23',
      '  da-tools patch-config demo-tenant mysql_memory_critical 960.69',
      '',
      '  # disk_io: warning=281.66',
      '  da-tools patch-config demo-tenant mysql_disk_io 281.66',
      '  da-tools patch-config demo-tenant mysql_disk_io_critical 355.7',
    ],
  },
};

export { DEMO_TRANSCRIPTS };
