---
title: "Component Health Dashboard"
tags: [health, dashboard, tier, coverage, tokens, quality]
audience: ["platform-engineer", "contributor"]
version: v2.6.0
lang: en
related: [threshold-heatmap, config-lint]
---

import React, { useState, useMemo } from 'react';

const t = window.__t || ((zh, en) => en);

/* ── Static health snapshot (generated by scan_component_health.py, v2.7.0 Phase .a) ── */
const HEALTH_DATA = [
  { key: 'wizard', title: 'Getting Started Wizard', tier: 'Tier 1', tierScore: 8, tokens: 64, palette: 21, group: 'B', pw: true, i18n: 1.00, loc: 684 },
  { key: 'playground', title: 'Config Playground', tier: 'Tier 1', tierScore: 8, tokens: 94, palette: 0, group: 'A', pw: true, i18n: 0.92, loc: 771 },
  { key: 'cicd-setup-wizard', title: 'CI/CD Setup Wizard', tier: 'Tier 1', tierScore: 8, tokens: 100, palette: 0, group: 'A', pw: true, i18n: 1.00, loc: 588 },
  { key: 'notification-previewer', title: 'Notification Previewer', tier: 'Tier 1', tierScore: 7, tokens: 174, palette: 0, group: 'A', pw: true, i18n: 0.94, loc: 802 },
  { key: 'config-lint', title: 'Config Lint', tier: 'Tier 1', tierScore: 7, tokens: 47, palette: 0, group: 'B', pw: true, i18n: 1.00, loc: 380 },
  { key: 'cost-estimator', title: 'Cost Estimator', tier: 'Tier 1', tierScore: 7, tokens: 117, palette: 0, group: 'A', pw: true, i18n: 1.00, loc: 578 },
  { key: 'tenant-manager', title: 'Tenant Manager', tier: 'Tier 1', tierScore: 8, tokens: 275, palette: 0, group: 'A', pw: true, i18n: 0.96, loc: 1310 },
  { key: 'deployment-wizard', title: 'Deployment Wizard', tier: 'Tier 1', tierScore: 7, tokens: 112, palette: 8, group: 'B', pw: true, i18n: 1.00, loc: 685 },
  { key: 'rbac-setup-wizard', title: 'RBAC Setup Wizard', tier: 'Tier 1', tierScore: 7, tokens: 120, palette: 0, group: 'A', pw: true, i18n: 0.99, loc: 495 },
  { key: 'operator-setup-wizard', title: 'Operator Setup Wizard', tier: 'Tier 1', tierScore: 8, tokens: 443, palette: 0, group: 'A', pw: true, i18n: 1.00, loc: 1528 },
  { key: 'threshold-heatmap', title: 'Threshold Heatmap', tier: 'Tier 1', tierScore: 7, tokens: 99, palette: 0, group: 'A', pw: true, i18n: 0.97, loc: 499 },
  { key: 'rule-pack-selector', title: 'Rule Pack Selector', tier: 'Tier 2', tierScore: 6, tokens: 0, palette: 48, group: 'C', pw: false, i18n: 1.00, loc: 460 },
  { key: 'cli-playground', title: 'CLI Playground', tier: 'Tier 2', tierScore: 6, tokens: 0, palette: 66, group: 'C', pw: false, i18n: 1.00, loc: 395 },
  { key: 'rule-pack-detail', title: 'Rule Pack Detail', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 47, group: 'C', pw: false, i18n: 1.00, loc: 552 },
  { key: 'threshold-calculator', title: 'Threshold Calculator', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 54, group: 'C', pw: false, i18n: 0.93, loc: 485 },
  { key: 'template-gallery', title: 'Template Gallery', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 66, group: 'C', pw: false, i18n: 1.00, loc: 398 },
  { key: 'alert-simulator', title: 'Alert Simulator', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 51, group: 'C', pw: false, i18n: 1.00, loc: 560 },
  { key: 'config-diff', title: 'Config Diff', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 61, group: 'C', pw: false, i18n: 1.00, loc: 480 },
  { key: 'health-dashboard', title: 'Health Dashboard', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 52, group: 'C', pw: false, i18n: 1.00, loc: 445 },
  { key: 'rule-pack-matrix', title: 'Rule Pack Matrix', tier: 'Tier 2', tierScore: 4, tokens: 0, palette: 39, group: 'C', pw: false, i18n: 1.00, loc: 380 },
  { key: 'onboarding-checklist', title: 'Onboarding Checklist', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 49, group: 'C', pw: false, i18n: 1.00, loc: 420 },
  { key: 'alert-timeline', title: 'Alert Timeline', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 52, group: 'C', pw: false, i18n: 1.00, loc: 510 },
  { key: 'alert-noise-analyzer', title: 'Alert Noise Analyzer', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 45, group: 'C', pw: false, i18n: 1.00, loc: 430 },
  { key: 'schema-explorer', title: 'Schema Explorer', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 35, group: 'C', pw: false, i18n: 1.00, loc: 390 },
  { key: 'capacity-planner', title: 'Capacity Planner', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 45, group: 'C', pw: false, i18n: 1.00, loc: 420 },
  { key: 'runbook-viewer', title: 'Runbook Viewer', tier: 'Tier 2', tierScore: 4, tokens: 0, palette: 32, group: 'C', pw: false, i18n: 1.00, loc: 350 },
  { key: 'dependency-graph', title: 'Dependency Graph', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 41, group: 'C', pw: false, i18n: 0.97, loc: 480 },
  { key: 'architecture-quiz', title: 'Architecture Quiz', tier: 'Tier 2', tierScore: 4, tokens: 0, palette: 48, group: 'C', pw: false, i18n: 1.00, loc: 360 },
  { key: 'promql-tester', title: 'PromQL Tester', tier: 'Tier 2', tierScore: 5, tokens: 0, palette: 63, group: 'C', pw: false, i18n: 1.00, loc: 450 },
  { key: 'platform-demo', title: 'Platform Demo', tier: 'Tier 2', tierScore: 4, tokens: 0, palette: 70, group: 'C', pw: false, i18n: 1.00, loc: 520 },
  { key: 'roi-calculator', title: 'ROI Calculator', tier: 'Tier 2', tierScore: 6, tokens: 122, palette: 0, group: 'A', pw: false, i18n: 0.93, loc: 540 },
  { key: 'migration-roi-calculator', title: 'Migration ROI Calculator', tier: 'Tier 2', tierScore: 6, tokens: 111, palette: 0, group: 'A', pw: false, i18n: 1.00, loc: 520 },
  { key: 'self-service-portal', title: 'Self-Service Portal', tier: 'Tier 2', tierScore: 4, tokens: 0, palette: 10, group: 'C', pw: false, i18n: 1.00, loc: 380 },
  { key: 'multi-tenant-comparison', title: 'Multi-Tenant Comparison', tier: 'Tier 2', tierScore: 5, tokens: 36, palette: 0, group: 'B', pw: false, i18n: 0.96, loc: 410 },
  { key: 'release-notes-generator', title: 'Release Notes Generator', tier: 'Tier 2', tierScore: 5, tokens: 165, palette: 0, group: 'A', pw: false, i18n: 1.00, loc: 480 },
  { key: 'platform-health', title: 'Platform Health', tier: 'Tier 3', tierScore: 3, tokens: 0, palette: 65, group: 'C', pw: false, i18n: 1.00, loc: 420 },
  { key: 'migration-simulator', title: 'Migration Simulator', tier: 'Tier 3', tierScore: 3, tokens: 0, palette: 57, group: 'C', pw: false, i18n: 1.00, loc: 380 },
  { key: 'glossary', title: 'Glossary', tier: 'Tier 3', tierScore: 2, tokens: 0, palette: 22, group: 'C', pw: false, i18n: 1.00, loc: 280 },
];

/* ── Design Token Styles ── */
const styles = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: 'var(--da-spacing-8)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--da-spacing-6)',
  },
  header: {
    marginBottom: 'var(--da-spacing-2)',
  },
  title: {
    fontSize: 'var(--da-font-size-2xl)',
    fontWeight: 'var(--da-font-weight-bold)',
    color: 'var(--da-color-text-primary)',
    margin: 0,
  },
  subtitle: {
    fontSize: 'var(--da-font-size-sm)',
    color: 'var(--da-color-text-secondary)',
    marginTop: 'var(--da-spacing-1)',
  },
  kpiRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: 'var(--da-spacing-4)',
  },
  kpiCard: {
    background: 'var(--da-color-surface)',
    border: '1px solid var(--da-color-border)',
    borderRadius: 'var(--da-radius-lg)',
    padding: 'var(--da-spacing-4)',
    textAlign: 'center',
  },
  kpiValue: {
    fontSize: 'var(--da-font-size-2xl)',
    fontWeight: 'var(--da-font-weight-bold)',
    color: 'var(--da-color-text-primary)',
  },
  kpiLabel: {
    fontSize: 'var(--da-font-size-xs)',
    color: 'var(--da-color-text-secondary)',
    marginTop: 'var(--da-spacing-1)',
  },
  section: {
    background: 'var(--da-color-surface)',
    border: '1px solid var(--da-color-border)',
    borderRadius: 'var(--da-radius-lg)',
    padding: 'var(--da-spacing-6)',
  },
  sectionTitle: {
    fontSize: 'var(--da-font-size-lg)',
    fontWeight: 'var(--da-font-weight-semibold)',
    color: 'var(--da-color-text-primary)',
    marginBottom: 'var(--da-spacing-4)',
    margin: 0,
  },
  filterRow: {
    display: 'flex',
    gap: 'var(--da-spacing-3)',
    flexWrap: 'wrap',
    marginBottom: 'var(--da-spacing-4)',
  },
  filterBtn: {
    padding: 'var(--da-spacing-1) var(--da-spacing-3)',
    border: '1px solid var(--da-color-border)',
    borderRadius: 'var(--da-radius-md)',
    background: 'var(--da-color-surface)',
    color: 'var(--da-color-text-secondary)',
    cursor: 'pointer',
    fontSize: 'var(--da-font-size-sm)',
    transition: 'all 0.15s ease',
  },
  filterBtnActive: {
    background: 'var(--da-color-primary)',
    color: 'var(--da-color-text-on-primary)',
    borderColor: 'var(--da-color-primary)',
  },
  barChart: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: 'var(--da-spacing-2)',
    height: '120px',
    padding: 'var(--da-spacing-2) 0',
  },
  barGroup: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    flex: 1,
    gap: 'var(--da-spacing-1)',
  },
  barLabel: {
    fontSize: 'var(--da-font-size-xs)',
    color: 'var(--da-color-text-secondary)',
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  barValue: {
    fontSize: 'var(--da-font-size-xs)',
    fontWeight: 'var(--da-font-weight-semibold)',
    color: 'var(--da-color-text-primary)',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 'var(--da-font-size-sm)',
  },
  th: {
    textAlign: 'left',
    padding: 'var(--da-spacing-2) var(--da-spacing-3)',
    borderBottom: '2px solid var(--da-color-border)',
    color: 'var(--da-color-text-secondary)',
    fontWeight: 'var(--da-font-weight-semibold)',
    fontSize: 'var(--da-font-size-xs)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    cursor: 'pointer',
    userSelect: 'none',
  },
  td: {
    padding: 'var(--da-spacing-2) var(--da-spacing-3)',
    borderBottom: '1px solid var(--da-color-border)',
    color: 'var(--da-color-text-primary)',
  },
  badge: {
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: 'var(--da-radius-full)',
    fontSize: 'var(--da-font-size-xs)',
    fontWeight: 'var(--da-font-weight-semibold)',
  },
  progressBar: {
    width: '100%',
    height: '6px',
    borderRadius: 'var(--da-radius-full)',
    background: 'var(--da-color-bg-secondary)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 'var(--da-radius-full)',
    transition: 'width 0.3s ease',
  },
};

/* ── Color mappings ── */
const TIER_COLORS = {
  'Tier 1': { bg: 'var(--da-color-success-soft)', text: 'var(--da-color-success)' },
  'Tier 2': { bg: 'var(--da-color-warning-soft)', text: 'var(--da-color-warning)' },
  'Tier 3': { bg: 'var(--da-color-error-soft)', text: 'var(--da-color-error)' },
};

const GROUP_COLORS = {
  A: { bg: 'var(--da-color-success-soft)', text: 'var(--da-color-success)', label: 'Mature' },
  B: { bg: 'var(--da-color-warning-soft)', text: 'var(--da-color-warning)', label: 'Partial' },
  C: { bg: 'var(--da-color-error-soft)', text: 'var(--da-color-error)', label: 'Unmigrated' },
};

/* ── Sub-components ── */
function KpiCard({ value, label, accent }) {
  return (
    <div style={styles.kpiCard} role="group" aria-label={label}>
      <div style={{ ...styles.kpiValue, color: accent || styles.kpiValue.color }}>{value}</div>
      <div style={styles.kpiLabel}>{label}</div>
    </div>
  );
}

function Badge({ tier }) {
  const tierKey = tier.startsWith('Tier 3') ? 'Tier 3' : tier;
  const colors = TIER_COLORS[tierKey] || TIER_COLORS['Tier 2'];
  return (
    <span style={{ ...styles.badge, background: colors.bg, color: colors.text }}>
      {tier}
    </span>
  );
}

function TokenBadge({ group }) {
  const c = GROUP_COLORS[group] || GROUP_COLORS.C;
  return (
    <span style={{ ...styles.badge, background: c.bg, color: c.text }} title={c.label}>
      {group} — {c.label}
    </span>
  );
}

function ProgressCell({ ratio }) {
  const pct = Math.round(ratio * 100);
  const color = pct >= 95
    ? 'var(--da-color-success)'
    : pct >= 80
    ? 'var(--da-color-warning)'
    : 'var(--da-color-error)';
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--da-spacing-2)' }}>
      <div style={styles.progressBar} role="progressbar" aria-valuenow={pct} aria-valuemin={0} aria-valuemax={100} aria-label={`i18n coverage ${pct}%`}>
        <div style={{ ...styles.progressFill, width: `${pct}%`, background: color }} />
      </div>
      <span style={{ fontSize: 'var(--da-font-size-xs)', minWidth: '36px', color }}>{pct}%</span>
    </div>
  );
}

function SimpleBar({ items, maxVal, colorFn }) {
  return (
    <div style={styles.barChart} role="img" aria-label={t('分佈圖', 'Distribution chart')}>
      {items.map(({ label, value }) => {
        const h = maxVal > 0 ? Math.max(4, (value / maxVal) * 100) : 4;
        return (
          <div key={label} style={styles.barGroup}>
            <div style={styles.barValue}>{value}</div>
            <div style={{ width: '100%', maxWidth: '60px', height: `${h}px`, borderRadius: 'var(--da-radius-sm)', background: colorFn(label), transition: 'height 0.3s ease' }} />
            <div style={styles.barLabel}>{label}</div>
          </div>
        );
      })}
    </div>
  );
}

/* ── Main Component ── */
export default function ComponentHealth() {
  const [tierFilter, setTierFilter] = useState('all');
  const [sortCol, setSortCol] = useState('tierScore');
  const [sortAsc, setSortAsc] = useState(false);

  const allTiers = ['all', 'Tier 1', 'Tier 2', 'Tier 3'];

  const filtered = useMemo(() => {
    let data = HEALTH_DATA;
    if (tierFilter !== 'all') {
      data = data.filter(d => d.tier.startsWith(tierFilter));
    }
    return [...data].sort((a, b) => {
      let va = a[sortCol], vb = b[sortCol];
      if (typeof va === 'boolean') { va = va ? 1 : 0; vb = vb ? 1 : 0; }
      if (typeof va === 'string') return sortAsc ? va.localeCompare(vb) : vb.localeCompare(va);
      return sortAsc ? va - vb : vb - va;
    });
  }, [tierFilter, sortCol, sortAsc]);

  /* ── Aggregate stats ── */
  const stats = useMemo(() => {
    const total = HEALTH_DATA.length;
    const tier1 = HEALTH_DATA.filter(d => d.tier === 'Tier 1').length;
    const groupA = HEALTH_DATA.filter(d => d.group === 'A').length;
    const groupB = HEALTH_DATA.filter(d => d.group === 'B').length;
    const groupC = HEALTH_DATA.filter(d => d.group === 'C').length;
    const pwCov = HEALTH_DATA.filter(d => d.pw).length;
    const avgI18n = HEALTH_DATA.reduce((s, d) => s + d.i18n, 0) / total;
    const tier1Pw = HEALTH_DATA.filter(d => d.tier === 'Tier 1' && d.pw).length;
    const tier1Total = tier1;
    return { total, tier1, groupA, groupB, groupC, pwCov, avgI18n, tier1Pw, tier1Total };
  }, []);

  const handleSort = (col) => {
    if (sortCol === col) setSortAsc(!sortAsc);
    else { setSortCol(col); setSortAsc(false); }
  };

  const sortIcon = (col) => sortCol === col ? (sortAsc ? ' ↑' : ' ↓') : '';

  /* ── Distribution data ── */
  const tierDist = [
    { label: 'Tier 1', value: stats.tier1 },
    { label: 'Tier 2', value: HEALTH_DATA.filter(d => d.tier.startsWith('Tier 2')).length },
    { label: 'Tier 3', value: HEALTH_DATA.filter(d => d.tier.startsWith('Tier 3')).length },
  ];
  const tokenDist = [
    { label: 'A', value: stats.groupA },
    { label: 'B', value: stats.groupB },
    { label: 'C', value: stats.groupC },
  ];

  return (
    <div style={styles.container}>
      {/* Header */}
      <header style={styles.header}>
        <h1 style={styles.title}>{t('元件健康儀表板', 'Component Health Dashboard')}</h1>
        <p style={styles.subtitle}>{t(
          'v2.7.0 Phase .a 基準線 — 38 個互動工具的品質、覆蓋率與設計 Token 合規概覽',
          'v2.7.0 Phase .a baseline — quality, coverage & design token compliance for 38 interactive tools'
        )}</p>
      </header>

      {/* KPI Row */}
      <div style={styles.kpiRow} role="region" aria-label={t('關鍵指標', 'Key metrics')}>
        <KpiCard value={stats.total} label={t('總工具數', 'Total Tools')} />
        <KpiCard value={`${stats.tier1Pw}/${stats.tier1Total}`} label={t('Tier 1 Playwright', 'Tier 1 Playwright')} accent="var(--da-color-success)" />
        <KpiCard value={`${stats.pwCov}/${stats.total}`} label={t('Playwright 覆蓋', 'Playwright Coverage')} />
        <KpiCard value={`${Math.round(stats.avgI18n * 100)}%`} label={t('平均 i18n 覆蓋', 'Avg i18n Coverage')} accent="var(--da-color-info)" />
        <KpiCard value={`${stats.groupA}`} label={t('Token Group A', 'Token Group A')} accent="var(--da-color-success)" />
        <KpiCard value={`${stats.groupC}`} label={t('Token Group C', 'Token Group C')} accent="var(--da-color-error)" />
      </div>

      {/* Distribution Charts */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--da-spacing-4)' }}>
        <div style={styles.section}>
          <h2 style={styles.sectionTitle}>{t('Tier 分佈', 'Tier Distribution')}</h2>
          <SimpleBar
            items={tierDist}
            maxVal={Math.max(...tierDist.map(d => d.value))}
            colorFn={(label) => TIER_COLORS[label]?.text || 'var(--da-color-text-secondary)'}
          />
        </div>
        <div style={styles.section}>
          <h2 style={styles.sectionTitle}>{t('Design Token 合規', 'Design Token Compliance')}</h2>
          <SimpleBar
            items={tokenDist}
            maxVal={Math.max(...tokenDist.map(d => d.value))}
            colorFn={(label) => GROUP_COLORS[label]?.text || 'var(--da-color-text-secondary)'}
          />
        </div>
      </div>

      {/* Tool Table */}
      <div style={styles.section}>
        <h2 style={{ ...styles.sectionTitle, marginBottom: 'var(--da-spacing-4)' }}>
          {t('工具明細', 'Tool Details')}
        </h2>

        {/* Tier filter */}
        <div style={styles.filterRow} role="radiogroup" aria-label={t('Tier 篩選', 'Tier filter')}>
          {allTiers.map(tier => (
            <button
              key={tier}
              role="radio"
              aria-checked={tierFilter === tier}
              onClick={() => setTierFilter(tier)}
              style={{
                ...styles.filterBtn,
                ...(tierFilter === tier ? styles.filterBtnActive : {}),
              }}
            >
              {tier === 'all' ? t('全部', 'All') : tier}
            </button>
          ))}
        </div>

        <div style={{ overflowX: 'auto' }}>
          <table style={styles.table}>
            <thead>
              <tr>
                <th style={styles.th} onClick={() => handleSort('title')}>
                  {t('工具', 'Tool')}{sortIcon('title')}
                </th>
                <th style={styles.th} onClick={() => handleSort('tierScore')}>
                  {t('Tier', 'Tier')}{sortIcon('tierScore')}
                </th>
                <th style={styles.th} onClick={() => handleSort('group')}>
                  {t('Token', 'Token')}{sortIcon('group')}
                </th>
                <th style={styles.th} onClick={() => handleSort('tokens')}>
                  {t('Tokens', 'Tokens')}{sortIcon('tokens')}
                </th>
                <th style={styles.th} onClick={() => handleSort('palette')}>
                  {t('Palette', 'Palette')}{sortIcon('palette')}
                </th>
                <th style={styles.th} onClick={() => handleSort('i18n')}>
                  {t('i18n', 'i18n')}{sortIcon('i18n')}
                </th>
                <th style={styles.th} onClick={() => handleSort('pw')}>
                  {t('Playwright', 'PW')}{sortIcon('pw')}
                </th>
                <th style={styles.th} onClick={() => handleSort('loc')}>
                  {t('LOC', 'LOC')}{sortIcon('loc')}
                </th>
              </tr>
            </thead>
            <tbody>
              {filtered.map(tool => (
                <tr key={tool.key}>
                  <td style={styles.td}>
                    <strong>{tool.title}</strong>
                    <div style={{ fontSize: 'var(--da-font-size-xs)', color: 'var(--da-color-text-tertiary)' }}>{tool.key}</div>
                  </td>
                  <td style={styles.td}><Badge tier={tool.tier} /></td>
                  <td style={styles.td}><TokenBadge group={tool.group} /></td>
                  <td style={styles.td}>{tool.tokens}</td>
                  <td style={styles.td}>
                    <span style={{ color: tool.palette > 0 ? 'var(--da-color-error)' : 'var(--da-color-success)' }}>
                      {tool.palette}
                    </span>
                  </td>
                  <td style={{ ...styles.td, minWidth: '120px' }}>
                    <ProgressCell ratio={tool.i18n} />
                  </td>
                  <td style={styles.td}>
                    <span
                      role="img"
                      aria-label={tool.pw ? t('有 Playwright 測試', 'Has Playwright test') : t('無 Playwright 測試', 'No Playwright test')}
                    >
                      {tool.pw ? '✓' : '—'}
                    </span>
                  </td>
                  <td style={styles.td}>{tool.loc}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div style={{ marginTop: 'var(--da-spacing-4)', fontSize: 'var(--da-font-size-xs)', color: 'var(--da-color-text-tertiary)' }}>
          {t(
            `顯示 ${filtered.length} / ${HEALTH_DATA.length} 工具 · 資料來源：scan_component_health.py · 快照日期：2026-04-17`,
            `Showing ${filtered.length} / ${HEALTH_DATA.length} tools · Source: scan_component_health.py · Snapshot: 2026-04-17`
          )}
        </div>
      </div>

      {/* Legend */}
      <div style={{ ...styles.section, fontSize: 'var(--da-font-size-sm)', color: 'var(--da-color-text-secondary)' }}>
        <h2 style={{ ...styles.sectionTitle, fontSize: 'var(--da-font-size-base)' }}>{t('圖例', 'Legend')}</h2>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--da-spacing-4)' }}>
          <div>
            <strong>{t('Tier 評分 (DEC-08)', 'Tier Scoring (DEC-08)')}</strong>
            <p style={{ margin: 'var(--da-spacing-1) 0' }}>{t(
              '5 維度加權：LOC + Audience + Journey Phase + Writer + Recency。Tier 1 ≥7, Tier 2 4-6, Tier 3 ≤3。',
              '5-dimensional weighted: LOC + Audience + Journey Phase + Writer + Recency. Tier 1 ≥7, Tier 2 4-6, Tier 3 ≤3.'
            )}</p>
          </div>
          <div>
            <strong>{t('Token Group', 'Token Group')}</strong>
            <p style={{ margin: 'var(--da-spacing-1) 0' }}>{t(
              'A = density ≥10/100LOC, 0 palette · B = 部分遷移 · C = 未遷移（density <5, ≥5 palette）',
              'A = density ≥10/100LOC, 0 palette · B = partial migration · C = unmigrated (density <5, ≥5 palette)'
            )}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
