"""Tests for check_undefined_tokens.py — Detect JSX/CSS references to --da-color-* tokens not defined in design-tokens.css.

Pinned contracts
----------------
1. **Detection**: `var(--da-color-<name>)` reference in JSX/JS/CSS
   where `<name>` is NOT a `--da-color-<name>:` definition in
   design-tokens.css. Captures `<name>`. Allows fallback `,` syntax
   (`var(--da-color-x, fallback)`) — still flags missing `--da-color-x`.
2. **Suppression**:
   - Per-line `# undefined-tokens: ignore` marker (3-line lookback).
   - Tokens defined in light OR dark `:root` block count as defined.
   - Non-color categories (`--da-space-*` / `--da-font-*` / etc) NOT
     in scope (regex anchors on `--da-color-` prefix).
3. **Severity matrix** (`_compute_exit_code`):
   - !ci, * → exit 0
   - ci, 0 findings → exit 0
   - ci, >0 findings → exit 1
4. **Robustness**: empty source / whitespace inside `var()` / no
   `tokens-css` file → exit 2 (misconfig).
5. **Live dogfood** (`TestLiveRepo`): real `docs/**` JSX/CSS yields
   zero findings — gates broken state from landing.

Generated by ``scripts/tools/dx/scaffold_lint.py``. See PR #171.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

_TOOLS_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..", "scripts", "tools", "lint"
)
sys.path.insert(0, _TOOLS_DIR)

import check_undefined_tokens as lint  # noqa: E402


def _scan(source: str, known_set, fake_path: str = "fake.jsx"):
    return lint.scan_source(Path(fake_path), source, known_set=known_set)


# ---------------------------------------------------------------------------
# Detection — positive cases
# ---------------------------------------------------------------------------
class TestDetection:
    def test_empty_source_no_findings(self):
        assert _scan("", {"fg"}) == []

    def test_undefined_token_flagged(self):
        src = 'color: var(--da-color-typo);'
        findings = _scan(src, {"fg"})
        assert len(findings) == 1
        assert findings[0].token_name == "typo"

    def test_defined_token_not_flagged(self):
        src = 'color: var(--da-color-fg);'
        assert _scan(src, {"fg"}) == []

    def test_var_with_fallback_still_checks_name(self):
        src = 'color: var(--da-color-typo, #ccc);'
        findings = _scan(src, {"fg"})
        assert len(findings) == 1
        assert findings[0].token_name == "typo"

    @pytest.mark.parametrize(
        "src",
        [
            'className="text-[color:var(--da-color-mising)]"',
            "background: var(--da-color-mising);",
            "border: 1px solid var(--da-color-mising);",
            "var( --da-color-mising )",
        ],
    )
    def test_various_contexts(self, src):
        findings = _scan(src, {"fg"})
        assert len(findings) == 1
        assert findings[0].token_name == "mising"

    def test_multiple_findings_in_one_line(self):
        src = "var(--da-color-x); var(--da-color-y);"
        findings = _scan(src, set())
        assert len(findings) == 2

    def test_multiple_findings_across_lines(self):
        src = "var(--da-color-x);\nvar(--da-color-y);\n"
        findings = _scan(src, set())
        assert findings[0].line == 1
        assert findings[1].line == 2


# ---------------------------------------------------------------------------
# Negative
# ---------------------------------------------------------------------------
class TestNegativeCases:
    @pytest.mark.parametrize(
        "src",
        [
            "padding: var(--da-space-3);",
            "font-size: var(--da-font-md);",
            "box-shadow: var(--da-shadow-md);",
            "border-radius: var(--da-radius-lg);",
            "transition: var(--da-transition-fast);",
        ],
    )
    def test_non_color_categories_not_flagged(self, src):
        assert _scan(src, set()) == []

    def test_var_outside_da_namespace_not_flagged(self):
        src = "color: var(--my-other-color); color: var(--bs-primary);"
        assert _scan(src, set()) == []


# ---------------------------------------------------------------------------
# Suppression
# ---------------------------------------------------------------------------
class TestSuppression:
    def test_ignore_on_same_line_suppresses(self):
        src = "color: var(--da-color-typo); # undefined-tokens: ignore\n"
        assert _scan(src, set()) == []

    def test_ignore_one_line_above_suppresses(self):
        src = "// # undefined-tokens: ignore\ncolor: var(--da-color-typo);\n"
        assert _scan(src, set()) == []

    def test_ignore_three_lines_above_suppresses(self):
        src = (
            "// # undefined-tokens: ignore\n"
            "// rationale: legacy compat shim\n"
            "// remove once X migrates\n"
            "color: var(--da-color-typo);\n"
        )
        assert _scan(src, set()) == []

    def test_ignore_four_lines_above_does_not_suppress(self):
        src = (
            "// # undefined-tokens: ignore\n"
            "// l2\n"
            "// l3\n"
            "// l4\n"
            "color: var(--da-color-typo);\n"
        )
        findings = _scan(src, set())
        assert len(findings) == 1


# ---------------------------------------------------------------------------
# Severity matrix
# ---------------------------------------------------------------------------
class TestComputeExitCode:
    @pytest.mark.parametrize("n", [0, 1, 5])
    def test_no_ci_always_exit_0(self, n):
        assert lint._compute_exit_code(ci=False, n_findings=n) == 0

    def test_ci_zero_findings_exit_0(self):
        assert lint._compute_exit_code(ci=True, n_findings=0) == 0

    @pytest.mark.parametrize("n", [1, 5, 100])
    def test_ci_with_findings_exit_1(self, n):
        assert lint._compute_exit_code(ci=True, n_findings=n) == 1


# ---------------------------------------------------------------------------
# Helpers — load_known_tokens
# ---------------------------------------------------------------------------
class TestLoadKnownTokens:
    def test_loads_light_and_dark_blocks(self, tmp_path):
        css = tmp_path / "tokens.css"
        css.write_text(
            ":root { --da-color-fg: #000; --da-color-bg: #fff; }\n"
            "[data-theme='dark'] { --da-color-fg: #fff; --da-color-bg: #000; "
            "--da-color-extra: #888; }\n",
            encoding="utf-8",
        )
        known = lint.load_known_tokens(css)
        assert known == {"fg", "bg", "extra"}

    def test_missing_file_returns_empty_set(self, tmp_path):
        assert lint.load_known_tokens(tmp_path / "nope.css") == set()


# ---------------------------------------------------------------------------
# main() integration
# ---------------------------------------------------------------------------
class TestMain:
    @pytest.mark.timeout(15)
    def test_main_clean_exit_0(self, tmp_path):
        css = tmp_path / "tokens.css"
        css.write_text(":root { --da-color-fg: #000; }\n", encoding="utf-8")
        clean = tmp_path / "clean.jsx"
        clean.write_text("color: var(--da-color-fg);\n", encoding="utf-8")
        rc = lint.main(["--ci", "--tokens-css", str(css), str(clean)])
        assert rc == 0

    @pytest.mark.timeout(15)
    def test_main_dirty_under_ci_exit_1(self, tmp_path, capsys):
        css = tmp_path / "tokens.css"
        css.write_text(":root { --da-color-fg: #000; }\n", encoding="utf-8")
        dirty = tmp_path / "dirty.jsx"
        dirty.write_text("color: var(--da-color-typo);\n", encoding="utf-8")
        rc = lint.main(["--ci", "--tokens-css", str(css), str(dirty)])
        assert rc == 1
        captured = capsys.readouterr()
        assert "1 undefined-token" in captured.err
        assert "typo" in captured.err

    @pytest.mark.timeout(15)
    def test_main_missing_tokens_css_returns_2(self, tmp_path):
        # Misconfig: tokens.css doesn't exist → empty known set → every
        # ref would be flagged → abort with rc=2 to surface the error.
        rc = lint.main(["--ci", "--tokens-css", str(tmp_path / "nope.css")])
        assert rc == 2


# ---------------------------------------------------------------------------
# Live dogfood — actual repo must pass
# ---------------------------------------------------------------------------
class TestLiveRepo:
    @pytest.mark.timeout(30)
    def test_live_repo_has_no_undefined_tokens(self):
        known = lint.load_known_tokens(lint._TOKENS_CSS)
        assert known, "expected design-tokens.css to be loadable"

        import argparse

        ns = argparse.Namespace(paths=[])
        candidates = lint._resolve_target_paths(ns)
        candidates = [p for p in candidates if p != lint._TOKENS_CSS]
        assert candidates, "expected docs/ jsx/js/css files to exist"

        all_findings = []
        for path in candidates:
            try:
                source = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            all_findings.extend(
                lint.scan_source(path, source, known_set=known)
            )

        assert all_findings == [], (
            f"Live repo has {len(all_findings)} undefined-token "
            f"reference(s):\n"
            + "\n".join(f"  - {f.render()}" for f in all_findings[:10])
        )
