"""Tests for check_hardcode_tenant.py — Detect hardcoded tenant literals in PromQL label selectors (Rule #2).

Pinned contracts
----------------
1. **Detection**: PromQL label selector ``tenant="<literal>"`` /
   ``tenant_id="<literal>"`` / ``tenantId="<literal>"`` with a
   non-template value (case-insensitive label key, single OR double
   quote).
2. **Suppression**:
   - Per-line ``<!-- hardcode-tenant: ignore -->`` marker.
   - 3-line lookback (covers multi-line rationale comments).
   - Template values (``$var`` / ``{{ var }}`` / ``<TENANT>`` /
     ``__TENANT__``) NOT flagged.
   - Regex / negation operators (``=~`` / ``!=`` / ``!~``) NOT flagged
     (only ``=`` exact-match is in scope).
3. **Severity matrix** (`_compute_exit_code`):
   - !ci, * → exit 0
   - ci, 0 findings → exit 0
   - ci, >0 findings → exit 1
4. **Robustness**: empty source / weird quote nesting / case variants.
5. **Live dogfood** (`TestLiveRepo`): production code paths (non-test,
   non-fixture) yield zero findings — gates broken state from landing.

Generated by ``scripts/tools/dx/scaffold_lint.py``. See PR #171.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

_TOOLS_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..", "scripts", "tools", "lint"
)
sys.path.insert(0, _TOOLS_DIR)

import check_hardcode_tenant as lint  # noqa: E402


def _scan(source: str, fake_path: str = "fake.go"):
    return lint.scan_source(Path(fake_path), source)


# ---------------------------------------------------------------------------
# Detection — positive cases
# ---------------------------------------------------------------------------
class TestDetection:
    def test_empty_source_no_findings(self):
        assert _scan("") == []

    @pytest.mark.parametrize(
        "src",
        [
            'rate(metric{tenant="db-a"}[5m])',
            'sum(metric{tenant_id="prod-a"})',
            'metric{tenantId="foo"}',
            "metric{tenant='single-quoted'}",
            'rate(metric{job="x", tenant="db-a"}[5m])',
            'rate(metric{tenant="DB-A"}[5m])',  # uppercase value
            'metric{TENANT="db-a"}',  # uppercase key (case-insensitive)
        ],
    )
    def test_positive_detection(self, src):
        findings = _scan(src)
        assert len(findings) == 1, f"expected 1 finding in {src!r}, got {findings}"

    def test_multi_label_first_position_caught(self):
        src = 'metric{tenant="db-a", env="prod"}'
        assert len(_scan(src)) == 1

    def test_multiple_findings_in_one_file(self):
        src = (
            'rate(a{tenant="db-a"}[5m])\n'
            'rate(b{tenant_id="prod-a"}[5m])\n'
        )
        findings = _scan(src)
        assert len(findings) == 2
        assert findings[0].line == 1
        assert findings[1].line == 2


# ---------------------------------------------------------------------------
# Negative — template values and non-equality operators do NOT flag
# ---------------------------------------------------------------------------
class TestNegativeCases:
    @pytest.mark.parametrize(
        "src",
        [
            'metric{tenant="$tenant"}',
            'metric{tenant="{{ tenant }}"}',
            'metric{tenant="<TENANT>"}',
            'metric{tenant="<STR>"}',
            'metric{tenant="__TENANT__"}',
            'metric{tenant=""}',  # empty placeholder
            'metric{tenant=~".*"}',  # regex match
            'metric{tenant!="db-a"}',  # negation
            'metric{tenant!~".*"}',
        ],
    )
    def test_template_or_non_eq_not_flagged(self, src):
        assert _scan(src) == []

    def test_unrelated_label_not_flagged(self):
        # `env="prod"` is fine — only `tenant`/`tenant_id`/`tenantId` are
        # in scope.
        assert _scan('metric{env="prod"}') == []

    def test_word_boundary_not_in_label_position(self):
        # Bare `tenant="db-a"` outside a label context (no preceding `{`
        # or `,`) is a comment / prose form and not flagged. This guards
        # against false-matching free-form documentation prose like
        # `// the tenant="db-a" example shows...`.
        assert _scan('// the tenant="db-a" example') == []


# ---------------------------------------------------------------------------
# Suppression — ignore comment behavior (3-line lookback)
# ---------------------------------------------------------------------------
class TestSuppression:
    def test_ignore_on_same_line_suppresses(self):
        src = 'rate(m{tenant="db-a"}[5m])  // <!-- hardcode-tenant: ignore -->\n'
        assert _scan(src) == []

    def test_ignore_one_line_above_suppresses(self):
        src = (
            "// <!-- hardcode-tenant: ignore -->\n"
            'rate(m{tenant="db-a"}[5m])\n'
        )
        assert _scan(src) == []

    def test_ignore_three_lines_above_suppresses(self):
        src = (
            "// <!-- hardcode-tenant: ignore -->\n"
            "// rationale: legacy default for migration smoke test.\n"
            "// remove once C-3 dual-entry ships.\n"
            'rate(m{tenant="db-a"}[5m])\n'
        )
        assert _scan(src) == []

    def test_ignore_four_lines_above_does_not_suppress(self):
        src = (
            "// <!-- hardcode-tenant: ignore -->\n"
            "// l2\n"
            "// l3\n"
            "// l4\n"
            'rate(m{tenant="db-a"}[5m])\n'
        )
        findings = _scan(src)
        assert len(findings) == 1


# ---------------------------------------------------------------------------
# Severity matrix
# ---------------------------------------------------------------------------
class TestComputeExitCode:
    @pytest.mark.parametrize("n", [0, 1, 5])
    def test_no_ci_always_exit_0(self, n):
        assert lint._compute_exit_code(ci=False, n_findings=n) == 0

    def test_ci_zero_findings_exit_0(self):
        assert lint._compute_exit_code(ci=True, n_findings=0) == 0

    @pytest.mark.parametrize("n", [1, 5, 100])
    def test_ci_with_findings_exit_1(self, n):
        assert lint._compute_exit_code(ci=True, n_findings=n) == 1


# ---------------------------------------------------------------------------
# Path exclusion
# ---------------------------------------------------------------------------
class TestPathExclusion:
    @pytest.mark.parametrize(
        "path",
        [
            "components/foo/bar_test.go",
            "components/foo/internal/x/y_test.go",
            "scripts/tools/tests/foo.py",
            "components/foo/testdata/cluster.yaml",
            "examples/baseline-discovery.py",
            "tests/golden/foo.go",
            "components/foo/fixtures/bar.yaml",
        ],
    )
    def test_excluded_paths(self, path):
        assert lint._is_excluded_path(Path(path)) is True

    @pytest.mark.parametrize(
        "path",
        [
            "components/foo/bar.go",
            "components/threshold-exporter/app/config.go",
            "scripts/tools/ops/check_alert.py",
            "rule-packs/rule-pack-mariadb.yaml",
            "pkg/config/types.go",
        ],
    )
    def test_included_paths(self, path):
        assert lint._is_excluded_path(Path(path)) is False


# ---------------------------------------------------------------------------
# main() integration
# ---------------------------------------------------------------------------
class TestMain:
    @pytest.mark.timeout(15)
    def test_main_clean_exit_0(self, tmp_path, capsys):
        clean = tmp_path / "clean.go"
        clean.write_text(
            'package x\nvar q = `rate(m{tenant="$tenant"}[5m])`\n',
            encoding="utf-8",
        )
        rc = lint.main(["--ci", str(clean)])
        assert rc == 0

    @pytest.mark.timeout(15)
    def test_main_dirty_under_ci_exit_1(self, tmp_path, capsys):
        dirty = tmp_path / "dirty.go"
        dirty.write_text(
            'package x\nvar q = `rate(m{tenant="db-a"}[5m])`\n',
            encoding="utf-8",
        )
        rc = lint.main(["--ci", str(dirty)])
        assert rc == 1
        captured = capsys.readouterr()
        assert "1 finding" in captured.err
        assert "db-a" in captured.err

    @pytest.mark.timeout(15)
    def test_main_dirty_no_ci_exit_0(self, tmp_path, capsys):
        dirty = tmp_path / "dirty.go"
        dirty.write_text(
            'package x\nvar q = `m{tenant="db-a"}`\n',
            encoding="utf-8",
        )
        rc = lint.main([str(dirty)])
        assert rc == 0  # report-only mode


# ---------------------------------------------------------------------------
# #1810 — the skip-set is judged below the scan root, not on the absolute path
# ---------------------------------------------------------------------------
_DIRTY_GO = 'package x\nvar q = `rate(m{tenant="db-a"}[5m])`\n'


def _checkout(root: Path) -> Path:
    """A minimal production tree: components/ with one dirty .go file."""
    (root / "components" / "svc").mkdir(parents=True)
    dirty = root / "components" / "svc" / "query.go"
    dirty.write_text(_DIRTY_GO, encoding="utf-8")
    return dirty


def _default_scan(monkeypatch, root: Path) -> set[Path]:
    import argparse

    monkeypatch.setattr(lint, "PROJECT_ROOT", root)
    paths = lint._resolve_target_paths(argparse.Namespace(paths=[]))
    return {p.relative_to(root) for p in paths}


class TestSkipSetIsJudgedBelowTheScanRoot:
    """#1810: a checkout under an ancestor named ``examples`` must be scanned.

    The old predicate looked at every component of the *absolute* path, so
    any ancestor named ``examples`` / ``tests`` / ``fixtures`` / ``testdata``
    excluded every file of the default scan and ``--ci`` printed a green
    "no files matched scan target". The positive case builds exactly that
    ancestor shape and compares against a neutral one; the negative case
    pins that the skip-set still applies *inside* the root.
    """

    def test_same_tree_under_examples_and_under_plain_scans_the_same_files(
            self, tmp_path, monkeypatch):
        clash = tmp_path / "examples" / "repo"
        plain = tmp_path / "plain" / "repo"
        _checkout(clash)
        _checkout(plain)
        under_clash = _default_scan(monkeypatch, clash)
        under_plain = _default_scan(monkeypatch, plain)
        assert under_clash == under_plain
        assert under_clash == {Path("components/svc/query.go")}

    def test_a_skip_directory_inside_the_root_is_still_skipped(
            self, tmp_path, monkeypatch):
        root = tmp_path / "examples" / "repo"
        _checkout(root)
        (root / "components" / "examples").mkdir()
        (root / "components" / "examples" / "demo.go").write_text(
            _DIRTY_GO, encoding="utf-8")
        (root / "components" / "svc" / "query_test.go").write_text(
            _DIRTY_GO, encoding="utf-8")
        assert _default_scan(monkeypatch, root) == {Path("components/svc/query.go")}

    def test_is_excluded_path_judges_below_the_given_root(self, tmp_path):
        root = tmp_path / "examples" / "repo"
        assert lint._is_excluded_path(root / "components" / "a.go", root=root) is False
        assert lint._is_excluded_path(
            root / "components" / "examples" / "a.go", root=root) is True

    def test_an_explicit_file_outside_the_root_is_judged_by_filename_only(
            self, tmp_path, monkeypatch):
        """A caller-named file is the population; its ancestors are not a
        reason to drop it. Only the filename rules apply."""
        outside = tmp_path / "examples" / "a.go"
        outside.parent.mkdir()
        outside.write_text(_DIRTY_GO, encoding="utf-8")
        assert lint._is_excluded_path(outside, root=tmp_path / "elsewhere") is False
        assert lint._is_excluded_path(
            tmp_path / "examples" / "a_test.go", root=tmp_path / "elsewhere") is True
        rc = lint.main(["--ci", str(outside)])
        assert rc == 1

    @pytest.mark.timeout(15)
    def test_ci_sees_the_finding_in_a_checkout_under_examples(
            self, tmp_path, monkeypatch, capsys):
        """Before the fix this exited 0 with "no files matched scan target"."""
        root = tmp_path / "examples" / "repo"
        _checkout(root)
        monkeypatch.setattr(lint, "PROJECT_ROOT", root)
        rc = lint.main(["--ci"])
        assert rc == 1
        assert "db-a" in capsys.readouterr().err


class TestExplicitPathsAreNormalisedBeforeTheRootTest:
    """The same file must get the same verdict however
    the caller spells it. A symlink alias of the checkout, or a `..` spelling
    that lexically sits under the root while the file does not, used to
    reach a different branch of _is_excluded_path than the real path."""

    def _tree(self, tmp_path):
        root = tmp_path / "real" / "repo"
        example = root / "components" / "examples" / "demo.go"
        example.parent.mkdir(parents=True)
        example.write_text(_DIRTY_GO, encoding="utf-8")
        return root, example

    def test_a_symlink_alias_of_the_checkout_gets_the_real_path_verdict(
            self, tmp_path, monkeypatch):
        root, example = self._tree(tmp_path)
        alias = tmp_path / "alias"
        try:
            alias.symlink_to(root, target_is_directory=True)
        except (OSError, NotImplementedError):
            pytest.skip("symlinks unavailable here")
        monkeypatch.setattr(lint, "PROJECT_ROOT", root)
        via_alias = alias / "components" / "examples" / "demo.go"
        assert lint.main(["--ci", str(example)]) == lint.main(["--ci", str(via_alias)])
        assert lint.main(["--ci", str(via_alias)]) == 0

    def test_a_dot_dot_spelling_of_an_outside_file_is_not_treated_as_inside(
            self, tmp_path, monkeypatch):
        root, _ = self._tree(tmp_path)
        outside = tmp_path / "outside" / "examples" / "o.go"
        outside.parent.mkdir(parents=True)
        outside.write_text(_DIRTY_GO, encoding="utf-8")
        monkeypatch.setattr(lint, "PROJECT_ROOT", root)
        spelled = "../../outside/examples/o.go"  # lexically under root
        assert lint.main(["--ci", spelled]) == lint.main(["--ci", str(outside)])
        assert lint.main(["--ci", str(outside)]) == 1

    def test_a_symlinked_file_is_judged_where_it_sits_at_all_three_entries(
            self, tmp_path, monkeypatch, capsys):
        """The leaf is not resolved: `components/svc/cfg.go -> ../examples/real.go`
        is production code at the default scan, at `components/` and when named
        directly. Resolving the leaf gave the named entry a different verdict."""
        root = tmp_path / "real" / "repo"
        target = root / "components" / "examples" / "real.go"
        target.parent.mkdir(parents=True)
        target.write_text(_DIRTY_GO, encoding="utf-8")
        link = root / "components" / "svc" / "cfg.go"
        link.parent.mkdir()
        try:
            link.symlink_to(Path("..") / "examples" / "real.go")
        except (OSError, NotImplementedError):
            pytest.skip("symlinks unavailable here")
        monkeypatch.setattr(lint, "PROJECT_ROOT", root)
        verdicts = {
            "default": lint.main(["--ci"]),
            "dir": lint.main(["--ci", "components"]),
            "file": lint.main(["--ci", "components/svc/cfg.go"]),
        }
        assert verdicts == {"default": 1, "dir": 1, "file": 1}
        assert "components/svc/cfg.go" in capsys.readouterr().err


# ---------------------------------------------------------------------------
# #1810 — an empty default-roots population is a caller error
# ---------------------------------------------------------------------------
class TestEmptyDefaultRootsPopulationIsACallerError:
    """#1810: 0 files under the default scan roots is rc 2, --ci or not.

    Before the floor, ``--ci`` printed "no files matched scan target" and
    exited 0 — indistinguishable from "every file is clean". Only the
    default-roots population is bound: explicit paths are the caller's own
    choice and keep rc 0 (with a stderr note).
    """

    @pytest.mark.parametrize("argv", [["--ci"], []])
    def test_no_files_under_default_roots_is_rc_2(
            self, tmp_path, monkeypatch, capsys, argv):
        """Red if the floor is removed, or if the reason stops reaching stdout
        (validate_all quotes only the last meaningful stdout line)."""
        (tmp_path / "components").mkdir()
        monkeypatch.setattr(lint, "PROJECT_ROOT", tmp_path)
        rc = lint.main(argv)
        assert rc == lint.EXIT_CALLER_ERROR
        captured = capsys.readouterr()
        assert "no files under default scan roots" in captured.err
        assert "no files under default scan roots" in \
            captured.out.strip().splitlines()[-1]
        assert "✓" not in captured.out

    def test_default_roots_that_hold_only_skipped_files_is_rc_2(
            self, tmp_path, monkeypatch, capsys):
        (tmp_path / "components" / "testdata").mkdir(parents=True)
        (tmp_path / "components" / "testdata" / "x.go").write_text(
            _DIRTY_GO, encoding="utf-8")
        monkeypatch.setattr(lint, "PROJECT_ROOT", tmp_path)
        assert lint.main(["--ci"]) == lint.EXIT_CALLER_ERROR
        assert "nothing was measured" in capsys.readouterr().err

    def test_explicit_paths_that_are_all_excluded_keep_rc_0_but_say_so(
            self, tmp_path, monkeypatch, capsys):
        """Explicit paths are the caller's population: not a caller error,
        but never silent either."""
        skipped = tmp_path / "a_test.go"
        skipped.write_text(_DIRTY_GO, encoding="utf-8")
        monkeypatch.setattr(lint, "PROJECT_ROOT", tmp_path)
        rc = lint.main(["--ci", str(skipped), str(tmp_path / "missing.go")])
        assert rc == 0
        captured = capsys.readouterr()
        assert "nothing was measured" in captured.err
        assert "no files matched scan target" in captured.out


# ---------------------------------------------------------------------------
# Live dogfood — actual repo must pass
# ---------------------------------------------------------------------------
class TestLiveRepo:
    """Run the lint against the actual repo. If this PR's edits don't
    fully eliminate findings, this test fails — preventing PR from
    landing in a broken state.
    """

    @pytest.mark.timeout(60)
    def test_live_repo_has_no_findings(self):
        import argparse

        ns = argparse.Namespace(paths=[])
        candidates = lint._resolve_target_paths(ns)
        assert candidates, "expected production code roots to exist"

        all_findings = []
        for path in candidates:
            try:
                source = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            all_findings.extend(lint.scan_source(path, source))

        assert all_findings == [], (
            f"Live repo has {len(all_findings)} finding(s):\n"
            + "\n".join(f"  - {f.render()}" for f in all_findings[:10])
        )
