"""Tests for check_hardcode_tenant.py — Detect hardcoded tenant literals in PromQL label selectors (Rule #2).

Pinned contracts
----------------
1. **Detection**: PromQL label selector ``tenant="<literal>"`` /
   ``tenant_id="<literal>"`` / ``tenantId="<literal>"`` with a
   non-template value (case-insensitive label key, single OR double
   quote).
2. **Suppression**:
   - Per-line ``<!-- hardcode-tenant: ignore -->`` marker.
   - 3-line lookback (covers multi-line rationale comments).
   - Template values (``$var`` / ``{{ var }}`` / ``<TENANT>`` /
     ``__TENANT__``) NOT flagged.
   - Regex / negation operators (``=~`` / ``!=`` / ``!~``) NOT flagged
     (only ``=`` exact-match is in scope).
3. **Severity matrix** (`_compute_exit_code`):
   - !ci, * → exit 0
   - ci, 0 findings → exit 0
   - ci, >0 findings → exit 1
4. **Robustness**: empty source / weird quote nesting / case variants.
5. **Live dogfood** (`TestLiveRepo`): production code paths (non-test,
   non-fixture) yield zero findings — gates broken state from landing.

Generated by ``scripts/tools/dx/scaffold_lint.py``. See PR #171.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

_TOOLS_DIR = os.path.join(
    os.path.dirname(__file__), "..", "..", "scripts", "tools", "lint"
)
sys.path.insert(0, _TOOLS_DIR)

import check_hardcode_tenant as lint  # noqa: E402


def _scan(source: str, fake_path: str = "fake.go"):
    return lint.scan_source(Path(fake_path), source)


# ---------------------------------------------------------------------------
# Detection — positive cases
# ---------------------------------------------------------------------------
class TestDetection:
    def test_empty_source_no_findings(self):
        assert _scan("") == []

    @pytest.mark.parametrize(
        "src",
        [
            'rate(metric{tenant="db-a"}[5m])',
            'sum(metric{tenant_id="prod-a"})',
            'metric{tenantId="foo"}',
            "metric{tenant='single-quoted'}",
            'rate(metric{job="x", tenant="db-a"}[5m])',
            'rate(metric{tenant="DB-A"}[5m])',  # uppercase value
            'metric{TENANT="db-a"}',  # uppercase key (case-insensitive)
        ],
    )
    def test_positive_detection(self, src):
        findings = _scan(src)
        assert len(findings) == 1, f"expected 1 finding in {src!r}, got {findings}"

    def test_multi_label_first_position_caught(self):
        src = 'metric{tenant="db-a", env="prod"}'
        assert len(_scan(src)) == 1

    def test_multiple_findings_in_one_file(self):
        src = (
            'rate(a{tenant="db-a"}[5m])\n'
            'rate(b{tenant_id="prod-a"}[5m])\n'
        )
        findings = _scan(src)
        assert len(findings) == 2
        assert findings[0].line == 1
        assert findings[1].line == 2


# ---------------------------------------------------------------------------
# Negative — template values and non-equality operators do NOT flag
# ---------------------------------------------------------------------------
class TestNegativeCases:
    @pytest.mark.parametrize(
        "src",
        [
            'metric{tenant="$tenant"}',
            'metric{tenant="{{ tenant }}"}',
            'metric{tenant="<TENANT>"}',
            'metric{tenant="<STR>"}',
            'metric{tenant="__TENANT__"}',
            'metric{tenant=""}',  # empty placeholder
            'metric{tenant=~".*"}',  # regex match
            'metric{tenant!="db-a"}',  # negation
            'metric{tenant!~".*"}',
        ],
    )
    def test_template_or_non_eq_not_flagged(self, src):
        assert _scan(src) == []

    def test_unrelated_label_not_flagged(self):
        # `env="prod"` is fine — only `tenant`/`tenant_id`/`tenantId` are
        # in scope.
        assert _scan('metric{env="prod"}') == []

    def test_word_boundary_not_in_label_position(self):
        # Bare `tenant="db-a"` outside a label context (no preceding `{`
        # or `,`) is a comment / prose form and not flagged. This guards
        # against false-matching free-form documentation prose like
        # `// the tenant="db-a" example shows...`.
        assert _scan('// the tenant="db-a" example') == []


# ---------------------------------------------------------------------------
# Suppression — ignore comment behavior (3-line lookback)
# ---------------------------------------------------------------------------
class TestSuppression:
    def test_ignore_on_same_line_suppresses(self):
        src = 'rate(m{tenant="db-a"}[5m])  // <!-- hardcode-tenant: ignore -->\n'
        assert _scan(src) == []

    def test_ignore_one_line_above_suppresses(self):
        src = (
            "// <!-- hardcode-tenant: ignore -->\n"
            'rate(m{tenant="db-a"}[5m])\n'
        )
        assert _scan(src) == []

    def test_ignore_three_lines_above_suppresses(self):
        src = (
            "// <!-- hardcode-tenant: ignore -->\n"
            "// rationale: legacy default for migration smoke test.\n"
            "// remove once C-3 dual-entry ships.\n"
            'rate(m{tenant="db-a"}[5m])\n'
        )
        assert _scan(src) == []

    def test_ignore_four_lines_above_does_not_suppress(self):
        src = (
            "// <!-- hardcode-tenant: ignore -->\n"
            "// l2\n"
            "// l3\n"
            "// l4\n"
            'rate(m{tenant="db-a"}[5m])\n'
        )
        findings = _scan(src)
        assert len(findings) == 1


# ---------------------------------------------------------------------------
# Severity matrix
# ---------------------------------------------------------------------------
class TestComputeExitCode:
    @pytest.mark.parametrize("n", [0, 1, 5])
    def test_no_ci_always_exit_0(self, n):
        assert lint._compute_exit_code(ci=False, n_findings=n) == 0

    def test_ci_zero_findings_exit_0(self):
        assert lint._compute_exit_code(ci=True, n_findings=0) == 0

    @pytest.mark.parametrize("n", [1, 5, 100])
    def test_ci_with_findings_exit_1(self, n):
        assert lint._compute_exit_code(ci=True, n_findings=n) == 1


# ---------------------------------------------------------------------------
# Path exclusion
# ---------------------------------------------------------------------------
class TestPathExclusion:
    @pytest.mark.parametrize(
        "path",
        [
            "components/foo/bar_test.go",
            "components/foo/internal/x/y_test.go",
            "scripts/tools/tests/foo.py",
            "components/foo/testdata/cluster.yaml",
            "examples/baseline-discovery.py",
            "tests/golden/foo.go",
            "components/foo/fixtures/bar.yaml",
        ],
    )
    def test_excluded_paths(self, path):
        assert lint._is_excluded_path(Path(path)) is True

    @pytest.mark.parametrize(
        "path",
        [
            "components/foo/bar.go",
            "components/threshold-exporter/app/config.go",
            "scripts/tools/ops/check_alert.py",
            "rule-packs/rule-pack-mariadb.yaml",
            "pkg/config/types.go",
        ],
    )
    def test_included_paths(self, path):
        assert lint._is_excluded_path(Path(path)) is False


# ---------------------------------------------------------------------------
# main() integration
# ---------------------------------------------------------------------------
class TestMain:
    @pytest.mark.timeout(15)
    def test_main_clean_exit_0(self, tmp_path, capsys):
        clean = tmp_path / "clean.go"
        clean.write_text(
            'package x\nvar q = `rate(m{tenant="$tenant"}[5m])`\n',
            encoding="utf-8",
        )
        rc = lint.main(["--ci", str(clean)])
        assert rc == 0

    @pytest.mark.timeout(15)
    def test_main_dirty_under_ci_exit_1(self, tmp_path, capsys):
        dirty = tmp_path / "dirty.go"
        dirty.write_text(
            'package x\nvar q = `rate(m{tenant="db-a"}[5m])`\n',
            encoding="utf-8",
        )
        rc = lint.main(["--ci", str(dirty)])
        assert rc == 1
        captured = capsys.readouterr()
        assert "1 finding" in captured.err
        assert "db-a" in captured.err

    @pytest.mark.timeout(15)
    def test_main_dirty_no_ci_exit_0(self, tmp_path, capsys):
        dirty = tmp_path / "dirty.go"
        dirty.write_text(
            'package x\nvar q = `m{tenant="db-a"}`\n',
            encoding="utf-8",
        )
        rc = lint.main([str(dirty)])
        assert rc == 0  # report-only mode


# ---------------------------------------------------------------------------
# Live dogfood — actual repo must pass
# ---------------------------------------------------------------------------
class TestLiveRepo:
    """Run the lint against the actual repo. If this PR's edits don't
    fully eliminate findings, this test fails — preventing PR from
    landing in a broken state.
    """

    @pytest.mark.timeout(60)
    def test_live_repo_has_no_findings(self):
        import argparse

        ns = argparse.Namespace(paths=[])
        candidates = lint._resolve_target_paths(ns)
        assert candidates, "expected production code roots to exist"

        all_findings = []
        for path in candidates:
            try:
                source = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            all_findings.extend(lint.scan_source(path, source))

        assert all_findings == [], (
            f"Live repo has {len(all_findings)} finding(s):\n"
            + "\n".join(f"  - {f.render()}" for f in all_findings[:10])
        )
