package routingpolicy

// merge_key_corpus_test.go — da-guard's half of
// tests/shared/merge_key_policy_corpus.json (#2677): `_domain_policy.yaml`
// documents built around YAML merge keys (anchors and aliases as keys,
// values and merge sources; every merge-key spelling; merge sequences;
// nested merges), each with what the route generator's reader (PyYAML)
// makes of it, generated by tests/shared/test_merge_key_policy_corpus.py,
// then the deterministic `shape` rows of hub #2486 (PR-7c/7d: #2730 §1, §2,
// §4, §5, §6, merge chains, #2715). ParseDomainPolicies must say exactly
// that, for every row — a `nonspecific_tag` row included. tenant-api's half is
// components/tenant-api/internal/policy/merge_key_corpus_test.go.

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"
	"unicode/utf16"
)

// MergeKeyCorpusRow is one row of the corpus. PyYAML is "unusable" or a
// map of domain to {tenants, forbidden}.
type mergeKeyCorpusRow struct {
	Doc         string          `json:"doc"`
	PyYAML      json.RawMessage `json:"pyyaml"`
	Nonspecific string          `json:"nonspecific_tag"`
	Shape       string          `json:"shape"`
	Encoding    string          `json:"encoding"`
	// Known is "stricter" for a row ParseDomainPolicies may refuse although
	// PyYAML reads it (a known gap, #2759); nothing else is excused.
	Known string `json:"known"`
}

// corpusBytes is the file a row stands for: its doc as UTF-8, or, for an
// `encoding` row, written in that encoding (the byte order mark, then
// UTF-16; Latin-1) — a file the generator, UTF-8 only, cannot read.
func corpusBytes(t *testing.T, doc, encoding string) []byte {
	t.Helper()
	switch encoding {
	case "":
		return []byte(doc)
	case "utf-16-le-bom", "utf-16-be-bom":
		var order binary.ByteOrder = binary.LittleEndian
		if encoding == "utf-16-be-bom" {
			order = binary.BigEndian
		}
		units := append([]uint16{0xFEFF}, utf16.Encode([]rune(doc))...)
		out := make([]byte, 2*len(units))
		for i, u := range units {
			order.PutUint16(out[2*i:], u)
		}
		return out
	case "latin-1":
		out := make([]byte, 0, len(doc))
		for _, r := range doc {
			if r > 0xFF {
				t.Fatalf("corpus row: %q is not Latin-1", r)
			}
			out = append(out, byte(r))
		}
		return out
	}
	t.Fatalf("corpus row: unknown encoding %q", encoding)
	return nil
}

type corpusPolicy struct {
	Tenants   []string `json:"tenants"`
	Forbidden []string `json:"forbidden"`
	// Allowed is set when allowed_receiver_types is a non-empty list: the
	// types it allows (none, for a list of only non-string entries — it
	// still restricts every type).
	Allowed    *[]string `json:"allowed"`
	Escalation bool      `json:"escalation"`
}

// String prints Allowed's list, not its address, in a failure message.
func (p corpusPolicy) String() string {
	allowed := "-"
	if p.Allowed != nil {
		allowed = fmt.Sprint(*p.Allowed)
	}
	return fmt.Sprintf("{tenants %v forbidden %v allowed %s escalation %v}", p.Tenants, p.Forbidden, allowed, p.Escalation)
}

func readMergeKeyCorpus(t *testing.T) []mergeKeyCorpusRow {
	t.Helper()
	_, thisFile, _, _ := runtime.Caller(0)
	raw, err := os.ReadFile(filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..", "..",
		"tests", "shared", "merge_key_policy_corpus.json"))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var c struct {
		Comment []string            `json:"_comment"`
		PyYAML  string              `json:"pyyaml"`
		Rows    []mergeKeyCorpusRow `json:"rows"`
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&c); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	if len(c.Rows) < 400 {
		t.Fatalf("corpus has %d rows — a near-empty corpus proves nothing", len(c.Rows))
	}
	return c.Rows
}

// corpusVerdict is "unusable" or the policies, as the corpus spells them.
func corpusVerdict(t *testing.T, raw json.RawMessage) (unusable bool, pols map[string]corpusPolicy) {
	t.Helper()
	if string(raw) == `"unusable"` {
		return true, nil
	}
	if err := json.Unmarshal(raw, &pols); err != nil {
		t.Fatalf("corpus verdict %s: %v", raw, err)
	}
	return false, pols
}

// corpusClass names a row's kind for the per-kind tally: its `shape`, or
// "seeded", with "/nonspecific" when it carries the non-specific tag `!` on a
// quoted scalar (read through the vendored yaml.v3 patch, #2730 §6).
func corpusClass(row mergeKeyCorpusRow) string {
	c := row.Shape
	if c == "" {
		c = "seeded"
	}
	if row.Nonspecific != "" {
		c += "/nonspecific"
	}
	return c
}

// corpusTally counts, per class, the rows and the rows that are red.
type corpusTally struct{ bad, all map[string]int }

func newCorpusTally() *corpusTally {
	return &corpusTally{bad: map[string]int{}, all: map[string]int{}}
}

func (c *corpusTally) report(t *testing.T, what string) {
	t.Helper()
	classes := make([]string, 0, len(c.all))
	for k := range c.all {
		classes = append(classes, k)
	}
	sort.Strings(classes)
	var b strings.Builder
	for _, k := range classes {
		fmt.Fprintf(&b, "\n  %-46s %3d of %3d %s", k, c.bad[k], c.all[k], what)
	}
	t.Logf("per class:%s", b.String())
}

// timedShape says whether a row's parse time is logged: the long merge
// chains and the #2715 aliased list.
func timedShape(shape string) bool {
	return strings.HasPrefix(shape, "merge-chain-") || strings.HasPrefix(shape, "2715-")
}

func TestMergeKeyCorpus_ParseDomainPoliciesIsPyYAMLs(t *testing.T) {
	t.Parallel()
	rows := readMergeKeyCorpus(t)
	// No row is skipped (hub #2486 Q7-2): a `nonspecific_tag` row — the
	// non-specific tag `!` the vendored yaml.v3 keeps — is held to PyYAML's verdict like any other.
	// A `known: stricter` row (#2759) may be refused although PyYAML reads
	// it — counted, not excused otherwise: read where PyYAML drops the file,
	// or other values, is red like any row's.
	compared, bad, knownStricter := 0, 0, 0
	knownBy := map[string]int{}
	tally := newCorpusTally()
	for i, row := range rows {
		compared++
		class := corpusClass(row)
		tally.all[class]++
		if row.Known != "" && row.Known != "stricter" {
			t.Fatalf("row %d: unknown `known` %q", i, row.Known)
		}
		wantUnusable, want := corpusVerdict(t, row.PyYAML)
		start := time.Now()
		pols, _, err := ParseDomainPolicies(corpusBytes(t, row.Doc, row.Encoding))
		if timedShape(row.Shape) {
			t.Logf("row %d (%s, %d bytes): ParseDomainPolicies took %v, err = %v",
				i, row.Shape, len(row.Doc), time.Since(start), err)
		}
		if wantUnusable || err != nil {
			if !wantUnusable && row.Known == "stricter" {
				knownStricter++
				knownBy[class]++
				continue
			}
			if wantUnusable != (err != nil) {
				bad++
				tally.bad[class]++
				if tally.bad[class] <= 2 {
					t.Errorf("row %d [%s]: ParseDomainPolicies err = %v, PyYAML unusable = %v\n%q",
						i, class, err, wantUnusable, row.Doc)
				}
			}
			continue
		}
		got := map[string]corpusPolicy{}
		for _, p := range pols {
			if len(p.ForbiddenReceiverTypes) == 0 && !p.AllowedListNonEmpty {
				continue
			}
			f := append([]string{}, p.ForbiddenReceiverTypes...)
			sort.Strings(f)
			cp := corpusPolicy{Tenants: append([]string{}, p.Tenants...), Forbidden: f,
				Escalation: p.RequireCriticalEscalation}
			if p.AllowedListNonEmpty {
				a := append([]string{}, p.AllowedReceiverTypes...)
				sort.Strings(a)
				cp.Allowed = &a
			}
			got[p.Domain] = cp
		}
		if !reflect.DeepEqual(got, want) {
			bad++
			tally.bad[class]++
			if tally.bad[class] <= 2 {
				t.Errorf("row %d [%s]: ParseDomainPolicies = %+v, PyYAML = %+v\n%q", i, class, got, want, row.Doc)
			}
		}
	}
	tally.report(t, "differ from PyYAML")
	if bad > 0 {
		t.Errorf("%d of %d rows differ from PyYAML", bad, compared)
	}
	t.Logf("%d rows compared, %d known stricter (refused, PyYAML reads; #2759): %v",
		compared, knownStricter, knownBy)
}
