package routingpolicy

// merge_key_corpus_test.go — da-guard's half of
// tests/shared/merge_key_policy_corpus.json (#2677): `_domain_policy.yaml`
// documents built around YAML merge keys (anchors and aliases as keys,
// values and merge sources; every merge-key spelling; merge sequences;
// nested merges), each with what the route generator's reader (PyYAML)
// makes of it, generated by tests/shared/test_merge_key_policy_corpus.py.
// ParseDomainPolicies must say exactly that. tenant-api's half is
// components/tenant-api/internal/policy/merge_key_corpus_test.go.

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"testing"
)

// MergeKeyCorpusRow is one row of the corpus. PyYAML is "unusable" or a
// map of domain to {tenants, forbidden}.
type mergeKeyCorpusRow struct {
	Doc     string          `json:"doc"`
	PyYAML  json.RawMessage `json:"pyyaml"`
	GoBlind string          `json:"go_blind"`
}

type corpusPolicy struct {
	Tenants   []string `json:"tenants"`
	Forbidden []string `json:"forbidden"`
}

func readMergeKeyCorpus(t *testing.T) []mergeKeyCorpusRow {
	t.Helper()
	_, thisFile, _, _ := runtime.Caller(0)
	raw, err := os.ReadFile(filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..", "..",
		"tests", "shared", "merge_key_policy_corpus.json"))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var c struct {
		Comment []string            `json:"_comment"`
		PyYAML  string              `json:"pyyaml"`
		Rows    []mergeKeyCorpusRow `json:"rows"`
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&c); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	if len(c.Rows) < 400 {
		t.Fatalf("corpus has %d rows — a near-empty corpus proves nothing", len(c.Rows))
	}
	return c.Rows
}

// corpusVerdict is "unusable" or the policies, as the corpus spells them.
func corpusVerdict(t *testing.T, raw json.RawMessage) (unusable bool, pols map[string]corpusPolicy) {
	t.Helper()
	if string(raw) == `"unusable"` {
		return true, nil
	}
	if err := json.Unmarshal(raw, &pols); err != nil {
		t.Fatalf("corpus verdict %s: %v", raw, err)
	}
	return false, pols
}

func TestMergeKeyCorpus_ParseDomainPoliciesIsPyYAMLs(t *testing.T) {
	t.Parallel()
	rows := readMergeKeyCorpus(t)
	compared, bad := 0, 0
	for i, row := range rows {
		if row.GoBlind != "" {
			continue
		}
		compared++
		wantUnusable, want := corpusVerdict(t, row.PyYAML)
		pols, _, err := ParseDomainPolicies([]byte(row.Doc))
		if wantUnusable || err != nil {
			if wantUnusable != (err != nil) {
				bad++
				if bad <= 5 {
					t.Errorf("row %d: ParseDomainPolicies err = %v, PyYAML unusable = %v\n%s", i, err, wantUnusable, row.Doc)
				}
			}
			continue
		}
		got := map[string]corpusPolicy{}
		for _, p := range pols {
			if len(p.ForbiddenReceiverTypes) == 0 {
				continue
			}
			f := append([]string{}, p.ForbiddenReceiverTypes...)
			sort.Strings(f)
			got[p.Domain] = corpusPolicy{Tenants: append([]string{}, p.Tenants...), Forbidden: f}
		}
		if !reflect.DeepEqual(got, want) {
			bad++
			if bad <= 5 {
				t.Errorf("row %d: ParseDomainPolicies = %+v, PyYAML = %+v\n%s", i, got, want, row.Doc)
			}
		}
	}
	if bad > 0 {
		t.Errorf("%d of %d rows differ from PyYAML", bad, compared)
	}
	t.Logf("%d rows compared", compared)
}
