package routingpolicy

// merge_key_corpus_test.go — da-guard's half of
// tests/shared/merge_key_policy_corpus.json (#2677): `_domain_policy.yaml`
// documents built around YAML merge keys (anchors and aliases as keys,
// values and merge sources; every merge-key spelling; merge sequences;
// nested merges), each with what the route generator's reader (PyYAML)
// makes of it, generated by tests/shared/test_merge_key_policy_corpus.py,
// then the deterministic `shape` rows of hub #2486 (PR-7c/7d: #2730 §1, §2,
// §4, §5, §6, merge chains, #2715) and #2759 (A, F, K1, N).
//
// ParseDomainPolicies must say what PyYAML says, for every row — a
// `nonspecific_tag` row included — or exactly what
// tests/shared/merge_key_go_verdicts.json records for that row under
// "da-guard" (ADR-036 step 2). The snapshot holds only the rows where
// da-guard differs: "unusable" (it refuses a file PyYAML reads) or the
// policies it reads, in the corpus's own verdict shape. Which way each
// difference leans, and which catalog entry accepts it, is decided once, in
// Python: tests/shared/test_reader_divergence_catalog.py against
// tests/shared/reader_divergence_catalog.yaml. A row whose verdict changed
// — a new difference, or a recorded one that healed — is red here until the
// snapshot is regenerated (which rewrites only the "da-guard" entries):
//
//	UPDATE_GO_VERDICTS=1 go test ./pkg/routingpolicy/ -run TestMergeKeyCorpus -count=1
//
// and the regenerated diff then has to pass the catalog test. tenant-api's
// half is components/tenant-api/internal/policy/merge_key_corpus_test.go.

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"
	"unicode/utf16"
)

// goVerdictsReader is this test's key in merge_key_go_verdicts.json.
const goVerdictsReader = "da-guard"

// MergeKeyCorpusRow is one row of the corpus. PyYAML is "unusable" or a
// map of domain to {tenants, forbidden}.
type mergeKeyCorpusRow struct {
	Doc         string          `json:"doc"`
	ID          string          `json:"id"`
	PyYAML      json.RawMessage `json:"pyyaml"`
	Nonspecific string          `json:"nonspecific_tag"`
	Shape       string          `json:"shape"`
	Encoding    string          `json:"encoding"`
	// PyYAMLDropped (the domains the generator drops with a blocking
	// --strict finding) is read only by the Python catalog test, to rank a
	// difference; the comparison here is the verdict's.
	PyYAMLDropped []string `json:"pyyaml_dropped"`
}

// corpusBytes is the file a row stands for: its doc as UTF-8, or, for an
// `encoding` row, written in that encoding (the byte order mark, then
// UTF-16; Latin-1) — a file the generator, UTF-8 only, cannot read.
func corpusBytes(t *testing.T, doc, encoding string) []byte {
	t.Helper()
	switch encoding {
	case "":
		return []byte(doc)
	case "utf-16-le-bom", "utf-16-be-bom":
		var order binary.ByteOrder = binary.LittleEndian
		if encoding == "utf-16-be-bom" {
			order = binary.BigEndian
		}
		units := append([]uint16{0xFEFF}, utf16.Encode([]rune(doc))...)
		out := make([]byte, 2*len(units))
		for i, u := range units {
			order.PutUint16(out[2*i:], u)
		}
		return out
	case "latin-1":
		out := make([]byte, 0, len(doc))
		for _, r := range doc {
			if r > 0xFF {
				t.Fatalf("corpus row: %q is not Latin-1", r)
			}
			out = append(out, byte(r))
		}
		return out
	}
	t.Fatalf("corpus row: unknown encoding %q", encoding)
	return nil
}

// corpusRowID is a row's id as the corpus spells it: the first 16 hex
// digits of the sha256 of the file it stands for.
func corpusRowID(file []byte) string {
	sum := sha256.Sum256(file)
	return hex.EncodeToString(sum[:])[:16]
}

// corpusPolicy is one domain in the corpus's verdict shape: `allowed` only
// when allowed_receiver_types is a non-empty list, `escalation` only when
// true.
type corpusPolicy struct {
	Tenants   []string `json:"tenants"`
	Forbidden []string `json:"forbidden"`
	// Allowed is set when allowed_receiver_types is a non-empty list: the
	// types it allows (none, for a list of only non-string entries — it
	// still restricts every type).
	Allowed    *[]string `json:"allowed,omitempty"`
	Escalation bool      `json:"escalation,omitempty"`
}

func readMergeKeyCorpus(t *testing.T) []mergeKeyCorpusRow {
	t.Helper()
	raw, err := os.ReadFile(sharedTestFile("merge_key_policy_corpus.json"))
	if err != nil {
		t.Fatalf("read corpus: %v", err)
	}
	var c struct {
		Comment []string            `json:"_comment"`
		PyYAML  string              `json:"pyyaml"`
		Rows    []mergeKeyCorpusRow `json:"rows"`
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&c); err != nil {
		t.Fatalf("parse corpus: %v", err)
	}
	if len(c.Rows) < 400 {
		t.Fatalf("corpus has %d rows — a near-empty corpus proves nothing", len(c.Rows))
	}
	return c.Rows
}

// sharedTestFile is a file under tests/shared/.
func sharedTestFile(name string) string {
	_, thisFile, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..", "..", "tests", "shared", name)
}

// canonicalVerdict renders a verdict as compact JSON, map keys sorted, `<`
// and `>` unescaped (tenant ids such as `<<` stay readable): the form the
// snapshot holds and the form two verdicts are compared in.
func canonicalVerdict(t *testing.T, v any) string {
	t.Helper()
	raw, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("verdict %v: %v", v, err)
	}
	var generic any
	if err := json.Unmarshal(raw, &generic); err != nil {
		t.Fatalf("verdict %s: %v", raw, err)
	}
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(generic); err != nil {
		t.Fatalf("verdict %s: %v", raw, err)
	}
	return strings.TrimSuffix(b.String(), "\n")
}

// goVerdictsFile is merge_key_go_verdicts.json: per reader, row id to that
// reader's verdict, for the rows where it differs from PyYAML.
type goVerdictsFile struct {
	Comment []string
	Readers map[string]map[string]json.RawMessage
}

func readGoVerdicts(t *testing.T) goVerdictsFile {
	t.Helper()
	raw, err := os.ReadFile(sharedTestFile("merge_key_go_verdicts.json"))
	if err != nil {
		t.Fatalf("read snapshot: %v", err)
	}
	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		t.Fatalf("parse snapshot: %v", err)
	}
	f := goVerdictsFile{Readers: map[string]map[string]json.RawMessage{}}
	for k, v := range top {
		if k == "_comment" {
			if err := json.Unmarshal(v, &f.Comment); err != nil {
				t.Fatalf("snapshot _comment: %v", err)
			}
			continue
		}
		var entries map[string]json.RawMessage
		if err := json.Unmarshal(v, &entries); err != nil {
			t.Fatalf("snapshot %q: %v", k, err)
		}
		f.Readers[k] = entries
	}
	return f
}

// writeGoVerdicts renders the snapshot deterministically: `_comment`, then
// each reader sorted by name, its rows sorted by id, one row a line. The
// tenant-api test renders the same way, so either rewrites the other's
// entries byte for byte.
func writeGoVerdicts(t *testing.T, f goVerdictsFile) {
	t.Helper()
	var b strings.Builder
	var comment bytes.Buffer
	enc := json.NewEncoder(&comment)
	enc.SetEscapeHTML(false)
	enc.SetIndent("  ", "  ")
	if err := enc.Encode(f.Comment); err != nil {
		t.Fatalf("render snapshot comment: %v", err)
	}
	b.WriteString("{\n  \"_comment\": " + strings.TrimSuffix(comment.String(), "\n"))
	readers := make([]string, 0, len(f.Readers))
	for k := range f.Readers {
		readers = append(readers, k)
	}
	sort.Strings(readers)
	for _, reader := range readers {
		fmt.Fprintf(&b, ",\n  %q: {", reader)
		ids := make([]string, 0, len(f.Readers[reader]))
		for id := range f.Readers[reader] {
			ids = append(ids, id)
		}
		sort.Strings(ids)
		for i, id := range ids {
			var v any
			if err := json.Unmarshal(f.Readers[reader][id], &v); err != nil {
				t.Fatalf("snapshot %s %s: %v", reader, id, err)
			}
			sep := ","
			if i == 0 {
				sep = ""
			}
			fmt.Fprintf(&b, "%s\n    %q: %s", sep, id, canonicalVerdict(t, v))
		}
		if len(ids) > 0 {
			b.WriteString("\n  ")
		}
		b.WriteString("}")
	}
	b.WriteString("\n}\n")
	if err := os.WriteFile(sharedTestFile("merge_key_go_verdicts.json"), []byte(b.String()), 0o644); err != nil {
		t.Fatalf("write snapshot: %v", err)
	}
}

// corpusClass names a row's kind for the per-kind tally: its `shape`, or
// "seeded", with "/nonspecific" when it carries the non-specific tag `!` on a
// quoted scalar (read through the vendored yaml.v3 patch, #2730 §6).
func corpusClass(row mergeKeyCorpusRow) string {
	c := row.Shape
	if c == "" {
		c = "seeded"
	}
	if row.Nonspecific != "" {
		c += "/nonspecific"
	}
	return c
}

// corpusTally counts, per class, the rows and the rows that are red.
type corpusTally struct{ bad, all map[string]int }

func newCorpusTally() *corpusTally {
	return &corpusTally{bad: map[string]int{}, all: map[string]int{}}
}

func (c *corpusTally) report(t *testing.T, what string) {
	t.Helper()
	classes := make([]string, 0, len(c.all))
	for k := range c.all {
		classes = append(classes, k)
	}
	sort.Strings(classes)
	var b strings.Builder
	for _, k := range classes {
		fmt.Fprintf(&b, "\n  %-46s %3d of %3d %s", k, c.bad[k], c.all[k], what)
	}
	t.Logf("per class:%s", b.String())
}

// timedShape says whether a row's parse time is logged: the long merge
// chains and the #2715 aliased list.
func timedShape(shape string) bool {
	return strings.HasPrefix(shape, "merge-chain-") || strings.HasPrefix(shape, "2715-")
}

// daGuardVerdict is ParseDomainPolicies's verdict on a file in the corpus's
// shape: "unusable" when it refuses the file, else each domain with
// forbidden types or a non-empty allowed list.
func daGuardVerdict(t *testing.T, file []byte, shape string, i int) string {
	t.Helper()
	start := time.Now()
	pols, _, err := ParseDomainPolicies(file)
	if timedShape(shape) {
		t.Logf("row %d (%s, %d bytes): ParseDomainPolicies took %v, err = %v",
			i, shape, len(file), time.Since(start), err)
	}
	if err != nil {
		return canonicalVerdict(t, "unusable")
	}
	got := map[string]corpusPolicy{}
	for _, p := range pols {
		if len(p.ForbiddenReceiverTypes) == 0 && !p.AllowedListNonEmpty {
			continue
		}
		f := append([]string{}, p.ForbiddenReceiverTypes...)
		sort.Strings(f)
		cp := corpusPolicy{Tenants: append([]string{}, p.Tenants...), Forbidden: f,
			Escalation: p.RequireCriticalEscalation}
		if p.AllowedListNonEmpty {
			a := append([]string{}, p.AllowedReceiverTypes...)
			sort.Strings(a)
			cp.Allowed = &a
		}
		got[p.Domain] = cp
	}
	return canonicalVerdict(t, got)
}

func TestMergeKeyCorpus_ParseDomainPoliciesIsPyYAMLsOrRecorded(t *testing.T) {
	t.Parallel()
	rows := readMergeKeyCorpus(t)
	snap := readGoVerdicts(t)
	recorded := snap.Readers[goVerdictsReader]
	update := os.Getenv("UPDATE_GO_VERDICTS") != ""
	// No row is skipped (hub #2486 Q7-2): a `nonspecific_tag` row — the
	// non-specific tag `!` the vendored yaml.v3 keeps — is held to PyYAML's
	// verdict, or to its recorded one, like any other.
	differ := map[string]json.RawMessage{}
	seen := map[string]bool{}
	bad := 0
	tally := newCorpusTally()
	for i, row := range rows {
		class := corpusClass(row)
		tally.all[class]++
		file := corpusBytes(t, row.Doc, row.Encoding)
		if id := corpusRowID(file); id != row.ID {
			t.Fatalf("row %d: id %q, the file's sha256 says %q", i, row.ID, id)
		}
		seen[row.ID] = true
		var py any
		if err := json.Unmarshal(row.PyYAML, &py); err != nil {
			t.Fatalf("row %d: verdict %s: %v", i, row.PyYAML, err)
		}
		pyVerdict := canonicalVerdict(t, py)
		got := daGuardVerdict(t, file, row.Shape, i)
		if got != pyVerdict {
			differ[row.ID] = json.RawMessage(got)
		}
		want, isRecorded := pyVerdict, false
		if rec, ok := recorded[row.ID]; ok {
			var v any
			if err := json.Unmarshal(rec, &v); err != nil {
				t.Fatalf("snapshot %s: %v", row.ID, err)
			}
			want, isRecorded = canonicalVerdict(t, v), true
		}
		if update || got == want {
			continue
		}
		bad++
		tally.bad[class]++
		if tally.bad[class] <= 2 {
			what := "PyYAML"
			if isRecorded {
				what = "the snapshot"
			}
			t.Errorf("row %d %s [%s]: ParseDomainPolicies = %s, %s = %s (PyYAML %s)\n%q",
				i, row.ID, class, got, what, want, pyVerdict, row.Doc)
		}
	}
	if update {
		if snap.Readers == nil {
			snap.Readers = map[string]map[string]json.RawMessage{}
		}
		snap.Readers[goVerdictsReader] = differ
		writeGoVerdicts(t, snap)
		t.Logf("UPDATE_GO_VERDICTS: wrote %d %q rows to merge_key_go_verdicts.json", len(differ), goVerdictsReader)
		return
	}
	for id := range recorded {
		if !seen[id] {
			bad++
			t.Errorf("snapshot row %s (%s) is in no corpus row: regenerate with UPDATE_GO_VERDICTS=1", id, goVerdictsReader)
		}
	}
	tally.report(t, "differ from PyYAML and the snapshot")
	if bad > 0 {
		t.Errorf("%d of %d rows: ParseDomainPolicies differs from merge_key_go_verdicts.json (absent = PyYAML's verdict);"+
			" if the change is intended, regenerate with UPDATE_GO_VERDICTS=1 and run"+
			" tests/shared/test_reader_divergence_catalog.py", bad, len(rows))
	}
	t.Logf("%d rows compared, %d differ from PyYAML (recorded in merge_key_go_verdicts.json)", len(rows), len(differ))
}
