package routingpolicy

// tagged_scalar_oracle_test.go — Go's half of
// tests/shared/pyyaml_tagged_scalar_matrix.json (#2325). The table is what
// PyYAML's safe_load (the route generator's reader) makes of `a: <source>`,
// generated by tests/shared/test_pyyaml_tagged_scalar_oracle.py. The
// contract pinned here: DecodePyYAML returns an error exactly on the rows
// PyYAML refuses, and otherwise the bool PyYAML builds, nil for None, and a
// non-bool for anything else.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"gopkg.in/yaml.v3"
)

type taggedScalarRow struct {
	Source  string `json:"source"`
	Refused string `json:"refused"`
	Type    string `json:"type"`
	Bool    *bool  `json:"bool"`
	GoBlind string `json:"go_blind"` // yaml.v3 cannot tell this row apart
}

func TestDecodePyYAML_MatchesPyYAMLOracle(t *testing.T) {
	t.Parallel()
	_, thisFile, _, _ := runtime.Caller(0)
	raw, err := os.ReadFile(filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..", "..",
		"tests", "shared", "pyyaml_tagged_scalar_matrix.json"))
	if err != nil {
		t.Fatalf("read matrix: %v", err)
	}
	var m struct {
		Comment []string          `json:"_comment"`
		PyYAML  string            `json:"pyyaml"`
		Rows    []taggedScalarRow `json:"rows"`
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&m); err != nil {
		t.Fatalf("parse matrix: %v", err)
	}
	if len(m.Rows) == 0 {
		t.Fatal("matrix has no rows — a vacuous table passes nothing")
	}
	for _, row := range m.Rows {
		if row.GoBlind != "" {
			continue // see the matrix _comment and pyyaml.go's header
		}
		var doc yaml.Node
		var v any
		err := yaml.Unmarshal([]byte("a: "+row.Source+"\n"), &doc)
		if err == nil {
			v, err = DecodePyYAML(doc.Content[0].Content[1])
		}
		switch {
		case row.Refused != "":
			if err == nil {
				t.Errorf("%s: PyYAML refuses it (%s), DecodePyYAML = %#v", row.Source, row.Refused, v)
			}
		case err != nil:
			t.Errorf("%s: PyYAML builds a %s, DecodePyYAML: %v", row.Source, row.Type, err)
		case row.Bool != nil:
			if v != *row.Bool {
				t.Errorf("%s: PyYAML builds %v, DecodePyYAML = %#v", row.Source, *row.Bool, v)
			}
		case row.Type == "NoneType":
			if v != nil {
				t.Errorf("%s: PyYAML builds None, DecodePyYAML = %#v", row.Source, v)
			}
		default:
			if _, isBool := v.(bool); isBool || v == nil {
				t.Errorf("%s: PyYAML builds a %s, DecodePyYAML = %#v", row.Source, row.Type, v)
			}
		}
	}
}

// A mapping or sequence is never a bool: one PyYAML accepts, and one PyYAML
// refuses only for something below its direct children (the accepted gap:
// `[!!bool y]` …), decodes to a non-bool with no error — an alias cycle or a
// fan-out included (#2325), so it must also be fast.
func TestDecodePyYAML_CollectionIsNonBool(t *testing.T) {
	t.Parallel()
	fan := "&l0 [x,x,x,x,x,x,x,x,x,x]"
	for i := 1; i <= 8; i++ {
		fan += fmt.Sprintf(", &l%d [%s]", i, strings.TrimSuffix(strings.Repeat(fmt.Sprintf("*l%d,", i-1), 10), ","))
	}
	for _, src := range []string{
		// PyYAML accepts these.
		"[yes]", "[true]", "{b: true}", "[]", "{}", "! [1]", "!!seq [1]", "!!map {a: 1}",
		"!!set {a: null}", "!!set {a}", "!!omap [{a: 1}]", "!!pairs [{a: 1}]", "!!omap []",
		"!!omap [{[1]: 2}]", "{<<: {b: 1}}", "{<<: [{b: 1}]}", "{<<: []}", "{<<: !foo {b: 1}}",
		"{\"<<\": 1}", "{!!merge x: {b: 1}}", "{a: [1]}", "&x [*x]", "&x {b: *x}", "[" + fan + "]",
		// PyYAML refuses these below the direct children: not seen here.
		"[!!bool y]", "{a: !!int x}", "!!set {!!bool y: null}", "!!omap [{a: !!bool y}]",
		"{<<: [{b: !!bool y}]}", "[[!!bool y]]", "{b: 2001-13-40}", "[2001-13-40]",
	} {
		var doc yaml.Node
		if err := yaml.Unmarshal([]byte("a: "+src+"\n"), &doc); err != nil {
			t.Fatalf("%s: %v", src, err)
		}
		start := time.Now()
		v, err := DecodePyYAML(doc.Content[0].Content[1])
		if _, isBool := v.(bool); err != nil || isBool || v == nil {
			t.Errorf("%.40s: DecodePyYAML = %#v, %v; want a non-bool, no error", src, v, err)
		}
		if d := time.Since(start); d > time.Second {
			t.Errorf("%.40s: DecodePyYAML took %v", src, d)
		}
	}
}

// A mapping or sequence PyYAML refuses for its own tag or its direct
// children is refused here too (#2325), as the generator drops the file.
func TestDecodePyYAML_CollectionRefusedOneLevel(t *testing.T) {
	t.Parallel()
	for _, src := range []string{
		// the collection's own tag
		"!!bool [true]", "!!bool {a: 1}", "!!str [1]", "!!int {a: 1}", "!foo [1]", "!!seq {a: 1}",
		"!!map [1]", "!!timestamp [1]", "!!binary [1]", "!!null {}", "!!omap {a: 1}", "!!set [1]",
		// its direct children
		"!!omap [1]", "!!pairs [a]", "!!omap [{a: 1, b: 2}]", "!!pairs [{}]",
		"{<<: 1}", "{<<: [1]}", "{<<: null}", "{!!merge x: 1}", "{! <<: 1}", "!!set {<<: 1}",
		"{[1]: 2}", "{? [1] : 2}", "{{a: 1}: 2}", "!!set {[1]: null}",
	} {
		var doc yaml.Node
		if err := yaml.Unmarshal([]byte("a: "+src+"\n"), &doc); err != nil {
			t.Fatalf("%s: %v", src, err)
		}
		if v, err := DecodePyYAML(doc.Content[0].Content[1]); err == nil {
			t.Errorf("%s: DecodePyYAML = %#v, nil; want the error PyYAML's refusal is", src, v)
		}
	}
	// An alias child is followed once for its kind.
	for _, src := range []string{"a: &a [1]\nb: {*a : 1}\n", "a: &a 1\nb: {<<: *a}\n",
		"a: &a 1\nb: {<<: [*a]}\n", "a: &a {c: 1, d: 2}\nb: !!omap [*a]\n"} {
		var doc yaml.Node
		if err := yaml.Unmarshal([]byte(src), &doc); err != nil {
			t.Fatalf("%q: %v", src, err)
		}
		if v, err := DecodePyYAML(doc.Content[0].Content[3]); err == nil {
			t.Errorf("%q: DecodePyYAML = %#v, nil; want an error", src, v)
		}
	}
	for _, src := range []string{"a: &a {c: 1}\nb: {<<: *a}\n", "a: &a {c: 1}\nb: {<<: [*a]}\n",
		"a: &a {c: 1}\nb: !!omap [*a]\n"} {
		var doc yaml.Node
		if err := yaml.Unmarshal([]byte(src), &doc); err != nil {
			t.Fatalf("%q: %v", src, err)
		}
		if v, err := DecodePyYAML(doc.Content[0].Content[3]); err != nil || v == nil {
			t.Errorf("%q: DecodePyYAML = %#v, %v; want a non-bool, no error", src, v, err)
		}
	}
}
