package routingpolicy

// tagged_scalar_oracle_test.go — Go's half of
// tests/shared/pyyaml_tagged_scalar_matrix.json (#2325). The table is what
// PyYAML's safe_load (the route generator's reader) makes of `a: <source>`,
// generated by tests/shared/test_pyyaml_tagged_scalar_oracle.py. The
// contract pinned here: DecodePyYAML returns an error exactly on the rows
// PyYAML refuses, and otherwise the bool PyYAML builds, nil for None, and a
// non-bool for anything else.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"gopkg.in/yaml.v3"
)

type taggedScalarRow struct {
	Source  string `json:"source"`
	Refused string `json:"refused"`
	Type    string `json:"type"`
	Bool    *bool  `json:"bool"`
	GoBlind string `json:"go_blind"` // yaml.v3 cannot tell this row apart
}

func TestDecodePyYAML_MatchesPyYAMLOracle(t *testing.T) {
	t.Parallel()
	_, thisFile, _, _ := runtime.Caller(0)
	raw, err := os.ReadFile(filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..", "..",
		"tests", "shared", "pyyaml_tagged_scalar_matrix.json"))
	if err != nil {
		t.Fatalf("read matrix: %v", err)
	}
	var m struct {
		Comment []string          `json:"_comment"`
		PyYAML  string            `json:"pyyaml"`
		Rows    []taggedScalarRow `json:"rows"`
	}
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&m); err != nil {
		t.Fatalf("parse matrix: %v", err)
	}
	if len(m.Rows) == 0 {
		t.Fatal("matrix has no rows — a vacuous table passes nothing")
	}
	for _, row := range m.Rows {
		if row.GoBlind != "" {
			continue // see the matrix _comment and pyyaml.go's header
		}
		var doc yaml.Node
		var v any
		err := yaml.Unmarshal([]byte("a: "+row.Source+"\n"), &doc)
		if err == nil {
			v, err = DecodePyYAML(doc.Content[0].Content[1])
		}
		switch {
		case row.Refused != "":
			if err == nil {
				t.Errorf("%s: PyYAML refuses it (%s), DecodePyYAML = %#v", row.Source, row.Refused, v)
			}
		case err != nil:
			t.Errorf("%s: PyYAML builds a %s, DecodePyYAML: %v", row.Source, row.Type, err)
		case row.Bool != nil:
			if v != *row.Bool {
				t.Errorf("%s: PyYAML builds %v, DecodePyYAML = %#v", row.Source, *row.Bool, v)
			}
		case row.Type == "NoneType":
			if v != nil {
				t.Errorf("%s: PyYAML builds None, DecodePyYAML = %#v", row.Source, v)
			}
		default:
			if _, isBool := v.(bool); isBool || v == nil {
				t.Errorf("%s: PyYAML builds a %s, DecodePyYAML = %#v", row.Source, row.Type, v)
			}
		}
	}
}

// A mapping or sequence is never a bool: DecodePyYAML returns a non-bool
// without looking inside, whatever PyYAML would make of the children — an
// alias cycle or a fan-out included (#2325), so it must also be fast.
func TestDecodePyYAML_CollectionIsNonBool(t *testing.T) {
	t.Parallel()
	fan := "&l0 [x,x,x,x,x,x,x,x,x,x]"
	for i := 1; i <= 8; i++ {
		fan += fmt.Sprintf(", &l%d [%s]", i, strings.TrimSuffix(strings.Repeat(fmt.Sprintf("*l%d,", i-1), 10), ","))
	}
	for _, src := range []string{
		"[yes]", "{b: true}", "[!!bool y]", "!foo [1]", "!!omap [{[1]: 2}]",
		"{<<: !foo {b: 1}}", "&x [*x]", "&x {b: *x}", "[" + fan + "]",
	} {
		var doc yaml.Node
		if err := yaml.Unmarshal([]byte("a: "+src+"\n"), &doc); err != nil {
			t.Fatalf("%s: %v", src, err)
		}
		start := time.Now()
		v, err := DecodePyYAML(doc.Content[0].Content[1])
		if _, isBool := v.(bool); err != nil || isBool || v == nil {
			t.Errorf("%.40s: DecodePyYAML = %#v, %v; want a non-bool, no error", src, v, err)
		}
		if d := time.Since(start); d > time.Second {
			t.Errorf("%.40s: DecodePyYAML took %v", src, d)
		}
	}
}
